### ISSUE TITLE
Build instructions inconsistent about SQLITE_TEMP_STORE

### ISSUE THREAD

**Issue by sschuberth** [sqlcipher/sqlcipher#108]
On the one hand, the readme says

    You must define SQLITE_HAS_CODEC and SQLITE_TEMP_STORE=2 when building sqlcipher

on the other hand the following build examples in the readme only define `SQLITE_HAS_CODEC`. 

Could you please either remove `SQLITE_TEMP_STORE` from the quoted line or add it to the examples depending on whether it is still needed?

**Comment by sjlombardo** [comment]
Hello @sschuberth - I agree that it is a bit confusing. However, in the examples using ./configure, the --enable-tempstore option actually sets SQLITE_TEMP_STORE=2 used for the build. If you are compiling SQLCipher in any different way (i.e. compiling sqlite3.c directly), you would need to ensure that SQLITE_TEMP_STORE=2 is defined. We've make a change to the README on the prerelease branch to reflect this.

**Comment by sschuberth** [comment]
Thanks! Is that prerelease branch on GitHub so that you can link the SHA1 to the commit here for reference?

**Comment by sjlombardo** [comment]
Correct, thats the prerelease branch on GitHub, commit https://github.com/sqlcipher/sqlcipher/commit/acb86dcc7e38e920da9450cec33471f1dea10099

Thanks for bringing this to our attention!

**Comment by permotion88** [comment]
Hello @sjlombardo - Is SQLITE_TEMP_STORE=2 really needed (that sqlcipher can correctly work)? Or it is required only for the performance improvements? From my experience, if you iterate in SQLite (with SELECT, some JOINs etc.) over huge sets of data (millions of rows), when PRAGMA temp_store = MEMORY was set, it need very lot (Gigabytes) of the RAM...

**Comment by brodybits** [comment]
> Hello @sjlombardo - Is SQLITE_TEMP_STORE=2 really needed (that sqlcipher can correctly work)?

It is needed to ensure that sensitive data is never written without encryption to a SQLite temporary file. I would personally recommend setting SQLITE_TEMP_STORE=3 as in android-database-sqlcipher to ensure that this setting can not be overridden by PRAGMA temp_store setting. I actually proposed enforcing this setting and making it harder to override in PR #133.
