### ISSUE TITLE
Compression support for sqlcipher

### ISSUE THREAD

**Issue by ray-pixar** [sqlcipher/sqlcipher#111]
Hi,
Is it possible to add transparent compression support to sqlcipher databases ?

**Comment by developernotes** [comment]
Hello @ray-pixar 

You could potentially use something like zlib before/after encryption/decryption.  If this is something you would like to discuss further, we have a [discuss forum](https://discuss.zetetic.net/c/sqlcipher) for SQLCipher discussions.  Thanks!
