### ISSUE TITLE
Xcode Static Analyzer indicates many "issues"

### ISSUE THREAD

**Issue by sedwo** [sqlcipher/sqlcipher#112]
![sqlcipher static analyzer issues](https://cloud.githubusercontent.com/assets/1434449/6656079/e68cf512-caf1-11e4-8980-d82c2805e699.png)

**Comment by sjlombardo** [comment]
Hello @sedwo - these issues all appear to be warnings stemming from the upstream SQLite source. We have a strong policy not to divert or change the upstream code more than necessary, as it makes merging and upgrading difficult and risky. As such, we would not fix these, though it may be possible to configure XCode to silence some of those warnings.
