### ISSUE TITLE
 'DSQLITE_HAS_CODEC' Error

### ISSUE THREAD

**Issue by narendra-ct** [sqlcipher/sqlcipher#113]
Hi,

I'm getting clang: error: no such file or directory: 'DSQLITE_HAS_CODEC' error and i'm following with ios-tutorial but no Luck .Please help me on this.

This is the full log ..

ProcessPCH /Users/sushil/Library/Developer/Xcode/DerivedData/FMP360-gzaojenqnmkfmvaygekerdcwrprg/Build/Intermediates/PrecompiledHeaders/FMP360-Prefix-aubnjcdgovefmlfhipmmxtbddsbd/FMP360-Prefix.pch.pch FMP360/FMP360-Prefix.pch normal arm64 c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/sushil/Desktop/FMP360/platforms/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c-header -arch arm64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.2.sdk -fstrict-aliasing -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -miphoneos-version-min=6.0 -iquote /Users/sushil/Library/Developer/Xcode/DerivedData/FMP360-gzaojenqnmkfmvaygekerdcwrprg/Build/Intermediates/FMP360.build/Debug-iphoneos/FMP360.build/FMP360-generated-files.hmap -I/Users/sushil/Library/Developer/Xcode/DerivedData/FMP360-gzaojenqnmkfmvaygekerdcwrprg/Build/Intermediates/FMP360.build/Debug-iphoneos/FMP360.build/FMP360-own-target-headers.hmap -I/Users/sushil/Library/Developer/Xcode/DerivedData/FMP360-gzaojenqnmkfmvaygekerdcwrprg/Build/Intermediates/FMP360.build/Debug-iphoneos/FMP360.build/FMP360-all-target-headers.hmap -iquote /Users/sushil/Library/Developer/Xcode/DerivedData/FMP360-gzaojenqnmkfmvaygekerdcwrprg/Build/Intermediates/FMP360.build/Debug-iphoneos/FMP360.build/FMP360-project-headers.hmap -I/Users/sushil/Library/Developer/Xcode/DerivedData/FMP360-gzaojenqnmkfmvaygekerdcwrprg/Build/Products/Debug-iphoneos/include -I/Users/sushil/Library/Developer/Xcode/DerivedData/FMP360-gzaojenqnmkfmvaygekerdcwrprg/Build/Products/Debug-iphoneos/usr/local/lib/include -I/Users/sushil/Library/Developer/Xcode/DerivedData/FMP360-gzaojenqnmkfmvaygekerdcwrprg/Build/Intermediates/UninstalledProducts/include -I/Users/sushil/Library/Developer/Xcode/DerivedData/FMP360-gzaojenqnmkfmvaygekerdcwrprg/Build/Products/Debug-iphoneos -Isqlcipher/src -I/Users/sushil/Library/Developer/Xcode/DerivedData/FMP360-gzaojenqnmkfmvaygekerdcwrprg/Build/Intermediates/FMP360.build/Debug-iphoneos/FMP360.build/DerivedSources/arm64 -I/Users/sushil/Library/Developer/Xcode/DerivedData/FMP360-gzaojenqnmkfmvaygekerdcwrprg/Build/Intermediates/FMP360.build/Debug-iphoneos/FMP360.build/DerivedSources -F/Users/sushil/Library/Developer/Xcode/DerivedData/FMP360-gzaojenqnmkfmvaygekerdcwrprg/Build/Products/Debug-iphoneos -F/Users/sushil/Desktop/FMP360/platforms/ios DSQLITE_HAS_CODEC -MD -MT dependencies -MF /Users/sushil/Library/Developer/Xcode/DerivedData/FMP360-gzaojenqnmkfmvaygekerdcwrprg/Build/Intermediates/PrecompiledHeaders/FMP360-Prefix-aubnjcdgovefmlfhipmmxtbddsbd/FMP360-Prefix.pch.d -c /Users/sushil/Desktop/FMP360/platforms/ios/FMP360/FMP360-Prefix.pch -o /Users/sushil/Library/Developer/Xcode/DerivedData/FMP360-gzaojenqnmkfmvaygekerdcwrprg/Build/Intermediates/PrecompiledHeaders/FMP360-Prefix-aubnjcdgovefmlfhipmmxtbddsbd/FMP360-Prefix.pch.pch --serialize-diagnostics /Users/sushil/Library/Developer/Xcode/DerivedData/FMP360-gzaojenqnmkfmvaygekerdcwrprg/Build/Intermediates/PrecompiledHeaders/FMP360-Prefix-aubnjcdgovefmlfhipmmxtbddsbd/FMP360-Prefix.pch.dia

clang: error: no such file or directory: 'DSQLITE_HAS_CODEC'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

**Comment by sjlombardo** [comment]
You are missing the - before DSQLITE_HAS_CODEC. It should be -DSQLITE_HAS_CODEC in the project setup.
