### ISSUE TITLE
when finished ./configure and typing make find this error

### ISSUE THREAD

**Issue by jammeska** [sqlcipher/sqlcipher#115]
./.libs/libsqlcipher.so: undefined reference to `dlopen'
./.libs/libsqlcipher.so: undefined reference to`dlclose'
./.libs/libsqlcipher.so: undefined reference to `dlerror'
./.libs/libsqlcipher.so: undefined reference to`dlsym'
./.libs/libsqlcipher.so: undefined reference to `dladdr'
collect2: error: ld returned 1 exit status
make: **\* [sqlcipher] Error 1

**Comment by BenPope** [comment]
It would help if you'd give a little more context such as compiler, platform, command line that eschewed that error.  It looks like you also need to link with libdl, so probably add -ldl to your link command, you should also be aware that g++ requires that -ldl comes after the things that require the symbols from that shared object, so put it after -lsqlcipher.

**Comment by jammeska** [comment]
OS Ubuntu server 14.04
gcc version 4.8.2
configur command 
./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC" LDFLAGS="/usr/lib/i386-linux-gnu/libcrypto.a"
this commad done. when go to make and print it on command line find
./.libs/libsqlcipher.so: undefined reference to `dlopen'
./.libs/libsqlcipher.so: undefined reference to `dlclose'
./.libs/libsqlcipher.so: undefined reference to `dlerror'
./.libs/libsqlcipher.so: undefined reference to `dlsym'
./.libs/libsqlcipher.so: undefined reference to `dladdr'
collect2: error: ld returned 1 exit status
make: *** [sqlcipher] Error 1

**Comment by developernotes** [comment]
Hello @jammeska 

I'm sorry for the considerable late reply, are you still working through the issue you described above?

**Comment by sjlombardo** [comment]
No update since Feb 2016, closing.
