### ISSUE TITLE
how to decrypt encrypted sqlite in sqlcipher?

### ISSUE THREAD

**Issue by neaGaze** [sqlcipher/sqlcipher#116]
i have encrypted the sql file using ATTACH command. I want to insert values in encrypted sqlite db. To do this first i tried to decrypt it. how can i decrypt the encrypted sql file?

**Comment by sjlombardo** [comment]
@neaGaze SQLCipher encrypts data on the fly. You do not decrypt the database then re-encrypt it. Once you have encrypted your database using the ATTACH command, close all database handles, then open the encrypted database. Provide the key for it using sqlite3_key or PRAGMA key='...'. From that point on all operations on the database will automatically be encrypted.
