### ISSUE TITLE
Odd handling of incorrect locales

### ISSUE THREAD

**Issue by Grunthos** [sqlcipher/sqlcipher#117]
I can execute the following and it all seems to work:

> sqlite> select icu_load_collation('[][][]','q');
> sqlite> select * from foo order by f1 collate q;

Which worries me.

Which locale is it using when the locale passed in invalid or missing?

**Comment by developernotes** [comment]
Hello @Grunthos 

The ICU support is not specific to SQLCipher, it is an extension provided by SQLite and is not provided by the default build in SQLCipher.  This inquiring may be better suited for the SQLite mailing list.
