### ISSUE TITLE
Incremental store doesn't support <fetchOffset>

### ISSUE THREAD

**Issue by sahara108** [sqlcipher/sqlcipher#122]
Hi, It looks like the store doesn't support fetchOffset of NSFetchRequest.

**Comment by developernotes** [comment]
Hello @sahara108 

Are you referring to integration with Core.Data?  We do not provide an implementation for that, however there is an open source project targeted for that [here](https://github.com/project-imas/encrypted-core-data).

**Comment by sahara108** [comment]
Thank you. I will take a look at this project. 

Tuan Nguyen
