### ISSUE TITLE
Contributions section in README.md

### ISSUE THREAD

**Issue by brodybits** [sqlcipher/sqlcipher#123]
Yesterday I found out that contributions should be based on the `prerelease` branch and NOT the `master` branch here: https://github.com/sqlcipher/android-database-sqlcipher/pull/171#issuecomment-106006905

In addition, a CLA (contributor license agreement) has to be signed before contributions will be accepted, as described here: https://www.zetetic.net/contributions/

Can we please have this information in the readme?

I am happy to contribute a draft of this section when I get a chance.

**Comment by brodybits** [comment]
Also in android-database-sqlcipher. Again, I am happy to contribute a draft when I get a chance.

**Comment by developernotes** [comment]
@brodybits I will update the README files today for both the sqlcipher project and the android-database-sqlcipher projects to reflect contribution steps.  Thanks!

**Comment by developernotes** [comment]
@brodybits I have updated the README in the sqlcipher core project on both `master` and `prerelease` branches, as well as the README in the android-database-sqlcipher project on `master`.  Thanks for pointing out the missing parts to the README!
