### ISSUE TITLE
Incorrect password but always saying "Password correct"

### ISSUE THREAD

**Issue by iamredeye** [sqlcipher/sqlcipher#124]
Hi everyone,

I have a problem using sqlcipher for ios.
I have followed this example to create database named "testing.db" :

https://charlesleifer.com/blog/encrypted-sqlite-databases-with-python-and-sqlcipher/

Then I moved to this tutorial to integrate sqlcipher source to my project and configure it :

https://www.zetetic.net/sqlcipher/ios-tutorial/

The problem is when I test my code with different password (keys), it always displays to me "Password is correct, or a new database has been initialized" even if I set a wrong filename for my database (always same message).

What can be the error here ?

Thanks in advance

**Comment by developernotes** [comment]
Hello @iamredeye 

Can you execute the following statement within your application and report what value is returned, you should retrieve a string value:

```
PRAGMA cipher_version;
```
This will help identify whether you have properly integrated the SQLCipher library within your application.

**Comment by iamredeye** [comment]
it displays "(null)"

**Comment by developernotes** [comment]
Hello @iamredeye 

That would mean that SQLCipher is not properly integrated within your project.  I would suggest reviewing the integration guide above and comparing that with your project.

**Comment by developernotes** [comment]
@iamredeye - let us know if you run into any issues and what you was missing in your project configuration.  There is likely a chance you have linked the platform SQLite implementation instead.

**Comment by iamredeye** [comment]
Just refollowed the exact same steps as mentionned in this url :
https://www.zetetic.net/sqlcipher/ios-tutorial/
and it didn't work.

I just remember that yesterday it worked, going back to a backup of the project that dates of yesterday and trying to launch it but have same results.

**Comment by developernotes** [comment]
@iamredeye - when you say "it didn't work", can you be a bit more specific?  Are you receiving build errors, do you continue to get a null value for `PRAGMA cipher_version;`?  Have you removed any other references to SQLite?

**Comment by iamredeye** [comment]
Having always PRAGMA cipher_version = (null)

What I have made is defining "No" for "Build only active architecture" in cipher ios project and building it for device to get the ".a" file

![1](https://cloud.githubusercontent.com/assets/6862889/7938081/a87136ac-093b-11e5-892e-1263d9901254.jpg)
![2](https://cloud.githubusercontent.com/assets/6862889/7938083/ac77df9e-093b-11e5-857b-d2345f54b37e.jpg)
![3](https://cloud.githubusercontent.com/assets/6862889/7938086/af6ae192-093b-11e5-818f-ea3599931e4b.jpg)
![4](https://cloud.githubusercontent.com/assets/6862889/7938089/b1b8a7a4-093b-11e5-92f6-1c7aad6fb5d4.jpg)
![5](https://cloud.githubusercontent.com/assets/6862889/7938092/b49e6eb8-093b-11e5-8515-df489289ab09.jpg)
![6](https://cloud.githubusercontent.com/assets/6862889/7938102/ba41d7e2-093b-11e5-99a4-fe7fd8ca0ae5.jpg)

**Comment by iamredeye** [comment]
After cleaning the project, I have noticed that PRAGMA cipher_version; was returning "3.3.0", but still displaying "Correct Password" when setting non correct ones

**Comment by developernotes** [comment]
@iamredeye - what is the test scenario with regard to opening a database that you are seeing a failure?  Does the database file already exist when you open a connection, or are you creating it within your application?  Is it a plain text database, or a SQLCipher encrypted database?

**Comment by iamredeye** [comment]
I have used a sqlite3 database, then encrypt it with sqlcipher and try to open it and detect if sqlcipher in ios project can open it with wrong password or no.

Now I have create sample database with these commands :

sqlite> .open testing.db
sqlite> PRAGMA key='testing';
sqlite> create table people (name text primary key);
sqlite> insert into people (name) values ('charlie'), ('huey');
sqlite> .quit

![1b](https://cloud.githubusercontent.com/assets/6862889/7940756/b6ce438e-094a-11e5-8b6b-6cb9f6ed23fa.jpg)
![1a](https://cloud.githubusercontent.com/assets/6862889/7940755/b6cc1e2e-094a-11e5-90c3-acda5d96ee21.jpg)

**Comment by developernotes** [comment]
@iamredeye can you verify the `testing.db` file is properly encrypted as well.  You can do this by viewing a raw hexdump of the file.  Something like:

```
hexdump -C testing.db
```
Does the content look indecipherable, or can you see the table schema(s)/content?

**Comment by iamredeye** [comment]
Yes the database is encrypted...
See images below...
![1](https://cloud.githubusercontent.com/assets/6862889/7946954/d9bea718-0971-11e5-9964-6ca139948e31.jpg)

![2](https://cloud.githubusercontent.com/assets/6862889/7946965/e152be38-0971-11e5-8183-5f165a908595.jpg)

![3](https://cloud.githubusercontent.com/assets/6862889/7946972/edacacfc-0971-11e5-8991-00f75eb9c1c3.jpg)

![4](https://cloud.githubusercontent.com/assets/6862889/7946977/f4b1c816-0971-11e5-83aa-a4797f1c110d.jpg)

**Comment by developernotes** [comment]
@iamredeye - a couple of questions:

- Does `[self.databaseURL path]` exist, and are you sure it is pointing to the same file you created from the SQLCipher command line prompt?
- What is the output from running `query0`?

**Comment by iamredeye** [comment]
1-Yes, it exists and pointing from same file created from SQLCipher command line prompt
2-Nothing

Here is a link with a sample ios project, you can see the code in there :
https://www.dropbox.com/s/a9zzq9ehk163jf3/SqlCipherSample.zip?dl=0

**Comment by developernotes** [comment]
@iamredeye - I took a look at your zipped application.  The database file you have included within the zip is not being included with the application when it compiles.

![screen shot 2015-06-03 at 8 17 51 am](https://cloud.githubusercontent.com/assets/3225/7960856/3eea552c-09c9-11e5-80f2-a8bd0d5fe7c4.png)

Since the file does not exist, SQLCipher creates it for you, accepting any password you provide.  You can open the path printed here `NSLog(@"database path:%@", [self.databaseURL path]);` and compare the database file is different.
