### ISSUE TITLE
Minor coverity issue: in sqlcipher_codec_ctx_migrate, unnecessary NULL check

### ISSUE THREAD

**Issue by harningt** [sqlcipher/sqlcipher#127]
On [sqlcipher/src/crypto_impl.c:1161](https://github.com/sqlcipher/sqlcipher/blob/fafb0d05bdae394037ac495fe7261573f5f675eb/src/crypto_impl.c#L1161) there is a check to see if pDB is null, however it cannot be so due to an earlier assignment: [sqlcipher/src/crypto_impl.c:1131](https://github.com/sqlcipher/sqlcipher/blob/fafb0d05bdae394037ac495fe7261573f5f675eb/src/crypto_impl.c#L1131)

Very very low priority, but thought it relevant to report.

**Comment by developernotes** [comment]
Hello @harningt 

Thank you for reporting the issue Coverity identified, I have applied a fix [here](https://github.com/sqlcipher/sqlcipher/commit/e451540b9c18faad0dfd6a3e708c274963483993).  Thanks!
