### ISSUE TITLE
Getting unable to open database file while inserting data around 5000 rows.

### ISSUE THREAD

**Issue by joshisunil-1983** [sqlcipher/sqlcipher#130]
I am using following code to insert rows more than 5000. if i am not using line **sqlite3_close(dbv);**  statement i got an error **unable to open database**. and if i use the statement  **sqlite3_close(dbv);**  data insertion taking around 10-15 mins. what can i do to insert record faster without getting error.

    -(void)insertrecordIntoTable:(NSString*)SQLStatement
    {
        NSString *sqlStr=SQLStatement;
        const char *sql=[sqlStr UTF8String];
         const char* key = [@"StrongPassword" UTF8String];
        sqlite3_stmt *statement1;
        @try {
            
            int res = sqlite3_open([[self.databaseURL path] UTF8String], &dbv);
            if (res != SQLITE_OK)
                sqlite3_open([[self.databaseURL path] UTF8String], &dbv);
            
            sqlite3_key(dbv, key, (int)strlen(key));
                
            if(sqlite3_prepare_v2(dbv, sql, -1, &statement1, nil)==SQLITE_OK)
            {
                NSLog(@"done");
            }
            else
            {
                 NSLog(@"the error occurred here is %s ",sqlite3_errmsg(dbv));
            }
            
            res =sqlite3_step(statement1);
            
            if(res !=SQLITE_DONE)
              NSLog(@"Error upadating table");
            
            sqlite3_finalize(statement1);
            sqlite3_close(dbv);
        }
        @catch (NSException *exception) {
            
        }
        @finally {
            sql=NULL;
            sqlStr=NULL;
            SQLStatement=NULL;
        }
    }

**Comment by joshisunil-1983** [comment]
update of values.

**Comment by developernotes** [comment]
Hello @joshisunil-1983 

Can you try just opening the database once, leaving the connection open during the entirely of your application, and close the connection on the termination of the application?  `sqlite3_key` is slow by design and the code above is forcing an open/key/close process for every record you insert which will slow down your operating considerably.

**Comment by sjlombardo** [comment]
@joshisunil-1983 In addition to @developernotes  suggestion, you should also run these updates in a transaction. Start the transaction before you begin updating the database and commit after you're done processing all 5000 records. They way you are doing it now SQLCipher will execute 5000 separate transactions, which will also be quite slow.
