### ISSUE TITLE
Existing SQLite db to Sqlcipher db.

### ISSUE THREAD

**Issue by joshisunil-1983** [sqlcipher/sqlcipher#131]
i have a ios app which already installed on client devices. i want to encrypt my database using sqlcipher. to do this i have implement the sqlcipher in my project and remove the old reference of sqlite. i am able to create new database using sqlcipher and other operations also can be performed over my new database. how can i use the old sqlite3 datase in my ios app which is updated with sqlcipher.

**Comment by brodybits** [comment]
SQLCipher can also read an normal, unencrypted sqlite database. Just open it without using a key. Also, if I am not mistaken if you open an encrypted database, you _should_ be able to ATTACH to an unencrypted database within the same sqlite database connection/handle. (@developernotes or other @sqlcipher owner correct me if I am not correct!)

**Comment by joshisunil-1983** [comment]
ok after using that without key can i convert simple sqlite db to sqlcipher db.

**Comment by brodybits** [comment]
Yes and a convenience function is documented here: https://www.zetetic.net/sqlcipher/sqlcipher-api/#sqlcipher_export

Note that this was also discussed in sqlcipher/android-database-sqlcipher#8.

**Comment by joshisunil-1983** [comment]
can i run the sqlcipher_export in ios app using execute or prepare. or can u please pass me some sample link.

**Comment by developernotes** [comment]
Hello @joshisunil-1983,

Yes, you can execute `sqlcipher_export(…)` using a prepared statement.  If you are new to the C interface provided by SQLite, you may find this [documentation](https://www.sqlite.org/cintro.html) helpful.

**Comment by joshisunil-1983** [comment]
thanks a lot.
