### ISSUE TITLE
Issues with static linking of libcrypto.a [Ubuntu 15.04]

### ISSUE THREAD

**Issue by brodycj** [sqlcipher/sqlcipher#134]
If I build with static crypto library (`libcrypto.a`) according to the instructions in README.md on my Lubuntu 15.0 amd64 system with the `libssl-dev` package installed:

``` shell
./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC" LDFLAGS="/usr/lib/x86_64-linux-gnu/libcrypto.a"
make
```

The I get the following at the end of my output:

``` shell
libtool: compile:  gcc -DSQLITE_HAS_CODEC -DSQLCIPHER_CRYPTO_OPENSSL -DSQLITE_OS_UNIX=1 -I. -I/home/brodybits/sqlcipher-ch1/src -I/home/brodybits/sqlcipher-ch1/ext/rtree -I/home/brodybits/sqlcipher-ch1/ext/fts3 -D_HAVE_SQLITE_CONFIG_H -DBUILD_sqlite -DNDEBUG -DSQLITE_THREADSAFE=1 -DSQLITE_TEMP_STORE=2 -c sqlite3.c  -fPIC -DPIC -o .libs/sqlite3.o
libtool: compile:  gcc -DSQLITE_HAS_CODEC -DSQLCIPHER_CRYPTO_OPENSSL -DSQLITE_OS_UNIX=1 -I. -I/home/brodybits/sqlcipher-ch1/src -I/home/brodybits/sqlcipher-ch1/ext/rtree -I/home/brodybits/sqlcipher-ch1/ext/fts3 -D_HAVE_SQLITE_CONFIG_H -DBUILD_sqlite -DNDEBUG -DSQLITE_THREADSAFE=1 -DSQLITE_TEMP_STORE=2 -c sqlite3.c -o sqlite3.o >/dev/null 2>&1
./libtool --mode=link gcc -DSQLITE_HAS_CODEC -DSQLCIPHER_CRYPTO_OPENSSL -DSQLITE_OS_UNIX=1 -I. -I/home/brodybits/sqlcipher-ch1/src -I/home/brodybits/sqlcipher-ch1/ext/rtree -I/home/brodybits/sqlcipher-ch1/ext/fts3 -D_HAVE_SQLITE_CONFIG_H -DBUILD_sqlite -DNDEBUG  -DSQLITE_THREADSAFE=1    /usr/lib/x86_64-linux-gnu/libcrypto.a  -o libsqlcipher.la sqlite3.lo -ldl -lcrypto -lpthread  \
     -rpath "/usr/local/lib" -version-info "8:6:8"

*** Warning: Linking the shared library libsqlcipher.la against the
*** static library /usr/lib/x86_64-linux-gnu/libcrypto.a is not portable!
libtool: link: gcc -shared  .libs/sqlite3.o   /usr/lib/x86_64-linux-gnu/libcrypto.a -ldl -lcrypto -lpthread    -Wl,-soname -Wl,libsqlcipher.so.0 -o .libs/libsqlcipher.so.0.8.6
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libcrypto.a(obj_dat.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib/x86_64-linux-gnu/libcrypto.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:545: recipe for target 'libsqlcipher.la' failed
make: *** [libsqlcipher.la] Error 1
```

I see the following problems:
- links with both static and dynamic crypto library
- I get a message that `libcrypto.a` has to be compiled with the `-fPIC` flag (_not_ an issue on the "i386" 32-bit installation)
- warning that I am linking againt a non-portable library (also an issue on my 32-bit installation)

Then I do `make distclean` and also `rm config.h` and then try again with the following command to omit dynamic sqlcipher library from build (see #132 and http://stackoverflow.com/questions/10384464/static-link-openssl-to-sqlcipher as referenced in #132):

``` shell
./configure  --disable-tcl --disable-shared --enable-static=yes --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC" LDFLAGS="/usr/lib/x86_64-linux-gnu/libcrypto.a"
make
```

Then it builds, though with both static and dynamic crypto libs linked!

I would like to recommend the following fixes:
- Add a `configure` option to omit the dynamic crypto lib, also for TomCrypt
- Please _let's_ fix README.md to omit LDFLAGS="-lcrypto" in case of building with the dynamic crypto lib
- Document in README.md how to build static sqlcipher library with _no_ dynamic lib dependencies

I plan to work on PRs over the next week or so to help implement these fixes. For the OpenSSL `-lPIC` issue, ~~I will raise a bug on Ubuntu~~ _I recommend one of us documents a workaround_.

~~A couple~~ _Three_ more minor points before I forget them:
- `distclean` should also remove `config.h` (I will check for any others on OSX) so that `git status --ignored` will show no "ignored" files. I ~~will~~ _may_ issue a PR for this _(see update below)_.
- I would like to see the TCL extension functionality disabled by default, i.e. replace `--disable-tcl` with `--enable-tcl-extension` or something (of course the TCL functionality is needed for automatic testing)
- Document how to regenerage `configure` file (make sure you have the "autotools" installed and use `autoconf`) for people like me who tend to forget

_FYI UPDATE:_ Here is a copy my request to sqlite.org to fix the `distclean` target to remove the generated config.h file: https://groups.google.com/forum/#!topic/sqlcipher/XdAb4HC-4yA (If accepted we should inherit this fix - someday.)

**Comment by sjlombardo** [comment]
I've lost track of a lot of the specific fixed on here and this ticket is super old. However, I know that we fixed several issues with configure and make. The linked ticket was also closed. Changes to configure, TCL, etc will not be relevant after the next release as the SQLite library is moving to away from autoconf to autosetup. I'm going to close this as a result.
