### ISSUE TITLE
Error 26. File is encrypted or is not a database. Possible sqlcipher_export fail.

### ISSUE THREAD

**Issue by COFRATECH** [sqlcipher/sqlcipher#135]
I compiled sqlcipher and it worked like a charm.
However, when trying to migrate SQLcipher 2.x DBs to 3.x using either PRAGMA CIPHER_MIGRATE (though it returns 0) or sqlcipher_export, the news DBs cannot be opened by SQLcipher in my apps. They return the above error code.
Furthermore, when exporting them with a empty string key (i.e. unencrypting them), they can be opened.
Any clue about making this work?

**Comment by developernotes** [comment]
Hello @COFRATECH 

Do you have any non-standard configuration settings for SQLCipher when creating SQLCipher 2.x database files?

**Comment by COFRATECH** [comment]
Hello @developernotes 

My files are plain vanilla SQLCipher files. I can open and browse them using .schema after having declared the correct key through PRAGMA KEY.

**Comment by developernotes** [comment]
Hello @COFRATECH 

Please include a sample of the code you are using to perform either the `cipher_migrate` or `sqlcipher_export(…)` function within your application.

**Comment by COFRATECH** [comment]
Thank you for the reply Nick @developernotes

From the command line:
> ./sqlcipher database.db
SQLCipher version 3.8.10.2 2015-05-20 18:17:19
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> PRAGMA KEY = "my_key";
sqlite> ATTACH DATABASE 'database_v2.db' AS newdb KEY "my_key";
sqlite> SELECT sqlcipher_export('newdb');

sqlite> DETACH DATABASE newdb;
sqlite> .quit

**Comment by COFRATECH** [comment]
As for the cipher_migrate:

$ ./sqlcipher database.db
SQLCipher version 3.8.10.2 2015-05-20 18:17:19
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> PRAGMA KEY = "my_key";
sqlite> PRAGMA CIPHER_MIGRATE;
0
sqlite> .quit

**Comment by developernotes** [comment]
Hello @COFRATECH 

>sqlite> ATTACH DATABASE 'database_v2.db' AS newdb KEY "my_key";

You should not double-quote the key value.

>sqlite> PRAGMA CIPHER_MIGRATE;
0
sqlite> .quit

Can you query any value from the table(s) after the `cipher_migrate` command?

If you are just upgrading the database format from v2 to v3, you will want to use the `PRAGMA cipher_migrate;` command instead of `sqlcipher_export(…);`.

**Comment by COFRATECH** [comment]
Hello @developernotes 

I could query some values just after running the CIPHER_MIGRATE command.

**Comment by developernotes** [comment]
Hello @COFRATECH,

That is great news, that means that the in place migration occurred successfully.

**Comment by COFRATECH** [comment]
Hello @developernotes 

But the app will issue an error message 26 when trying to open the database.
Moreover, no modification seems to occur on the database when I run PRAGMA CIPHER_MIGRATE;
The file modification when I open the information is much older than the time I ran PRAGMA CIPHER_MIGRATE;

**Comment by developernotes** [comment]
We would be glad to take a look at an open source example that replicates the scenario you are seeing.  Can you try replicating it within the SQLCipher test suite available [here](https://github.com/sqlcipher/sqlcipher/blob/master/test/crypto.test)?

**Comment by COFRATECH** [comment]
Should I run this script in the bash?

**Comment by COFRATECH** [comment]
I got a Permission denied when I try to run tester.tcl

**Comment by developernotes** [comment]
Hi @COFRATECH 

A couple of items, make sure when you `./configure` that you include `-ltcl8.5` within your `LDFLAGS`.  Then you will want to run `make testfixture`.  Next, once you have built the test fixture, you will want to run the following command to execute the tests:

```
./testfixture test/crypto.test
```

**Comment by COFRATECH** [comment]
1 errors out of 96 tests
Failures on these tests: export-database

**Comment by COFRATECH** [comment]
export-database...
Error: no such module: fts3

**Comment by developernotes** [comment]
Hello @COFRATECH 

Try running the following to configure:

```
./configure --enable-load-extension --enable-tempstore=yes \
CFLAGS="-DSQLITE_HAS_CODEC -DSQLITE_ENABLE_FTS3" \
 LDFLAGS="-lcrypto -ltcl8.5"
```

**Comment by COFRATECH** [comment]
Hello @developernotes 

I ran the configure script with dynamic linking.
The test fixture provided no error, especially on export-database.
However, the PRAGMA cipher_migrate still doesn't do its job as it leaves the DB unchanged.

**Comment by developernotes** [comment]
Hello @COFRATECH 

Can you provide an open source example that replicates the problem you are seeing?

**Comment by COFRATECH** [comment]
Something odd, I performed a VACUUM on the database.
Now, the PRAGMA CIPHER_MIGRATE will not work and return 1.

**Comment by sjlombardo** [comment]
@COFRATECH can you run "PRAGMA integrity_check" on the database you are attempting to migrate?

**Comment by COFRATECH** [comment]
Hello @sjlombardo 

sqlite> PRAGMA INTEGRITY_CHECK;
ok

**Comment by sjlombardo** [comment]
@COFRATECH I'd like to narrow down whether this is a problem with your specific databases, or something with your environment, since we're not observing the same issues. Would it be possible for you to create a very simple version two database on the command line:

1. check out to the latest version 2 tag (https://github.com/sqlcipher/sqlcipher/tree/v2.2.1)
2. Configure and build as above
3. Create an encrypted database with a single table and some test data

Then, once you have the version 2 database, try to migrate it using version 3 outside of your application. If it doesn't work either, you can send over the test database you are using so we can take a look at it, and try from our environment. If it does work, then we can start narrowing things down a bit, either to your database, or perhaps your application.

**Comment by COFRATECH** [comment]
@sjlombardo 

I downloaded the 2.2.1 version and configured and built it. I could load data into the table, however, when running PRAGMA CIPHER_MIGRATE, sqlcipher returned 1.
My database contains LTR and RTL text, would that be the start of an explanation?

**Comment by COFRATECH** [comment]
OK, I forgot to run PRAGMA CIPHER_MIGRATE just after the PRAGMA KEY, so I ran it again duly, and I returned 0. However, there still is no change performed on the database after I run the CIPHER_MIGRATE pragma.

**Comment by developernotes** [comment]
Hello @COFRATECH 

`PRAGMA cipher_migrate;` was designed to migrate the database file format from a 1.x or 2.x format to the 3.x format.  It was not available until the 3.0.0 release of SQLCipher.  In order to migrate a database file that was created using the 1.x or 2.x format, you would need to have either a SQLCipher shell, or library that reports a `PRAGMA cipher_version;` >= `3.0.0`.  Your statement above implies you tried to run the `PRAGMA cipher_migrate` command from the 2.2.1 version of SQLCipher which would not work.  If that is the case, can you try your steps again with a SQLCipher shell based on master?

**Comment by COFRATECH** [comment]
@developernotes 

I tried to run PRAGMA CIPHER_MIGRATE from the 3.3.1 shell. It returned 0 but no changes were performed on the database.

**Comment by COFRATECH** [comment]
@developernotes 
I tried the following steps:
1. Configure and build the master
2. Run PRAGMA KEY and PRAGMA CIPHER_MIGRATE in the shell.
No change on the database occurred.

**Comment by developernotes** [comment]
Hello @COFRATECH 

When you provided the key, then ran `PRAGMA cipher_migrate;`, was that database file itself built using SQLCipher 2.x?  Can you provide the database file that you are trying to migrate?

**Comment by COFRATECH** [comment]
There seems to be a problem with the database, indeed. I will try to fix this and keep you updated.
Thank you very much for the support.

**Comment by COFRATECH** [comment]
Hello @developernotes 

I created a very simple db with only one line of data and tried to open it in the app in place of the former db.
I still get the error code = 26 message.
10-07 02:23:23.016: I/Database(635): sqlite returned: error code = 26, msg = file is encrypted or is not a database
10-07 02:23:23.016: E/Database(635): CREATE TABLE android_metadata failed
10-07 02:23:23.036: E/Database(635): Failed to setLocale() when constructing, closing the database
10-07 02:23:23.036: E/Database(635): net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: create locale table failed

**Comment by sjlombardo** [comment]
@COFRATECH it would be helpful if you could provide the example database you are using so we could take a look at it. Can you make it available to us?

**Comment by COFRATECH** [comment]
Do you want me to send the test file to your email address?

**Comment by developernotes** [comment]
Hello @COFRATECH 

You can include a link here in the Github issue or send it in with the password to [support@zetetic.net](mailto:support@zetetic.net).

**Comment by COFRATECH** [comment]
Hello @developernotes 
I just sent by email the file and password.
Thank you for your support.

**Comment by developernotes** [comment]
Hello @COFRATECH 

We have received the example database and password and have sent you an email regarding the issue.  Please let us know if you have any further questions.  Thanks!

**Comment by COFRATECH** [comment]
Hello @developernotes 
Actually, the right single quote mark was unduly entered when I typed the database password on Apple's TextEdit.
I use plain single quote marks in my app, and it still does not work...
Thanks!

**Comment by developernotes** [comment]
Hello @COFRATECH 

There may be another issue with your application, using the SQLCipher command line shell, we were able to correctly open the database when we used single quotes.

**Comment by JayeshMohan4** [comment]
Hi Sir, I need a solution. I have encrypted DB file in asset directory.I encrypt the DB through SQLiteDB Browser. I am reading the data from DB through SQLiteAssetHelper class but it gives error "file is encrypted or is not a database". Is there any option to decrypt my DB in asset directory for reading data?.  I didin't get any solution from google.

**Comment by developernotes** [comment]
Hi @JayeshMohan4 

These questions are best suited for the SQLCipher [discuss](https://discuss.zetetic.net/c/sqlcipher) site. You will need to extract the database to a permanent location, see [this](https://github.com/sqlcipher/sqlcipher-android-tests/blob/master/src/main/java/net/zetetic/ZeteticApplication.java#L63-L77) example.
