### ISSUE TITLE
Backup results in seg fault

### ISSUE THREAD

**Issue by austinjp** [sqlcipher/sqlcipher#136]
Hi there.

Running a backup using `.backup` results in instant segfault.

I've just installed sqlcipher using apt-get on Ubuntu 14.04. I created a tiny database with one table (as per the instructions as https://guardianproject.info/code/sqlcipher/ ) and then tried to run a backup using `.backup`. Unfortunately it seg-faulted and the backup file was empty.

Running this in gdb produces the following:

```
sqlite> .backup test.db backup.db

Program received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/x86_64/strlen.S:106
106     ../sysdeps/x86_64/strlen.S: No such file or directory.
```

As mentioned, I installed from apt-get rather than compiling. Happy to help with further debugging if I can.

**Comment by developernotes** [comment]
Hi @austinjp 

The `.backup` command creates a plain text SQLite database, is that what you are attempting to do?  In that case you would need to open and key a SQLCipher database.  SQLCipher doesn't modify the `.backup` command behavior in the command line interface.  You may wish to review the [`sqlcipher_export(…);`](https://www.zetetic.net/sqlcipher/sqlcipher-api/#sqlcipher_export) convenience function instead.

**Comment by austinjp** [comment]
I confess naivety in all things SQLite/SQLCipher. I was just running through tests with a fresh install in preparation for using with a personal project. This was my first test, and it gave a seg-fault so I thought it would be best reported :)

`sqlcipher_export()` does look suitable for my needs, many thanks.

**Comment by developernotes** [comment]
Hello @austinjp 

Glad to hear `sqlcipher_export(…)` will fit your needs.  Take care!
