### ISSUE TITLE
First time schema change invalidates other open connections to same DB

### ISSUE THREAD

**Issue by borrrden** [sqlcipher/sqlcipher#138]
This is possibly related to issue #95 but I am able to reproduce this with just the native command line on OS X.  Do the following using two sqlcipher command line programs built from v3.3.1 (here labeled s1 and s2) opened fresh on the same new (non-existent, or otherwise not touched by previous operations) file:

s1> PRAGMA key="john";
s2> PRAGMA key="john";
s1> CREATE TABLE foo (bar TEXT);
s2> SELECT * FROM foo;
Error: file is encrypted or is not a database

I've narrowed it down to this:

Altering the schema for the first time makes any other open connections unreliable.  After the first change, for some reason, if you close and reopen the second connection everything is back to normal and any further changes do not cause the same effect.  Furthermore, before the first change you can also run queries without getting the error.  Here is one example (s1 and s2 refer to two instances of sqlcipher command line)

s1> PRAGMA key="john";
s2> PRAGMA key="john";
s1> SELECT * FROM sqlite_master; // succeeds
s2> SELECT * FROM sqlite_master; // succeeds
s1> CREATE TABLE foo (bar TEXT);
s1> SELECT * FROM sqlite_master;
table|foo|foo|2|CREATE TABLE foo (bar TEXT)
s2> SELECT * FROM sqlite_master;
Error: file is encrypted or is not a database
s2> .q
\> ./sqlcipher \<filename\>
s2> PRAGMA key="john";
s2> SELECT * FROM sqlite_master;
table|foo|foo|2|CREATE TABLE foo (bar TEXT)

Further changes after reopening have no problem:

s1> CREATE TABLE bar (foo TEXT);
s2> SELECT * FROM sqlite_master;
table|foo|foo|2|CREATE TABLE foo (bar TEXT)
table|bar|bar|3|CREATE TABLE bar (foo TEXT)

If this is expected behavior, or incorrect usage then let me know so I can plan on how to deal with it.  I am trying to drop in SQLCipher on a library I am working on that is using plain SQLite using this sort of connection segregation model.

P.S. Just for a sanity check, I ran the same commands without setting a key as a control and it worked as expected:

// without PRAGMA key
s1> CREATE TABLE foo (bar TEXT);
s1> SELECT * FROM sqlite_master;
table|foo|foo|2|CREATE TABLE foo (bar TEXT)
s2> SELECT * FROM sqlite_master;
table|foo|foo|2|CREATE TABLE foo (bar TEXT)

**Comment by developernotes** [comment]
Hello @borrrden 

The reason you are seeing a difference when the file does not exist is although you are providing the same key material, since the database does not exist each SQLCipher command line shell will will compute a unique a per database salt.  This is the behavior that prevents two databases with the same password from having the same encryption key.

If you wish, you can specify the same database salt value when you provide a key via the [raw hex key format](https://www.zetetic.net/sqlcipher/sqlcipher-api/#key).  As an example, trying your steps above with the following key produces different results:
```
PRAGMA key = "x'2DD29CA851E7B56E4697B0E1F08507293D761A05CE4D1B628663F411A8086D993D761A05CE4D1B628663F411A8086D99'";
```
In the key above, the last 32 characters of the raw key represent the database salt value.

**Comment by borrrden** [comment]
Thanks for the explanation.  Ironically I am already doing that in the library project and facing a different error (second connection reports "no such table" etc) and thought that this might be related.  I'll come back when I can simply reproduce that one.

**Comment by borrrden** [comment]
Well, it might be a while before that happens so I'll close this until I get some new information (switched to another task at the moment).

**Comment by developernotes** [comment]
Hello @borrrden 

Is it possible that you are using a raw hex key, but not supplying the salt at the end of the hex key?

**Comment by borrrden** [comment]
@developernotes Is that required?  The link that you provided doesn't seem to mention that but now I noticed that your hex string is 96 characters long instead of 64.

**Comment by developernotes** [comment]
Hello @borrrden 

In the approach you are suggesting above, yes it would be.  I think if you were to adjust your scenario such that the file exists by the time the secondary instance is opened you would see different results and you could then use a single 64 byte raw hex key.

**Comment by borrrden** [comment]
@developernotes I'm not digging up this issue, I've been able to implement it as you said since then but I'm curious about the salt now.  If I provide a 64 byte raw key (that got derived with my own salt), then what value gets set in the database file and is it used?  I suppose the answer is "random bytes" and "yes"?

**Comment by developernotes** [comment]
Hello @borrrden 

>If I provide a 64 byte raw key (that got derived with my own salt), then what value gets set in the database file and is it used? I suppose the answer is "random bytes" and "yes"?

There are two scenarios in which you can provide a raw hex key within SQLCipher. In the first, you would provide a value in the format of `x'hexvalue'`, where the hex value is 64 characters (i.e., 256 bit key). In that scenario, SQLCipher will skip the key derivation process, however it will generate a random salt value used for computing the HMAC key.

In the second scenario, you would provide a raw key again in the format of `x'hexvalue'` where the hex value is 92 hex characters (i.e., 256 bit key + 16 byte salt). The key derivation process would also be skipped, however SQLCipher would not generate a random salt for computing the HMAC key, instead it would used the provided salt from the extended raw key.
