### ISSUE TITLE
Memory leak in sqlite3_step

### ISSUE THREAD

**Issue by sahara108** [sqlcipher/sqlcipher#139]
<img width="261" alt="screen shot 2015-10-22 at 10 50 32 am" src="https://cloud.githubusercontent.com/assets/1707951/10656612/c92613fc-78aa-11e5-9474-3b57b78089bd.png">

**Comment by sjlombardo** [comment]
Hello @sahara108. It looks like you are using [Encrypted Core Data](https://github.com/project-imas/encrypted-core-data), is that correct? A few questions:

1. Can you please attempt to reproduce this outside of Encrypted Core Data? For instance, create a test that calls prepares a statement and calls sqlite3_step directly to see if you see the same results. If so, please provide us with the reference code.
2. Please provide information on what version of SQLCipher you are using. This should be available by calling PRAGMA cipher_version;

**Comment by sahara108** [comment]
Thank you for your response. I am using EncryptedCoreData. And the version is 3.1.0.

**Comment by sjlombardo** [comment]
Thank you for the information. Can you please reproduce the issue with a standalone statement and sqlite3_step? If the issue can't be reproduced in a standalone test, it might be a result of an issue with the Encrypted Core Data wrapper, and not SQLCipher itself.

**Comment by sahara108** [comment]
Ok. I will try to reproduce it, may be in the end of this week. I will get back to you as soon as I have the result.

**Comment by shaozi** [comment]
I also observed similar memory issue in my app. I am using encrypted-core-data too. How is the progress?

**Comment by sjlombardo** [comment]
Hello @shaozi - we still haven't received any confirmation about whether this is an issue in a standalone tests using sqlite3_step, or if it is somehow related to the Encrypted Core Data wrapper. If you are experiencing this now, could you try to reproduce the issue with a standalone statement and sqlite3_step?

**Comment by sahara108** [comment]
Re profile with the latest iOS version, 9.2 and the leak is gone. I haven't change anything with the code. Have no idea.

**Comment by sjlombardo** [comment]
Hello @sahara108 thanks for letting us know this issue is resolved.
