### ISSUE TITLE
sqlite3_key not encrypting database

### ISSUE THREAD

**Issue by chtombleson** [sqlcipher/sqlcipher#140]
Im using the c api and calling sqlite3_key function to key & encrypt the database but if use the sqlcipher command line app the database is unencrypted. I'm not sure why.

    sqlite3 *db;

    int res = sqlite3_open("test.db", &db);

    if (res != SQLITE_OK) {
        printf("Cannot open database\n");
        exit(1);
    }

    res = sqlite3_key(db, "testing", 7);

    if (res != SQLITE_OK) {
        printf("Cannot key database\n");
        exit(1);
    }
    
    if (db != NULL) {
        sqlite3_close(db);
    }

If I open test.db up using the sqlcipher command line app it is not encrypted. I have a feeling I'm missing something simple here.

Any help would be greatly appreciated.

**Comment by developernotes** [comment]
Hello @chtombleson 

Did the `test.db` file already exist as a plain text SQLite database?  If so, you will want to look into using the [`sqlcipher_export(…)`](https://www.zetetic.net/sqlcipher/sqlcipher-api/#sqlcipher_export) convenience function to export your plain text database to a SQLCipher encrypted database file.

**Comment by chtombleson** [comment]
@developernotes Thanks for the quick reply.

The test.db file is created by the C program. After I run the C program if I open up the test.db file using the sqlcipher program the database is not encrypted.

**Comment by developernotes** [comment]
Hi @chtombleson 

The sample source you posted above does not force any content to be created within the file.  Are you adding a schema and/or data to the database once you create and key the database, before you close it?

**Comment by chtombleson** [comment]
Thanks @developernotes, if I create my schema before closing the database it is now encrypted.

**Comment by developernotes** [comment]
Glad to hear that resolved the issue - take care!

**Comment by brodybits** [comment]
Just a suggestion from the [peanut gallery](https://en.wikipedia.org/wiki/Peanut_gallery) to get this documented when you guys get a chance:)

**Comment by developernotes** [comment]
Hi @brodybits - what part specifically do you think needs further documentation?

**Comment by sjlombardo** [comment]
@brodybits We've just published a new SQLCipher FAQ item about this. Hopefully it helps to clear up some confusion.

https://discuss.zetetic.net/t/how-to-encrypt-a-plaintext-sqlite-database-to-use-sqlcipher-and-avoid-file-is-encrypted-or-is-not-a-database-errors/868

**Comment by brodybits** [comment]
@sjlombardo thanks for adding the FAQ item.

To be honest, what *I* found especially confusing was that someone could open a database and do sqlite3_key(), but the database is *still* not encrypted if someone closes the database without adding any data. Also, am I right to assume the same thing if someone opens a database, executes a PRAGMA key statement, then closes the database without actually adding any data?

I highly recommend a clear notice or warning statement in the following sections of the API page:
- https://www.zetetic.net/sqlcipher/sqlcipher-api/#key (["PRAGMA key"](https://www.zetetic.net/sqlcipher/sqlcipher-api/#key)) section (assuming that I am not mistaken)
- https://www.zetetic.net/sqlcipher/sqlcipher-api/#sqlite3_key

I would also recommend a couple more things on the https://www.zetetic.net/sqlcipher/sqlcipher-api/ page:
- a note or tip with a pointer where to find the documentation about how to encrypt an existing sqlite database, which I *did* already find in a post from December 2009: https://www.zetetic.net/blog/2009/12/29/how-to-encrypt-a-plaintext-sqlite-database-to-use-sqlcipher.html
- a pointer to where a new user should find the FAQ

**Comment by sjlombardo** [comment]
@brodybits If an application opens a database, calls sqlite3_key, and then immediately closes the database without adding any data, a SQLCipher database doesn't really exist at that point. Because nothing was written to the database, it is just a zero length file sitting on the file system.

``` bash
zenzic% ls -al test.db
ls: test.db: No such file or directory
zenzic% ./sqlcipher test.db
SQLCipher version 3.8.4.3 2014-04-03 16:53:12
sqlite> pragma key = 'test123';
sqlite> .q
zenzic% ls -al test.db
-rw-r--r--  1 sjlombardo  501  0 Nov  9 12:48 test.db
```

Now from there, if the database is opened again, it is still up to the application to provide a key. If they do, then the database will be encrypted as soon as a write occurs:

``` bash
zenzic% ./sqlcipher test.db
SQLCipher version 3.8.4.3 2014-04-03 16:53:12
sqlite> pragma key='test123';
sqlite> create table t1(a,b);
sqlite> insert into t1(a,b) values (1,2);
sqlite> .q
zenzic% hexdump -C test.db| head -5
00000000  a0 d0 e9 a4 b6 23 15 13  04 3c ac d2 73 d9 ff d1  |.....#...<..s...|
00000010  1f e8 81 1e 9a 45 2c 8b  99 6a 5f 8b d2 2a 50 6b  |.....E,..j_..*Pk|
00000020  2c 2e 4b ec ad b5 7d 7d  98 08 dc 7c af 27 8d 6d  |,.K...}}...|.'.m|
00000030  10 63 bf ac b2 82 1f df  79 f0 92 2a 9b b1 f2 ef  |.c......y..*....|
00000040  5e 8f 82 73 d4 23 82 96  1c 66 aa 28 d3 91 d7 31  |^..s.#...f.(...1|
```
Once the write occurs, the database can't be opened without the key

``` bash
zenzic% ./sqlcipher test.db
SQLCipher version 3.8.4.3 2014-04-03 16:53:12
sqlite> .schema
Error: file is encrypted or is not a database
sqlite> .q
zenzic% ./sqlcipher test.db
SQLCipher version 3.8.4.3 2014-04-03 16:53:12
sqlite> pragma key = 'test123';
sqlite> select * from t1;
1|2
```

Of course, if you were to open any zero length file without a key and then insert some data into it, then it would be treated as a standard SQLite database. That is because this is the same as creating a new database without a key.

``` bash
zenzic% ls -al this-is-not-a-database.txt
ls: this-is-not-a-database.txt: No such file or directory
zenzic% touch this-is-not-a-database.txt
zenzic% ls -al this-is-not-a-database.txt
-rw-r--r--  1 sjlombardo  501  0 Nov  9 12:59 this-is-not-a-database.txt
zenzic% sqlite3 this-is-not-a-database.txt
SQLite version 3.8.5 2014-08-15 22:37:57
Enter ".help" for usage hints.
sqlite> create table t1(a);
sqlite> insert into t1(a) values ('now it is a database');
sqlite> .q
zenzic% hexdump -C this-is-not-a-database.txt
00000000  53 51 4c 69 74 65 20 66  6f 72 6d 61 74 20 33 00  |SQLite format 3.|
00000010  10 00 01 01 00 40 20 20  00 00 00 02 00 00 00 02  |.....@  ........|
00000020  00 00 00 00 00 00 00 00  00 00 00 01 00 00 00 04  |................|
00000030  00 00 00 00 00 00 00 00  00 00 00 01 00 00 00 00  |................|
00000040  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 02  |................|
00000060  00 2d e6 05 0d 00 00 00  01 0f dc 00 0f dc 00 00  |.-..............|
00000070  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000fd0  00 00 00 00 00 00 00 00  00 00 00 00 22 01 06 17  |............"...|
00000fe0  11 11 01 31 74 61 62 6c  65 74 31 74 31 02 43 52  |...1tablet1t1.CR|
00000ff0  45 41 54 45 20 54 41 42  4c 45 20 74 31 28 61 29  |EATE TABLE t1(a)|
00001000  0d 00 00 00 01 0f e8 00  0f e8 00 00 00 00 00 00  |................|
00001010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00001fe0  00 00 00 00 00 00 00 00  16 01 02 35 6e 6f 77 20  |...........5now |
00001ff0  69 74 20 69 73 20 61 20  64 61 74 61 62 61 73 65  |it is a database|
00002000
```

Therefore, I'm not really sure what would warrant a warning in this case. If the application calls sqlite3_key when opening a database before writing any data, then the data will be encrypted. If the application does not write any data to the file, then there is nothing in the file to encrypt (even if we wanted to to), and thus no information disclosure. 

Let me know if this makes sense or if you disagree with the above analysis.

With regard to the FAQ items, that blog post from 2009 is quite dated. I'll make a note to update it to link to the new FAQ. It's also a good idea to add a link to the FAQ from the API and documentation page. We'll take care of that soon.

**Comment by brodybits** [comment]
> If an application opens a database, calls sqlite3_key, and then immediately closes the database without adding any data, a SQLCipher database doesn't really exist at that point. Because nothing was written to the database, it is just a zero length file sitting on the file system.

Right. I learned that one through experience when working on some simple tests on the sqlite plugin. IMHO that _could_ still be confusing for a newcomer. Just my $0.02 worth.

I do want to thank you guys for your care in keeping the documentation and FAQ up to date.

**Comment by sinall** [comment]
I was confused too, maybe we could add some metadata into database when doing sqlite3_key.

**Comment by sabiks** [comment]
I have a database encrypted using "SQLite DB Browser", and I am trying to decrypt using sqlite3_key() in the code. But the function returns value SQLITE_MISUSE (21 /* Library used incorrectly */). I am using the correct passphrase used for encrypting the db. 
What could be the reason for the error return from sqlite3_key() function? 
I appreciate your help on this. 
    const char* key = "test";
	if ((rc = sqlite3_open (dbname, &db)) != SQLITE_OK)
	{
		printf ("sqlite3 error:%d", rc);
		return -1;
	}
      if((rc = sqlite3_key(db, key, strlen(key))) != SQLITE_OK)
    {
        printf("failed to key database: error %d\n", rc);
    }

**Comment by developernotes** [comment]
Hello @sabiks 

Did you build SQLCipher yourself? If so, you might try opening the database with the SQLCipher command line shell first to see if you are able to open the database file.
