### ISSUE TITLE
Push podspec for the latest 3.3.1 release

### ISSUE THREAD

**Issue by cnoon** [sqlcipher/sqlcipher#141]
Hello everyone!

First off, I want to say thanks for the awesome product! SQLCipher makes database encryption crazy simple. In order to make it a bit easier to use the latest version, would it by possible for someone to push an updated podspec for the 3.3.1 release? Here's a link to the current [podspec](https://github.com/CocoaPods/Specs/blob/5e07088fac755758513e8533b934b779361fc3b1/Specs/SQLCipher/3.1.0/SQLCipher.podspec.json) which looks like it's about a year and a half out-of-date. Since CocoaPods is one of the main ways iOS developers bring dependencies into their projects, it would be awesome if we could get an updated version. It would also be cool if it could support iOS, OS X, tvOS and watchOS while you're at it.

I'd be glad to help out in any way I can. If I was more familiar with the project, I would put one together myself. But I'd prefer to have the experts do it.

Thanks in advance! 🎉

**Comment by cnoon** [comment]
After continuing to dig into this, it appears that there are some issues getting SQLCipher to work as a framework on iOS with CocoaPods. What I'm trying to do is add SQLCipher as a dependency to my own Swift library that wraps SQLite. When using CocoaPods with Swift, your dependencies will be built as frameworks, not as static libs. This seems to be the root of the problem that I'm running into.

I've been meddling with podspecs to pull down the latest 3.3.1 version and I'm managed to do so. I've also modified to the `./config` script to match the 3.3.1 release in the podspec. I'm fully able to build the SQLCipher framework using CocoaPods, but I'm deadlocking when attempting to set the encryption key. Here's a quick screenshot of the deadlock.

![screen shot 2015-11-15 at 8 26 06 pm](https://cloud.githubusercontent.com/assets/169110/11174352/2abc0d80-8bd7-11e5-8c79-4644657f5b84.png)

On a different note, if I use the static lib as a submodule to link to my framework I don't run into this issue. While this is a temporary workaround, it's certainly not a long-term solution for using SQLCipher in Swift.

I'm going to continue to dig in here, but I'm a bit out of my depth with this locking issue. Any help would be greatly appreciated!

**Comment by developernotes** [comment]
Hello @cnoon 

Thank you for your interest in SQLCipher.  Unfortunately we do not maintain the podspec for SQLCipher, you might consider creating an [issue](https://github.com/CocoaPods/Specs/issues) within the CocoaPods project to discuss updating their podspec to our latest release.

With regard to your crash, SQLCipher is a superset of SQLite, so you will want to make sure you are not including any SQLite dylibs within your project if you are including SQLCipher.  Does your application include `-DSQLITE_HAS_CODEC`, that flag is required for access to the keying API in SQLCipher.

**Comment by cnoon** [comment]
Thanks for getting back to me @developernotes! After digging in some more, I found all sorts of small issues that were causing framework version of sqlcipher to not work. Mainly they were just new settings that needed to be updated since the podspec syntax has changed a bit over the last year and a half.

I've managed to get a new podspec crafted and submitted a [PR #13639](https://github.com/CocoaPods/Specs/pull/13639) against the CocoaPods Specs repo. If you could possibly give that a thumbs up at some point I'd greatly appreciate it. I would assume they'll merge it without it since it passes all the `pod spec lint` checks, but it's always nice as a maintainer to see a thumbs up from another maintainer before taking action on someone's behalf.

With that said, I'm going to attempt to restructure the current Xcode project a bit to bring it some new life. The podspec supports iOS 8.0+, OSX 10.9+, tvOS 9.0+ and watchOS 2.0+. Seems to me that the Xcode project should support those same versions with frameworks. Then you can get the same behavior between CocoaPods, Carthage and Submodules. I'm going to start putting this together and will hopefully have a PR up tonight or tomorrow.

**Comment by cnoon** [comment]
PR is up in #142. I'm going to go ahead and close this issue out since it's completed. If you could give the podspec PR a thumbs up, I think they'll happily merge it. Thanks again! 🍻

**Comment by orta** [comment]
@developernotes just to confirm, would you feel comfortable with us giving access for @cnoon to push a version to CocoaPods?

**Comment by sjlombardo** [comment]
@orta @cnoon we're discussing PR #13639 and PR #142  internally and should be back in touch soon. Thanks for your patience.

**Comment by cnoon** [comment]
Just wanted to ping this before everybody heads out for the holidays. Any updates?

**Comment by sjlombardo** [comment]
Hi @cnoon thanks so much for your patience and for this recent work on SQLCipher. Before merging we need to have a contributor agreement on file. I'll be contacting you directly via email about this shortly. Once we have the CLA in place, our intent would be to perform a final review and test, then merge the changes in #142. With regard to the CocoaPods changes, we would also provide a conditional approval for PR #13639. The main condition on that request would be that we would take over maintenance of the podspec on an ongoing basis, so that we can keep it up to date with other official releases. This is generally better from both a security and scheduling perspective, so I hope you won't mind.

**Comment by cnoon** [comment]
Hi @sjlombardo, I'll be working through the CLA most likely today. As for the podspec, if your team wants to own the podspec publishing, that would be awesome! I merely created one due to the original response from @developernotes.

**Comment by hartbit** [comment]
Sorry for hijacking this thread, but I'm using Cocoapod's podspec for 3.3.1 by @cnoon and I'm experiencing the same deadlock he pointed to above. Perhaps someone from SQLCipher (or @cnoon ) can help me understand why this is happening.

I've stepped through the code and entered on:

```c
void sqlcipher_activate() {
  sqlite3_mutex_enter(sqlite3_mutex_alloc(SQLITE_MUTEX_STATIC_MASTER));

  if(sqlcipher_provider_mutex == NULL) {
    /* allocate a new mutex to guard access to the provider */
    sqlcipher_provider_mutex = sqlite3_mutex_alloc(SQLITE_MUTEX_FAST); // DEADLOCKING HERE
  }
```

Basically, what is happening is that sqlite3_mutex_alloc(SQLITE_MUTEX_FAST) is entering the SQLITE_MUTEX_STATIC_MASTER mutex. But that mutex has already been entered a few lines above. Hence the deadlock.

Any ideas?

**Comment by johnryan** [comment]
@cnoon i'm seeing the same issue you noticed in your screenshot above when using FMDB with SQLCipher and swift. Cocoapods says i'm using 3.3.1, did you get this working? If so, any guidance would be greatly appreciated.

**Comment by hartbit** [comment]
@johnryan I found the issue. My project depends on FMDB's SQLCipher podspec. Due to cocoapods details about subspects inheritance, it would link with the system sqlite3 library, instead of using the SQLCipher framework. I fixed it by hacking a podspec that does not declare the sqlite library.

**Comment by johnryan** [comment]
@hartbit Awesome, that what I was seeing as well. How did you hack the podspec to reference the correct sqlite version? Just removing the sqlite3 dependency from the main podspec?

**Comment by hartbit** [comment]
Yes. Unfortunately, it will break the standard subspec, but should fix your issue.

**Comment by johnryan** [comment]
@hartbit Not sure if this will work for you but I originally had both:
pod 'FMDB' , '2.6'
and
pod 'FMDB/SQLCipher', '2.6'

I removed the 'FMDB' one and ran another pod install...now it seems to be linking as intended.
