### ISSUE TITLE
Apple - TVOS integration issues.

### ISSUE THREAD

**Issue by srkrambo** [sqlcipher/sqlcipher#143]
I use SQLite.swift which internally uses sqlcipher. 

And I get following error when I try to integrate for TVOS
I get following errors when trying to build for TV os

"Target 'SQLiteCipher.swift' of project 'Pods' was rejected as an implicit dependency for 'SQLiteCipher.framework' because it doesn't contain platform 'appletvsimulator' in its SUPPORTED_PLATFORMS 'iphonesimulator, iphoneos'"

There is a similar error for "Target 'SQLCipher' of project 'Pods' was rejected as an implicit dependency for 'SQLCipher.framework' because it doesn't contain platform 'appletvsimulator' in its SUPPORTED_PLATFORMS 'iphonesimulator, iphoneos'".

Here in Cocoapods, http://blog.cocoapods.org/CocoaPods-0.39/
Its mentioned we need to explicitly add in podspec to support TV OS.

https://github.com/stephencelis/SQLite.swift/issues/272

The author mentioned the following. 
" it looks like the upstream version of SQLCipher hasn't had its project file updated for tvOS or watchOS support."
Is there anything that can be done for this?

**Comment by developernotes** [comment]
Hello @srkrambo 

We are currently reviewing a pull request (#142) that would add support for tvOS and watchOS.

**Comment by rajkumariosdev** [comment]
Awesome. Looking forward to it.

**Comment by sjlombardo** [comment]
Hello @rajkumariosdev - we've merged  PR #142 into the prerelease branch for the project. You can access the changes there, and we'll also include these in the next full release.
