### ISSUE TITLE
How to migrate my 2.x db file in iOS program

### ISSUE THREAD

**Issue by sunnylymexxl** [sqlcipher/sqlcipher#144]
I use sqlite3_key api to entropy my db file with an old version static library. Recently I have to make my program support arm64, so I compile a new library with sqlcipher v3.0.0. But I can't open the db file with error code 26, please help me.THX!

I have a doubt. When i started creating my app i had installed SQLCIPHER version 2.1.4 . but with the introduction of ios9 i upgraded my app to unified api projects and i am using SQLCipher 3.0.3. But when i override the app on my previous app. then it is crashing citing sqlciper error. When i looked into solutions i found we have to use the command "PRAGMA ciper _migrate" but i am unable to understand where to write it. Please help me

**Comment by developernotes** [comment]
Hello @sunnylymexxl 

The [`PRAGMA cipher_migrate;`](https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_migrate) command should be run immediately following your call to `sqlite3_key(…)`.  We provide free support on the public SQLCipher discuss site [here](https://discuss.zetetic.net/c/sqlcipher).
