### ISSUE TITLE
Update to sqlite 3.9.2

### ISSUE THREAD

**Issue by brodybits** [sqlcipher/sqlcipher#145]
I just got a request for this on my free Cordova plugin at: https://gitter.im/litehelpers/Cordova-sqlite-storage?at=565e659e2488cc807874937d

It seems like there are some more enhancements such as some micro-optimizations, FTS5, optional json1 extension included in the amalgamation, etc.

**Comment by developernotes** [comment]
Hi @brodybits 

We will be looking at merging the current SQLite 3.9.2 upstream into SQLCipher soon.  We generally wait a month of so following a SQLite release to allow for any bugs to bubble up before we merge.
