### ISSUE TITLE
'openssl/rand.h' file not found

### ISSUE THREAD

**Issue by gilnuy** [sqlcipher/sqlcipher#146]
i was worred by one whole day.
1.download v 3.3.1
2.unzip
3.cd folder
4../configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC" LDFLAGS="-lcrypto"  
5.make

error appear

i want to build a mac exe application to encrypt a .db file. then i can integarate [sqlcipher for ios](https://www.zetetic.net/sqlcipher/ios-tutorial/) to my project.
help!
help!
help!

**Comment by developernotes** [comment]
Hello @gilnuy 

SQLCipher uses OpenSSL by default, however it appears the OpenSSL headers are not available on your system.  This may be the case if you are running El Capitan, I believe they have removed those headers with the latest OS release.

Since you are first targeting OS X, you will want to specify the CommonCrypto provider instead of OpenSSL:

```
./configure --enable-tempstore=yes --with-crypto-lib=commoncrypto CFLAGS="-DSQLITE_HAS_CODEC -DSQLITE_TEMP_STORE=2"
```

**Comment by gilnuy** [comment]
i'll try it .thx

**Comment by gilnuy** [comment]
hi.
when i do this 
```
./sqlcipher test2.db
```
i get error:
```
dyld: Symbol not found: _kSecRandomDefault
  Referenced from: /Users/pro/Downloads/sqlcipher-3.3.1/.libs/libsqlcipher.0.dylib
  Expected in: flat namespace
 in /Users/pro/Downloads/sqlcipher-3.3.1/.libs/libsqlcipher.0.dylib
Trace/BPT trap: 5
```
i geuss it may need securty.framework.
how can i link that?

**Comment by developernotes** [comment]
Hello @gilnuy 

Yes, it looks like the additional arguments were clipped in the previous post.  Here is the full configure which will include the Security framework:

```
./configure --enable-tempstore=yes --with-crypto-lib=commoncrypto \
CFLAGS="-DSQLITE_HAS_CODEC -DSQLITE_TEMP_STORE=2" \
LDFLAGS="-framework Security"
```

**Comment by gilnuy** [comment]
thank you so much!
i did it.

**Comment by telander** [comment]
I do the configuration like this: 
`./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC" LDFLAGS="-lcrypto" CPPFLAGS="-I/usr/local/opt/openssl/include"` 
and it works
