### ISSUE TITLE
How to encrypt a database

### ISSUE THREAD

**Issue by gilnuy** [sqlcipher/sqlcipher#147]
I already have a stored data database, like: boney.db
then i integrate the project into my project. and  i try to encrypt it. but it doesn't work.
this is my code:
```
 sqlite3 *db;
        if (sqlite3_open([path UTF8String], &db) == SQLITE_OK) {
            const char* key = [@"123456" UTF8String];
            sqlite3_key(db, key, (int)strlen(key));
            if (sqlite3_exec(db, (const char*) "SELECT count(*) FROM sqlite_master;", NULL, NULL, NULL) == SQLITE_OK) {
                NSLog(@"Password is correct, or a new database has been initialized");
            } else {
                NSLog(@"Incorrect password!");
            }
            sqlite3_close(db);
        }
```
log in consol is``` Incorrect password!```

so ,how can i encrypt a database which has stored data.

**Comment by sjlombardo** [comment]
Hello @gilnuy - please see [this article](https://discuss.zetetic.net/t/how-to-encrypt-a-plaintext-sqlite-database-to-use-sqlcipher-and-avoid-file-is-encrypted-or-is-not-a-database-errors/868), it provides the information you need.
