### ISSUE TITLE
SQLCipher installed as pod suppress #warnings in project

### ISSUE THREAD

**Issue by RishatShamsutdinov** [sqlcipher/sqlcipher#148]
I have a lot of #warnings defined in my project. I've installed SQLCipher pod and they are gone. Solution: remove -W* from xcconfig in SLQCipher pod. Should it be fixed?

**Comment by developernotes** [comment]
Hello @RishatShamsutdinov,

I'm sorry for the late reply, are you still working through the issue you described above?

**Comment by RishatShamsutdinov** [comment]
Hi @developernotes!

I have to add the following OTHER_FLAGS (they duplicates my project settings) to my project settings:
 ```-Wint-conversion
-Wambiguous-macro
-W#warnings
-Wunused-const-variable
-Wunused-function
-Wunreachable-code
-Wconversion```

**Comment by developernotes** [comment]
Hello @RishatShamsutdinov 

We are preparing a new update to the podspec related to our 3.4.0 release of SQLCipher.  We will remove those warning flags as well.  Thanks!
