### ISSUE TITLE
iOS Deadlock with FMDB

### ISSUE THREAD

**Issue by johnryan** [sqlcipher/sqlcipher#154]
Not sure if this is the right repo to file this issue, but seeing a deadlock when calling: sqlite3_key

here's a link to a project demonstrating the issue: https://github.com/johnryan/sqlcipher-deadlock

Thanks,
John

**Comment by sjlombardo** [comment]
Hi @johnryan Thanks for submitting this and preparing a demonstration project. We'll take a look at this shortly and see if there is anything obvious that might be going awry.

**Comment by johnryan** [comment]
@sjlombardo Thanks, from what I can tell so far the FMDB code isn't using the SQLCipher sqlite.c file when it's being used as a framework. Please let me know if I can be of any more assistance.

**Comment by johnryan** [comment]
@sjlombardo I think I may actually have figured out the issue...I was originally installing both FMDB pods:
pod 'FMDB' , '2.6' and pod 'FMDB/SQLCipher', '2.6'

This caused some sqlite linking issues, by removing the 'FMDB' one it seems to have resolved the issue.
