### ISSUE TITLE
sqlcipher installation for Qt using ubuntu

### ISSUE THREAD

**Issue by pramodjadhav123** [sqlcipher/sqlcipher#155]
Hi,
    I am installed sqlcipher library. From command line the database encryption & decryption is working properly, but when I try to encrypt the database from QT
it gives the error.

QSqlDatabase: QSQLCIPHER driver not loaded
QSqlDatabase: available drivers: QSQLITE QMYSQL QMYSQL3 QPSQL QPSQL7

Any Idea about this error,please give me a reply.

Thanks & Regards,
Pramod Jadhav.
pramod.jadhav@citiustech.com

**Comment by developernotes** [comment]
Hello @pramodjadhav123 

Unless you are reporting an issue with SQLCipher, you might consider posting this type of question in the SQLCipher [discuss](https://discuss.zetetic.net/c/sqlcipher) site, a public searchable community forum for SQLCipher.
