### ISSUE TITLE
.sql can't open when the iphone locked

### ISSUE THREAD

**Issue by bulice** [sqlcipher/sqlcipher#156]
it will report I/O error, did some one meet this issue too ?

**Comment by developernotes** [comment]
Hello @bulice 

Do you have a specific issue to report with the SQLCipher library?

**Comment by bulice** [comment]
SQLCipher did not support SQLITE_OPEN_FILEPROTECTION_NONE flag, in my app, when app run in background mode and the iPhone locked, at this time i update the db,  the SQLCipher will report the I/O error.

**Comment by bulice** [comment]
please take a look this issue, many people talk about this issue. https://github.com/ccgus/fmdb/issues/262

**Comment by billymeltdown** [comment]
@bulice while I'm sorry about the trouble, this is not a problem specific to SQLCipher. If you are using FMDB you should make sure you are not opening the database prior with different flags. Depending on your flags, writes should fail when device is locked. This is a problem with using SQLite and working with file protection, not SQLCipher. There's a lot of good information at the FMDB issue thread you linked. You might also try stepping through your code paths in the debugger when the database is opened and when you try to access the data after the device is locked for more clues. I hope that helps!

**Comment by bulice** [comment]
@billymeltdown , i used to FMDB to store data, it war works fine when device locked. now i change the sqlite with SQLCipher, then this issue shown.

**Comment by brodybits** [comment]
@bulice are you using SQLCipher directly or are you still using FMDB to access SQLCipher?

FMDB does seem to support SQLCipher. Perhaps you should raise this on FMDB as well, in case they can help you and in case this question can help someone else, someday.

**Comment by developernotes** [comment]
Hi @bulice 

SQLCipher is based on the SQLite mainline source.  The flags mainline SQLite make available for opening a connection are documented [here](http://www.sqlite.org/c3ref/c_open_autoproxy.html).  These are defined within the `sqlite.h.in` file, [here](https://github.com/sqlcipher/sqlcipher/blob/master/src/sqlite.h.in#L515-L534) are the same values used in the current release of SQLCipher.

SQLite that is shipped with Apple appears to have been modified, you can verify this by reviewing your `sqlite3.h` file located within the `/usr/include` directory.  They define the following values, note the inclusion of various `SQLITE_OPEN_FILEPROTECTION_*` options below:

```
/*
** CAPI3REF: Flags For File Open Operations
**
** These bit values are intended for use in the
** 3rd parameter to the [sqlite3_open_v2()] interface and
** in the 4th parameter to the [sqlite3_vfs.xOpen] method.
*/
#define SQLITE_OPEN_READONLY         0x00000001  /* Ok for sqlite3_open_v2() */
#define SQLITE_OPEN_READWRITE        0x00000002  /* Ok for sqlite3_open_v2() */
#define SQLITE_OPEN_CREATE           0x00000004  /* Ok for sqlite3_open_v2() */
#define SQLITE_OPEN_DELETEONCLOSE    0x00000008  /* VFS only */
#define SQLITE_OPEN_EXCLUSIVE        0x00000010  /* VFS only */
#define SQLITE_OPEN_AUTOPROXY        0x00000020  /* VFS only */
#define SQLITE_OPEN_URI              0x00000040  /* Ok for sqlite3_open_v2() */
#define SQLITE_OPEN_MEMORY           0x00000080  /* Ok for sqlite3_open_v2() */
#define SQLITE_OPEN_MAIN_DB          0x00000100  /* VFS only */
#define SQLITE_OPEN_TEMP_DB          0x00000200  /* VFS only */
#define SQLITE_OPEN_TRANSIENT_DB     0x00000400  /* VFS only */
#define SQLITE_OPEN_MAIN_JOURNAL     0x00000800  /* VFS only */
#define SQLITE_OPEN_TEMP_JOURNAL     0x00001000  /* VFS only */
#define SQLITE_OPEN_SUBJOURNAL       0x00002000  /* VFS only */
#define SQLITE_OPEN_MASTER_JOURNAL   0x00004000  /* VFS only */
#define SQLITE_OPEN_NOMUTEX          0x00008000  /* Ok for sqlite3_open_v2() */
#define SQLITE_OPEN_FULLMUTEX        0x00010000  /* Ok for sqlite3_open_v2() */
#define SQLITE_OPEN_SHAREDCACHE      0x00020000  /* Ok for sqlite3_open_v2() */
#define SQLITE_OPEN_PRIVATECACHE     0x00040000  /* Ok for sqlite3_open_v2() */
#define SQLITE_OPEN_WAL              0x00080000  /* VFS only */
#define SQLITE_OPEN_FILEPROTECTION_COMPLETE                             0x00100000
#define SQLITE_OPEN_FILEPROTECTION_COMPLETEUNLESSOPEN                   0x00200000
#define SQLITE_OPEN_FILEPROTECTION_COMPLETEUNTILFIRSTUSERAUTHENTICATION 0x00300000
#define SQLITE_OPEN_FILEPROTECTION_NONE                                 0x00400000
#define SQLITE_OPEN_FILEPROTECTION_MASK                                 0x00700000
```
I do not know why changes from Apple have not been merged into the SQLite mainline, however due to it not existing in mainline SQLite explains why you would not be able to open a connection using the `SQLITE_OPEN_FILEPROTECTION_NONE` flag when using SQLCipher.

**Comment by bulice** [comment]
@developernotes , thanks a lot, I will take a look at that.
