### ISSUE TITLE
Sqlcipher not opening the database with the correct password in SQLiteManager after exception occurs

### ISSUE THREAD

**Issue by aakash1313** [sqlcipher/sqlcipher#159]
Hi,
I am facing a weird issue with SQLCipher , we are implementing sql cipher in our databases.Sometimes we are able to perform the operations on the database correctly.But after the following exception occurs we are neither able to perform any operation on the database nor we can open the database in the SQLiteManager from the browser.
The exception which we observe is : 
16,2000,01.08.2016_01.56.42.303,Warning,Exception in SQLiteAccess.getRecords()
16,2000,01.08.2016_01.56.42.307,net.sqlcipher.database.SQLiteException: file is encrypted or is not a database
net.sqlcipher.database.SQLiteDatabase.native_setLocale(Native Method)
net.sqlcipher.database.SQLiteDatabase.setLocale(SQLiteDatabase.java:2092)
net.sqlcipher.database.SQLiteDatabase.<init>(SQLiteDatabase.java:1958)
net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:875)
net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:934)
net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:219)
net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:184)

We are kind of stuck with this issue. Any help is appreciated

**Comment by developernotes** [comment]
Hello @aakash1313 

Are you certain you are providing the correct password to the database?  Are you able to reproduce the behavior consistently?  Can you log the password being provided to the database connection in debug mode to verify you are providing the correct password when you receive the error?  Thanks!

**Comment by aakash1313** [comment]
Hi, 
Thanks for the immediate reply.
Yes, we are providing the correct password to the database.The behaviour is not consistent. I'll just narrate the entire scenario.
So we are creating three databases, and we are able to perform the operation very smoothly on all three databases,but sometime after this exceptions occurs we are not able to open one database with correct password, while the other two we are able to open with correct password.
I have attached the three databases ,you just have to change the file type to .db
The password with which we have created these file is : 9adead4611c68f7ef7baabc8207413bf96d6575b35c1140fbd620e47e5348fee
[DBWorking.txt](https://github.com/sqlcipher/sqlcipher/files/177949/DBWorking.txt)
[DBWorking2.txt](https://github.com/sqlcipher/sqlcipher/files/177950/DBWorking2.txt)
[DBNotWorking.txt](https://github.com/sqlcipher/sqlcipher/files/177951/DBNotWorking.txt)
Please help us with this.
I also wanted to know is there any way to recover the data if such kind of issue occurs

**Comment by aakash1313** [comment]
Hi , 
Also I wanted to know is there any way to avoid such kind of weird behavior in future

**Comment by developernotes** [comment]
Hi @aakash1313 

Is the database password being hardcoded?  How did you verify the password that was being provided to create the connection every time within your application matched correctly?

**Comment by aakash1313** [comment]
Hi Nick,
We are generating the password through a java hash generator which takes a salt value and android device imei to generate a hash value which we are setting as the password while creating the database as mentioned in the documentation for sql cipher for android. Is there any specific way to set the password?.We tried to  debug the working code it was showing the correct password whenever it is making the connection.
What we are doing is :
In getWritable(generatedHashValue)  and getReadable(generatedHashValue) we are setting the generated hash value as the password.
Are we going somewhere wrong in the approach?
Moreover it is difficult to reproduce the issue but whenever it is happening I am losing a lot of data. :(

**Comment by aakash1313** [comment]
The salt value and device imei will always be same.. therefore the hash value generated will also be same. But I am not able figure out what happens suddenly. :(

**Comment by developernotes** [comment]
Hi @aakash1313 

Please log the password while in a debug scenario to verify the code that is executing is always receiving the same value until you receive the exception again.  Can you please then provide the full debug output?

**Comment by aakash1313** [comment]
Hi Nick, 
We have been trying to do the same since the past 3-4 days. Everytime we debug we get the correct password. It is bit difficult to reproduce the same issue(5%). Out of 10 device in 1 device it can happen we are not sure on which it might happen. It's becoming strenuous to reproduce it.
Moreover it is happening to just one db others are working are perfectly fine. Is there any other way by which we can make sure that this doesn't happen? Some pragma statement or something else?

**Comment by aakash1313** [comment]
Is there some efficient or better way of setting the password?

**Comment by developernotes** [comment]
Hi @aakash1313 

We would need the debug logs to analyze what is going on any further.  We will review them once you are able to provide the full log output.

**Comment by aakash1313** [comment]
Hi Nick,

Please find the full device logs when the exception occured.Hope this helps in finding the solution.
[devicelog.txt](https://github.com/sqlcipher/sqlcipher/files/178378/devicelog.txt)

**Comment by developernotes** [comment]
Hello @aakash1313 

The logs that would need to be analyzed should log the password being provided each time finally terminating where you receive the exception.  Once we have those we will be able to review further.

**Comment by aakash1313** [comment]
Hi @developernotes 

We are trying to do that since the past 3-4 but that issue is not happening. It happened once 1 month ago and now again happened few days back. Doing this would be a little difficult. Is there any other way to work around this problem? Are you able to figure out something from the complete error log?

**Comment by aakash1313** [comment]
Nick,
Any other way please? :(

**Comment by aakash1313** [comment]
Hello Nick,

Any other work around?

**Comment by developernotes** [comment]
Hello @aakash1313 

We took a look at the database file provided in DBNotWorking.txt, it turns out that the first page of the database appears to be corrupt.  After the password is applied, the [locale](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/src/net/sqlcipher/database/SQLiteDatabase.java#L2338) is set which triggers a SQL statement to be [run](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/jni/net_sqlcipher_database_SQLiteDatabase.cpp#L489).  The first page of your database appears to be corrupt so it fails to properly access the database.  Something is writing to your database file causing the corruption.  As you can see below, the first part of the file reads `IO*WRITE*HEADER` – this is not from SQLCipher.

![screen shot 2016-03-17 at 3 38 57 pm](https://cloud.githubusercontent.com/assets/3225/13860759/fb29a0a0-ec57-11e5-96a6-cca35a34c445.png)

**Comment by aakash1313** [comment]
Hello Nick,

Thanks for the further analysis .
So does it mean that: 
1.There is nothing wrong in the implementation of the sqlcipher in our project?
2. Is it happening because we are writing something to the database after accessing it which is not right?
3. If second is true, should it not raise any db write exception instead of corrupting the database?

**Comment by developernotes** [comment]
Hello @aakash1313 

Without further analysis of the application it is difficult to say what is causing the file to become corrupt.  The value `IO*WRITE*HEADER*` is not part of SQLCipher itself, nor the client library SQLCipher for Android.  We would recommend you investigate further all code paths that interface with the database that becomes corrupt to narrow down the possible causes.  It is possible that something in your application other than SQLCipher is writing to the database file and causing the corruption.

**Comment by aakash1313** [comment]
Hello Nick,

Thanks for the update. We'll try to investigate where in our code this bug value is being written to the database. Thanks again :+1:  :)..

**Comment by aakash1313** [comment]
Hi @developernotes ,

Just one quick question, is there any way to recover the data if such of scenario occurs?

**Comment by developernotes** [comment]
Hello @aakash1313 

I'm not certain that would be possible.  It would require knowing the unique per database salt that was generated when the database was created, along with knowing the database password.  Without those two pieces, you would not be able to attempt to decrypt any of the remaining fragments of the database.  If you had that information it would still take considerable effort to attempt to recover any data if possible at all.  Were you able to locate the source that was modifying your database?

**Comment by aakash1313** [comment]
Hi @developernotes ,

We went through our code and didn't find any issue in our code. There is no case where we access Database other than SQL Cipher API. We had a scenario where we insert transaction into Database and exit the application then we enter into application and insert transaction into Database.Before exit the application transaction was inserted properly but after restarting application and trying to insert into database this issue started coming. We are doing insertion of records as a Transaction in following way.
db.beginTransaction();
db.executeInsert();
db.setSucess();
db.endTransaction();

And this is not coming every time. It is happening Intermittently and we are not able to figure out when it happens.
And we are not able to understand how our application can cause setLocale() failure as our application never sets Locale details in DB?
We could not  conclude on this whether it is application issue or not?
**This became critical issue for my application as I am about release with this API.
Please help me on this.**

**Comment by developernotes** [comment]
Hello @aakash1313 

>And we are not able to understand how our application can cause setLocale() failure as our application never sets Locale details in DB?

The call to `setLocale(…)` occurs directly within the SQLCipher for Android library immediately following the keying operation on the database.  The internals to `setLocale(…)` include performing a query against the database, which triggers SQLCipher for Android to attempt to decrypt a portion of your database.

>We could not conclude on this whether it is application issue or not?
This became critical issue for my application as I am about release with this API.
Please help me on this.

We would be happy to review a publicly available sample application, isolated from your current application that consistently reproduces the behavior you experience.  Alternatively, your organization may consider opening an advanced support agreement with Zetetic for further analysis.  If you are interested in a support agreement, please contact us separately at [support@zetetic.net](mailto:support@zetetic.net).
