### ISSUE TITLE
Adding SQLCipher to MSYS2 Packages

### ISSUE THREAD

**Issue by PhenomRetroShare** [sqlcipher/sqlcipher#161]
Hello,
Can you add SQLCipher to [MSYS2 Packages](https://github.com/Alexpux/MSYS2-packages)?
You can read [Contributing to MSYS2](https://sourceforge.net/p/msys2/wiki/Contributing%20to%20MSYS2/).
I've made an [issue](https://github.com/Alexpux/MSYS2-packages/issues/527) in their side.

**Comment by developernotes** [comment]
Hello @PhenomRetroShare 

At this time we do not have plans to add SQLCipher to the MSYS2 package repository.  Thanks!
