### ISSUE TITLE
Compilation options mismatch between sqlcipher.xcodeproj, SQLCipher podspec, and Apple's builds.

### ISSUE THREAD

**Issue by groue** [sqlcipher/sqlcipher#163]
Hello,

I was wondering why the SQLCipher podspec and the sqlcipher.xcodeproj project do not use the same compilation options:

- [sqlcipher.xcodeproj](https://github.com/sqlcipher/sqlcipher/blob/v3.3.1/sqlcipher.xcodeproj/project.pbxproj#L162): `-DSQLITE_HAS_CODEC -DSQLITE_TEMP_STORE=2`
- [podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/SQLCipher/3.3.1/SQLCipher.podspec.json#L14): `-DSQLITE_HAS_CODEC -DSQLITE_TEMP_STORE=2 -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_UNLOCK_NOTIFY`

Actually, when I inspect the stock sqlite3 shipped in Apple operation systems (with `PRAGMA compile_options`), I get yet another set of compilation options:

- MacOSX SDK (10.11)
    - ENABLE_API_ARMOR
    - ENABLE_FTS3
    - ENABLE_FTS3_PARENTHESIS
    - ENABLE_LOCKING_STYLE=1
    - ENABLE_RTREE
    - ENABLE_UPDATE_DELETE_LIMIT
    - OMIT_AUTORESET
    - OMIT_BUILTIN_TEST
    - OMIT_LOAD_EXTENSION
    - SYSTEM_MALLOC
    - THREADSAFE=2

- iPhoneSimulator SDK (9.3)
    - ENABLE_API_ARMOR
    - ENABLE_FTS3
    - ENABLE_FTS3_PARENTHESIS
    - ENABLE_LOCKING_STYLE=1
    - ENABLE_RTREE
    - ENABLE_UPDATE_DELETE_LIMIT
    - MAX_MMAP_SIZE=0
    - OMIT_AUTORESET
    - OMIT_BUILTIN_TEST
    - OMIT_LOAD_EXTENSION
    - SYSTEM_MALLOC
    - THREADSAFE=2

- iPhoneOS SDK (9.3)
    - ENABLE_API_ARMOR
    - ENABLE_FTS3
    - ENABLE_FTS3_PARENTHESIS
    - ENABLE_LOCKING_STYLE=1
    - ENABLE_RTREE
    - ENABLE_UPDATE_DELETE_LIMIT
    - MAX_MMAP_SIZE=0
    - OMIT_AUTORESET
    - OMIT_BUILTIN_TEST
    - OMIT_LOAD_EXTENSION
    - SYSTEM_MALLOC
    - THREADSAFE=2

I'm lost. What do you think?

**Comment by developernotes** [comment]
Hello @groue 

The [sqlcipher.xcodeproj](https://github.com/sqlcipher/sqlcipher/tree/master/sqlcipher.xcodeproj) provides a _minimum_ base line in terms of what CFLAG's are required for building SQLCipher.  Each developer utilizing SQLCipher may have a specific set of requirements in terms of the features they wish to include when compiling SQLCipher.  We have just recently taken ownership of the podspec for SQLCipher, it was not originally authored by Zetetic.

**Comment by groue** [comment]
Hi @developernotes, thanks for your answer.

If I understand well, the only way to personalize is through forking this repository. Am I right?

**Comment by developernotes** [comment]
Hello @groue 

You can certainly fork the project if you wish to make public changes to your own version of the repository.

**Comment by groue** [comment]
OK @developernotes! Thanks for maintaining SQLCipher.

**Comment by groue** [comment]
And have a look at http://github.com/groue/GRDB.swift one day :smile:
