### ISSUE TITLE
Thought for the SQLite readme

### ISSUE THREAD

**Issue by justinclift** [sqlcipher/sqlcipher#169]
The README.md file is a bit confusing as-is, due to the unclear separation of the SQLite README.md from the SQLCipher one.

As an idea maybe renaming the SQLite one to (say) README.SQLite.md would make things clearer? :smile:

**Comment by brodybits** [comment]
I would favor starting the SQLite part with a top-level header that says
something like "Original SQLite Documentation" or "Original SQLite part
below".

~~+1~~ **+10** for making this more clear!

**Comment by justinclift** [comment]
Yeah, it needs "something" for sure. :smile:

**Comment by developernotes** [comment]
Hi @justinclift, @brodybits 

While we do have [beginning](https://github.com/sqlcipher/sqlcipher#sqlcipher) and [ending](https://github.com/sqlcipher/sqlcipher#end-sqlcipher) identifiers, do you think those are confusing, or just not clear enough?

**Comment by brodybits** [comment]
I would favor "something" like the following change:

```diff
diff --git a/README.md b/README.md
index a3abad4..f03ef55 100644
--- a/README.md
+++ b/README.md
@@ -1,4 +1,4 @@
-## SQLCipher
+# SQLCipher
 
 SQLCipher is an SQLite extension that provides transparent 256-bit AES encryption of 
 database files. Pages are encrypted before being written to disk and are decrypted 
@@ -132,7 +132,9 @@ ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-## End SQLCipher
+## End of SQLCipher part
+
+# Original SQLite part
 
 This directory contains source code to 
 ```

- Clear `<H1>` title of the SQLCipher part of the documentation
- Clear `<H1>` separation between SQLCipher-specific part and original SQLite part
- Makes the start of the original SQLite part harder to miss

I would be happy to raise a PR with this change if you like.

**Comment by developernotes** [comment]
Hi @justinclift, @brodybits 

Thank you for your feedback. We have discussed this internally and will make some changes to the README in the `prerelease` branch soon.

**Comment by developernotes** [comment]
Hi @justinclift, @brodybits 

We've pushed the updated changes to the README [here](https://github.com/sqlcipher/sqlcipher/blob/prerelease/README.md). Let us know what you think!

**Comment by brodybits** [comment]
Looks good to me, thanks!

**Comment by justinclift** [comment]
Yep, that's very clear now. :smile:

**Comment by developernotes** [comment]
Thanks for the feedback and quick responses!

**Comment by justinclift** [comment]
You're welcome. :smile:
