### ISSUE TITLE
Potential deadlock caused by sqlite3CodecAttach

### ISSUE THREAD

**Issue by oliveriobw** [sqlcipher/sqlcipher#170]
There is a potential deadlock caused by an early return and an unreleased mutex in sqlite3CodecAttach:

```
int sqlite3CodecAttach(sqlite3* db, int nDb, const void *zKey, int nKey) { 
  if(nKey && zKey && pDb->pBt) {
     //...
    sqlite3_mutex_enter(db->mutex);

    if(rc != SQLITE_OK) return rc; /* initialization failed, do not attach potentially corrupted context */
    //...
    sqlite3_mutex_leave(db->mutex); 
  }
  return SQLITE_OK;
}
```
SQLCipher version:3.11.0

**Comment by developernotes** [comment]
Hi @oliveriobw 

Thank you for the report, that is a good catch! I've pushed up a [fix](https://github.com/sqlcipher/sqlcipher/commit/e873a49d99191ced94f4247a9b5ca608d9d01815) in our `prerelease` branch. Thanks again!
