### ISSUE TITLE
Sqlcipher compilation does not work in docker container and in centos os.

### ISSUE THREAD

**Issue by silikathapa** [sqlcipher/sqlcipher#178]
The sqlcipher compiles and runs normally when executed in Ubuntu OS, but when compiled on Ubuntu container and also in Centos OS, it fails.  
I am using gcc 6.0.2 in the Ubuntu docker container and gcc 5.4 in Centos 7, and openssl 1.0.2. The error that shows up during compilation is:

Warning: can't find tclsh - defaulting to non-amalgamation build.
./configure: line 11723: tclsh: command not found
configure: Version set to 3.11
configure: Release set to 3.11.0
configure: Version number set to 3011000
checking whether to support threadsafe operation... yes
checking for library containing pthread_create... -lpthread
checking for library containing pthread_mutexattr_init... none required
checking for crypto library to use... openssl
checking for HMAC_Init_ex in -lcrypto... no
configure: error: Library crypto not found. Install openssl!"

It would be great to get help on this issue. Thanks.

**Comment by developernotes** [comment]
Hi @silikathapa 

>configure: error: Library crypto not found. Install openssl!"

Would you try installing OpenSSL within your container, then attempting the build?

**Comment by silikathapa** [comment]
Well,  I have installed OpenSSL-1.0.2 in the ubuntu docker container and have libcrypto.a library in usr/local/lib. But it still doesnot work.

**Comment by developernotes** [comment]
Hello @silikathapa,

From the build output above:

>checking for HMAC_Init_ex in -lcrypto... no

You appear to have configured SQLCipher to link dynamically to OpenSSL, you will need to adjust your configure step if you wish to link against the static library instead.
