### ISSUE TITLE
NULL pointer dereference in sqlite3PcacheRefCount pCache

### ISSUE THREAD

**Issue by chrisballinger** [sqlcipher/sqlcipher#179]
### Expected Behavior

Normal operation.

### Actual Behavior

Crash.

### Steps to Reproduce

SQLCipher is integrated using CocoaPods and is being invoked by the [libsqlfs](https://github.com/guardianproject/libsqlfs/blob/master/sqlfs.c) library. [YapDatabase](https://github.com/yapstudios/YapDatabase) also uses SQLCipher within the same application and doesn't cause a crash. Yap issues some [pragma commands](https://github.com/yapstudios/YapDatabase/blob/e05584ad54b827844866e840cb4aa0ffbe14a6f3/YapDatabase/YapDatabase.m#L816) to change the cipher page size but on a separate unrelated database.

Everything worked fine when integrated with CocoaPods 0.39 and Xcode 7. We updated to CocoaPods 1.0.1 and Xcode 8 and started seeing this crash and can't seem to figure out why it started failing when the code itself is unchanged. Possibly a compiler bug?

<img width="279" alt="screen shot 2016-09-13 at 2 45 22 pm" src="https://cloud.githubusercontent.com/assets/518687/18492573/dc0ad53a-79c0-11e6-95c9-8f325969842c.png">

`pCache` is NULL:

```c
/* 
** Return the total number of references to all pages held by the cache.
**
** This is not the total number of pages referenced, but the sum of the
** reference count for all pages.
*/
SQLITE_PRIVATE int sqlite3PcacheRefCount(PCache *pCache){
  return pCache->nRefSum;
}
```
SQLCipher version: 3.4.0

**Comment by chrisballinger** [comment]
So it seems that the `sqlite3_open` function that's being called is from Apple's libsqlite3.dylib and then failing during `sqlite3_key` because the db pointer is incorrect. Really confused about why this used to work fine, and still works in YapDatabase but not in this case.

```
(lldb) image lookup -n sqlite3_open
1 match found in /Users/chrisbal/Library/Developer/Xcode/DerivedData/ChatSecure-bgbdueswhbvwehacitzrmgfutmci/Build/Products/Debug-iphonesimulator/ChatSecure.app/Frameworks/SQLCipher.framework/SQLCipher:
        Address: SQLCipher[0x000000000001bc80] (SQLCipher.__TEXT.__text + 110304)
        Summary: SQLCipher`sqlite3_open at sqlite3.c:138882
1 match found in /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/libsqlite3.dylib:
        Address: libsqlite3.dylib[0x000000000001bd70] (libsqlite3.dylib.__TEXT.__text + 110240)
        Summary: libsqlite3.dylib`sqlite3_open
(lldb) 
```

**Comment by chrisballinger** [comment]
Durrrrr figured it out. I was pulling in both the `libsqlfs` and `libsqlfs/SQLCipher` pods which linked against both Apple and SQLCipher.

**Comment by sjlombardo** [comment]
Hello @chrisballinger - we are looking into related issues with cocoapods and sqlcipher. Can you please provide a list of all the Pods you are using? Can you also provide the resolved value of the Other Linker Flags build setting for your project?

**Comment by sjlombardo** [comment]
@chrisballinger in addition to the question above related to the Other Linker Flag, did you have both the libsqlfs and libsqlfs/SQLCipher pods included previously when it was working under 0.39 and Xcode 7?

**Comment by chrisballinger** [comment]
The main issue is that CocoaPods 1.0+ has a bug when compiling C code: https://github.com/CocoaPods/CocoaPods/pull/5844

I altered the SQLCipher and libsqlfs podspecs to rename the .c to .m to work around the issue until CocoaPods fixes it upstream. I then overrode the podspecs in my Podfile, but forgot to use libsqlfs/SQLCipher subspec when in the Podfile. IOCipher depends on libsqlfs/SQLCipher so both specs were included at the same time, which should be an error case. The dynamic linker had no problem using symbols from both libraries. The YapDatabase podspec/code addresses this by detecting if two defines are present: https://github.com/yapstudios/YapDatabase/blob/e05584ad54b827844866e840cb4aa0ffbe14a6f3/YapDatabase/YapDatabase.h#L33

**Comment by chrisballinger** [comment]
This is our Podfile for 0.39: https://github.com/ChatSecure/ChatSecure-iOS/blob/develop/Podfile and for 1.0.1 https://github.com/ChatSecure/ChatSecure-iOS/blob/cocoapods_1.0.1/Podfile

**Comment by sjlombardo** [comment]
Thanks @chrisballinger, I appreciate the additional details! It's not directly related, but we've published some additional [information regarding SQLCipher with XCode 8 and iOS 10](https://discuss.zetetic.net/t/important-advisory-sqlcipher-with-xcode-8-and-ios-10/1688) as well, it might be of interest.
