### ISSUE TITLE
Unable to build sqlcipher code on ubuntu machine

### ISSUE THREAD

**Issue by AshiqKony** [sqlcipher/sqlcipher#181]
Hi,

I have cloned the source code from below repo
git clone https://github.com/sqlcipher/android-database-sqlcipher.git

I have downloaded and configured ANDROID_NDK_ROOT in bashrc to android-ndk-r12b

After that I triggered the "make init" but build is getting  failed with following error --

===========================================

 Entering directory `/home/kony/AndroidN-Sqlcipher-support/sqlcipher/android-database-sqlcipher/external/openssl/crypto'
/usr/bin/perl ../util/mkbuildinf.pl "arm-linux-androideabi-i686-linux-android-gcc -I. -I.. -I../include  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -fPIC -mandroid -I/home/kony/adt-bundle-linux-x86_64-20131030/android-ndk-r12b/platforms/android-19/arch-arm/usr/include -B/home/kony/adt-bundle-linux-x86_64-20131030/android-ndk-r12b/platforms/android-19/arch-arm/usr/lib -O3 -fomit-frame-pointer -Wall -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DGHASH_ASM" "android-x86" >buildinf.h
arm-linux-androideabi-i686-linux-android-gcc -I. -I.. -I../include  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -fPIC -mandroid -I/home/kony/adt-bundle-linux-x86_64-20131030/android-ndk-r12b/platforms/android-19/arch-arm/usr/include -B/home/kony/adt-bundle-linux-x86_64-20131030/android-ndk-r12b/platforms/android-19/arch-arm/usr/lib -O3 -fomit-frame-pointer -Wall -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DGHASH_ASM   -c -o cryptlib.o cryptlib.c
make[2]: arm-linux-androideabi-i686-linux-android-gcc: Command not found
make[2]: *** [cryptlib.o] Error 127
make[2]: Leaving directory `/home/kony/AndroidN-Sqlcipher-support/sqlcipher/android-database-sqlcipher/external/openssl/crypto'
make[1]: *** [build_crypto] Error 1
make[1]: Leaving directory `/home/kony/AndroidN-Sqlcipher-support/sqlcipher/android-database-sqlcipher/external/openssl'
mv: cannot stat ‘libcrypto.a’: No such file or directory
make: *** [build-openssl-libraries] Error 1

================================================

I have attached the detailed build logs for more details.
[sqlcipher_Build_Fail.txt](https://github.com/sqlcipher/sqlcipher/files/482509/sqlcipher_Build_Fail.txt)

**Comment by developernotes** [comment]
Hi @AshiqKony 

We have some instructions in the README to address [building from source](https://github.com/sqlcipher/android-database-sqlcipher#building), specifically we recommend you build with the NDK r11c version.

**Comment by AshiqKony** [comment]
Thanks for response.

Now I have taken NDK r11c version and still build is getting failed like above attached log.  One thing I have noticed here is that, if commenting below line from bashrc file, build is getting success.
----------------------------------------------------
#export CROSS_COMPILE="arm-linux-androideabi-"
-----------------------------------------------------

So my concern is that, this configuration was working for earlier version. Can you please confirm that, keeping CROSS_COMPILE variable is mandatory for this latest version as well?

**Comment by developernotes** [comment]
Hi @AshiqKony 

>if commenting below line from bashrc file, build is getting success

Setting that within your `~/.bashrc` file is not part of the SQLCipher for Android build process. That may certainly cause issues if you are overriding the value when building the OpenSSL binaries. I would remove that from your default configuration.

**Comment by AshiqKony** [comment]
Thanks a lot for quick response.
can you please help me out if i want to build OpenSSL binaries also? I am sharing below my ~/.bashrc detail. It may help you to understand the problem,

export USE_CCACHE=1
export target_os="['android']"
export PATH="/usr/local/":$PATH
echo "printing ashiq : $PATH"
export PATH="/usr/lib/":$PATH
export PATH="/usr/local/include":$PATH
export JAVA_HOME=/usr/lib/jvm/jdk1.6.0_45
export PATH=/usr/lib/jvm/jdk1.6.0_45/bin:/usr/lib/jvm/java-7-openjdk-amd64/bin:/home/kony/CHROME_SOURCE_BUILD/depot_tools/:$PATH
export ANDROID_NDK_ROOT=/home/kony/adt-bundle-linux-x86_64-20131030/android-ndk-r11c
export PATH=/home/kony/adt-bundle-linux-x86_64-20131030/sdk/platform-tools:$PATH
export PATH=/home/kony/adt-bundle-linux-x86_64-20131030/sdk/tools:$PATH:$ANDROID_NDK_ROOT
export ANDROID_NDK=/home/kony/adt-bundle-linux-x86_64-20131030/android-ndk-r11c
export PATH="~/bin":$PATH
export PATH="/root/bin/":$PATH
export MACHINE=armv7l
export RELEASE=2.6.37
export SYSTEM=android
export ARCH=arm
export CROSS_COMPILE=arm-linux-androideabi-
export ANDROID_DEV=$ANDROID_NDK/platforms/android-19/arch-arm/usr
export ANDROID_API="android-19"
export HOSTCC=gcc

**Comment by developernotes** [comment]
Hi @AshiqKony 

Running `make init` will build the OpenSSL binaries for the library.

**Comment by AshiqKony** [comment]
But 'make init' is getting failed when below entry is present in ~/.bashrc

export CROSS_COMPILE=arm-linux-androideabi-

**Comment by developernotes** [comment]
Hi @AshiqKony 

I previously replied above to your inquiry regarding your `CROSS_COMPILE` entry in the `~/.bashrc` file; please remove that.

**Comment by AshiqKony** [comment]
Thanks a lot...I will check further.
