### ISSUE TITLE
File is encrypted or is not a database error

### ISSUE THREAD

**Issue by dhegi123** [sqlcipher/sqlcipher#186]
Hi,

I am getting the below error while using sqlcipher to my existing sqlite database application.
E/Database: file is encrypted or is not a database, while compiling: select count(*) from sqlite_master;

I followed the steps mentioned in zetetic website to integrate sqlcipher.
please help me to solve this issue

**Comment by developernotes** [comment]
Hi @dhegi123 

Thank you for your interest in SQLCipher. Since it does not appear that you are reporting an issue with SQLCipher, but rather an integration issue, we would ask that you post your inquiry over in SQLCipher [discuss](https://discuss.zetetic.net/c/sqlcipher) site. Thanks!
