### ISSUE TITLE
Fix OpenSSL external initialization detection

### ISSUE THREAD

**Issue by b-spencer** [sqlcipher/sqlcipher#187]
SQLCipher incorrectly assumes that if OpenSSL was externally initialized when sqlcipher_openssl_activate() first ran, then OpenSSL will remain (externally) initialized forever. Instead, once the `sqlcipher_openssl_activate()`/`sqlcipher_openssl_deactivate()` reference count returns to zero, and thus SQLCipher is no longer using any OpenSSL contexts, it should forget whether OpenSSL was externally initialized so that the same check will be performed again when `sqlcipher_openssl_activate()` is called next. Doing so allows the OpenSSL environment to be different between uses of SQLCipher. One place this can easily happen is in a series of unit tests, for example.

### Expected Behavior

Once the `openssl_init_count` reaches zero, reset `openssl_external_init` to zero (false) as well so that the next initialization checks to see if OpenSSL is still externally initialized and sets `openssl_external_init` appropriately.

This appears to be as simple as adding an else clause near here that sets `openssl_external_init` to zero: https://github.com/sqlcipher/sqlcipher/blob/master/src/crypto_openssl.c#L120

### Actual Behavior

The `openssl_external_init` flag can never go to back to zero (false), even after SQLCipher (and any surrounding context) has been uninitialized.  Re-initializing SQLCipher in these circumstances can cause a crash when OpenSSL is presumed to still be initialized but isn't.

### Steps to Reproduce

Re-initialize SQLCipher in the above circumstances.

SQLCipher version: 3.4.0

**Comment by developernotes** [comment]
Hello @b-spencer,

Thank you for the suggestion. We will make the change in our prerelease branch and include it with our next release. Thanks!
