### ISSUE TITLE
Slow Read and write in Android App

### ISSUE THREAD

**Issue by mohitYogi** [sqlcipher/sqlcipher#188]
I am currently using sql cipher in my android studio project. Writing and reading operations take too much of time. kindly help.

**Comment by developernotes** [comment]
Hi @mohitYogi 

We have prepared some general guidance on SQLCipher performance [here](https://discuss.zetetic.net/t/sqlcipher-performance/14). I would recommend reviewing that document relative to your application usage. If you have any additional question, please feel free to post a question on the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!
