### ISSUE TITLE
spontanous iOS crash on reload of react-native package

### ISSUE THREAD

**Issue by dryganets** [sqlcipher/sqlcipher#190]
### Expected Behavior
don't crash
### Actual Behavior
crashes from time to time in the debugger if I reload react-native package
(on close of SQLCipher)
### Steps to Reproduce

SQLCipher version:
3.4.0
*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by developernotes** [comment]
Hello @dryganets 

Are you directly utilizing the SQLCipher C API, or through an alternative wrapper library? Can you provide a small demo application that reproduces the behavior you are seeing? Thanks!

**Comment by dryganets** [comment]
I'm using it as a part of sqlite https://github.com/andpor/react-native-sqlite-storage
I have it integrated through cocoa pods.

It doesn't crash every time, hard to repro.
Only happens in case debugging of the app is active.

Also crash doesn't happen on a simulator.

Looks like a race condition.

**Comment by dryganets** [comment]
I figured out the problem. It was incorrect synchronization inside of the react-native-sqlite-storage module.
Has nothing to do with sqlitecipher of SQLite :)

**Comment by brodybits** [comment]
@dryganets can you report how you got it to work to the react-native-sqlite for the benefit of others?

**Comment by dryganets** [comment]
I synchronized access to the Dictionary with mapping of database name to database pointer.
I suppose the problem we had was caused by calling close on an already closed database.

I will publish a link with the pull request to that repository here once we publish it.

**Comment by dryganets** [comment]
https://github.com/andpor/react-native-sqlite-storage/pull/130
