### ISSUE TITLE
Cocoapods support?

### ISSUE THREAD

**Issue by revolter** [sqlcipher/sqlcipher#191]
It looks like this repo is on Cocoapods, but there is no `podspec` file or any mention in the README. Why is that?

**Comment by developernotes** [comment]
Hi @revolter 

The main source of SQLCipher is managed separately from the Cocoapods podspec. You can find the latest podspec for SQLCipher [here](https://github.com/CocoaPods/Specs/blob/e486ad4a691f9b24c894ac1ab6c9cbdf646765bc/Specs/1/2/7/SQLCipher/3.4.0/SQLCipher.podspec.json).

**Comment by revolter** [comment]
But shouldn't the README mention that it is available on Cocoapods, as other libraries do?

**Comment by revolter** [comment]
Also, why is the version `3.1.0` installed by default?

**Comment by developernotes** [comment]
Hi @revolter 

>But shouldn't the README mention that it is available on Cocoapods, as other libraries do?

SQLCipher is available across many different platforms, some are open source, others are commercial. We do not maintain that list within the README however.
