### ISSUE TITLE
Couldn't upgrade to sqlcipher

### ISSUE THREAD

**Issue by srinivas3120** [sqlcipher/sqlcipher#192]
Facing cash when upgrading my app from non encrypted db to encrypted sqlcipher ? 
using
compile `'net.zetetic:android-database-sqlcipher:3.5.4@aar'`

    12-18 19:58:41.075 23624-23624/? A/art: art/runtime/runtime.cc:405]   native: #08 pc 0009273b  /data/app/com.awwdb-2/lib/arm/libsqlcipher.so (_ZN9sqlcipher43register_android_database_SQLiteCompiledSqlEP7_JNIEnv+14)
    12-18 19:58:41.075 23624-23624/? A/art: art/runtime/runtime.cc:405]   native: #09 pc 00092991  /data/app/com.awwdb-2/lib/arm/libsqlcipher.so (JNI_OnLoad+32)
    12-18 19:58:41.076 23624-23624/? A/art: art/runtime/runtime.cc:405]   native: #10 pc 0009273b  /data/app/com.awwdb-2/lib/arm/libsqlcipher.so (_ZN9sqlcipher43register_android_database_SQLiteCompiledSqlEP7_JNIEnv+14)
    12-18 19:58:41.077 23624-23624/? A/art: art/runtime/runtime.cc:405]   native: #11 pc 00092991  /data/app/com.awwdb-2/lib/arm/libsqlcipher.so (JNI_OnLoad+32)
    12-18 19:58:41.084 23624-23624/? A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 23624 (m.awwdb)

**Comment by sjlombardo** [comment]
This issue doesn't contain enough information to troubleshoot. If you are still having trouble please start a discussion on the SQLCipher forum for https://discuss.zetetic.net/c/sqlcipher - I'm going to close this for now since it is not specifically a bug with SQLCipher.
