### ISSUE TITLE
NOT Support 'COLLATE LOCALIZED ASC' when upgrade to 3.5.4

### ISSUE THREAD

**Issue by mtxcfw** [sqlcipher/sqlcipher#193]
### Expected Behavior
I want to get a sorted result by the sql below
``` sql
SELECT id, nickname, sex, pinyin, avatar FROM friends ORDER BY pinyin COLLATE LOCALIZED ASC;
```

### Actual Behavior
It just throw me an SQLiteException: 
```
no such collation sequence: LOCALIZED: , while compiling: SELECT id, nickname, sex, pinyin, avatar FROM friends ORDER BY pinyin COLLATE LOCALIZED ASC;
```

### Steps to Reproduce
Just execute 'db.rawQuery(sqlString, null);' and sqlString has keywords "ORDER BY xxx COLLATE LOCALIZED ASC"

SQLCipher version: 3.5.4
It works fine on original sqlite and it works on SqlCipher 3.3.1. When I upgrade SqlCipher to version 3.5.4, it throw me the SQLiteException. Now, how do I resolove this problem?

**Comment by groue** [comment]
See https://discuss.zetetic.net/t/workaround-for-using-androids-localized-collator-after-3-5-0-update/1515

**Comment by mtxcfw** [comment]
@groue
Get it. Thank you !
