### ISSUE TITLE
SQLCipher and Google Pixel Android 7.1 (Nougat)

### ISSUE THREAD

**Issue by earamsey** [sqlcipher/sqlcipher#194]
### Expected Behavior
SQLiteDatabase.loadLibs(this); -- should load library when I click on debug app from android studio. Is there something I must do other than click on "Debug-'app'" button to get it to work?

### Actual Behavior
it crashes -
```
E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.zzzzzzzz.xxxxxxxx, PID: 3523
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.zzzzzzzz.xxxxxxxx-2/base.apk"],nativeLibraryDirectories=[/data/app/com.zzzzzzzz.xxxxxxxx-2/lib/x86_64, /data/app/com.zzzzzzzz.xxxxxxxx-2/base.apk!/lib/x86_64, /system/lib64, /vendor/lib64]]] couldn't find "libsqlcipher.so"
at java.lang.Runtime.loadLibrary0(Runtime.java:984)
at java.lang.System.loadLibrary(System.java:1530)
at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:196)
at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:189)
at com.zzzzzzzz.xxxxxxxx.HomeActivity.onCreate(HomeActivity.java:122)
at android.app.Activity.performCreate(Activity.java:6679)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6119)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Disconnected from the target VM, address: 'localhost:8621', transport: 'socket'
```

### Steps to Reproduce
**Android studio Gradle File)**
```
dependencies {
compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.1.0'
    compile 'net.zetetic:android-database-sqlcipher:3.5.4@aar'
    compile 'org.igniterealtime.smack:smack-android-extensions:4.1.0'
    compile 'org.igniterealtime.smack:smack-experimental:4.1.0'
    compile 'org.igniterealtime.smack:smack-tcp:4.1.0'
    compile 'com.android.support:appcompat-v7:25.1.0'
    compile 'com.android.support:support-v4:25.1.0'
    compile 'com.squareup.okhttp3:okhttp:3.5.0'
    compile 'com.squareup.okio:okio:1.11.0'
    compile 'com.google.android.gms:play-services-maps:10.0.1'
    // Gson
    compile 'com.google.code.gson:gson:2.7'
    testCompile 'junit:junit:4.12'
}
```
**Activity)** 
```
@Override
protected void onCreate(Bundle savedInstanceState) {
    SQLiteDatabase.loadLibs(this);
    super.onCreate(savedInstanceState);
    requestWindowFeature(Window.FEATURENO_TITLE);
```

**Emulator)**
Android Nougat 7.1.1 Emulator API 25 X86_64

SQLCipher version:
net.zetetic:android-database-sqlcipher:3.5.4@aar

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!
Tried posting to discussion group and NO HELP!

**Comment by developernotes** [comment]
Hi @earamsey 

From the stack trace, the runtime is attempting to load the native libraries from the `x86_64` folder. SQLCipher for Android does not include 64-bit libraries currently, however it will work on 64-bit devices so long as you remove any other 3rd party native 64-bit libraries, too. We have a discuss post on this [here](https://discuss.zetetic.net/t/sqlcipher-for-android-native-library-support/1440).

**Comment by mohalaci** [comment]
@developernotes I got this error too, I read your discuss but it was not helped for me...

**Comment by developernotes** [comment]
Hi @mohalaci 

SQLCipher for Android includes native support for both 32 and 64-bit architectures now. Would you ty the latest release, currently 3.5.7 and let us know your results? Thanks!

**Comment by petemit** [comment]
THANK YOU!  

Whew!  I was going down the line of getting "splits" to work and then I mercifully found this post.  My crashes stopped immediately.  

 Would you mind updating this other post?  Google led me there,  
https://discuss.zetetic.net/t/sqlcipher-for-android-native-library-support/1440

**Comment by developernotes** [comment]
Hi @petemit 

We are happy to hear everything is working properly for you now. I have updated the article as well since we now support 64-bit platforms in SQLCipher for Android.
