### ISSUE TITLE
Add support for OpenSSL 1.1

### ISSUE THREAD

**Issue by kalikaneko** [sqlcipher/sqlcipher#196]
The patch in #195 is basically the one that debian is applying (see https://mail-archive.com/debian-bugs-rc@lists.debian.org/msg444801.html), but it changes the usage of EVP_CipherInit for its _ex version to avoid a segfault.

**Comment by developernotes** [comment]
Hello @kalikaneko 

We will be including support for OpenSSL 1.1.0 in our upcoming release of SQLCipher. Thanks!

**Comment by kalikaneko** [comment]
Hi @developernotes, good to know.
Some ETA? Some stuff crashing in debian testing now.

**Comment by developernotes** [comment]
Hello @kalikaneko 

Are you experiencing a crash when linking with the OpenSSL 1.0.2 series? We do not have a specific date, however it should be in the near term.

**Comment by csoler** [comment]
Hi, 
I am experiencing the same kind of problems. Valgrind reports that a crash happens when sqcipher is calling EVP_EncryptUpdate. Retroshare users on debian are stuck because of this ;-)
Thx for your help in fixing it.

**Comment by kalikaneko** [comment]
hi @developernotes. No, the crash is when linking to openssl 1.1, which is in debian testing now.

@csoler: can you check if this workaround works for you?
https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1492433.html

we should try to get the patch included in debian until the new release comes down the pipe

**Comment by developernotes** [comment]
Hi @csoler, @kalikaneko,

We released a new version of SQLCipher, version 3.4.1 which now includes support for OpenSSL 1.1.0, and has backwards compatibility with OpenSSL 1.0.2*. Can you give that a try?

**Comment by csoler** [comment]
I'm using v3.2.0, on debian stretch. Since we're using sqlcipher as an external package, we cannot easily patch it, and we would prefer to avoid recompiling it. So I dont have much choice beyond waitng that 3.4.1 becomes main stream.

**Comment by kalikaneko** [comment]
> I'm using v3.2.0, on debian stretch. Since we're using sqlcipher as an 
> external
> package, we cannot easily patch it, and we would prefer to avoid recompiling
> it. So I dont have much choice beyond waitng that 3.4.1 becomes main stream.

I have already pinged hans, the maintainer of the debian package, to include the 
patch in the debian package while waiting for the next release.

once the patch enters experimental it can be uploaded to testing. I think the 
same issue is affecting qTox and possibly other packages that depend on 
sqlcipher, see this thread:
https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1492433.html

**Comment by kalikaneko** [comment]
> We released a new version of SQLCipher, version 3.4.1 which now includes support for OpenSSL 1.1.0, and has backwards compatibility with OpenSSL 1.0.2*. Can you give that a try?

sorry, I managed to miss this comment.
I'll try this release today, thanks

**Comment by cavebeat** [comment]
would be nice to have libsqlcipher0 in stretch-backports with v3.4.1 

a requirement for this, is to have it in buster/testing, so it can be moved from testing to backports repository

https://packages.debian.org/en/sid/libsqlcipher0
https://backports.debian.org/news/stretch-backports/

**Comment by kalikaneko** [comment]
@cavebeat a coworker is working in the package https://0xacab.org/simonft/debian-sqlcipher

**Comment by csoler** [comment]
Any update on this? It seems to me that stretch still ships with unpatched sqlcipher-3.2.0

**Comment by developernotes** [comment]
Hi @csoler 

Mentioned [above](https://github.com/sqlcipher/sqlcipher/issues/196#issuecomment-282122535) that we added support for OpenSSL 1.1.0 in SQLCipher 3.4.1. SQLCipher is also backwards compatible with OpenSSL 1.0.2*.

**Comment by developernotes** [comment]
Hi @csoler,

We (Zetetic) are not responsible for SQLCipher updates within Debian release management. Possibly @eighthave can comment on this further, otherwise, you might bring this up on one of the Debian [mailing lists](https://www.debian.org/MailingLists/) instead.

**Comment by kalikaneko** [comment]
Hi all - 3.4.1-1 is now on debian sid, please do test it. It should be easy to get it added to stretch-backports. https://packages.debian.org/sid/sqlcipher
