### ISSUE TITLE
[build error] sqlite3.c:18401:12: error: storage size of ‘hctx’ isn’t known

### ISSUE THREAD

**Issue by AnimusPEXUS** [sqlcipher/sqlcipher#197]
### Expected Behavior
should build

### Actual Behavior
not building

### Steps to Reproduce
variation of ./configure && make

SQLCipher version: 3.4.0

### Additional Notes
sqlite-autoconf-3160200 builds ok in same environment

## Error Log
sqlite3.c: In function ‘sqlcipher_openssl_hmac’:
sqlite3.c:18401:12: error: storage size of ‘hctx’ isn’t known
   HMAC_CTX hctx;
            ^~~~
sqlite3.c:18403:3: warning: implicit declaration of function ‘HMAC_CTX_init’ [-Wimplicit-function-declaration]
   HMAC_CTX_init(&hctx);
   ^~~~~~~~~~~~~
sqlite3.c:18408:3: warning: implicit declaration of function ‘HMAC_CTX_cleanup’ [-Wimplicit-function-declaration]
   HMAC_CTX_cleanup(&hctx);
   ^~~~~~~~~~~~~~~~
sqlite3.c: In function ‘sqlcipher_openssl_cipher’:
sqlite3.c:18418:18: error: storage size of ‘ectx’ isn’t known
   EVP_CIPHER_CTX ectx;
                  ^~~~
make: *** [Makefile:673: sqlite3.lo] Error 1

**Comment by sjlombardo** [comment]
that error likely indicates you don't have a compatible version of the openssl development tools.

**Comment by AnimusPEXUS** [comment]
openssl-1.1.0d - isn't compatible?

**Comment by sjlombardo** [comment]
no, use 1.0.2. 1.1.0 had a very substantial restructuring of the API that breaks compatibility with nearly everything. The next release of SQLCipher will have conditional compile time support for 1.1.0.

**Comment by psamim** [comment]
Hi,
I am on Archlinux and have both versions installed. How can I specify which to use?

**Comment by sjemens** [comment]
@psamim for archlinux the best way is to use the package manager which links to openssl-1.1
`pacman -S sqlcipher`
If you want to compile your own version change the LDFLAGS in configure.
For openssl-1.0 `LDFLAGS="-L/usr/lib/openssl-1.0 -lcrypto"`
Openssl-1.1 is in system path so just leave it `LDFLAGS="-lcrypto"`
