### ISSUE TITLE
SQLCipher executable binary shell on Android

### ISSUE THREAD

**Issue by gwtool** [sqlcipher/sqlcipher#198]
Hello! Help me please.
I need to work with sqlcipher in text mode through the ADB.
How do I build the SQLCipher static executable binary, not library?
I need to run SQLCipher command-line from adb shell.
Thanks.

**Comment by developernotes** [comment]
Hi @gwtool 

We have documentation that covers build the SQLCipher command line shell [here](https://www.zetetic.net/sqlcipher/introduction/).

**Comment by gwtool** [comment]
Hi! Thans? but
For your documentation, I just built a library for integration to Android.
But not executable/

**Comment by developernotes** [comment]
Hi @gwtool 

The easiest approach would be to just use adb to pull the database file off device/emulator; then you can use the standard SQLCipher shell to interface with the encrypted database.

**Comment by gwtool** [comment]
I used SQLite comand-line from adb shell without pull/push database
And I want to use sqlcipher from adb shell.
Becouse my db very large.

**Comment by developernotes** [comment]
Hi @gwtool 

We do not provide a SQLCipher command line shell that operates directly on an Android device. If your organization needs something like, please feel free to reach out to us at [support@zetetic.net](mailto:support@zetetic.net) to discuss licensing a custom build.
