### ISSUE TITLE
support WAL?

### ISSUE THREAD

**Issue by ruanshanshan** [sqlcipher/sqlcipher#199]
### Expected Behavior
hi ，develpoers :

does the sqlcipher have the way to open the WAL? Thanks!

### Steps to Reproduce

SQLCipher version:

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by developernotes** [comment]
Hello @ruanshanshan 

You can enable WAL mode, or any other journal mode by executing [`PRAGMA journal_mode;`](https://www.sqlite.org/pragma.html#pragma_journal_mode) with the desired mode.
