### ISSUE TITLE
Custom openssl installation

### ISSUE THREAD

**Issue by theodelrieu** [sqlcipher/sqlcipher#201]
Hi, I would like to know if there was a way to specify a custom location to the `configure` script for openssl include files and libraries.

I have a different version on my system than my project, can I do this without hijacking the Makefile?
Thanks in advance.

SQLCipher version:
3.4.0

**Comment by developernotes** [comment]
Hi @theodelrieu 

You can specify directory paths for headers and libraries via `CFLAGS` and `LDFLAGS` arguments when running `./configure`. In doing this, it will modify the Makefile pathing for you. [Here](https://www.zetetic.net/sqlcipher/introduction/) is an example.

**Comment by theodelrieu** [comment]
Thanks, I tried that at first, but it just worked when launchin `make sqlite3.c`, `make` gives me undefined references to a few openssl methods.

It's weird but I'm better off with the amalgamation.

**Comment by developernotes** [comment]
Hi @theodelrieu,

A few follow up questions:

- What version of OpenSSL are you attempting to link? 
- Did you build OpenSSL yourself? 
- What symbols are being reported as missing?
- Are you certain the symbols are present in your build of OpenSSL?

Compiling the amalgamation still requires that you properly link OpenSSL if you are using the default crypto provider.

**Comment by theodelrieu** [comment]
I built openssl 1.0.2j myself, here are the missing symbols:

* OPENSSL_add_all_algorithms_noconf
* EVP_cleanup
* HMAC_CTX_init
* HMAC_CTX_cleanup
* EVP_CIPHER_CTX_cleanup

I just ran `nm` on my `libcrypto.a` and all the symbols are here (unless I misunderstand nm's output, which is very possible):

>0000000000000a60 T HMAC_CTX_cleanup
>0000000000000910 T HMAC_CTX_copy
>00000000000008e0 T HMAC_CTX_init
>0000000000000ca0 T HMAC_CTX_set_flags

**Comment by developernotes** [comment]
Hi @theodelrieu 

Are you providing the path in `CFLAGS` to the OpenSSL include directory? What does your `./configure` command look like?

**Comment by theodelrieu** [comment]
Here is my full command:

> ./configure --enable-tempstore=yes CFLAGS="-I../../../deps/Openssl/include-linux -DSQLITE_HAS_CODEC" LDFLAGS=../../../deps/Openssl/lib-linux/libcrypto.a --disable-debug --disable-shared

**Comment by developernotes** [comment]
Hello @theodelrieu 

Can you verify the directory path you are providing to `./configure` is correct for the include directory. Typically, there will be a directory at the root of the OpenSSL source tree called `include`.

**Comment by theodelrieu** [comment]
I'm quite positive the include folder is correct, though it looks like this:

`include-linux/openssl/...` (I tried to rename it to `include`)
The errors were at compile time instead of link-time once I did that.

I could join the scripts we use to build openssl and sqlcipher, that could help you

**Comment by theodelrieu** [comment]
Hi, here is a small zip containing the sources of openssl 1.0.2j, and the script to build it, and then attempt to build sqlcipher.

Hope this can help, thanks again
[openssl_sqlcipher.zip](https://github.com/sqlcipher/sqlcipher/files/812063/openssl_sqlcipher.zip)
