### ISSUE TITLE
v3.5.5 and higher disables libscrypt.so in an Android project

### ISSUE THREAD

**Issue by btcontract** [sqlcipher/sqlcipher#203]
### Expected Behavior
In my Bitcoin wallet I use native `libscrypt.so` instead of Java implementation to speed up password encryption/decryption times (https://github.com/btcontract/wallet/tree/master/app/src/main/jniLibs), adding `compile 'net.zetetic:android-database-sqlcipher:3.5.5@aar'` to `build.gradle` should not affect that.

### Actual Behavior
Adding `compile 'net.zetetic:android-database-sqlcipher:3.5.5@aar'` to `build.gradle` causes application to ignore `libscrypt.so` and use a slow Java implementation. Does not happen with v3.5.4 or lower.

### Steps to Reproduce
Compile https://github.com/btcontract/wallet with `compile 'net.zetetic:android-database-sqlcipher:3.5.5@aar'` added to `build.gradle`, observe slow encryption/decryption times (over a minute instead of a few seconds on my device).

SQLCipher version: 3.5.5 and 3.5.6

**Comment by developernotes** [comment]
Hi @btcontract 

What platforms are you including `libscrypt.so` for? Starting with 3.5.5, SQLCipher for Android included native libraries supporting 64-bit CPU's. We are now shipping `armeabi`, `armeabi-v7a`, `x86`, `x86_64`, and `arm64-v8a`. If you do not have all of those platforms for your native dependencies, you might consider building for those architectures, or removing support for specific architectures to seem if your application behaves differently.

SQLCipher for Android statically links it's own version of OpenSSL directly within the library, it should not impact the runtime behavior of other libraries.

**Comment by btcontract** [comment]
In my project there are no `libscrypt.so` versions for `x86_64` and `arm64-v8a`. I'll follow your advice and try again with those versions added. Thanks!
