### ISSUE TITLE
Cannot build with SQLITE_OMIT_DEPRECATED defined

### ISSUE THREAD

**Issue by brodybits** [sqlcipher/sqlcipher#204]
### Expected Behavior

From <https://www.sqlite.org/compile.html#recommended_compile_time_options>: I should be able to build with SQLITE_OMIT_DEPRECATED defined.

### Actual Behavior

If I build with SQLITE_OMIT_DEPRECATED defined then it fails due an undefined symbol. 

### Steps to Reproduce

For example: if I would configure with the following command on macOS:

```
./configure --enable-tempstore=yes --with-crypto-lib=commoncrypto CFLAGS="-DSQLITE_HAS_CODEC -DSQLITE_OMIT_DEPRECATED" LDFLAGS="-framework Security -framework CoreServices"
```

and then build with `make` it fails with the following output:
```
Undefined symbols for architecture x86_64:
  "_sqlite3_profile", referenced from:
      _sqlcipher_cipher_profile in sqlite3.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libsqlcipher.la] Error 1
```

SQLCipher version: `3.4.1`

### Possible solution

```diff
diff --git a/src/crypto_impl.c b/src/crypto_impl.c
index e43704d..9bd11ac 100644
--- a/src/crypto_impl.c
+++ b/src/crypto_impl.c
@@ -1205,6 +1205,9 @@ int sqlcipher_codec_add_random(codec_ctx *ctx, const char *zRight, int random_sz
 }
 
 int sqlcipher_cipher_profile(sqlite3 *db, const char *destination){
+#if defined(SQLITE_OMIT_TRACE) || defined(SQLITE_OMIT_DEPRECATED)
+  return SQLITE_ERROR;
+#else
   FILE *f;
   if(sqlite3StrICmp(destination, "stdout") == 0){
     f = stdout;
@@ -1225,6 +1228,7 @@ int sqlcipher_cipher_profile(sqlite3 *db, const char *destination){
   }
   sqlite3_profile(db, sqlcipher_profile_callback, f);
   return SQLITE_OK;
+#endif
 }
 
 static void sqlcipher_profile_callback(void *file, const char *sql, sqlite3_uint64 run_time){
```

### Other

In general I am not able to do `make test` on my macOS (10.12) system.

**Comment by developernotes** [comment]
Hi @brodybits 

Thank you for this, we have made this change in `prerelease`. I would like to point out that we do not have any plans to ship any of our SQLCipher packages with either `SQLITE_OMIT_TRACE` or `SQLITE_OMIT_DEPRECATED` defined, however you are welcome to do so within your own fork. Thanks!
