### ISSUE TITLE
File is encrypted or is not a database error

### ISSUE THREAD

**Issue by arden** [sqlcipher/sqlcipher#205]
i have a ios app
run app in iphone's simulator that work ok.
but run app in iphone mobile that work error: File is encrypted or is not a database error

**Comment by developernotes** [comment]
Hello @arden 

A few follow up questions:

- Are you certain you are providing the correct password to the database? 
- Does the database exist? 
- Is the database encrypted with SQLCipher already?
- Are you able to debug the application on the device through Xcode?
- What version of SQLCipher are you using?
- What does `PRAGMA cipher_version;` report when you run it?

**Comment by njafei** [comment]
@developernotes 
I have the same question with this,here is my situation:

I try to open a file with sqlcipher

```
sqlcipher EnMicroMsg.db
sqlite> PRAGMA key = '2801209'; 
sqlite> create table a(id, int);
```

and i turn out an error: `Error: file is encrypted or is not a database`

but i can open the file with sqliteManager.

and `PRAGMA cipher_version;` report : 3.3.0

can u help me?

**Comment by developernotes** [comment]
Hello @njafei 

What version of SQLCipher was used to create the database file? Are you certain that is the correct password?

**Comment by njafei** [comment]
@developernotes

I'm sure the password is correct，but not sure about the database file? how can I see the version of SQLCipher was used to create the database file? I have the file .

**Comment by developernotes** [comment]
Hello @njafei 

If you are able to execute code against the original version of the SQLCipher library that created the database, you will want to execute the following SQL command:

```
PRAGMA cipher_version;
```

What does your application report?

**Comment by njafei** [comment]
@developernotes 

application is using V3.5，but I can't find the V3.5 for mac os . is that the reason ?
I'm a little confused about the versions...

**Comment by developernotes** [comment]
Hi @njafei 

We have not released SQLCipher 3.5 on macOS. Are you developing an Android application on macOS by chance? Are you attempting to open an existing database and modify it, or are you creating a new database and modifying it?

**Comment by njafei** [comment]
@developernotes  

My team is developing a Android application , they use SQLCipher 3.5 on it . And I'm trying to use the database file that application created, is that ok? and SQLCipher on mac is 3.4.1.

**Comment by developernotes** [comment]
Hello @njafei 

Yes, SQLCipher 3.4.1 on macOS will be able to read a SQLCipher database created using SQLCipher for Android 3.5. Note the latest version of SQLCipher for Android is 3.5.7.

**Comment by sjlombardo** [comment]
Closed for lack of updates
