### ISSUE TITLE
unknown type name ‘CRITICAL_SECTION’ on Cygwin64 Window 10

### ISSUE THREAD

**Issue by sinall** [sqlcipher/sqlcipher#206]
### Expected Behavior
Successful build on Cygwin

### Actual Behavior

> $ ./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC" && make
> checking build system type... x86_64-unknown-cygwin
> checking host system type... x86_64-unknown-cygwin
> checking how to print strings... printf
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.exe
> checking for suffix of executables... .exe
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking for a sed that does not truncate output... /usr/bin/sed
> checking for grep that handles long lines and -e... /usr/bin/grep
> checking for egrep... /usr/bin/grep -E
> checking for fgrep... /usr/bin/grep -F
> checking for ld used by gcc... /usr/x86_64-pc-cygwin/bin/ld.exe
> checking if the linker (/usr/x86_64-pc-cygwin/bin/ld.exe) is GNU ld... yes
> checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
> checking the name lister (/usr/bin/nm -B) interface... BSD nm
> checking whether ln -s works... yes
> checking the maximum length of command line arguments... 8192
> checking how to convert x86_64-unknown-cygwin file names to x86_64-unknown-cygwin format... func_convert_file_noop
> checking how to convert x86_64-unknown-cygwin file names to toolchain format... func_convert_file_noop
> checking for /usr/x86_64-pc-cygwin/bin/ld.exe option to reload object files... -r
> checking for objdump... objdump
> checking how to recognize dependent libraries... file_magic ^x86 archive import|^x86 DLL
> checking for dlltool... dlltool
> checking how to associate runtime and link libraries... func_cygming_dll_for_implib
> checking for ar... ar
> checking for archiver @FILE support... @
> checking for strip... strip
> checking for ranlib... ranlib
> checking for gawk... gawk
> checking command to parse /usr/bin/nm -B output from gcc object... ok
> checking for sysroot... no
> checking for a working dd... /usr/bin/dd
> checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
> checking for mt... no
> checking if : is a manifest tool... no
> checking how to run the C preprocessor... gcc -E
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking for dlfcn.h... yes
> checking for objdir... .libs
> checking if gcc supports -fno-rtti -fno-exceptions... no
> checking for gcc option to produce PIC... -DDLL_EXPORT -DPIC
> checking if gcc PIC flag -DDLL_EXPORT -DPIC works... yes
> checking if gcc static flag -static works... yes
> checking if gcc supports -c -o file.o... yes
> checking if gcc supports -c -o file.o... (cached) yes
> checking whether the gcc linker (/usr/x86_64-pc-cygwin/bin/ld.exe) supports shared libraries... yes
> checking whether -lc should be explicitly linked in... yes
> checking dynamic linker characteristics... Win32 ld.exe
> checking how to hardcode library paths into programs... immediate
> checking whether stripping libraries is possible... yes
> checking if libtool supports shared libraries... yes
> checking whether to build shared libraries... yes
> checking whether to build static libraries... yes
> checking for a BSD-compatible install... /usr/bin/install -c
> checking for special C compiler options needed for large files... no
> checking for _FILE_OFFSET_BITS value needed for large files... no
> checking for int8_t... yes
> checking for int16_t... yes
> checking for int32_t... yes
> checking for int64_t... yes
> checking for intptr_t... yes
> checking for uint8_t... yes
> checking for uint16_t... yes
> checking for uint32_t... yes
> checking for uint64_t... yes
> checking for uintptr_t... yes
> checking for sys/types.h... (cached) yes
> checking for stdlib.h... (cached) yes
> checking for stdint.h... (cached) yes
> checking for inttypes.h... (cached) yes
> checking malloc.h usability... yes
> checking malloc.h presence... yes
> checking for malloc.h... yes
> checking for fdatasync... yes
> checking for gmtime_r... yes
> checking for isnan... yes
> checking for localtime_r... yes
> checking for localtime_s... no
> checking for malloc_usable_size... yes
> checking for strchrnul... yes
> checking for usleep... yes
> checking for utime... yes
> checking for pread... yes
> checking for pread64... no
> checking for pwrite... yes
> checking for pwrite64... no
> checking for tclsh8.6... no
> checking for tclsh8.5... tclsh8.5
> configure: Version set to 3.15
> configure: Release set to 3.15.2
> configure: Version number set to 3015002
> checking whether to support threadsafe operation... yes
> checking for library containing pthread_create... none required
> checking for library containing pthread_mutexattr_init... none required
> checking for crypto library to use... openssl
> checking for HMAC_Init_ex in -lcrypto... yes
> checking whether to allow connections to be shared across threads... no
> checking whether to support shared library linked as release mode or not... no
> checking whether to use an in-ram database for temporary tables... yes
> checking if executables have the .exe suffix... unknown
> checking for Tcl configuration... configure: WARNING: Can't find Tcl configuration definitions
> configure: WARNING: *** Without Tcl the regression tests cannot be executed ***
> configure: WARNING: *** Consider using --with-tcl=... to define location of Tcl ***
> checking for library containing readline... no
> checking for library containing tgetent... no
> checking for readline in -lreadline... no
> checking readline.h usability... no
> checking readline.h presence... no
> checking for readline.h... no
> checking for /usr/include/readline.h... no
> checking for /usr/include/readline/readline.h... no
> checking for /usr/local/include/readline.h... no
> checking for /usr/local/include/readline/readline.h... no
> checking for /usr/local/readline/include/readline.h... no
> checking for /usr/local/readline/include/readline/readline.h... no
> checking for /usr/contrib/include/readline.h... no
> checking for /usr/contrib/include/readline/readline.h... no
> checking for /mingw/include/readline.h... no
> checking for /mingw/include/readline/readline.h... no
> checking for library containing fdatasync... none required
> checking for library containing dlopen... none required
> checking whether to support MEMSYS5... no
> checking whether to support MEMSYS3... no
> configure: creating ./config.status
> config.status: creating Makefile
> config.status: creating sqlcipher.pc
> config.status: creating config.h
> config.status: executing libtool commands
> tclsh8.5 /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/tool/mksqlite3h.tcl /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1 >sqlite3.h
> gcc  -DSQLITE_HAS_CODEC -DSQLCIPHER_CRYPTO_OPENSSL -o mkkeywordhash.exe   /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/tool/mkkeywordhash.c
> ./mkkeywordhash.exe >keywordhash.h
> gcc  -DSQLITE_HAS_CODEC -DSQLCIPHER_CRYPTO_OPENSSL -o lemon.exe /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/tool/lemon.c
> cp /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/tool/lempar.c .
> cp /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/parse.y .
> rm -f parse.h
> ./lemon.exe   parse.y
> mv parse.h parse.h.temp
> tclsh8.5 /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/tool/addopcodes.tcl parse.h.temp >parse.h
> cat parse.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/vdbe.c | tclsh8.5 /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/tool/mkopcodeh.tcl >opcodes.h
> tclsh8.5 /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/tool/mkopcodec.tcl opcodes.h >opcodes.c
> cp /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts5/fts5parse.y .
> rm -f fts5parse.h
> ./lemon.exe  fts5parse.y
> tclsh8.5 /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts5/tool/mkfts5c.tcl
> cp /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts5/fts5.h .
> rm -rf tsrc
> mkdir tsrc
> cp -f /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/crypto.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/sqlcipher.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/crypto.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/crypto_impl.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/crypto_libtomcrypt.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/crypto_openssl.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/crypto_cc.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/alter.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/analyze.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/attach.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/auth.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/backup.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/bitvec.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/btmutex.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/btree.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/btree.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/btreeInt.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/build.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/callback.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/complete.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/ctime.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/date.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/dbstat.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/delete.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/expr.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/fault.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/fkey.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/func.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/global.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/hash.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/hash.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/hwtime.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/insert.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/legacy.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/loadext.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/main.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/malloc.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/mem0.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/mem1.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/mem2.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/mem3.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/mem5.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/memjournal.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/msvc.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/mutex.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/mutex.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/mutex_noop.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/mutex_unix.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/mutex_w32.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/notify.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/os.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/os.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/os_common.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/os_setup.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/os_unix.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/os_win.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/os_win.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/pager.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/pager.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/parse.y /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/pcache.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/pcache.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/pcache1.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/pragma.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/pragma.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/prepare.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/printf.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/random.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/resolve.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/rowset.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/select.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/status.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/shell.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/sqlite.h.in /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/sqlite3ext.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/sqliteInt.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/sqliteLimit.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/table.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/tclsqlite.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/threads.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/tokenize.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/treeview.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/trigger.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/utf.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/update.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/util.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/vacuum.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/vdbe.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/vdbe.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/vdbeapi.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/vdbeaux.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/vdbeblob.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/vdbemem.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/vdbesort.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/vdbetrace.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/vdbeInt.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/vtab.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/vxworks.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/wal.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/wal.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/walker.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/where.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/wherecode.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/whereexpr.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src/whereInt.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts1/fts1.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts1/fts1.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts1/fts1_hash.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts1/fts1_hash.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts1/fts1_porter.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts1/fts1_tokenizer.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts1/fts1_tokenizer1.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts2/fts2.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts2/fts2.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts2/fts2_hash.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts2/fts2_hash.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts2/fts2_icu.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts2/fts2_porter.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts2/fts2_tokenizer.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts2/fts2_tokenizer.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts2/fts2_tokenizer1.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts3/fts3.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts3/fts3.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts3/fts3Int.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts3/fts3_aux.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts3/fts3_expr.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts3/fts3_hash.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts3/fts3_hash.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts3/fts3_icu.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts3/fts3_porter.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts3/fts3_snippet.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts3/fts3_tokenizer.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts3/fts3_tokenizer.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts3/fts3_tokenizer1.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts3/fts3_tokenize_vtab.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts3/fts3_unicode.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts3/fts3_unicode2.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts3/fts3_write.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/icu/sqliteicu.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/icu/icu.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/rtree/rtree.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/rtree/rtree.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/session/sqlite3session.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/session/sqlite3session.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/rbu/sqlite3rbu.h /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/rbu/sqlite3rbu.c /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/misc/json1.c keywordhash.h opcodes.c opcodes.h parse.c parse.h config.h sqlite3.h tsrc
> rm tsrc/sqlite.h.in tsrc/parse.y
> tclsh8.5 /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/tool/vdbe-compress.tcl  <tsrc/vdbe.c >vdbe.new
> mv vdbe.new tsrc/vdbe.c
> cp fts5.c fts5.h tsrc
> touch .target_source
> tclsh8.5 /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/tool/mksqlite3c.tcl
> cp tsrc/shell.c tsrc/sqlite3ext.h .
> cp /cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/session/sqlite3session.h .
> ./libtool --mode=compile --tag=CC gcc -DSQLITE_HAS_CODEC -DSQLCIPHER_CRYPTO_OPENSSL -DSQLITE_OS_WIN=1 -I. -I/cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src -I/cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/rtree -I/cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/icu -I/cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts3 -I/cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/async -I/cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/session -D_HAVE_SQLITE_CONFIG_H -DBUILD_sqlite -DNDEBUG  -DSQLITE_THREADSAFE=1    -DSQLITE_TEMP_STORE=2 -c sqlite3.c
> libtool: compile:  gcc -DSQLITE_HAS_CODEC -DSQLCIPHER_CRYPTO_OPENSSL -DSQLITE_OS_WIN=1 -I. -I/cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/src -I/cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/rtree -I/cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/icu -I/cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/fts3 -I/cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/async -I/cygdrive/c/Users/ruigao/Documents/Visual_Studio_2015/Projects/sqlcipher-3.4.1/ext/session -D_HAVE_SQLITE_CONFIG_H -DBUILD_sqlite -DNDEBUG -DSQLITE_THREADSAFE=1 -DSQLITE_TEMP_STORE=2 -c sqlite3.c  -DDLL_EXPORT -DPIC -o .libs/sqlite3.o
> sqlite3.c:27280:3: error: unknown type name ‘CRITICAL_SECTION’
>    CRITICAL_SECTION mutex;    /* Mutex controlling the lock */
>    ^
> 

### Steps to Reproduce
./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC" && make

SQLCipher version: 3.4.1

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by sjlombardo** [comment]
@sinall I don't have a readily available Cygwin environment to test in, however, it seems like the platform has been identified as Windows (note the `-DSQLITE_OS_WIN=1`), and is therefore trying to use the windows CRITICAL_SECTION in mutex_w32.c, which doesn't appear to be available. We could try to look into this further in the future, but in the mean time you might be better off trying to build this yourself using the amalgamation, i.e. just `make sqlite3.c`, then compile the resulting file yourself using appropriate flags (instead of via the Makefile).

**Comment by sjlombardo** [comment]
@sinall I'm going to close this ticket for inactivity. If this is still an issue please let us know.

**Comment by fengerzh** [comment]
This is the most important option to add in Makefile.msc:

```
-DSQLITE_HAS_CODEC
```

![image](https://user-images.githubusercontent.com/2883744/70783271-8bd45c80-1dc3-11ea-8524-17d86efd1e06.png)
