### ISSUE TITLE
sqlcipher does not work in genymotion.

### ISSUE THREAD

**Issue by tree1891** [sqlcipher/sqlcipher#208]
SQLCipher version: 3.5.6

In Genymotion, SQLiteDatabase.loadLibs(context) fails.

**Comment by developernotes** [comment]
Hello @tree1891 

I apologize for missing this report until now. I just ran the latest SQLCipher for Android test suite, using the latest library, currently at 3.5.9 within a Genymotion emulator and everything worked properly. Would you try the latest version and let us know your results? Thanks!

![screen shot 2018-01-04 at 10 02 53 am](https://user-images.githubusercontent.com/3225/34572327-bf30de5c-f136-11e7-8c76-2ffea0217a9e.png)
