### ISSUE TITLE
Can't build with SQLITE_THREADSAFE=2

### ISSUE THREAD

**Issue by yurivict** [sqlcipher/sqlcipher#209]
I use these commands:
```
./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC -DSQLITE_THREADSAFE=2" LDFLAGS="-L/usr/lib -lcrypto"
gmake
```

However, sqlite3_threadsafe() in the resulting library returns 1, not 2.

SQLITE_THREADSAFE shouldn't differ from its counterpart in SQLite.

The command using the amalgamated version also produces the library with the wrong sqlite3_threadsafe() value.

```
gmake sqlite3.c
cc -O3 -fPIC -DSQLITE_HAS_CODEC -DSQLITE_THREADSAFE=2 -L/usr/lib -lcrypto -DSQLITE_THREADSAFE=2 -shared sqlite3.c -o libsqlite-safe.so
```

**Comment by developernotes** [comment]
Hello @yurivict 

`sqlite3_threadsafe()` returns true or false, depending on the configuration supplied at compile time. Specifically, `sqlite3_threadsafe()` predates multi-thread mode, start-time, and run-time mode selection so is unable to distinguish between multi-thread and serialized mode. More information is available in section 2 of the documentation [here](https://www.sqlite.org/threadsafe.html).

**Comment by yurivict** [comment]
> sqlite3_threadsafe() returns true or false

This isn't true for the current SQLite sources. I just verified with their amalgamated version, it returns values 0,1,2. I am not sure if this is the latest modification, or has always been this way.

**Comment by yurivict** [comment]
For my application I am specifically interested in self-locking version of sqlcipher (SQLITE_THREADSAFE=2).

**Comment by sjlombardo** [comment]
@yurivict I am seeing correct behavior with compilation of the amalgamations (i.e. outside of the configure / make scenario). Using a simple console program that just dumps out the value returned from sqlite3_threadsafe(), it is returning 2 using the SQLCipher amalgamation and the Standard SQLite amalgamation when they are compiled with -DSQLITE_THREADSAFE=2

For test 1, I compile the standard amalgamation and the test program to use it

```
gcc -shared -fPIC -DSQLITE_TEMP_STORE=2 -DSQLITE_THREADSAFE=2 sqlite3.c -o sqlite3.o

gcc -I ../sqlite-amalgamation-3170000  threadsafe.c ../sqlite-amalgamation-3170000/sqlite3.o -l dl -l pthread -o threadsafe
```

result: sqlite3_threadsafe() = 2

For test 2, using make sqlite3.c to assemble the SQLCipher amalgamation and build test program. Note that everything is identical, except for the addition of -DSQLITE_HAS_CODEC and linking of librypto.

```
gcc -shared -fPIC -DSQLITE_HAS_CODEC -DSQLITE_TEMP_STORE=2 -DSQLITE_THREADSAFE=2 sqlite3.c -o sqlite3.o

gcc -I ../sqlcipher -DSQLITE_HAS_CODEC  threadsafe.c ../sqlcipher/sqlite3.o -l dl -l pthread -l crypto -o threadsafe
```
result: sqlite3_threadsafe() = 2

So, in either case the amalgamation is producing the correct results.

**Comment by yurivict** [comment]
@sjlombardo 
Thanks, I retested amalgamated version, and it does produce ```sqlite3_threadsafe() = 2```
