### ISSUE TITLE
Did Sqlcipher support Bitcode ?

### ISSUE THREAD

**Issue by Power-** [sqlcipher/sqlcipher#210]
### Steps to Reproduce

SQLCipher version:

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by sjlombardo** [comment]
@Power- yes, SQLCipher supports bitcode.
