### ISSUE TITLE
Updating to version 10.3 makes SQLCipher have macro issues

### ISSUE THREAD

**Issue by DarkInnocence** [sqlcipher/sqlcipher#212]
After the 10.3 update of iOS, the SQLCipher upon building is giving macro definition errors. It was fine before updating to the latest version of swift which supports 10.3 iOS version.I have used this library with SQLite.swift and installed it using the following pod command pod 'SQLite.swift/SQLCipher', '~> 0.11.2'

After updating to latest version I have run pod update on SQLite.swift/SQLCipher, but the problem still persisted.
Please help!

![screen shot 2017-03-30 at 5 59 15 pm](https://cloud.githubusercontent.com/assets/26249846/24506655/d85650de-157b-11e7-991a-e8f3fdee3bef.png)

**Comment by sjlombardo** [comment]
There is no simple fix for this in SQLCipher itself. MAX is originally defined in sqlite3.c. However, it then later includes sys/param.h, which is part of the iOS SDK. That header contains another definition for MAX, which is not wrapped by an #ifndef MAX to avoid re-definition. 

We can't modify that file directly, and restructuring of the amalgamation would need to happen upstream. For now, you could either ignore the warning, or try to suppress it by working `-Wno-ambiguous-macro` into the cflags.

**Comment by DarkInnocence** [comment]
Thanks..
