### ISSUE TITLE
Database cannot open.

### ISSUE THREAD

**Issue by renjithkrish89** [sqlcipher/sqlcipher#214]
When I created the SQLite on the external Directory using SQlCipher database cannot created. But creating it internally it was working fine. is SQLCipher support the External Directory?

**Comment by developernotes** [comment]
Hi @renjithkrish89 

Yes, SQLCipher for Android supports read/writing to external storage. [Here](https://github.com/sqlcipher/sqlcipher-android-tests/blob/master/src/main/java/net/zetetic/tests/ReadWriteDatabaseToExternalStorageTest.java) is a test example from the SQLCipher for Android test suite.
