### ISSUE TITLE
Unable to attach encrypted database with custom cipher_page_size

### ISSUE THREAD

**Issue by RishatShamsutdinov** [sqlcipher/sqlcipher#215]
### Expected Behavior

Successful DB attaching.

### Actual Behavior

Error: file is encrypted or is not a database.

### Steps to Reproduce

1. Create encrypted db (A).
2. Set custom cipher_page_size for A.
3. Create another encrypted db (B) with same key (using URI with `mode=rwc` param). 
4. Attach B to A.
5. Set custom cipher_page_size for B.
6. Close all db connections.
7. Open A.
8. Set custom cipher_page_size for A.
9. Attach B to A.
10. Observe error.

SQLCipher version: 3.4.1

**Comment by developernotes** [comment]
Hi @RishatShamsutdinov 

You didn't show the exact SQL commands you issued, however I believe [this](https://github.com/sqlcipher/sqlcipher/blob/master/test/crypto.test#L2278-L2298) test case covers what you are referring to. Would you confirm? If not, would you please provide the SQL commands for your specific scenario? Thanks!

**Comment by RishatShamsutdinov** [comment]
`cipher_default_page_size` solved my issue. Thanks!

**Comment by developernotes** [comment]
Hi @RishatShamsutdinov 

Glad to hear your issue is resolved. Take care!
