### ISSUE TITLE
Crash with sqlcipher_export when a trace hook has been installed with sqlite3_trace() or sqlite_trace_v2()

### ISSUE THREAD

**Issue by groue** [sqlcipher/sqlcipher#216]
### Expected Behavior

No crash

### Actual Behavior

A crash on this line: https://github.com/sqlcipher/sqlcipher/blob/df092f0a7af1c8e3558a743036c089e6ef8e6307/src/vdbe.c#L6849

### Steps to Reproduce

1. Open a connection (conn1) to a plaintext database which contains with some data
2. Setup a trace callback on conn1 with the legacy function `sqlite3_trace()`
3. Open another connection (conn2) to a new empty database at path path/to/encrypted.sqlite, and set up encryption with `sqlite3_key()`
4. Execute `ATTACH DATABASE 'path/to/encrypted.sqlite' AS encrypted KEY '...'` on conn1
5. Execute `SELECT sqlcipher_export('encrypted')` on conn1

The last step crashes.

SQLCipher version: 3.4.1

**Comment by groue** [comment]
When the trace callback is defined with sqlite_trace_v2(), the crash happens as well, but on line https://github.com/sqlcipher/sqlcipher/blob/df092f0a7af1c8e3558a743036c089e6ef8e6307/src/vdbe.c#L6854

I thus don't know of any workaround for this bug :'(

**Comment by developernotes** [comment]
Hello @groue 

Thank you for reaching out. We were able to reproduce the behavior described above and are investigating this issue further. We will reach out again once we have additional information to share. Thanks!

**Comment by developernotes** [comment]
Hello @groue 

I have just pushed up [this](https://github.com/sqlcipher/sqlcipher/commit/8a43a6273ad17cd1e3c26f4dcdaed0478a5e777f) commit to our prerelease branch which addresses the issue you are experiencing. This will be included in the next release of SQLCipher. Thanks!
