### ISSUE TITLE
Can I browse encrypted db file in ubuntu System   

### ISSUE THREAD

**Issue by mahendramahi** [sqlcipher/sqlcipher#217]
I have an android app which is using sqlchiper local db, but suddenly Some devices give error 
net.sqlcipher.database.SQLiteMisuseException
.. on Some Screen.
but i m not caught this error on my devices ..
i have that user's db file and encrypted key both  but how can i open it ...

Please help me out ...

Many Thanks .... :-)

**Comment by developernotes** [comment]
Hi @mahendramahi 

You can review our guidance on building SQLCipher for the command line [here](https://www.zetetic.net/sqlcipher/introduction/). The various SQLCipher API's are also documented [here](https://www.zetetic.net/sqlcipher/sqlcipher-api/).
