### ISSUE TITLE
dlopen is Private api

### ISSUE THREAD

**Issue by 94else** [sqlcipher/sqlcipher#219]
### Steps to Reproduce

SQLCipher version:

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by sjlombardo** [comment]
This issue contains insufficient information. You will need to provide adequate and specific details about the issue from the template. If you update the ticket with the required information I will re-open it.
