### ISSUE TITLE
Open bitcode used archive package doesn't work well.

### ISSUE THREAD

**Issue by Power-** [sqlcipher/sqlcipher#222]
An error：Bitcode bundle could not be generated because '../../../../libsqlcipher.a(sqlite3.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7

What should I do，thanks.

**Comment by sjlombardo** [comment]
@Power- you will need to use a libsqlcipher.a that is compiled with bitcode support. How are you integrating SQLCipher now (e.g. via commercial edition pre-built library, Xcode project, cocopods, other)?

**Comment by Power-** [comment]
Excuse me, can you use Chinese, you ask me the question, can I answer in Chinese? ^_^
中文：我在您的开源项目上用模拟器和真机分别build(command+B)出libsqlcipher.a文件，然后在终端用命令将这两个文件合成一个libsqlcipher.a，再把它拖到我的工程中使用，当我打开bitcode后，archive不成功，报的错就是我之前给您截的图
English：I on your open source project, each in simulator and real machine build out(command + B) libsqlcipher.a file, and then with a command to synthesize these two files in terminal a libsqlcipher.a, then put it to use in my project, when I opened the bitcode, archive is not successful, the fault is the figure before I give you cut

**Comment by sjlombardo** [comment]
Hello @Power- The Xcode project included with the source distribution is not really intended to build complete standalone archives. It is instead intended to be used as a subproject, so it may inherit some settings from the master project. The documentation is here: https://www.zetetic.net/sqlcipher/ios-tutorial/

**Comment by Power-** [comment]
Well, thank you very much
