### ISSUE TITLE
configured but can't link using MacOS

### ISSUE THREAD

**Issue by ohhmm** [sqlcipher/sqlcipher#223]
### Expected Behavior
build success

### Actual Behavior
libtool: link: gcc -dynamiclib  -o .libs/libsqlcipher.0.dylib  .libs/sqlite3.o      -install_name  /usr/local/lib/libsqlcipher.0.dylib -compatibility_version 9 -current_version 9.6 -Wl,-single_module
Undefined symbols for architecture x86_64:
  "_CFBundleGetBundleWithIdentifier", referenced from:
      _sqlcipher_cc_get_provider_version in sqlite3.o
  "_CFBundleGetValueForInfoDictionaryKey", referenced from:
      _sqlcipher_cc_get_provider_version in sqlite3.o
  "_CFStringGetCStringPtr", referenced from:
      _sqlcipher_cc_get_provider_version in sqlite3.o
  "_SecRandomCopyBytes", referenced from:
      _sqlcipher_cc_random in sqlite3.o
  "___CFConstantStringClassReference", referenced from:
      CFString in sqlite3.o
      CFString in sqlite3.o
  "_kSecRandomDefault", referenced from:
      _sqlcipher_cc_random in sqlite3.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libsqlcipher.la] Error 1
### Steps to Reproduce

SQLCipher version:
master

**Comment by developernotes** [comment]
Hi @ohhmm 

For your specific build, make sure your `LDFLAGS` include:
```
-framework Security \
-framework Foundation
```

**Comment by ohhmm** [comment]
Hi @developernotes , thank you! I also needed to add /usr/local/opt/openssl/include to includes in Xcode project for openssl. Do you want me to make the pull request?

**Comment by developernotes** [comment]
Hi @ohhmm 

>I also needed to add /usr/local/opt/openssl/include to includes in Xcode project for openssl. Do you want me to make the pull request?

If you are building for CommonCrypto, you should not need OpenSSL. The default crypto provider is OpenSSL, however the path in which OpenSSL is resolved at compilation time can be provided during the `./configure` step, so no pull request is necessary.
