### ISSUE TITLE
PRAGMA cipher deprecated

### ISSUE THREAD

**Issue by mdomke** [sqlcipher/sqlcipher#230]
I was trying to change the cipher that is being used, but was notified that the `PRAGMA cipher` command is deprecated. Is there an alternative way to do this?

### Steps to Reproduce

```
sqlite> PRAGMA key = "foo bar";
sqlite> PRAGMA cipher = "aes-256-gcm";
PRAGMA cipher command is deprecated, please remove from usage.
sqlite> PRAGMA cipher_provider;
openssl
```

SQLCipher version: 3.15.2 2016-11-28 19:13:37

**Comment by mdomke** [comment]
So… I found this [answer](https://discuss.zetetic.net/t/pragma-cipher-command-is-deprecated-please-remove-from-usage/1766). I guess the feature is going to be removed.

**Comment by developernotes** [comment]
Hi @mdomke 

Yes, we plan to remove the ability to change cipher's at runtime in a future release. For now, it will continue to work, you will just receive the warning message when switching.
