### ISSUE TITLE
Unable to link libsqlcipher.a with application

### ISSUE THREAD

**Issue by aashayshah** [sqlcipher/sqlcipher#231]
I have configured sqlite3 to include libcryto like this,

`./configure --enable-tempstore=yes --disable-shared --enable-static=yes CFLAGS='-DSQLITE_HAS_CODEC' LDFLAGS="/usr/lib/x86_64-linux-gnu/libcrypto.a"
`

and then I do,

`make`
which does not give me any errors, however when I try to link the libsqlcipher.a library with my application, and when trying to build with this command:

`gcc -DSQLITE_OMIT_LOAD_EXTENSION -Wall -g -DSQLITE_HAS_CODEC main.c ./.libs/libsqlcipher.a -o main.out
`
It gives me the following error:

```
main.c: In function ‘main’:
main.c:98:10: warning: unused variable ‘zErrMsg’ [-Wunused-variable]
    char *zErrMsg = 0;
          ^
/usr/bin/ld: ./.libs/libsqlcipher.a(sqlite3.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
I tried dynamically linking using `"-lcrypto"` which gives me the same error while using that gcc command.

**Comment by aashayshah** [comment]
I did `make install` and referenced the library using the -L "/usr/local/lib" and `-lsqlcipher` which somehow fixed the error.

**Comment by developernotes** [comment]
Hi @aashayshah 

We are glad to hear you were able to resolve your build error. Take care!
