### ISSUE TITLE
"file is encrypted or is not a database" after executing "pragma cipher_migrate"

### ISSUE THREAD

**Issue by authurlan** [sqlcipher/sqlcipher#233]
### Expected Behavior

Access the encrypted database successfully.

### Actual Behavior

Returned error with "file is encrypted or is not a database".

### Steps to Reproduce

1. Use sqlcipher v2.x.x, create a database, set the key contains 'zero' byte, like x'3f2ae1c00a7ba5a8bf00fa7ac10da18e493065fc21c6769ff1bcdd1ce5366aeb'.
2. Upgrade sqlcipher to v3.x.x, reopen the database, set the key used at step one, execute "pragma cipher_migrate";
3. Reopen the database and set the key again, and do some query, then the error will be printed. 

### My founds

1. After doing "pragma cipher_migrate", the key is truncated, which becomes x'3f2ae1c00a7ba5a8bf'.
2. After checking the code, I think the cause is at line 1055 of crypto_impl.c(master branch)
`char *attach_command = sqlite3_mprintf("ATTACH DATABASE '%s-migrated' as migrate KEY '%q';",
                                                                    db_filename, key);`

SQLCipher version: Upgrade from v2.2.1 to v3.3.1.
I had tried to fix, but my patch not worked. Thanks for help.

**Comment by developernotes** [comment]
Hello @authurlan 

You can use SQLCipher 3.x to create a 2.x data file. Using the current build of SQLCipher, I did the following:

```
$ ./sqlcipher foo.db
sqlcipher> PRAGMA key = "x'3f2ae1c00a7ba5a8bf00fa7ac10da18e493065fc21c6769ff1bcdd1ce5366aeb'";
sqlcipher> PRAGMA kdf_iter = 4000;
sqlcipher> CREATE TABLE t1(alb);
sqlcipher> INSERT INTO t1(alb) VALUES (1,2);
sqlcipher> .q
```

Next, we open `foo.db` and migrate it to the 3.x file format:

```
$ ./sqlcipher foo.db
sqlcipher> PRAGMA key = "x'3f2ae1c00a7ba5a8bf00fa7ac10da18e493065fc21c6769ff1bcdd1ce5366aeb'";
sqlcipher> PRAGMA cipher_migrate;
sqlcipher> .q
```

Finally, we attempt to open the database file again after keying it using default configurations:

```
$ ./sqlcipher foo.db
sqlcipher> pragma key = "x'3f2ae1c00a7ba5a8bf00fa7ac10da18e493065fc21c6769ff1bcdd1ce5366aeb'";
sqlcipher> select * from t1;
a|b
1|2
sqlcipher> .q
```

This appears to be working as expected. Would you please verify the routine your application is attempting matches?

**Comment by authurlan** [comment]
I had read the source code，the use of 'PRAGMA key' is not expected to convert the hex. The below syntax should be used instead.
`pragma hexkey = '3f2ae1c00a7ba5a8bf00fa7ac10da18e493065fc21c6769ff1bcdd1ce5366aeb';`

**Comment by authurlan** [comment]
OK. I have try you procedure, it worked.
The problem I found at using the C API,  I am not sure why it work prefectly at cmd. I will have another try. Thanks.

**Comment by developernotes** [comment]
Hi @authurlan 

To utilize a raw hex key in SQLCipher, you must use the [blob literal format](https://www.zetetic.net/sqlcipher/sqlcipher-api/#key) with the `PRAGMA key` command:

```
PRAGMA key = "x'3f2ae1c00a7ba5a8bf00fa7ac10da18e493065fc21c6769ff1bcdd1ce5366aeb'";
```

**Comment by authurlan** [comment]
Oh, I am sorry. I used the my modified version of sqlcipher 3.x.x. After I revert the change. I try the procedure again, the error happened.

> ./sqlcipher foo.db
> sqlite> pragma hexkey='3f2ae1c00a7ba5a8bf00fa7ac10da18e493065fc21c6769ff1bcdd1ce5366aeb';
> sqlite> create table t1(id integer primary key);
> sqlite> insert into t1(id) values(1);
> sqlite> select * from t;
> 1
> sqlite> .q
> ./sqlcipher foo.db
> sqlite> pragma hexkey='3f2ae1c00a7ba5a8bf00fa7ac10da18e493065fc21c6769ff1bcdd1ce5366aeb';
> sqlite> pragma cipher_migrate;
> 0
> sqlite> .q
> ./sqlcipher foo.db
> sqlite> pragma hexkey='3f2ae1c00a7ba5a8bf00fa7ac10da18e493065fc21c6769ff1bcdd1ce5366aeb';
> sqlite> select * from t1;
> Error: file is encrypted or is not a database

By the way, I doubt the usage of the raw hex you claim. I had ever used the C API to encrypt a database, but when I use the raw hex method that the document claimed to decode the database by sqlcipher tool, it not worked. But it worked at using "pragma hexkey".
Thanks.

**Comment by groue** [comment]
> By the way, I doubt the usage of the raw hex you claim.

Maybe your trouble is here. It's easy to mismatch passphrases (strings of variable length, like `secret`) with keys (256-bits blobs). See https://www.zetetic.net/sqlcipher/sqlcipher-api.

As soon as you use an hex string, confusion is possible. Is `3f2ae1c00a7ba5a8bf00fa7ac10da18e493065fc21c6769ff1bcdd1ce5366aeb` a passphrase (a string that still has to be converted into a key), or the hex representation of a key (256-bits blob)? It's highly ambiguous. Do you know if you are using passphrases or keys? If you are using them *correctly*? A clarification of the kind of secrets you use would make this issue much more clear.

**Comment by authurlan** [comment]
Yes, I do. I am using the hex representation of a key, always. Also in my application.

**Comment by sjlombardo** [comment]
Hello @authurlan - I just wanted to close the loop on this thread. Using PRAGMA hexkey is most likely not the solution you are looking for. That will accept hex bytes, but will still pass them through key derivation. 

Note that if you use a raw key with the syntax described at https://www.zetetic.net/sqlcipher/sqlcipher-api then the database may be opened with SQLCipher 2 or 3. In other words, the main compatibility difference between SQLCipher 2 and 3 was the change from 4,000 to 64,000 rounds for the key derivation function. When using a RAW key, i.e. x'<64 hex>' then key derivation is not applied.
