### ISSUE TITLE
Shall i integrate and use sqlcipher to Nativescript with angular framework?

### ISSUE THREAD

**Issue by kumaran-dena** [sqlcipher/sqlcipher#235]
### Steps to Reproduce

SQLCipher version:

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by developernotes** [comment]
Hi @kumaran-dena 

We typically reserve Github issues for reporting issues found within SQLCipher. You might consider posting your question on our community [discuss site](https://discuss.zetetic.net/c/sqlcipher) along with some additional details regarding your inquiry. If your organization is looking for a commercially supported solution, please feel free to reach out to us at [support@zetetic.net](mailto:support@zetetic.net).
