### ISSUE TITLE
Cannot decrypt the db at server side

### ISSUE THREAD

**Issue by DarkInnocence** [sqlcipher/sqlcipher#239]
I need to know what is the flavour of AES 256 encryption Sqlcipher is using. I cannot decrypt my files at server side (using Node.js). It says invalid algorithm. Currently, I am trying to decrypt using the standard AES 256.

**Comment by sahilmanchal** [comment]
I am also facing same issue.

**Comment by developernotes** [comment]
Hello @DarkInnocence, @sahilmanchal 

We use 256-bit AES in CBC mode using various cryptographic libraries (i.e., OpenSSL, CommonCrypto, libtomcrypt) depending on the build. Please note that while the entire file is encrypted, it is done so in pages, where each page is encrypted individually. Please feel free to post more information about the problem you are attempting to solve on our [discuss](https://discuss.zetetic.net/c/sqlcipher) page, we would be happy to help. Thanks!
