### ISSUE TITLE
shell.c:3659:9: error: 'system' is unavailable: not available on iOS

### ISSUE THREAD

**Issue by Filipe-Figueiredo** [sqlcipher/sqlcipher#240]
### Expected Behavior
The code compiles in XCode 9 (targeting iOS 11)

### Actual Behavior
The code doesn't compile with XCode 9.

**src/shell.c:3659:9: error: 'system' is unavailable: not available on iOS
    x = system(zCmd);**

**/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/usr/include/stdlib.h:195:6: note: 'system' has been explicitly marked unavailable here
int      system(const char *) __DARWIN_ALIAS_C(system);**

**Comment by developernotes** [comment]
Hello @Filipe-Figueiredo 

Is there a reason you are attempting to build `shell.c` using the iOS SDK? `shell.c` is not part of the amalgamation, so it wouldn't be included when building the library for iOS. Would you mind providing some additional details regarding what you are attempting to accomplish? Thanks!

**Comment by Filipe-Figueiredo** [comment]
Hello @developernotes. Is there a way to exclude this file from compilation in iOS specifically? I need to produce a static library of libsqlcipher, because this is a dependency of our project (a C++ lib used for both iOS, Android OSX and Windows platforms).
Thanks!

**Comment by developernotes** [comment]
Hi @Filipe-Figueiredo 

Since you are building a static library, you might consider compiling the amalgamation which you can generate by executing `make sqlite3.c` once you have properly executed `./configure` with the requisite arguments.

**Comment by sjlombardo** [comment]
Hello @Filipe-Figueiredo I'm going to close out this ticket for now, but feel free to comment back if this is still an issue. As @developernotes mentioned, shell.c is not part of the standard "library" it is a command line tool that is meant to be compiled separately for use on desktop systems. If you are compiling the amalgamation (i.e. sqlite3.c / sqlcipher.c) you will not run into this problem.
