### ISSUE TITLE
Implicit declaration of function 'sqlite3_key'   in XCode 9.0

### ISSUE THREAD

**Issue by hbwangcaihua** [sqlcipher/sqlcipher#241]
Implicit declaration of function 'sqlite3_key'   in XCode 9.0

no this function in sqlit3.h, what can I do know ?

**Comment by developernotes** [comment]
Hi @hbwangcaihua 

Can you share a bit more information about how you are specifically building SQLCipher and/or integrating it within your application? Did you previously have SQLCipher integrated before Xcode 9? We will be able to assist once we have more information regarding your specific situation. Thanks!

**Comment by hbwangcaihua** [comment]
Before XCode 9 is work ok . It is error in FMDatabase , the function sqlite3_rekey and sqlite3_key can't be called in XCode 9 .  I want to know how to solve the problem ? Thank you!

**Comment by PointPower** [comment]
Change
#import <sqlite3.h>
To
#import <SQLCipher/sqlite3.h>

**Comment by sjlombardo** [comment]
@hbwangcaihua Please see this document on how to resolve the project setup problems: https://discuss.zetetic.net/t/important-advisory-sqlcipher-with-xcode-9-and-new-sdks/2371
