### ISSUE TITLE
configuration stage prints errors: CFLAGS+= -DSQLCIPHER_CRYPTO_OPENSSL: not found

### ISSUE THREAD

**Issue by yurivict** [sqlcipher/sqlcipher#242]
```
./configure: CFLAGS+= -DSQLCIPHER_CRYPTO_OPENSSL: not found
./configure: BUILD_CFLAGS+= -DSQLCIPHER_CRYPTO_OPENSSL: not found
```

Version: 3.4.1
Found in the FreeBSD port.

**Comment by developernotes** [comment]
Hello @yurivict 

SQLCipher will attempt to use OpenSSL as the default crypto provider (we support several). When compiling SQLCipher, you will need to point the `LDFLAGS` to a static or dynamic OpenSSL library. You can read further details [here](https://www.zetetic.net/sqlcipher/introduction/).
