### ISSUE TITLE
SQLITE_HAS_CODEC, value?

### ISSUE THREAD

**Issue by ducarpit** [sqlcipher/sqlcipher#243]
### Steps to Reproduce

SQLCipher version:

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by ducarpit** [comment]
Which value have i to insert in SQLITE_HAS_CODEC environment variable?
Thanks a lot

**Comment by developernotes** [comment]
Hi @ducarpit 

`-DSQLITE_HAS_CODEC` must be defined when compiling SQLCipher, however there is no associated value for that flag. For more information on building SQLCipher from source, please review [this](https://www.zetetic.net/sqlcipher/introduction/) page. Thanks!
