### ISSUE TITLE
Problem compiling SQLcipher!!!!!

### ISSUE THREAD

**Issue by ducarpit** [sqlcipher/sqlcipher#244]
Hi,
i am trying to compile SQLCipher in Ubuntu, but i got this errore when i run the make command:

```
./.libs/libsqlcipher.so: undefined reference to `OPENSSL_init_crypto'
./.libs/libsqlcipher.so: undefined reference to `HMAC_CTX_new'
./.libs/libsqlcipher.so: undefined reference to `HMAC_CTX_free'
collect2: error: ld returned 1 exit status
Makefile:611: set di istruzioni per l'obiettivo "sqlcipher" non riuscito
make: *** [sqlcipher] Errore 1
```

I tried to instal openssl-dev but it still not work...
How can i solve this?
Thanks

**Comment by ducarpit** [comment]
Hi,
i am trying to compile SQLCipher in Ubuntu, but i got this errore when i run the _make_ command:

```
./.libs/libsqlcipher.so: undefined reference to `OPENSSL_init_crypto'
./.libs/libsqlcipher.so: undefined reference to `HMAC_CTX_new'
./.libs/libsqlcipher.so: undefined reference to `HMAC_CTX_free'
collect2: error: ld returned 1 exit status
Makefile:611: set di istruzioni per l'obiettivo "sqlcipher" non riuscito
make: *** [sqlcipher] Errore 1
```

I tried to instal openssl-dev but it still not work...
How can i solve this?
Thanks

**Comment by billymeltdown** [comment]
Hi @ducarpit, sorry to hear you're having trouble compiling SQLCipher on Ubuntu! We use Github Issues to track *bugs* in SQLCipher, if you need help compiling the software please re-post your question on our discussion forum: https://discuss.zetetic.net/c/sqlcipher

Be sure to show your work, too. For instance, I compiled and installed SQLCipher from source into /usr/local with the following:

    git clone https://github.com/sqlcipher/sqlcipher.git
    cd sqlcipher
    ./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC" LDFLAGS="-lcrypt"
    make
    sudo make install

One of the reasons that works is that I have OpenSSL installed via apt-get.
