### ISSUE TITLE
sqlcipher with dqlite patch

### ISSUE THREAD

**Issue by krzysztofantczak** [sqlcipher/sqlcipher#246]
Hi,

Is it somehow possible, to apply dqlite (https://github.com/CanonicalLtd/dqlite) patch (https://github.com/CanonicalLtd/sqlite/commit/2a9aa8b056f37ae05f38835182a2856ffc95aee4) to sqlcipher code base? Any chance those two will work together?

Here's similar question i asked on dqlite repo.
https://github.com/CanonicalLtd/dqlite/issues/32

What i have tried: https://gist.github.com/krzysztofantczak/6f2816b6206ec7b72bed8af45e6b786a
Which results with:
```
error: patch failed: src/pager.c:4103
error: src/pager.c: patch does not apply
error: patch failed: src/pager.h:178
error: src/pager.h: patch does not apply
error: patch failed: src/sqlite.h.in:8503
error: src/sqlite.h.in: patch does not apply
error: patch failed: src/wal.h:38
error: src/wal.h: patch does not apply
```

**Comment by developernotes** [comment]
Hi @krzysztofantczak 

Since this is not an issue with SQLCipher, I am closing this ticket on Github. Discussions about SQLCipher integrations are better suited on the community [discuss](https://discuss.zetetic.net/c/sqlcipher) site. Please feel free to post your inquiry there. Thanks!
