### ISSUE TITLE
Support for PHP windows.?

### ISSUE THREAD

**Issue by misa3l** [sqlcipher/sqlcipher#248]
Hello, I would like to know if it is possible to compile an external dll for apache windows. I would like to be able to use it in my project. I would really appreciate your help.

**Comment by developernotes** [comment]
Hi @misa3l 

We utilize Github issues for reporting issues with SQLCipher. For questions regarding building the software, we recommend posting within the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by misa3l** [comment]
as ? if they never answer the questions of other people. for example. https://discuss.zetetic.net/t/sqlcipher-integration-to-php/1593   only one answer is needed: it works with php in windows (YES) - (NO)

**Comment by developernotes** [comment]
Hi @misa3l 

Unfortunately I missed that post. Yes, you can compile SQLCipher on Windows for PHP. I have now replied to that thread as well. Thanks!
