### ISSUE TITLE
failed to decrypt data from 1.1.x database using 3.4.x sqlcipher. 

### ISSUE THREAD

**Issue by bbqz007** [sqlcipher/sqlcipher#249]
### Expected Behavior
decrypt data from a 1.1.x database using >2.0 sqlcipher.
### Actual Behavior
2.x sqlciphers work fine, but 3.x ones never.
### Steps to Reproduce
i follow the way of example 3, convert from a 1.1.x to 2.0 Database with HMAC.
steps like:
$ ./sqlcipher my.1.1.x.db
sqlite> pragma key="mykey";
sqlite> pragma cipher_use_hmac=0;
sqlite> select * from sqlite_master;
Error: file is encrypted or is not a database

SQLCipher version: 3.4.0, 3.4.1

i trace this problem by callgrind. the callgrind.out shows 
![image](https://user-images.githubusercontent.com/19798738/33167848-df768f1e-d079-11e7-9d05-dd3a34c0ee0e.png)
![image](https://user-images.githubusercontent.com/19798738/33167928-19a30c3a-d07a-11e7-9758-77dc12f3961b.png)

after this control path, sqlite3RunParser returns with ErrMsg.

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by bbqz007** [comment]
the 2.2.0 sqlcipher's callgrind.out shows
![image](https://user-images.githubusercontent.com/19798738/33169290-15d8fa10-d07f-11e7-8306-c41eeb339461.png)
![image](https://user-images.githubusercontent.com/19798738/33169306-26c0207e-d07f-11e7-996e-9106f9bf882e.png)

the difference between 3.4.x and 2.2.0 is that
the sqlcipher_codec_key_derive function is called 80 times on v2.2.0, while only 1 time on 3.4.x.

does it mean that the 2.2.0 sqlcipher enumerates codec algorithms， and the 3.4.x sqlcipher does not.
or any else reasons.

**Comment by developernotes** [comment]
Hi @bbqz007 

The key derivation length would need to be adjusted if you are attempting to access a 1.1x database using the 3.x software. Try the following:

```
$ ./sqlcipher my.1.1.x.db
sqlite> pragma key='mykey';
sqlite> pragma cipher_use_hmac=0;
sqlite> pragma kdf_iter = 4000;
sqlite> select * from sqlite_master;
```

If that works, you should be able to use the [`PRAGMA cipher_migrate;`](https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_migrate) command to convert the file format in place like this:

```
$ ./sqlcipher my.1.1.x.db
sqlite> pragma key='mykey';
sqlite> pragma cipher_migrate;
sqlite> select count(*) from sqlite_master;
```

Once you have converted the file, you will no longer need to specify different runtime configurations to open the database when using version 3.x of SQLCipher.

**Comment by bbqz007** [comment]
yes, the command 'pragma kdf_iter=4000' makes it work again, thanks.
there is a question that,
a 1.1.x db migrate to 3.x by command 'pragma cipher_migrarte', and can i use a early sqlcipher to access this db normally. for the reason that i should share this db with an another program which use the early sqlcipher.

**Comment by bbqz007** [comment]
by the way, the commad '.dbinfo' seems to work not well. i have no idea about it's the problem of sqlite or sqlcipher. this new command did not come before 3.7.x of sqlite.
![image](https://user-images.githubusercontent.com/19798738/33538330-b13a18d4-d8fb-11e7-90a6-089dd7392a5a.png)
the numbers of tables (table, index, view, trigger) match, but the page size looks odd and does not match the result of command 'pragma page_size'. the statistics counters go so wrong.

**Comment by developernotes** [comment]
Hello @bbqz007 

We are happy to hear everything is working properly for you now. If you migrate the database file, you will need to either update the client library version for applications that will interface with the updated database, or you will need to adjust their configuration at runtime. We recommend the former of the two options. As we use Github Issues for reporting repeatable defects within SQLCipher, I am going to close this ticket. If you have any follow-up questions, we would recommend you ask them on the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by sjlombardo** [comment]
Hello @bbqz007 - The .dbinfo command reads data directly from the database file header without passing it through the pager system. As a result most of the reported values will contain random values. In other words, .dbinfo will not work properly on a SQLCipher database.
