### ISSUE TITLE
unable to encrypt database in sqlcipher

### ISSUE THREAD

**Issue by ganeshpadole55** [sqlcipher/sqlcipher#250]
here is my code. 
 var db: OpaquePointer? = nil
        
        let databasePath = Util.getPath("demo.sqlite")
        print("Database Path: ",databasePath)
        
        
        // first create database file in document directory with empty data
        
        let newDstPath11 = String(format: "%@/Documents/encrypted1.sqlite",NSHomeDirectory())
        
        let newFullDestPath = NSURL(fileURLWithPath: newDstPath11)
        let newDstPath = newFullDestPath.path
        let fileManager = FileManager.default
        
        let success = fileManager.createFile(atPath: newDstPath!, contents: nil, attributes: nil)
        print("Success: ", success)
        
        
        // check newly created file exist at path or not
        
        print("File is present or not: ",fileManager.fileExists(atPath: newDstPath!)) // prints true
        
        
        
        // check sqlite3_open function on newly created file path
        
        let databasePath_NewFile = Util.getPath("encrypted1.sqlite")
        
        
        if (sqlite3_open(databasePath, &db) == SQLITE_OK) {
            
            
//            let  key = "ganesh"
//            let aaa = sqlite3_key(db, key, Int32(strlen(key)) );
//            print("AAA: ", aaa)
//
//            
            
            // 62408519228
            
            let aStr = String(format: "%@/Documents/encrypted1.sqlite",NSHomeDirectory())
            print("Database Path: ", aStr)
            
            
           
            if sqlite3_exec(db, "attach database \(aStr) AS encrypted KEY 'ganesh'".cString(using: .utf8), nil, nil, nil) != SQLITE_OK{
                let errmsg = String(cString: sqlite3_errmsg(db))
                NSLog("Error opening database: \(errmsg)")
            }
            
            
            
            if sqlite3_exec(db, "SELECT sqlcipher_export('encrypted')", nil, nil, nil) != SQLITE_OK {
                let errmsg = String(cString: sqlite3_errmsg(db))
                NSLog("Error sqlcipher_export: \(errmsg)")
            }
            
            
            // Detach encrypted database

            if sqlite3_exec(db, "DETACH DATABASE encrypted", nil, nil, nil) != SQLITE_OK {
                let errmsg = String(cString: sqlite3_errmsg(db))
                NSLog("DETACH DATABASE encrypted: \(errmsg)")
            }
            
            sqlite3_close(db);
            
            
        
        }else{
        
            sqlite3_close(db);
            sqlite3_errmsg(db);
            
        }

/////Expected Behaviour

database should be encrypted

///// Actual behaviour 
here is response
Database Path:  /var/mobile/Containers/Data/Application/FB45BB4B-4314-4AE6-868D-664BA37BA561/Documents/encrypted1.sqlite
2017-11-24 11:30:36.949898+0530 SQLCipherDemo_21nov[3826:2057757] Error opening database: near "/": syntax error
2017-11-24 11:30:36.959923+0530 SQLCipherDemo_21nov[3826:2057757] Error sqlcipher_export: unknown database encrypted
2017-11-24 11:30:36.960310+0530 SQLCipherDemo_21nov[3826:2057757] DETACH DATABASE encrypted: no such database: encrypted

please tell me where is problem

**Comment by sjlombardo** [comment]
Hello @ganeshpadole55 - we use GitHub to track reproducible defects/bugs and feature requests only. This use case is explicitly covered in the test cases for SQLCipher, and we have not been able to reproduce it. We did see your cross-post on the SQLCipher User Forum (https://discuss.zetetic.net/t/unable-to-encrypt-database-in-swift-3/2495) and will respond to your question there. I am closing this ticket for now.
