### ISSUE TITLE
findLibrary returned null

### ISSUE THREAD

**Issue by susanSanjhya** [sqlcipher/sqlcipher#251]
Before upgrading android studio from 2.3.3 to 3.0.1, the library was working fine. But after upgrading android studio, the following error occurs when trying to open database.

Couldn't load sqlcipher_android from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.coa.ec.chekea-1.apk", zip file "/data/data/com.coa.ec.chekea/code_cache/secondary-dexes/com.coa.ec.chekea-1.apk.classes2.zip", zip file "/data/data/com.coa.ec.chekea/code_cache/secondary-dexes/com.coa.ec.chekea-1.apk.classes3.zip"],nativeLibraryDirectories=[/data/app-lib/com.coa.ec.chekea-1, /vendor/lib, /system/lib]]]: findLibrary returned null

I am using sqlcipher.jar. I also tried to use Maven URL but it is not allowing me to update my existing app in play store.

**Comment by developernotes** [comment]
Hi @susanSanjhya,

We utilize Github Issues for reporting verifiable issues within SQLCipher. This issue appears to be an IDE integration issue of sorts. I would recommend reviewing our integration guidance for Android [here](https://www.zetetic.net/sqlcipher/sqlcipher-for-android). If you have any follow-up questions, please consider posting to our SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher) site instead. Thanks!
