### ISSUE TITLE
About 109 issues (Semantic Issues) using (SQLCipher)

### ISSUE THREAD

**Issue by saormart** [sqlcipher/sqlcipher#253]
### Expected Behavior
No warning messages!
### Actual Behavior
about 109 warning messages! 
**Xcode version: 9.1
**Swift version: 4
### Steps to Reproduce
import into project using cocoa pod
SQLCipher version: 3.4.1

Thanks !

**Comment by R4N** [comment]
@saormart 

This post may be helpful for you: https://discuss.zetetic.net/t/how-can-i-remove-all-the-warning-issues-in-xcode-9/2405

TLDR; 
My assumption is most of the warnings are showing up from upstream sqlite (within the sqlite3.c file) and can be safely ignored (for now).  If they bother you, there are steps in the post linked above to silence them just for the sqlite3.c file.

If this assumption isn't correct, please let me know.  Thanks!

**Comment by saormart** [comment]
Hi @R4N, thanks for the tip !
Bu by the way would be awesome to fix them instead of hide it ! 
For me it's fine, because it's working, but the problem is when xcode deprecate it and the framework just stop working !
Thanks for the tip again !

**Comment by R4N** [comment]
>by the way would be awesome to fix them instead of hide it !

Many of the warnings come from the upstream sqlite (i.e. implicit conversion loses integer precision), from which we don't want to diverge .

There are a couple of warnings that we plan on adjusting for in the future like:

```
void sqlcipher_activate();
```

This function declaration is not a prototype
