### ISSUE TITLE
SQLCipher compatibility with dexguard

### ISSUE THREAD

**Issue by hherreraOT** [sqlcipher/sqlcipher#254]
We are trying to apply dexguard configuration found on your samples for sqlCipher, but for the latest version of your library (3.5.7) we find a crash in runtime. Does your latest version support dexguard?

**Comment by developernotes** [comment]
Hi @hherreraOT 

It appears you are referring to the [android-database-sqlcipher](https://github.com/sqlcipher/android-database-sqlcipher) project? If so, please take a look at this [sample ProGuard file](https://raw.githubusercontent.com/sqlcipher/android-database-sqlcipher/v3.4.0/proguard-project.txt), you may need to adjust it to your specific needs. We utilize Github Issues for tracking reproducible issues within SQLCipher. I would recommend the SQLCipher [discuss](https://discuss.zetetic.net/c/sqlcipher) site for integration questions. Thanks!
