### ISSUE TITLE
Does not work on Windows XP due to fopen_s call

### ISSUE THREAD

**Issue by fap008c** [sqlcipher/sqlcipher#257]
### Expected Behavior
SQLCipher does work on WindowsXP

### Actual Behavior
SQLCipher does not work on WindowsXP

### Steps to Reproduce
/src/crypto_impl.c

in function 
```cpp
int sqlcipher_cipher_profile(sqlite3 *db, const char *destination){
#if defined(SQLITE_OMIT_TRACE) || defined(SQLITE_OMIT_DEPRECATED)
  return SQLITE_ERROR;
#else
  FILE *f;
  if(sqlite3StrICmp(destination, "stdout") == 0){
    f = stdout;
  }else if(sqlite3StrICmp(destination, "stderr") == 0){
    f = stderr;
  }else if(sqlite3StrICmp(destination, "off") == 0){
    f = 0;
  }else{
#if defined(_WIN32) && (__STDC_VERSION__ > 199901L) || defined(SQLITE_OS_WINRT)
    if(fopen_s(&f, destination, "a") != 0){
#else
    f = fopen(destination, "a");
    if(f == 0){
#endif    
    return SQLITE_ERROR;
} 
```
The line causing problem
```cpp
    if(fopen_s(&f, destination, "a") != 0){
```
fopen_s does not exists in msvcrt.dll version for win XP

Does this conditional compile is really required? May be simple fopen will be enough for else scope?

I have tested that simple fopen works on WinXP, Win7, Win8.1. From other side I am not sure for all other cases.

SQLCipher version:
sqlcipher-3.4.2.zip

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by developernotes** [comment]
Hi @fap008c 

Unfortunately, `fopen` caused issues with Windows Runtime/Windows UAP, thus requiring the usage of `fopen_s`. We will look into addressing this to allow Windows XP to pass through to `fopen` in a future release of SQLCipher. Thanks!

**Comment by sjlombardo** [comment]
@fap008c As of the latest release you should now now compile SQLCipher with -DSQLCIPHER_PROFILE_USE_FOPEN for compatibility in this scenario.
