### ISSUE TITLE
Multiple DB connections with encryption turned on doesn't work

### ISSUE THREAD

**Issue by kakashidinho** [sqlcipher/sqlcipher#260]
Hi,

### Steps to Reproduce
I'm using sqlcipher, and create multiple connections to a same DB. The DB is encrypted.
I tried to create a table in one connection in one thread, and read that table in another connection in another thread.

SQLCipher version: 3.11.0

### Expected Behavior
The reading thread should be able to see the created table.

### Actual Behavior
The reading thread wasn't able to see the created table. But the creating thread was able to.

**Comment by kakashidinho** [comment]
Additional observation, even when in the same threads, the two connections seem to have problem query changes made by other

**Comment by kakashidinho** [comment]
More observations: If the two connections were created at the time when Database has no table then the 2nd connection won't see new table created by 1st connection.
However, after I created one table, then open 2nd connection, it will be able to see any tables created by 1st connection thereafter

**Comment by developernotes** [comment]
Hi @kakashidinho 

Can you provide some additional details regarding your usage scenario? Specifically, what [threading mode](https://sqlite.org/threadsafe.html) is your version of SQLCipher using? Also, are you using [WAL journaling mode](https://sqlite.org/wal.html)? If not, would you try both WAL and the serialized threading mode and let us know your results?

**Comment by kakashidinho** [comment]
This is the code sample. You see that I created 2 connections, and when 2nd connection tries to read from the table created by 1st connection, "no such table" exception will be thrown:

```java
    String dbFolder = ContextCompat.getDataDir(this) + "/tmp";
    String dbFile = dbFolder + "/test.db";
    String dbJavaPassword = "12345";

    // delete older db folder
    try {
      delete(new File(dbFolder));
    } catch (Exception e) {
    }

    // recreate the db folder
    new File(dbFolder).mkdirs();

    // Open java connections to our test DB
    SQLiteDatabase.loadLibs(this);

    SQLiteDatabase javaDB = SQLiteDatabase.openOrCreateDatabase(new File(dbFile), dbJavaPassword, null);
    SQLiteDatabase javaDB2 = SQLiteDatabase.openOrCreateDatabase(new File(dbFile), dbJavaPassword, null);

    // Now create a table using our 1st connection
    javaDB.execSQL("create table RequireDone "
                      + "( "
                      + "  Name   text not null, "
                      + "  Value  integer not null "
                      + ");");

    javaDB.execSQL("insert into RequireDone "
              + "  (Name, Value) "
              + "values "
              + "  ('Foo', 1);");
 
    // verify that table using 2nd connection
    {
      // Exception "no such table RequireDone" will be thrown below
      Cursor c = javaDB2.rawQuery("select * from RequireDone", new String[]{});
      if (c.moveToNext()) ;
      {
        String name = c.getString(0);
        int value = c.getInt(1);

        Log.d(LOG_NAME, "java --> name=" + name + " value=" + value);
      }
    }
```

**Comment by kakashidinho** [comment]
If I create 2nd connection after 1st connection created the table, then 2nd one will be able to read the table correctly

**Comment by developernotes** [comment]
Hi @kakashidinho 

What behavior do you observe when enabling WAL journaling mode with your same scenario?

**Comment by sjlombardo** [comment]
Hello @kakashidinho - thanks for providing the code sample. After reviewing, we believe we know what is happening here. Because you are opening the two database connections in immediate sequence, there is no data actually on the filesystem when the second connection is open. This causes the second connection to create a new encryption key which is different than the first, along with a cached empty schema. Once you create the table and data, the second connection is unable to requery the schema because the keys are different.

The best way to avoid this situation is to ensure that the database is persisted to the file system before opening the second connection. For if you were to create the table on the first connection, then open the second connection, it would be able to read subsequent changes. 

Could you give that and let us know if that resolves the issue?

**Comment by kakashidinho** [comment]
Thanks for letting me know the problem. Yes, I guess I have to make sure there is data on the filesystem before creating another connection.
