### ISSUE TITLE
Zero-out page cache on close

### ISSUE THREAD

**Issue by rnewman** [sqlcipher/sqlcipher#262]
This is an issue to track [this topic](https://discuss.zetetic.net/t/zero-page-cache-on-close/2743).

In summary:

---

The SQLite pager will cache pages read from disk and decrypted by SQLCipher. These will be cleartext in memory.

On close, the cache is destroyed. Reading the code, that seems to simply involve truncation, which will leave cleartext page data in unallocated memory.

Not only is the pager responsible for the largest amount of allocated memory in SQLite, but while the application is in control of the creation of temporary tables and (to an extent) cursors and wrapper libraries, it has little control over this lower level.

Setting `cache_size=0` prevents cleartext data from remaining in the page cache, but only works if you set that before running any queries. Presumably this has a significant impact on query performance.

It would be worth adding code to SQLCipher (or, indeed, upstreaming it to SQLite) to zero-out the page cache, either page-by-page as they're freed, or for the entire memory region on closing the database if it's contiguous.

**Comment by sjlombardo** [comment]
Hello @rnewman  - The release of SQLCipher 4 adds functionality that will wipe memory allocated by SQLite internally,including the page cache. These hooks are enabled by default upon initialization of the library. The behavior can be disabled using [`PRAGMA cipher_memory_security=OFF`](https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_memory_security) for a small performance boost.
