### ISSUE TITLE
How to compile the source codes with C or C++ on Windows?

### ISSUE THREAD

**Issue by lishanlei** [sqlcipher/sqlcipher#263]
### Expected Behavior
I want to use the SQLCipher for a encrypted database. But it seems that SQLCipher could not support the compilin on Windows. Is there any one can help me ?
### Steps to Reproduce

SQLCipher version: The Lasted

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by developernotes** [comment]
Hello @lishanlei 

SQLCipher can be compiled on various Windows platforms. We utilize Github Issues as a source to collect defects in the software itself. We maintain a [discuss](https://discuss.zetetic.net/c/sqlcipher) site for the community to post questions of this nature. Please feel free to post there. Thanks!
