### ISSUE TITLE
[doc] please provide a list of build dependencies

### ISSUE THREAD

**Issue by sudden6** [sqlcipher/sqlcipher#265]
It would really help when building from source to have a list of needed build dependencies, at least for one popular distribution like Debian.

So far I could find that the following packages are needed
```
buiid-essentials tclsh libssl-dev
```

Would be nice to have a complete list with all the mandatory and optional dependencies somewhere near the build instructions.

**Comment by developernotes** [comment]
Hello @sudden6 

Thank you for your interest in SQLCipher. We will update our [SQLCipher Introduction](https://www.zetetic.net/sqlcipher/introduction/) page to provide a bit more information for getting started. We will then link to that from the README. Thanks!
