### ISSUE TITLE
Archive issue via CI server

### ISSUE THREAD

**Issue by iosfitness** [sqlcipher/sqlcipher#266]
I am not able to generate libsqlcipher.a inside **Release-iphoneos**

Logs from the CI Server [Jenkins] :

clang: error: no such file or directory: '~/Library/Developer/Xcode/DerivedData/XXX-fqalbxsdmrbgnmefqteljbygjazu/Build/Intermediates.noindex/ArchiveIntermediates/XXX/BuildProductsPath/Release-iphoneos/libsqlcipher.a'

** ARCHIVE FAILED **

The following build commands failed:
~/Library/Developer/Xcode/DerivedData/XXX-fqalbxsdmrbgnmefqteljbygjazu/Build/Intermediates.noindex/ArchiveIntermediates/XXX/IntermediateBuildFilesPath/XXX.build/Release-iphoneos/XXX.build/Objects-normal/arm64/XXX normal arm64

~/Library/Developer/Xcode/DerivedData/XXX-fqalbxsdmrbgnmefqteljbygjazu/Build/Intermediates.noindex/ArchiveIntermediates/XXX/IntermediateBuildFilesPath/XXX.build/Release-iphoneos/XXX.build/Objects-normal/armv7/XXX normal armv7
(2 failures)
Build step 'Xcode' marked build as failure
[AWS CodePipeline Plugin] Publishing artifacts
[AWS CodePipeline Plugin] Build failed, calling PutJobFailureResult
Build step 'AWS CodePipeline Publisher' marked build as failure
Finished: FAILURE

However, libsqlcipher.a is getting generated in **Release** folder ~/Library/Developer/Xcode/DerivedData/XXX-fqalbxsdmrbgnmefqteljbygjazu/Build/Intermediates.noindex/ArchiveIntermediates/XXX/IntermediateBuildFilesPath/XXX.build/Release/

Any help ?

**Comment by developernotes** [comment]
Hello @iosfitness 

Would you please post a full build log output via [gist](https://gist.github.com/) for review? Thanks!

**Comment by iosfitness** [comment]
@developernotes I was able to resolve this issue.
I am using a Master-Slave setup at my end for CI server. There were some issues with the permissions hence this error. I added a shell script in Jenkins to add permissions to these files

**Comment by iosfitness** [comment]
@developernotes Thanks for replying
 I was able to resolve this issue.
I am using a Master-Slave setup at my end for CI server. There were some issues with the permissions hence this error. I added a shell script in Jenkins to add permissions to these files
