### ISSUE TITLE
Pod installation error

### ISSUE THREAD

**Issue by iosfitness** [sqlcipher/sqlcipher#267]
It worked for the first time but then when I try to install the pod again, it's complaining..

Installing SQLCipher (3.4.2)
[!] /bin/bash -c 
set -e
./configure --enable-tempstore=yes --with-crypto-lib=commoncrypto CFLAGS="-DSQLITE_HAS_CODEC -DSQLITE_TEMP_STORE=2 -DSQLITE_SOUNDEX -DSQLITE_THREADSAFE -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_STAT3 -DSQLITE_ENABLE_STAT4 -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_MEMORY_MANAGEMENT -DSQLITE_ENABLE_LOAD_EXTENSION -DSQLITE_ENABLE_UNLOCK_NOTIFY -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS4_UNICODE61 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_FTS5 -DHAVE_USLEEP=1 -DSQLITE_MAX_VARIABLE_NUMBER=99999"; make sqlite3.c

checking build system type... i386-apple-darwin17.4.0
checking host system type... i386-apple-darwin17.4.0
checking how to print strings... printf
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... 
configure: error: in `/Users/xxxx/Library/Caches/CocoaPods/Pods/Release/SQLCipher/3.4.2-f9fcf':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

[!] Automatically assigning platform `ios` with version `9.0` on target `XXX` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

 pod 'SQLCipher'

Reference : 
https://github.com/CocoaPods/Specs/blob/master/Specs/1/2/7/SQLCipher/3.4.2/SQLCipher.podspec.json

**Comment by developernotes** [comment]
Hi @iosfitness 

Is this the same issue you reported in a separate issue #266?

**Comment by iosfitness** [comment]
@developernotes . Not exactly, but I tried this approach as an alternative to fix  #266

**Comment by developernotes** [comment]
Hi @iosfitness 

If you haven't resolved the issue. What is the content of the `config.log`?

**Comment by YuryBogdanov** [comment]
I had this issue because of wrong path to Xcode. `config.log` had this error message:
```
xcrun: error: active developer path ("/Applications/Xcode-beta.app/Contents/Developer") does not exist
Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
```

All I had to do was to run suggested xcode-select command and then `pod install` worked without any errors. 
Hope that'll help.

**Comment by sjlombardo** [comment]
Since we haven't heard back from the OP, I'm going to close this ticket due to inactivity.
