### ISSUE TITLE
Generate lib for custom build configuration

### ISSUE THREAD

**Issue by iosfitness** [sqlcipher/sqlcipher#268]
I have custom build configurations in my App.

Now, when I try to point the App to Integration environment, all my pods and files get created for that but libSqlCipher is not generated (Perhaps it needs to point to the same configuration). However, it works well for Release and Debug build configuration

I followed the steps from https://www.zetetic.net/sqlcipher/ios-tutorial/

I also tried editing the Per configuration build product path and  Per configuration intermediate build files path to release but then I get an error with cocoa pods.

I also have to automate the process via Jenkins

Can anyone suggest the approach how this can be handled ?.

**Comment by billymeltdown** [comment]
Hi @iosfitness, this GitHub Issue you filed with SQLCipher is not a bug report or problem with SQLCipher and will be closed. Our GitHub Issues page is for tracking problems with SQLCipher itself, not user configuration problems and questions. [On our discussion forum](https://discuss.zetetic.net/c/sqlcipher) you'll find other posts similar to your own and there may be some folks hanging around there who can answer your question, you might consider asking there after doing some research. Thanks!
