### ISSUE TITLE
Where is file of static library after make is done?

### ISSUE THREAD

**Issue by sergorl** [sqlcipher/sqlcipher#269]
I tryed to build static library on Ubuntu 16.04 so I did this:
```
./configure  --disable-tcl --disable-shared --enable-static=yes --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC" LDFLAGS="/usr/lib/x86_64-linux-gnu/libcrypto.a"
make
```
But I can't find file of static library which ends on `.a`. Where is it?

**Comment by sergorl** [comment]
I forgot this:
```
make install DESTDIR=/path/to/lib
```
After above command `libsqlcipher.a` will be in:
`/path/to/lib/usr/local/lib`

**Comment by developernotes** [comment]
Hi @sergorl 

Glad to hear you resolved your issue!
