### ISSUE TITLE
compile errors for 3.4.2 with libressl 2.7.x

### ISSUE THREAD

**Issue by thomaslegg** [sqlcipher/sqlcipher#271]
### Expected Behavior
compiles safely

### Actual Behavior
fails to compile due to following errors.
-------
sqlite3.c:21642:18: error: static declaration of 'HMAC_CTX_new' follows non-static declaration
static HMAC_CTX *HMAC_CTX_new(void)
                 ^
/usr/local/include/openssl/hmac.h:86:11: note: previous declaration is here
HMAC_CTX *HMAC_CTX_new(void);
          ^
sqlite3.c:21655:13: error: static declaration of 'HMAC_CTX_free' follows non-static declaration
static void HMAC_CTX_free(HMAC_CTX *ctx)
            ^
/usr/local/include/openssl/hmac.h:87:6: note: previous declaration is here
void HMAC_CTX_free(HMAC_CTX *ctx);

----------

### Steps to Reproduce
try to compile

SQLCipher version: 3.4.2

**Comment by sjlombardo** [comment]
This issue should now be resolved in the SQLCipher 4 release. It should now be possible to build against LibreSSL 2.7.0+ (and also OpenSSL 1.1.x).
