### ISSUE TITLE
How to make sqlcipher support file protection in IOS

### ISSUE THREAD

**Issue by zedzhao** [sqlcipher/sqlcipher#274]
The sqlcipher doesn't support the file protection flag in IOS. Is there any way may let sqlcipher support the file protection feature in iOS platform?

**Comment by brodybits** [comment]
SQLITE_OPEN_FILEPROTECTION does not seem to be supported by open-source SQLite, not even by the `apple-osx` branch ref: <https://www.sqlite.org/src/timeline?n=100&r=apple-osx>

I think the only solution is to set value for NSFileProtectionKey in `setAttributes: ofItemAtPath: error:` instance method of NSFileManager ref:
- <https://developer.apple.com/documentation/foundation/nsfileattributekey?language=objc>
- <https://developer.apple.com/documentation/foundation/nsfilemanager/1413667-setattributes>

This was discussed before in #156 and <https://github.com/ccgus/fmdb/issues/262>, I think this is the only solution.

**Comment by zedzhao** [comment]
OK， I see it, thank you.

**Comment by zedzhao** [comment]
If the sqlite db file use 'WAL' mode, do I need use FileManager to set the shm and wal file protection attribute? If so, what time is the best option to change the file attribute, because I see the shm and wal file wasn't created once db file was created. The shm and wal file was created at the first I/O operation.

**Comment by sjlombardo** [comment]
@zedzhao you would need to account for that at the application level, by tracking the point at which an IO operation would cause the files to be created, and then invoking the API to set the flags. You could certainly perform an operation immediately once the database is opened to force creation to happen early in the application lifecycle.
