### ISSUE TITLE
A lot of warnings in new Xcode 10.

### ISSUE THREAD

**Issue by lolgear** [sqlcipher/sqlcipher#275]
I have installed SQLCipher by Cocoapods as a dependency of [EncryptedCoreData](https://github.com/project-imas/encrypted-core-data
) (project-imas).

This library has following warnings:

- Semantic issues 
-- Function declaration is not a prototype
-- Possible misuse of comma operator
- Lexical or Preprocessor issues
-- Ambiguous expansion of macro ( MIN/MAX )
- Value Conversion issues
-- A lot of implicit conversions.

Could they be fixed?

Thanks!

**Comment by R4N** [comment]
Hi @lolgear 

Have a look a this comment on our discussion forum: https://discuss.zetetic.net/t/how-can-i-remove-all-the-warning-issues-in-xcode-9/2405/2

specifically this portion:

> If the warnings are from upstream sqlite3 and they bother you, you should either be able to silence them with a -w compiler flag or compile SQLCipher once and link against the .a
