### ISSUE TITLE
Error when executing pod 'SQLCipher'

### ISSUE THREAD

**Issue by BBB1n** [sqlcipher/sqlcipher#278]
An error occurred while executing pod 'SQLCipher', but it was successful yesterday.

SQLCipher version:
3.4.1 or 3.4.2

The following is the error content:
Installing SQLCipher (3.4.1)
[!] /bin/bash -c
Set -e
./configure --enable-tempstore = yes --with-crypto-lib = commoncrypto CFLAGS = "- DSQLITE_HAS_CODEC -DSQLITE_TEMP_STORE = 2 -DSQLITE_SOUNDEX -DSQLITE_THREADSAFE -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_STAT3 -DSQLITE_ENABLE_STAT4 -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_MEMORY_MANAGEMENT -DSQLITE_ENABLE_LOAD_EXTENSION -DSQLITE_ENABLE_UNLOCK_NOTIFY -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS4_UNICODE61 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_FTS5"; make sqlite3.c

Checking build system type... i386-apple-darwin17.5.0
Checking host system type... i386-apple-darwin17.5.0
Checking how to print strings... printf
Checking for gcc... clang
Rating whether the C compiler works... yes
Checking for C compiler default output file name... a.out
Checking for suffix of executables...
Checking whether we are cross compiling...
Configure: error: in `/Users/zhaowenbin/Library/Caches/CocoaPods/Pods/Release/SQLCipher/3.4.1-43d12':
Configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

**Comment by developernotes** [comment]
Hi @BBB1n 

>See `config.log' for more details

Would you please post the full content of the `config.log` file? We will need that to review any reported errors from the build system. Thanks!

**Comment by BBB1n** [comment]
Thank you for your reply, I found that there may be a problem with the pod configuration. Yesterday I tried it with my own computer. Thank you again.

**Comment by developernotes** [comment]
Hi @BBB1n 

Thank you for the update, we are happy to hear that you were able to address the issue. Take care!
