### ISSUE TITLE
Can sqlcipher replace the aes256 encryption algorithm?

### ISSUE THREAD

**Issue by BBB1n** [sqlcipher/sqlcipher#280]
I want to use the sm4 encryption algorithm, how to replace the default aes256

**Comment by developernotes** [comment]
Hello @BBB1n 

You would need to implement and register your own crypto provider. You might review the OpenSSL crypto provider for reference [here](https://github.com/sqlcipher/sqlcipher/blob/master/src/crypto_openssl.c).
