### ISSUE TITLE
Security weak overwriting sqlite3_key

### ISSUE THREAD

**Issue by marcobeninca71** [sqlcipher/sqlcipher#284]
### Expected Behavior
Not possible to crack the passkey

### Actual Behavior
It's possible to steal the passkey overwriting the function sqlite3_key

### Steps to Reproduce

SQLCipher version: last

Suppose I want to write an application running locally on a PC and I need a DB which could not be accessed by the user; using sqlcipher in my application I can specify a passkey to open the DB: the passkey is passed directly to sqlite3_key function or using PRAGMA Key = ... .

Now suppose that the user is a developer; he can download the code of sqlcipher library, overwite the sqlite3_key function putting some code to print the passkey used by my application. Now he can open the DB using some SQLIte browsing software downloaded from the internet.

Which kind of protection can I use to prevent this scenario?

Thanks in advance

Marco

**Comment by developernotes** [comment]
Hello @marcobeninca71 

Thank you for your interest in SQLCipher. We reserve GitHub Issues as a location for reporting issues with the SQLCipher library itself. This type of scenario-based question is best posted within our public SQLCipher discuss site which allows for further dialog. Please feel free to post [here](https://discuss.zetetic.net/c/sqlcipher) to discuss further. Thanks!
