### ISSUE TITLE
Understanding how it works

### ISSUE THREAD

**Issue by trounce1** [sqlcipher/sqlcipher#285]
hi hopefully someone can help me with understanding the crypto in this.

so if i have a pragma key, i know the encryption is AES CBC 256 and i can pull the IV from the database

what else do i need to know to just run a decrypt on the first block of the database?

**Comment by developernotes** [comment]
Hi @trounce1 

We reserve GitHub Issues as location for reporting defects in the SQLCipher library itself. This question is rooted more in the design of the library. I would recommend you take a look at our [design doc](https://www.zetetic.net/sqlcipher/design/), and if you have further questions feel free to post the specifics to our SQLCipher [community discuss](https://discuss.zetetic.net/c/sqlcipher) site. Thanks!
