### ISSUE TITLE
Better handling of random buffer

### ISSUE THREAD

**Issue by MarcSchoenefeld** [sqlcipher/sqlcipher#286]
https://github.com/sqlcipher/sqlcipher/blob/c6f709fca81c910ba133aaf6330c28e01ccfe5f8/src/crypto_libtomcrypt.c#L156-L175

a) Consider adding check:   if(random_buffer == NULL) return SQLITE_NOMEM; 
b) Consider calling sqlcipher_free(..)  in case of early return.

**Comment by sjlombardo** [comment]
Hello @MarcSchoenefeld  - thanks so much for the suggested changes! these will be corrected in the forthcoming release of SQLCipher. I will leave the ticket open until that is published.

**Comment by sjlombardo** [comment]
Hello @MarcSchoenefeld - The underlying issue here should now be resolved in SQLCipher 4, as the sqlcipher_ltc_kdf() function has been modified so that it dose not allocate a temporary buffer internally. Thanks again for this report!
