### ISSUE TITLE
Msg:recovered 2 frames from WAL file

### ISSUE THREAD

**Issue by wdq123550** [sqlcipher/sqlcipher#288]
un.. I just ask the log that Msg:recovered 2 frames from WAL file xx....
what it's means?

**Comment by developernotes** [comment]
Hello @wdq123550 

That message is logged during the recovery process [here](https://github.com/sqlcipher/sqlcipher/blob/master/src/wal.c#L1236-L1239) when rebuilding the WAL-index to match the WAL. You can read more about recovery [here](https://www.sqlite.org/walformat.html#recovery).

**Comment by wdq123550** [comment]
well.un..my able is poor.Can you tell me this log means I used is wrong？I ask other people that say let it go.So,Can i ignore this log？thank you

**Comment by developernotes** [comment]
Hello @wdq123550 

The log message is reporting that 2 frames were recovered such that the WAL-index is now consistent with the WAL file itself. Either the last client did not call `sqlite3_close()`, or the last client to disconnect was read-only. The [Files On Disk](https://www.sqlite.org/walformat.html#files_on_disk) section of the WAL format documentation covers further the purpose of the files. The message being logged should be viewed as informational.

If you have further questions after reviewing the documentation links provided, please post further to the SQLCipher [discuss](https://discuss.zetetic.net/c/sqlcipher) site as we utilize Github Issues for reporting defects with the SQLCipher library itself. Thanks!
