### ISSUE TITLE
Build static lib with VS 2017 

### ISSUE THREAD

**Issue by mtissington** [sqlcipher/sqlcipher#289]
### Steps to Reproduce

SQLCipher version:

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by mtissington** [comment]
I have successfully built using VS 2017 and openssl by modifying makefile.msc. However how can I create a static lib for sqlcipher?

**Comment by developernotes** [comment]
Hello @mtissington 

SQLCipher can be compiled on various Windows platforms. We utilize Github Issues as a source to collect defects in the software itself. We maintain a [discuss site](https://discuss.zetetic.net/c/sqlcipher) for the community to post questions of this nature. Please feel free to post there. Alternatively we sell commercial editions of the library prebuilt for Windows [here](https://www.zetetic.net/sqlcipher/commercial-edition-ordering). Thanks!
