### ISSUE TITLE
Source code signature unavailable

### ISSUE THREAD

**Issue by svetlemodry** [sqlcipher/sqlcipher#291]
### Expected Behavior
Signing key to be be available in the https://www.zetetic.net/sqlcipher/verify/4.0.0/sqlcipher-4.0.0.zip.sig location.

### Actual Behavior
 404 Not Found error received.
Also the https://www.zetetic.net/sqlcipher/verify/ page links at the bottom to another file with a possibly wrong file name: sqlcipher-4.0.04.0.0.zip.sig

### Steps to Reproduce
wget https://www.zetetic.net/sqlcipher/verify/4.0.0/sqlcipher-4.0.0.zip.sig
404 Not Found

SQLCipher version: 4.0.0

**Comment by developernotes** [comment]
Hello @svetlemodry 

Thank you for your interest in SQLCipher. Unfortunately, we do not directly control the distribution of the SQLCipher core zip file, that is generated from GitHub. We have decided to only provide digital signatures for packages that we have generated ourselves. I have updated the website to remove the incorrect link. Thanks!

**Comment by developernotes** [comment]
Hi @svetlemodry 

We have decided to host a tagged snapshot of the source tree directly and will provide a corresponding digital signature for those snapshots. Please find the verify page updated [here](https://www.zetetic.net/sqlcipher/verify/). Thanks!
