### ISSUE TITLE
add "make uninstall" target

### ISSUE THREAD

**Issue by yuriescl** [sqlcipher/sqlcipher#295]
### Expected Behavior

There should be a target for uninstalling (like `make uninstall`), which undoes `make install`.

### Actual Behavior

It's difficult to remove files manually without the `make uninstall` option.

### Steps to Reproduce

```
make
make install
# now there's no option to undo the install, so files have to be removed manually
```

SQLCipher version: 3.25.2

**Comment by developernotes** [comment]
Hi @yuriescl 

Would you try using the `--prefix=/path/to/alternative/directory` option passed to your `./configure` instead? This will allow all files to be installed into a single directory when `make install` is invoked, and will simplify cleanup as you can just `rm -rf` the path you install to.

We try to avoid major changes to the Makefile's and build scripts as they would diverge from the upstream. This is certainly something you might consider inquiring with the sqlite-dev team directly.

**Comment by yuriescl** [comment]
Sure, thanks!
