### ISSUE TITLE
Problem with SQLCipher 4.0 pod

### ISSUE THREAD

**Issue by vostreltsov** [sqlcipher/sqlcipher#298]
I am trying to use SQLCipher 4.0.0 for iOS/swift development.

I use `pod 'SQLCipher', '~>4.0'` and here is my code for opening a db connection:

```
func open(dbPath: String, key: String? = nil) -> Bool {
    var error = sqlite3_open_v2(dbPath, &db, SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE, nil)
    if error != SQLITE_OK {
        sqlite3_close(db)
        return false
    }
    
    if key != nil {
        error = sqlite3_key(db, key!, Int32(key!.utf8CString.count))    // this fails
        if error != SQLITE_OK {
            let errmsg = String(cString: sqlite3_errmsg(db))
            NSLog("Error preparing SQL: \(errmsg)")
            sqlite3_close(db)
            return false
        }
    }
    
    return true
}
```

The error returned is `SQLITE_MISUSE`. I have checked C compiler flags, linker flags, etc, etc, a million times (according to [the ios tutorial](https://www.zetetic.net/sqlcipher/ios-tutorial/), even though it should work out of the box for pods), but still get this error. What can possibly be wrong?

Thank you.

**Comment by R4N** [comment]
Hi @vostreltsov 

Thanks for your interest in SQLCipher.  We reserve GitHub issues for reporting flaws within the SQLCipher library.  For questions/issues with integration could you please post over to the SQLCipher discussion forum here: https://discuss.zetetic.net/c/sqlcipher

>I have checked C compiler flags, linker flags, etc, etc, a million times (according to the ios tutorial, even though it should work out of the box for pods)

Pods integration should work out of the box without having to adjust the flags (I just retested a simple sample application integration).  The only other thing you should have to add is the bridging header as described in the tutorial you linked.

So my initial thoughts are:

1. Are you properly adding the bridging header?
2. Are you including some other pod/library that could be including another copy of sqlite which could be conflicting with the one used in SQLCipher?

If these suggestions don't help you resolve the integration issue, please feel free to post over the discussion board so the SQLCipher community can attempt to assist (it may be helpful to create a sample GitHub project with a very simple reproducible example)
