### ISSUE TITLE
Error: file is not a database with the latest version

### ISSUE THREAD

**Issue by revolter** [sqlcipher/sqlcipher#299]
> sqlcipher -cmd PRAGMA key = 'password' database.sqlite .dump

fails with `Error: file is not a database`.

It worked before I updated it, but I don't know what version I had before.

SQLCipher version: `3.25.2 2018-09-25 19:08:10 fb90e7189ae6d62e77ba3a308ca5d683f90bbe633cf681865365b8e92792alt1`

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by developernotes** [comment]
Hello @revolter 

Thanks for using SQLCipher! What version of SQLCipher was used to create the file `database.sqlite`? While the current release of SQLCipher is now [4.0.1](https://www.zetetic.net/blog/2018/12/18/sqlcipher-401-release/), the release of SQLCipher [4.0.0](https://www.zetetic.net/blog/2018/11/30/sqlcipher-400-release/) included many improvements, including a  new page size of 4096, 256,000 KDF iterations, use of PBKDF2-HMAC-SHA512 and HMAC-SHA512 all modify important database settings. Thus, SQLCipher 4 will not open older databases by default. If you were using a different major version of SQLCipher to create `database.sqlite`, you might want to read through the release notes, and our guide on upgrading to SQLCipher 4 [here](https://discuss.zetetic.net/t/upgrading-to-sqlcipher-4/3283). Thanks!

**Comment by revolter** [comment]
Wooow, this is bad. The database wasn't create using SQLCipher. It was created using DB Browser for SQLite, and encrypted in the same app. I can't migrate it, so it needs to work with the database file exactly how it is now. So isn't there any option that will make it work? If not, where can I find a binary with an older SQLCipher version?

**Comment by developernotes** [comment]
Hello @revolter 

If you were using DB Browser for SQLite, they are embedding the SQLCipher directly within their application. How did you acquire the SQLCipher command line shell you are using above? Are you able to update to the latest version (i.e., 4.0.1)? If so, you can specify a compatibility mode such as the following example which would allow you to access a SQLCipher database file created using SQLCipher 3.x:

```
./sqlcipher demo.db
PRAGMA key = 'YourPasswordKere';
PRAGMA cipher_compatibility = 3;
```

Would you give that a try?

**Comment by revolter** [comment]
> How did you acquire the SQLCipher command line shell you are using above?

`brew install sqlcipher`

> Are you able to update to the latest version (i.e., 4.0.1)?

I ran `brew update && brew upgrade sqlcipher` and even `brew uninstall --force sqlcipher && brew install sqlcipher` but `sqlcipher --version` still shows `3.26.0 2018-12-01 12:34:55 bf8c1b2b7a5960c282e543b9c293686dccff272512d08865f4600fb58238alt1`.

> Would you give that a try?

It worked, thank you!

**Comment by developernotes** [comment]
Hello @revolter 

Great, we are happy to hear that worked for you!
