### ISSUE TITLE
sqlite3_rekey a plaintext database

### ISSUE THREAD

**Issue by ndusart** [sqlcipher/sqlcipher#301]
Documentation of `sqlite3_rekey` says that we can use it to encrypt a database that is not currently encrypted: 

``` c
/*
** Change the key on an open database.  If the current database is not
** encrypted, this routine will encrypt it.  If pNew==0 or nNew==0, the
** database is decrypted.
**
** The code to implement this API is not available in the public releasejavascript:noop()
** of SQLite.
*/
```

The documentation of `PRAGMA rekey` however states that it cannot be used to encrypt a standard sqlite database.

You should either update the documentation of the `sqlite3_rekey` function or plan to implement that feature.

**Comment by developernotes** [comment]
Hi @ndusart 

Thank you for reaching out regarding SQLCipher. Those [comments](https://github.com/sqlcipher/sqlcipher/blob/master/src/sqlite.h.in#L5534-L5541) originate from the upstream SQLite source. The SQLCipher implementation does not behave in that manner and we will include an update to the source file for a future release to explicitly note the difference in behavior.

If you are looking to encrypt a plain-text SQLite database using SQLCipher, we include a [`sqlcipher_export(...)`](https://www.zetetic.net/sqlcipher/sqlcipher-api/#sqlcipher_export) convenience function which will allow for this, specifically example # 1 within the documentation.
