### ISSUE TITLE
FMDB/SQLCipher 3.x to 4.x migration issue

### ISSUE THREAD

**Issue by suprajadarisa** [sqlcipher/sqlcipher#309]
Hi Team,

I am using FMDB/SQLCipher for encrypting my database. I have an old version of the application running on the 3.x version of SQLCipher. When trying to install a new update(which is running on the 4.x version of SQLCipher), we got an error mentioning file is not a database.

We tried to migrate the Cipher version by using cipher_migrate, tried for backward compatibility using cipher_compatibilty, tried creating a new database and copying the old data, but nothing worked.

Please let me know how can I solve this issue

**Comment by sjlombardo** [comment]
Hello @suprajadarisa.The `cipher_compatibilty` and `cipher_migrate` features should work for you, but they must be called immediately after keying the database (i.e. after `sqlite3_key` or `PRAGMA key`. The most likely reason for those to fail would be that something is happening on the database after keying and before the compatibility or migrate commands are being called. Can you run through your code and/or the FMDB logic and ensure that nothing would be using the database prior to invocation of the migration commands?

**Comment by suprajadarisa** [comment]
Thanks @sjlombardo 

cipher_migrate worked for me.

 if (sqlite3_open(oldDBPath, &db) == SQLITE_OK) {
            
            if sqlite3_exec(db, "PRAGMA key = '\(sqlCipherKey)';", nil, nil, nil) == SQLITE_OK {
                
                if sqlite3_exec(db, "PRAGMA cipher_migrate;", nil, nil, nil) == SQLITE_OK {
                    debugPrint("Everything ok")
                }
            }
        }

**Comment by chappanagavendra** [comment]
Hi suprajadarisa,

I am also facing same problem . please help me . regrading migrate . Where should i write above condition ?

**Comment by suprajadarisa** [comment]
Hi @chappanagavendra 

On the launch of your application, please check if the database is already created and after opening the DB connection, you can place the migration code

**Comment by chappanagavendra** [comment]
Give me your number please , then i will explain clearly (Or ) below is my number (9558888218) please ping me ..Its urgent ...I have to upload the Appstore

**Comment by chappanagavendra** [comment]
Give me some sample code .. Please

**Comment by chappanagavendra** [comment]
Hi @suprajadarisa  Please respond on my message .

**Comment by suprajadarisa** [comment]
Hi @chappanagavendra 

Please see the below code 

let fileManger = FileManager.default
        if fileManger.fileExists(atPath: Utilities.filePathInDocumentsFolder(fileName: CORE_DATABASE_NAME)) {
            migrateSQLCipherVersion()
            return
        }


 func migrateSQLCipherVersion() {
        let oldDBPath = Utilities.filePathInDocumentsFolder(fileName: CORE_DATABASE_NAME)
        var db: OpaquePointer? = nil
        
        if (sqlite3_open(oldDBPath, &db) == SQLITE_OK) {
            
            if sqlite3_exec(db, "PRAGMA key = '\(sqlCipherKey)';", nil, nil, nil) == SQLITE_OK {
                
                if sqlite3_exec(db, "PRAGMA cipher_migrate;", nil, nil, nil) == SQLITE_OK {
                    debugPrint("Everything ok")
                }
            }
        }
    }
