### ISSUE TITLE
what makes no such function: sqlcipher_export

### ISSUE THREAD

**Issue by pzwwei** [sqlcipher/sqlcipher#31]
here is the infomartion;$ ./sqlite3 aa.db
SQLite version 3.6.23.1
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> ATTACH DATABASE 'dd.db' AS encrypted KEY '';
sqlite> SELECT sqlcipher_export('dd');
Error: no such function: sqlcipher_export
sqlite> DETACH DATABASE dd;
Error: no such database: dd

**Comment by nitin-negi267** [comment]
@developernotes  I am getting following error :

Caused by: android.database.sqlite.SQLiteException: no such function: sqlcipher_export (code 1 SQLITE_ERROR): , while compiling: SELECT sqlcipher_export('database')
 
after executing this :

database.execSQL("SELECT sqlcipher_export('The 1 Database The 1 Database')")

Sqlcipher lib version used : 4.4.1

Please help

**Comment by developernotes** [comment]
Hi @nitin-negi267,

Are you building your own version of the library, using a Community edition, or Commercial edition build of the software? Are you able to run the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) on your device? What are your results?

**Comment by developernotes** [comment]
Hi @nitin-negi267,

Additionally, would you please validate the value returned from your application at runtime by invoking the following SQL command:

```
PRAGMA cipher_version;
```

**Comment by Shruthi125** [comment]
\path\to\sqlite3.exe: sqlite3 mydb.db
SQLite version 3.39.2 2022-07-21 15:24:47
Enter ".help" for usage hints.
sqlite> PRAGMA key ='12345';
sqlite> ATTACH DATABASE 'encrypted.db' AS encrypted key '12345';
sqlite> SELECT sqlcipher_export('encrypted');
Parse error: no such function: sqlcipher_export
  SELECT sqlcipher_export('encrypted');
         ^--- error here
Why is this error shown?

**Comment by Shruthi125** [comment]
I have already built sqlcipher on windows and got sqlite3.exe and sqlite3.dll files. From there did I execute these commands.

**Comment by developernotes** [comment]
Hello @Shruthi125,

What is printed in your SQLCipher command line shell when you execute the following command?

```
PRAGMA cipher_version;
```
