### ISSUE TITLE
Impact of VACUUM

### ISSUE THREAD

**Issue by petko** [sqlcipher/sqlcipher#310]
I am trying to encrypt a certain plaintext databases into encrypted. Most of them are encrypted successfully, but some of them fail with an Sqlite error when using the `SELECT sqlcipher_export('encrypted')` command.

However, I've found out that if I use `VACUUM` before that, it will work OK.

So how could this be related? Is it a problem in my database (integrity checks say that is is OK), or is it something from the SqlCipher?

P.S.: My plain and encrypted databases use custom page size/cipher page size (8192) and custom collations.

**Comment by sjlombardo** [comment]
Hello @petko - Just to clarify here to make sure I understand: you have a plaintext database that fails to `sqlcipher_export` to an encrypted database. However, if you run VACUUM on the same database prior to running `sqlcipher_export` then the export succeeds. Is that correct?

If so, this is not something that has been reported before, or that we have observed ourselves. 

1. What version of SQLCipher are you using?
2. If you are not using the latest SQLCipher (currently 4.0.1), can you attempt the same function with the latest release?
3. Does your attached encrypted database already exist prior to calling `sqlcipher_export`?
4. Which approach to `sqlcipher_export` are you using (either attaching the encrypted database to a plaintext database and exporting, or the other way around, attaching the plaintext database to encrypted and exporting in the other direction)
5. What error code do you receive back when calling `sqlcipher_export`
6. Are you only seeing this issue in your application, or can you reproduce the same thing using a SQLCipher shell?
7. Can you provide us with a sample database (ideally that does not contain sensitive information) that can reliably reproduce this issue?

**Comment by petko** [comment]
Yes, I have a plain database that fails to `sqlcipher_export` to an encrypted database, but succeeds if I run VACUUM on the plain database first.

1. I use SQLCipher 4.0.1 with default settings except the 8192 page size.
3. The database is newly created via the ATTACH command
4. I attach the encrypted database and export the plain database there (see below for code)
5. The error is SQLITE_ERROR
6. I do not have the SQLCipher shell, but if I try to change the password via DB Browser (SQLCipher) I get an error with the `sqlcipher_export` function too
7. Yes, I can provide you the plaintext database

**Comment by sjlombardo** [comment]
Hello @petko. We would like examine a sample database. Provided it contains non-sensitive data, can you share a link to it with us? You can email us directly at support@zetetic.net. You can optionally encrypt your [message with GPG](https://www.zetetic.net/security/).

**Comment by petko** [comment]
I've sent it.

**Comment by sjlombardo** [comment]
Hello @petko - We have been looking into this issue. Can you provide some information about how these databases were created? There is some unusual content in the sqlite_master table, in particular CREATE TABLE statements that include IF NOT EXISTS clauses, which we do not believe should be present. Were these files created with a very old version of SQLite? If so, what version? Have you ever made direct changes to the SQL in the sqlite_master table? Can you provide the source code for the part of the application that creates the schema?

**Comment by petko** [comment]
This is an evolving file format for an application, which is currently in development. So the schema was changed a lot via migrations, some of which are direct changes in the sqlite_master table's SQL. At some point we reformatted the tables' SQL schema and probably this is the moment the `IF NOT EXISTS` clauses got there.

After some further research, I think that I understand your point: `CREATE TABLE IF NOT EXISTS` is allowed by the SQLite spec (https://www.sqlite.org/lang_createtable.html), however probably it is not allowed (or at least not expected) in the schema definition.

If I remove these `IF NOT EXISTS` clauses, the file is encrypted fine. So, if this is the problem, I can add a migration to remove these `IF NOT EXISTS` clauses before encryption.

**Comment by sjlombardo** [comment]
Hello @petko - yes, the `IF NOT EXISTS` clauses are valid statements, but are not generally expected in the schema definition, and likely result from direct manipulation of `sqlite_master`. In this case running `VACUUM` actually "fixes" the schema when the database is recreated by the process, so the `IF NOT EXISTS` qualifiers are not present in the vacuumed database. This allows SQLCipher to complete the export.

We have created a test and a fix for this issue that will be included in a forthcoming release of SQLCipher. In the mean time, you can certainly fix the schema of your database, or run a VACUUM prior to using `sqlcipher_export`.

**Comment by petko** [comment]
Thank you. I will do that.
