### ISSUE TITLE
How to decrypt the .db file generated by sqlcipher encryption? Looking forward to your reply

### ISSUE THREAD

**Issue by OnexZgj** [sqlcipher/sqlcipher#311]
SQLCipher version:  api 'net.zetetic:android-database-sqlcipher:4.0.1@aar'

**Comment by developernotes** [comment]
Hi @OnexZgj 

We use GitHub Issues for reporting defects in the software library only. This type of question is best asked on our public community forum [here](https://discuss.zetetic.net/c/sqlcipher). Please feel free to post your question there. Thanks!
