### ISSUE TITLE
how to decrypt the db file

### ISSUE THREAD

**Issue by OnexZgj** [sqlcipher/sqlcipher#312]
### Steps to Reproduce

SQLCipher version:

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by developernotes** [comment]
Hi @OnexZgj

We use GitHub Issues for reporting defects in the software library only. This type of question is best asked on our public community forum [here](https://discuss.zetetic.net/c/sqlcipher). Please feel free to post your question there. Thanks!
