### ISSUE TITLE
user_version and sqlcipher_export

### ISSUE THREAD

**Issue by petko** [sqlcipher/sqlcipher#313]
Is the `sqlcipher_export` function supposed to copy the `user_version` pragma between plain and encrypted databases? It gets stripped for some reason when I do encryption/decryption.. 

As far as I remember it was working in the beginning of my tests, that why I am asking what is the expected behavior..

**Comment by developernotes** [comment]
Hello @petko 

No, `sqlcipher_export(...)` does not migrate the `user_version` of the attached database. If you wish to replicate that value on the export, you would need to capture the value first, then set it on the exported database.

**Comment by petko** [comment]
Thanks, will do.

**Comment by joshuapinter** [comment]
If you're curious, here's an example of how you might do that after you have attached your `encrypted` database and run `sqlcipher_export` to migrate the data from your main/unencrypted database to the `encrypted` database: 

1. Get the `user_version` from the main/unencrypted/current database: 
    ```sql
    PRAGMA user_version;
    ```

2. Then set the `user_version` in the attached `encrypted` database: 
    ```sql
    PRAGMA encrypted.user_version = <user_version>;
    ```
