### ISSUE TITLE
Questions about using sqlcipher in Java projects

### ISSUE THREAD

**Issue by zhaxingaz** [sqlcipher/sqlcipher#316]
### Expected Behavior
I want to use sqlcipher for personal java project, but I don't know how to do it. Please help me?

**Comment by developernotes** [comment]
Hello @zhaxingaz,

Thank you for your interest in SQLCipher. We use GitHub Issues as a mechanism for users to report defects within the software library itself. I would recommend you direct your question instead to the SQLCipher public community discuss site [here](https://discuss.zetetic.net/c/sqlcipher). Thanks!
