### ISSUE TITLE
migrate

### ISSUE THREAD

**Issue by chappanagavendra** [sqlcipher/sqlcipher#317]
### Steps to Reproduce

SQLCipher version:

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by sjlombardo** [comment]
Thank you for your interest in SQLCipher. We use GitHub Issues as a mechanism for users to report defects within the software library itself. I would recommend you direct your question instead to the [SQLCipher public community discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!
