### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by gregkr** [sqlcipher/sqlcipher#318]
### Expected Behavior
no link errors

### Actual Behavior
make
./libtool --mode=link gcc -I/usr/local/opt/openssl/include -I/Users/administrator/pjx -I/usr/include  -DSQLITE_HAS_CODEC -DSQLCIPHER_CRYPTO_OPENSSL -DSQLITE_OS_UNIX=1 -I. -I/Users/administrator/sqlcipher/src -I/Users/administrator/sqlcipher/ext/rtree -I/Users/administrator/sqlcipher/ext/icu -I/Users/administrator/sqlcipher/ext/fts3 -I/Users/administrator/sqlcipher/ext/async -I/Users/administrator/sqlcipher/ext/session -I/Users/administrator/sqlcipher/ext/userauth -D_HAVE_SQLITE_CONFIG_H -DBUILD_sqlite -DNDEBUG -I/System/Library/Frameworks/Tcl.framework/Versions/8.5/Headers -DSQLITE_THREADSAFE=1 -DSQLITE_ENABLE_UNLOCK_NOTIFY  -DSQLITE_HAVE_ZLIB=1  -lcrypto  -no-undefined -o libsqlcipher.la sqlite3.lo -lz -lcrypto   \
		 -rpath "/usr/local/lib" -version-info "8:6:8"
libtool: link: gcc -dynamiclib  -o .libs/libsqlcipher.0.dylib  .libs/sqlite3.o   -lz -lcrypto    -install_name  /usr/local/lib/libsqlcipher.0.dylib -compatibility_version 9 -current_version 9.6 -Wl,-single_module
Undefined symbols for architecture x86_64:
  "_PKCS5_PBKDF2_HMAC", referenced from:
      _sqlcipher_openssl_kdf in sqlite3.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libsqlcipher.la] Error 1

### Steps to Reproduce
./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC -DSQLITE_ENABLE_UNLOCK_NOTIFY" LDFLAGS="-lcrypto"

OpenSSL version : 3.0.0.-dev
SQLCipher version: 3.27.2

OS X El Capitan ver.10.11.6 Mac mini (Late 2014)
Intel Core i5

Xcode version: 7.3.1
gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by developernotes** [comment]
Hi @gregkr 

Would you confirm your copy of the OpenSSL library your are attempting to link with SQLCipher contains the symbol `_PKCS5_PBKDF2_HMAC`?

**Comment by gregkr** [comment]
Hi, Nick.
I confirm that "my copy" ( master from https://github.com/openssl/openssl )  not contains symbol  _PKCS5_PBKDF2_HMAC.
Consequently, either give me a link to the OpenSSL repository in which this symbol _PKCS5_PBKDF2_HMAC exists, or remove its use in SqlCipher.

In the end, I am satisfied with any option that will allow me to successfully complete the library assembly.


    понедельник, 29 апреля 2019 г., 22:11:07 GMT+3, Nick Parker <notifications@github.com> написал(-а):  
 
 
Hi @gregkr

Would you confirm your copy of the OpenSSL library your are attempting to link with SQLCipher contains the symbol _PKCS5_PBKDF2_HMAC?

**Comment by developernotes** [comment]
Hello @gregkr,

Please try downloading and building a current release of OpenSSL (source snapshots can be found [here](https://www.openssl.org/source/)). `PKCS5_PBKDF2_HMAC` is available in the latest source releases of OpenSSL. This is not an issue within SQLCipher.

We utilize GitHub Issues for reporting defects in the SQLCipher library itself. If you have further build integration issues, you might consider posting to our public community discuss site for SQLCipher [here](https://discuss.zetetic.net/c/sqlcipher). Thanks!
