### ISSUE TITLE
Build fails with many sqlite3.c errors

### ISSUE THREAD

**Issue by wuno** [sqlcipher/sqlcipher#319]
### Expected Behavior

Build sqlcipher

### Actual Behavior

Fails with many sqlite3.c errors.

### Steps to Reproduce

- Build OpenSSL locally
- Update Makefile.msc with path to installed OpenSSL and path to libs libcrypto.lib / libssl.lib

> TCC = $(TCC) -DSQLITE_TEMP_STORE=2 -DSQLITE_HAS_CODEC -I"C:\Program Files\OpenSSL\include"

> LTLIBPATHS = $(LTLIBPATHS) /LIBPATH:"C:\Program Files\OpenSSL\lib"
> LTLIBS = $(LTLIBS) libcrypto.lib libssl.lib

- C:\sqlcipher>nmake /f Makefile.msc

SQLCipher version:

3.27.2

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

> C:\sqlcipher>nmake /f Makefile.msc
> 
> Microsoft (R) Program Maintenance Utility Version 14.16.27031.1
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
>         copy /Y tsrc\sqlite3ext.h sqlite3ext.h
>         1 file(s) copied.
>         tclsh .\tool\mksqlite3c.tcl
>         copy .\ext\session\sqlite3session.h .
>         1 file(s) copied.
>         cl -nologo -W4 -DINCLUDE_MSVC_H=1   -DSQLITE_OS_WIN=1 -I. -I. -I.\src -fp:precise -MT -DNDEBUG -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -DSQLITE_THREADSAFE=1 -DSQLITE_THREAD_OVERRIDE_LOCK=-1 -DSQLITE_TEMP_STORE=2 -DSQLITE_HAS_CODEC -I"C:\Program Files\OpenSSL\include"  -DSQLITE_MAX_TRIGGER_DEPTH=100  -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_GEOPOLY=1 -DSQLITE_ENABLE_JSON1=1 -DSQLITE_ENABLE_STMTVTAB=1 -DSQLITE_ENABLE_DBPAGE_VTAB=1 -DSQLITE_ENABLE_DBSTAT_VTAB=1 -DSQLITE_INTROSPECTION_PRAGMAS=1 -DSQLITE_ENABLE_DESERIALIZE=1 -DSQLITE_ENABLE_COLUMN_METADATA=1   -O2 -Zi -Fosqlite3.lo  -c sqlite3.c
> sqlite3.c
> sqlite3.c(1928): error C2061: syntax error: identifier 'i64'
> sqlite3.c(1928): error C2059: syntax error: ';'
> sqlite3.c(1929): error C2061: syntax error: identifier 'u64'
> sqlite3.c(1929): error C2059: syntax error: ';'
> sqlite3.c(2003): error C2061: syntax error: identifier 'uptr'
> sqlite3.c(2003): error C2059: syntax error: ';'
> sqlite3.c(2320): error C2061: syntax error: identifier 'Bitmask'
> sqlite3.c(2320): error C2059: syntax error: ';'
> sqlite3.c(2395): error C2143: syntax error: missing ')' before '*'
> sqlite3.c(2395): error C2143: syntax error: missing '{' before '*'
> sqlite3.c(2395): warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
> sqlite3.c(2396): error C2059: syntax error: 'type'
> sqlite3.c(2401): error C2059: syntax error: ')'
> sqlite3.c(2418): error C2081: 'sqlite3_int64': name in formal parameter list illegal
> sqlite3.c(2594): error C2146: syntax error: missing ')' before identifier 'intKey'
> sqlite3.c(2594): error C2081: 'i64': name in formal parameter list illegal
> sqlite3.c(2594): error C2061: syntax error: identifier 'intKey'
> sqlite3.c(2594): error C2059: syntax error: ';'
> sqlite3.c(2594): error C2059: syntax error: ','
> sqlite3.c(2597): error C2059: syntax error: ')'
> sqlite3.c(2642): error C2061: syntax error: identifier 'sqlite3_int64'
> sqlite3.c(2644): error C2143: syntax error: missing '{' before '*'
> sqlite3.c(2644): warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
> sqlite3.c(2644): warning C4218: nonstandard extension used: must specify at least a storage class or a type
> sqlite3.c(2648): error C2059: syntax error: '}'
> sqlite3.c(2660): error C2061: syntax error: identifier 'sqlite3BtreeIntegerKey'
> sqlite3.c(2660): error C2059: syntax error: ';'
> sqlite3.c(2660): error C2059: syntax error: '<parameter-list>'
> sqlite3.c(2667): error C2061: syntax error: identifier 'sqlite3BtreeMaxRecordSize'
> sqlite3.c(2667): error C2059: syntax error: ';'
> sqlite3.c(2667): error C2059: syntax error: '<parameter-list>'
> sqlite3.c(2671): error C2061: syntax error: identifier 'sqlite3BtreeRowCountEst'
> sqlite3.c(2671): error C2059: syntax error: ';'
> sqlite3.c(2671): error C2059: syntax error: '<parameter-list>'
> sqlite3.c(2690): error C2143: syntax error: missing ')' before '*'
> sqlite3.c(2690): error C2081: 'i64': name in formal parameter list illegal
> sqlite3.c(2690): error C2143: syntax error: missing '{' before '*'
> sqlite3.c(2690): error C2059: syntax error: ')'
> sqlite3.c(2690): error C2059: syntax error: ';'
> sqlite3.c(2709): error C2143: syntax error: missing ')' before '*'
> sqlite3.c(2709): error C2143: syntax error: missing '{' before '*'
> sqlite3.c(2709): error C2059: syntax error: ')'
> sqlite3.c(2709): error C2059: syntax error: ';'
> sqlite3.c(2724): error C2143: syntax error: missing ')' before '*'
> sqlite3.c(2724): error C2143: syntax error: missing '{' before '*'
> sqlite3.c(2724): error C2059: syntax error: ')'
> sqlite3.c(2724): error C2059: syntax error: ';'
> sqlite3.c(2800): error C2061: syntax error: identifier 'i64'
> sqlite3.c(2803): error C2143: syntax error: missing '{' before '*'
> sqlite3.c(2803): warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
> sqlite3.c(2803): warning C4218: nonstandard extension used: must specify at least a storage class or a type
> sqlite3.c(2815): error C2059: syntax error: '}'
> sqlite3.c(2827): error C2059: syntax error: '}'
> sqlite3.c(2994): error C2143: syntax error: missing ')' before '*'
> sqlite3.c(2994): error C2143: syntax error: missing '{' before '*'
> sqlite3.c(2994): error C2059: syntax error: ','
> sqlite3.c(2994): error C2059: syntax error: ')'
> sqlite3.c(3008): error C2143: syntax error: missing '{' before '*'
> sqlite3.c(3008): warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
> sqlite3.c(3008): warning C4218: nonstandard extension used: must specify at least a storage class or a type
> sqlite3.c(3017): error C2143: syntax error: missing '{' before '*'
> sqlite3.c(3017): warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
> sqlite3.c(3017): warning C4218: nonstandard extension used: must specify at least a storage class or a type
> sqlite3.c(3037): error C2143: syntax error: missing ')' before '*'
> sqlite3.c(3037): error C2143: syntax error: missing '{' before '*'
> sqlite3.c(3037): error C2059: syntax error: ')'
> sqlite3.c(3037): error C2059: syntax error: ';'
> sqlite3.c(3260): error C2143: syntax error: missing ')' before '*'
> sqlite3.c(3260): error C2143: syntax error: missing '{' before '*'
> sqlite3.c(3260): error C2059: syntax error: ','
> sqlite3.c(3268): error C2143: syntax error: missing ')' before '*'
> sqlite3.c(3268): error C2081: 'sqlite3': name in formal parameter list illegal
> sqlite3.c(3268): error C2143: syntax error: missing '{' before '*'
> sqlite3.c(3268): error C2059: syntax error: ')'
> sqlite3.c(3268): error C2059: syntax error: ';'
> sqlite3.c(3280): error C2081: 'sqlite3_int64': name in formal parameter list illegal
> sqlite3.c(3287): error C2061: syntax error: identifier 'sqlite3PagerJournalSizeLimit'
> sqlite3.c(3287): error C2059: syntax error: ';'
> sqlite3.c(3287): error C2059: syntax error: '<parameter-list>'
> sqlite3.c(3288): error C2143: syntax error: missing '{' before '*'
> sqlite3.c(3288): warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
> sqlite3.c(3288): warning C4218: nonstandard extension used: must specify at least a storage class or a type
> sqlite3.c(3320): error C2143: syntax error: missing ')' before '*'
> sqlite3.c(3320): error C2081: 'sqlite3': name in formal parameter list illegal
> sqlite3.c(3320): error C2143: syntax error: missing '{' before '*'
> sqlite3.c(3320): error C2059: syntax error: ','
> sqlite3.c(3320): error C2059: syntax error: ')'
> sqlite3.c(3324): error C2143: syntax error: missing ')' before '*'
> sqlite3.c(3324): error C2081: 'sqlite3': name in formal parameter list illegal
> sqlite3.c(3324): error C2143: syntax error: missing '{' before '*'
> sqlite3.c(3324): error C2059: syntax error: ')'
> sqlite3.c(3324): error C2059: syntax error: ';'
> sqlite3.c(3350): error C2143: syntax error: missing '{' before '*'
> sqlite3.c(3350): warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
> sqlite3.c(3350): warning C4218: nonstandard extension used: must specify at least a storage class or a type
> sqlite3.c(3351): error C2143: syntax error: missing '{' before '*'
> sqlite3.c(3351): warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
> sqlite3.c(3351): warning C4218: nonstandard extension used: must specify at least a storage class or a type
> sqlite3.c(3352): error C2143: syntax error: missing '{' before '*'
> sqlite3.c(3352): warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
> sqlite3.c(3352): warning C4218: nonstandard extension used: must specify at least a storage class or a type
> sqlite3.c(3358): error C2143: syntax error: missing ')' before '*'
> sqlite3.c(3358): error C2143: syntax error: missing '{' before '*'
> sqlite3.c(3358): error C2059: syntax error: ')'
> sqlite3.c(3358): error C2059: syntax error: ';'
> sqlite3.c(3420): error C2061: syntax error: identifier 'sqlite3_pcache_page'
> sqlite3.c(3421): error C2373: 'pData': redefinition; different type modifiers
> sqlite3.c(2643): note: see declaration of 'pData'
> sqlite3.c(3442): error C2059: syntax error: '}'
> sqlite3.c(3488): error C2143: syntax error: missing '{' before '*'
> sqlite3.c(3488): warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
> sqlite3.c(3488): warning C4218: nonstandard extension used: must specify at least a storage class or a type
> sqlite3.c(3489): error C2143: syntax error: missing ')' before '*'
> sqlite3.c(3489): error C2081: 'sqlite3_pcache_page': name in formal parameter list illegal
> sqlite3.c(3489): error C2143: syntax error: missing '{' before '*'
> sqlite3.c(3489): error C2059: syntax error: ')'
> sqlite3.c(3489): error C2059: syntax error: ';'
> sqlite3.c(3490): error C2143: syntax error: missing ')' before '*'
> sqlite3.c(3490): error C2081: 'sqlite3_pcache_page': name in formal parameter list illegal
> sqlite3.c(3490): error C2143: syntax error: missing '{' before '*'
> sqlite3.c(3490): error C2059: syntax error: ')'
> sqlite3.c(3490): fatal error C1003: error count exceeds 100; stopping compilation
> NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.EXE"' : return code '0x2'
> Stop.
>

**Comment by developernotes** [comment]
Hello @wuno,

We utilize GitHub Issues for reporting defects in the software library itself. As this issue is related to building the software, we would recommend that you instead post this to the SQLCipher public [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!
