### ISSUE TITLE
Community edition source code + signature v4.2.0 unavailable

### ISSUE THREAD

**Issue by svetlemodry** [sqlcipher/sqlcipher#322]
Hi all!
It looks like the links to the community source and signature files at the bottom of this page are empty: https://www.zetetic.net/sqlcipher/verify/
Seems like a similar issue reported in https://github.com/sqlcipher/sqlcipher/issues/291
I am the packager of [sqlcipher](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/sqlcipher) for Arch, so I'd prefer a signed source over unsigned github tarball, if the plan still is to keep the above page updated.
Thanks & cheers!
J

**Comment by developernotes** [comment]
Hi @svetlemodry 

Thank you for the report, we have fixed the issue. Please let us know if you are able to access the source and signature for the 4.2.0 release. Thanks!

**Comment by svetlemodry** [comment]
Fixed! Thanks a lot for the quick update here!
Cheers!
J

**Comment by developernotes** [comment]
Great, glad to hear it, thank you!
