### ISSUE TITLE
Does sqlcipher support 64-bit devices？

### ISSUE THREAD

**Issue by midiao** [sqlcipher/sqlcipher#323]
Our app use sqlcipher.so and was published on Google Play. But starting August 1, 2019, apps published on Google Play should support 64-bit architectures.

**Comment by developernotes** [comment]
Hello @midiao 

We utilize GitHub Issues for reporting defects in the software library only. SQLCipher for Android does support 64-bit CPU's. If you have any further questions, we ask that you direct those to our [community SQLCipher discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!
