### ISSUE TITLE
An exception occurred when compiling 64-bit DLL on win10 system

### ISSUE THREAD

**Issue by zhaxingaz** [sqlcipher/sqlcipher#326]
sqlcipher: 3.28.0
OpenSSL: 1.0.1f
Tcl:8.5
msys2
mingw64

I try to compile sqlcipher on win10 system. I want to get 64-bit DLL file. The compilation process is normal. The exe I get after compilation can also be used normally. But the sqlite3.def file is empty. Why? After compiling 32-bit dll, the sqlite3.def file contains content. Can you give me some advice? Thank you.

**Comment by zhaxingaz** [comment]
I'm just using it for personal study and hobbies. Please reply again. Thank you.

**Comment by developernotes** [comment]
Hello @zhaxingaz,

Thank you for your interest in SQLCipher. We reserve GitHub Issues for reporting defects in the software library itself. We would recommend posting this build related question to the SQLCipher community discuss site [here](https://discuss.zetetic.net/c/sqlcipher) instead. Thanks!
