### ISSUE TITLE
VACUUM operation makes memory go up continously for big database(13G) in my computer

### ISSUE THREAD

**Issue by jackinelee** [sqlcipher/sqlcipher#328]
### Expected Behavior
When I do vacuuming operation for a big database about 13G using latest SQLCipher  code in git,
I found the memory go up high continuously,  but when I use pure SQLite3 3.28.0 to test , it doesn't make memory high , so I don't know where I am wrong to use SQLCipher or some bug in SQLCipher
### Actual Behavior
it shoudn't make memory go up high continuously, which seems memory leak issue
### Steps to Reproduce
Just do VACCUM operation for a big database , then you will see memory go up high continously
SQLCipher version:
4.2.0
*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by sjlombardo** [comment]
@jackinelee - Please provide some information as follows:
1. Is the database you are vacuuming encrypted, or are you observing this behavior on a non-encrypted database when vacuuming with SQLCipher?
2. What version of SQLCipher are you testing with?
3. How are you measuring the memory utilization?
4. What specific platform are you running this test on and how did you build SQLCipher for that platform?
5. How fragmented is the database you are vacuuming (e.g. what do `PRAGMA page_count` and `PRAGMA freelist_count` return?
6. Are you able to reproduce this with multiple databases or is it happening only with one specific database?

**Comment by sjlombardo** [comment]
Hello @jackinelee - can you please provide any of the previously requested information on this ticket? Do you still have the problem?

**Comment by sjlombardo** [comment]
Closing due to lack of response
