### ISSUE TITLE
boringssl compatible

### ISSUE THREAD

**Issue by quininer** [sqlcipher/sqlcipher#329]
The boringssl is basically compatible with openssl, but boringssl [removes `EVP_CIPHER_name`](https://boringssl-review.googlesource.com/c/boringssl/+/3932/). This makes it impossible to use boringssl on sqlcipher.

We can still get the cipher name using `EVP_CIPHER_nid` and `OBJ_nid2sn`, which also works in openssl.

https://github.com/quininer/sqlcipher/commit/eb1811e25b301691cdaddc81752d9e2cdc99c704

**Comment by sjlombardo** [comment]
Hello @quininer thanks for reporting this, we'll take a look.

**Comment by sjlombardo** [comment]
Hello @quininer - I just wanted to let you know that htis was recently resolved in release 4.3.0
