### ISSUE TITLE
PRAGMA cipher_compatibility Fail   Fail

### ISSUE THREAD

**Issue by joncen** [sqlcipher/sqlcipher#333]
### Expected Behavior

Open Success

### Actual Behavior
Fail,  Not A DB

### Steps to Reproduce
 a sqlite 3.28 DB using SQLCipher 3.00 。

upgrade SQLCipher to 4.2.0
using
PRAGMA cipher_compatibility = 3 ，
to open Original DB 

SQLCipher version: 4.2.0

I found that ,
![image](https://user-images.githubusercontent.com/19607102/62341713-de009980-b516-11e9-9d03-9871e40e41ed.png)

in crypto.c Line 477. when processing with "cipher_compatibility ", all sqlcipher_codec_ctx_set_pagesize is hard code for 1024 page size.
Because my original DB changed thd default page size to 4096.

When I Change the hard code 1024 to SQLITE_DEFAULT_PAGE_SIZE 。 It will open succeed.

**Comment by developernotes** [comment]
Hi @joncen 

>Because my original DB changed thd default page size to 4096.

SQLCipher compatibility modes are specific to the default configurations used with major release versions of SQLCipher. If you deviate from any one standard with custom values, as you did, `cipher_compatibility` will not work for you. The default page size in SQLCipher 3 was 1024. This is not a defect. In your situation with a custom runtime configuration, you would need to use [`sqlcipher_export(...)`](https://www.zetetic.net/sqlcipher/sqlcipher-api/#sqlcipher_export) to convert from your custom settings to a 4.x series format.
