### ISSUE TITLE
..\Makefile.msc(2547) : fatal error U1052: file '..\sqlite\ext\lsm1\Makefile.msc' not found

### ISSUE THREAD

**Issue by mikeitexpert** [sqlcipher/sqlcipher#336]
### Expected Behavior
I have installed VS 2017 and I am trying to build the sqlcipher command (as in Ubuntu 18) for my Windows 10 x64.

### Actual Behavior
but I get the below error:

**..\Makefile.msc(2547) : fatal error U1052: file '..\sqlite\ext\lsm1\Makefile.msc' not found**

### Steps to Reproduce
 so I tried to do so by

```
    mkdir bld
    cd bld
    nmake /f Makefile.msc sqlite3.exe TOP=..\sqlite
```

But firstly I get the below error which is pretty obvious. It is most likely because in the bld folder there is no Makefile.msc. 

**
Microsoft (R) Program Maintenance Utility Version 14.16.27032.1
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1052: file 'Makefile.msc' not found
Stop.
**

So I tried to fix that by adding "..\" before Makefile.msc

**
    nmake /f ..\Makefile.msc sqlite3.exe TOP=..\sqlite
                   ^
**

But then I get the below error  which I believe is pretty obviously because I don't have the sqlite source folder in the source folder but I don't know where to get the source for sqlite and how to fix this.

**Microsoft (R) Program Maintenance Utility Version 14.16.27032.1
Copyright (C) Microsoft Corporation.  All rights reserved.

..\Makefile.msc(2547) : fatal error U1052: file '..\sqlite\ext\lsm1\Makefile.msc' not found
Stop.**

to be honest I couldn't find a step by step instruction on how to build sqlcipher using MSVC. The only one I found is [this](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Win64-setup-%E2%80%94-Compiling-SQLCipher) which is pretty old.

I would appreciate if sb could shed some light.

Thank you

SQLCipher version: 4.2.0

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by Gloria0-0** [comment]
You need alter TOP value.   TOP= ..\

**Comment by sjlombardo** [comment]
Closing as answered by @Gloria0-0 (thanks!)
