### ISSUE TITLE
Database not open ErrorCode : 14

### ISSUE THREAD

**Issue by GauravCreed** [sqlcipher/sqlcipher#337]
### try to open Password protected database from asstes but it will gove you error like : Database not open ErrorCode : 14

![Capture](https://user-images.githubusercontent.com/13447384/64430711-7bcb2380-d0d6-11e9-977d-4cdd049b628c.PNG)

i am using `net.zetetic:android-database-sqlcipher:4.2.0`

my database file is https://drive.google.com/file/d/1uZRKiXrVCSQ0INi1bva5yPhyjVeuxZ4C/view?usp=sharing

Thanks.

**Comment by R4N** [comment]
@GauravCreed 

Did you recently change from using SQLCipher 3.x to using SQLCipher 4.x.  The default encryption settings are different between versions, so SQLCipher 4.x will not open a SQLCipher 3.x database without migrating the database or using [PRAGMA cipher_compatability](https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_compatibility)

Here's additional information about migrating to SQLCipher 4: https://discuss.zetetic.net/t/upgrading-to-sqlcipher-4/3283 with recommendations from my colleague on one fairly standard way to handle migration: https://discuss.zetetic.net/t/upgrading-to-sqlcipher-4/3283/17

**Comment by GauravCreed** [comment]
@R4N 

i am already using `net.zetetic:android-database-sqlcipher:4.2.0` this version

**Comment by R4N** [comment]
@GauravCreed 

But were you previously using SQLCipher 3.x when the database was created?  When switching from SQLCipher 3.x to SQLCipher 4.x you'll need to migrate SQLCipher 3.x database to use the SQLCipher 4.x settings (they won't be able to be opened by default).

To confirm that this database was created using SQLCipher 3.x, you can attempt to open it using [PRAGMA cipher_compatability](https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_compatibility) -- setting to to `PRAGMA cipher_compataibility = 3` as mentioned in the documentation linked.  If it opens, then you know that the database was created with SQLCipher 3 and you need to perform the migration as reference in the links above.

**Comment by sjlombardo** [comment]
I've confirmed that database was previously using SQLCipher 3 and needed to either upgrade via `PRAGMA cipher_migrate` or run in compatibility mode via `PRAGMA cipher_compatability = 3`.
