### ISSUE TITLE
Question: backping up encrypted database

### ISSUE THREAD

**Issue by petko** [sqlcipher/sqlcipher#338]
What is the proper way to create a backup copy of an open, encrypted database, provided that I want to optimize the space it uses. For plain databases one does that with `VACUUM INTO [filename]`, but this command produces corrupt database when used with a encrypted database as a source.

Can I use `sqlcipher_export` (does it optimize the space of the target database) or should I create an encrypted database and then use `VACUUM INTO [filename]`?

**Comment by sjlombardo** [comment]
Hello @petko you can use either `VACUUM INTO 'filename'` or `sqlcipher_export` to backup a database. `sqlcipher_export` provides a bit more flexibility (e.g. it can also be used to upgrade a database, encrypt a plaintext, or decrypt and encrypted database). Otherwise, in the case of encrypted to encrypted, they both operate very similarly.

**Comment by petko** [comment]
Unfortunately, in my tests if you create and encrypt a database and then use `VACUUM INTO` some file, the produced file is corrupted and can't be opened with the password of the original database. 

Moreover, for a more complex databases only part of the produced database is encrypted and most of it is stored in plain text. 

Do you have a test where you do the same (create db, encrypt it with password X, `VACUUM INTO` and open it with the password X)?

**Comment by petko** [comment]
OK, I think that I've found the problem. I was not setting `cipher_default_page_size` for my database, as I do not use ATTACH anywhere in my codebase. However, it seems that `VACUUM INTO` uses it internally..

**Comment by sjlombardo** [comment]
@petko Are you using custom encryption settings for SQLCipher on the main database? Can you provide a short sample that demonstrates then issue? Use of vacuum into is included in one of the SQLCipher vacuum tests: 

https://github.com/sqlcipher/sqlcipher/blob/750f5e32474ee23a423376203e671cab9841c67a/test/sqlcipher-compatibility.test#L593

Does your use case differ substantially?

**Comment by petko** [comment]
Yes, I use 8192 byte page size. That is what caused the problem. I was not setting the `cipher_default_page_size` PRAGMA as I was unaware that it affects the `VACUUM INTO`.
