### ISSUE TITLE
Document SQLite compatibility with SQLCipher

### ISSUE THREAD

**Issue by mafavale** [sqlcipher/sqlcipher#343]
I had a super hard time to understand some incompatibility issues i was having within my application and i had to go through the extensive list of commits here to understand that you include SQLite within your code and you bump the SQLite version once in a while and a SQLCipher version was incompatible with the DB version i was using, so it would be great to have a compatibility matrix between SQLCipher version and SQLite version and avoid others to suffer my pain.

Thanks.

**Comment by developernotes** [comment]
Hi @mafavale 

Thanks for your interest in SQLCipher, although I'm sorry to hear you experienced an issue. SQLCipher has always included SQLite. Can you elaborate further on any compatibility issues you experienced when integrating SQLCipher?

**Comment by mafavale** [comment]
Thanks for your quick response @developernotes. Basically i had to understand the underlying version of SQLite that SQLCipher is shipping due to some versioning upgrades we've been doing and in that process it was hard to figure out which SQLIte version was included in SQLCipher. I had to go through the whole commit history to find that information, something that could be easily added to the README and have every user know about which SQLite version is shipping in each SQLCipher version.

**Comment by developernotes** [comment]
Hi @mafavale 

The [`VERSION`](https://github.com/sqlcipher/sqlcipher/blob/master/VERSION) file will always reflect the version of SQLite the SQLCipher source tree is based on. In addition, we maintain a [`CHANGELOG.md`](https://github.com/sqlcipher/sqlcipher/blob/master/CHANGELOG.md) which annotates which version of SQLite was included with a respective SQLCipher release. Was there additional information you were looking to identify? We can certainly add a link to the changelog within the README.

**Comment by brodybits** [comment]
Another thing is that `SELECT SQLITE_VERSION()` should give the underlying SQLite version.

**Comment by developernotes** [comment]
Just for clarification, `SELECT sqlite_version()` does report the underlying SQLite version in SQLCipher.

**Comment by sjlombardo** [comment]
It looks like this was answered so I'm going to close it. To summarize the comments from @developernotes and @brodybits:

1. if you are looking at the source distribution, consult the `VERSION` file to see the upstream SQLite version that SQLCipher is based on
2. If you need to check at runtime, execute `SELECT sqlite_version()`
