### ISSUE TITLE
Out of memory both on macOS and Android

### ISSUE THREAD

**Issue by skys215** [sqlcipher/sqlcipher#345]
### Expected Behavior

Expected to return result using SQL statements.

### Actual Behavior

On macOS:
```
$ sqlcipher encrypted_database.db
SQLCipher version 3.28.0 2019-04-16 19:49:53
Enter ".help" for usage hints.
sqlite> PRAGMA key ='<key>';
sqlite> PRAGMA cipher_migrate;
0
sqlite> PRAGMA cipher_use_hmac=off;
sqlite> PRAGMA cipher_page_size=1024;
sqlite> PRAGMA kdf_iter=4000;
sqlite> SELECT name FROM sqlite_master WHERE type='table';
Error: out of memory
sqlite>
```

On Android:
```
2019-11-14 22:51:03.285 12984-12984/com.example.test E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.test, PID: 12984
    net.sqlcipher.database.SQLiteException: out of memory
        at net.sqlcipher.database.SQLiteQuery.native_fill_window(Native Method)
        at net.sqlcipher.database.SQLiteQuery.fillWindow(SQLiteQuery.java:80)
        at net.sqlcipher.database.SQLiteCursor.fillWindow(SQLiteCursor.java:324)
        at net.sqlcipher.database.SQLiteCursor.getCount(SQLiteCursor.java:292)
        at net.sqlcipher.AbstractCursor.moveToPosition(AbstractCursor.java:178)
        at net.sqlcipher.AbstractCursor.moveToFirst(AbstractCursor.java:222)
        at android.database.CursorWrapper.moveToFirst(CursorWrapper.java:71)
```

But the weird thing is: I have downloaded  a SQLite Browser with SQLCipher somewhere on the Internet and it can open and browse the database normally.
On the `About` tab it just written `Version 2.1`, don't know it's a SQLCipher version or SQLite Browser version, or even SQLite version?
At first I thought that maybe it's my computer's problem and I tried on Android, but also failed.
And then I was willing to debug it since SQLCipher is an open-source project, but I failed to compile a debug version of SQLCipher. So I came here asking for help.

### Steps to Reproduce

Opening a database of specific android app  with the right password causes this problem.

SQLCipher version (macOS): a bit confusing... I don't know it's 3.28 or 4.2

```
$ sqlcipher --version
3.28.0 2019-04-16 19:49:53 884b4b7e502b4e991677b53971277adfaf0a04a284f8e483e2553d0f8315alt1
$ brew list sqlcipher
/usr/local/Cellar/sqlcipher/4.2.0_1/bin/sqlcipher
/usr/local/Cellar/sqlcipher/4.2.0_1/include/sqlcipher/ (2 files)
/usr/local/Cellar/sqlcipher/4.2.0_1/lib/libsqlcipher.0.dylib
/usr/local/Cellar/sqlcipher/4.2.0_1/lib/pkgconfig/sqlcipher.pc
/usr/local/Cellar/sqlcipher/4.2.0_1/lib/ (2 other files)
$
```

SQLCipher version (android): 4.2.0(`net.zetetic:android-database-sqlcipher:4.2.0`)

**Comment by developernotes** [comment]
Hi @skys215 

Can you provide some additional details regarding what you are attempting to do below given your sample posting? It appears you are migrating a SQLCipher database to the current version, but then changing various runtime settings to match SQLCipher version 1 settings before you attempt to read from the `sqlite_master` table? How large is your database file?

>$ sqlcipher encrypted_database.db
SQLCipher version 3.28.0 2019-04-16 19:49:53
Enter ".help" for usage hints.
sqlite> PRAGMA key ='<key>';
sqlite> PRAGMA cipher_migrate;
0
sqlite> PRAGMA cipher_use_hmac=off;
sqlite> PRAGMA cipher_page_size=1024;
sqlite> PRAGMA kdf_iter=4000;
sqlite> SELECT name FROM sqlite_master WHERE type='table';
Error: out of memory
sqlite>

The [nightly versions](https://nightlies.sqlitebrowser.org/latest/) support operating on both SQLCipher 3 and 4 file formats. Once we have a bit more information, we will be able to provide additional feedback. Thanks!

**Comment by skys215** [comment]
I want to read the data from the database. And the above mentioned SQLs seems to be the most simple way to check if the key is correct or not. I believed that if the key is correct, I can run almost any SQLs on it. So `SELECT name FROM sqlite_master WHERE type='table';` was the first SQL statement for that.

About the file size of the database, the weird thing is I can open a larger database(like 40MB, the one I can't open is like 12MB) file with the same SQLCipher command line(not tested with the android yet). I assume that there's some data/table name/field name or something in the table that corrupts allocating memory which causes out of memory error.

I tried to open with the nightly build, but it seems that it didn't support opening a encrypted database. It doesn't pop up a window to type the password.
One more thing, I'm not sure the v3.* version of sqlite browser will run `cipher_migrate` before those runtime settings if it's doesn't match the selectable version of sqlcipher which is v3 and v4 (in case mine is v1 or v2, I'm not sure).

**Comment by developernotes** [comment]
Hi @skys215 

Why are you executing the below PRAGMA commands following the `cipher_migrate` operation? 

>sqlite> PRAGMA cipher_use_hmac=off;
sqlite> PRAGMA cipher_page_size=1024;
sqlite> PRAGMA kdf_iter=4000;

Would you try performing a `PRAGMA cipher_migrate` on a copy of the file again. Immediately after it completes the migration, would you please attempt to run the following command:

```
SELECT count(*) FROM sqlite_master;
```

**Comment by skys215** [comment]
Yeah, skipping those runtime settings works!

I was told to do so to decrypt the database of this specific app according to an old article online. It has succeed couple of time, that makes me ignore all other methods to open the database. 
What I can guess about the difference of these two situations(decrypt with & without the runtime settings) is: I was decrypting a database of an older version of that specific app with runtime settings and  decrypting the database of newer version of that app with same runtime settings. I assume that the newer version of that app is using newer version of SQLCipher?

Are there anyway to check which SQLCipher version the database is using before decrypting it?

Since I can browse the data correctly without the runtime settings, I am closing this issue.
Thank you for spending time on replying.

**Comment by developernotes** [comment]
Hi @skys215 

The database _file_ does not encode a specific version number, however the database library does. You can always query the library for the version of the software it is running via:

```
PRAGMA cipher_version;
```

Presuming no non-standard runtime settings have been changed, `PRAGMA cipher_migrate` will perform a one-time file format migration to the latest version of SQLCipher (relative to the version of the library you are currently using). We are happy to hear you are able to access your migrated file now. Thanks!
