### ISSUE TITLE
sqlcipher_export adding new tables like ecdUsers instead of ZUSERS table?

### ISSUE THREAD

**Issue by longfanshotmailcom** [sqlcipher/sqlcipher#348]
### Expected Behavior
I'm using sqlcipher_export to encrypte .sqlite file generated with Core Data (Xcode), the new table has new tables like ecdUsers where the original file contains only ZUSERS table.

### Actual Behavior
New table has new tables like ecdUsers where the original file contains only ZUSERS table.

### Steps to Reproduce
Was following steps in this link https://www.zetetic.net/sqlcipher/sqlcipher-api/
$ ./sqlcipher plaintext.db
sqlite> ATTACH DATABASE 'encrypted.db' AS encrypted KEY 'testkey';
sqlite> SELECT sqlcipher_export('encrypted');
sqlite> DETACH DATABASE encrypted;

SQLCipher version:
Latest as 2019 Dec 23.

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by sjlombardo** [comment]
@longfanshotmailcom Does encrypted.db already exist before doing the export? It sounds like you are using encrypted core data. Please refer to this issue as it is likely related: https://github.com/project-imas/encrypted-core-data/issues/293

**Comment by longfanshotmailcom** [comment]
Hi, encrypted.db not exists when I run export.

**Comment by developernotes** [comment]
Hi @longfanshotmailcom 

While we do not support encrypted core data, you might check to see what version of SQLCipher was used to create the encrypted core data database. If it wasn't SQLCipher 4, you will need to look into using [`PRAGMA cipher_default_compatibility`](https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_default_compatibility) options prior to performing your migration. 

If you have any other utilization questions, we would recommend posting those over within the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher) as we use GitHub Issues for reports of defects within the software library. Thanks!
