### ISSUE TITLE
Running tests is undocumented

### ISSUE THREAD

**Issue by lgrahl** [sqlcipher/sqlcipher#349]
Unfortunately there is no section in the readme on how to start the tests. From reading #172, `make test` apparently is not supposed to work. However, the test mentioned in #172 also does not exist any longer (assuming it has been renamed to `sqlcipher.test`).

Can you document how to run the tests in the readme?

**Comment by sjlombardo** [comment]
Hello @lgrahl - thanks for reporting this. We will update the readme. In the mean time, the correct way to run the test is:

```
make testfixture
./testfixture test/sqlcipher.test
```

**Comment by sjlombardo** [comment]
Hello @lgrahl - I wanted to let you know that we've documented the instructions for running SQLCipher tests in the README.md of the v4.4.0 release. Thank you for making this suggestion!
