### ISSUE TITLE
Running test/all.test segfaults at altermalloc-1.transient.85

### ISSUE THREAD

**Issue by lgrahl** [sqlcipher/sqlcipher#350]
Running `test/all.test` results in a segfault on Linux:

```
...
altermalloc-1.transient.79... Ok
altermalloc-1.transient.80...
! altermalloc-1.transient.80 expected: [1 1]
! altermalloc-1.transient.80 got:      [0 {}]
altermalloc-1.transient.81...
! altermalloc-1.transient.81 expected: [1 1]
! altermalloc-1.transient.81 got:      [0 {}]
altermalloc-1.transient.82...
! altermalloc-1.transient.82 expected: [1 1]
! altermalloc-1.transient.82 got:      [0 {}]
altermalloc-1.transient.83...
! altermalloc-1.transient.83 expected: [1 1]
! altermalloc-1.transient.83 got:      [0 {}]
altermalloc-1.transient.84...
! altermalloc-1.transient.84 expected: [1 1]
! altermalloc-1.transient.84 got:      [0 {}]
altermalloc-1.transient.85...
! altermalloc-1.transient.85 expected: [1 1]
! altermalloc-1.transient.85 got:      [0 {}]
altermalloc-1.transient.86...[1]    62802 segmentation fault (core dumped)  ./testfixture ../test/all.test
```

### Steps to Reproduce

1. Configure as described in the readme
2. Run `make testfixture`
3. Run `./testfixture test/all.test`

SQLCipher version: v4.3.0

**Comment by developernotes** [comment]
Hello @lgrahl 

In general, you should not expect the full SQLite test suite to operate with SQLCipher enabled. Some of the tests require low level access to database file for testing, call unsupported pragmas, etc. Thus, the test suite covers features that may be in conflict when the codec is enabled for SQLCipher. Those tests that are intended to support encryption, are often geared towards non-SQLCipher implementations (i.e. SEE). Furthermore, SQLite tests are not always isolated, so if one test fails, it can trigger a domino effect with other failures in later steps. 

As a result, the SQLCipher package includes a separate test harness for SQLCipher. It consists of individual tests that exercise and verify the functionality of the SQLCipher extensions. This is intended solely as an abbreviated test to verify SQLCipher's internal logic; it does not perform an exhaustive test of the SQLite database system as a whole, or verify functionality on specific platforms.  If you are looking to run SQLCipher specific tests, I might recommend running this instead:

```
make testfixture
./testfixture test/sqlcipher.test
```

It's worth noting that the SQLite core is almost untouched in SQLCipher, and we only base SQLCipher releases on tested public releases of SQLite. This means that we consider it a basic assumption that the core SQLite library code is operating properly based on it's own exhaustive test suite.

**Comment by lgrahl** [comment]
Thanks for the clarification. :+1: Perhaps its worth adding this clarification to a testing section in the readme (in combination with #349)?

**Comment by developernotes** [comment]
Hi @lgrahl 

We will include this additional information in the README. Thanks!

**Comment by sjlombardo** [comment]
As mentioned in #349, testing information is now included in the README. Thanks for the suggestion @lgrahl!
