### ISSUE TITLE
Build Error: 'gethostuuid' is unavailable: not available on macCatalyst with xcode11.2

### ISSUE THREAD

**Issue by jepiqueau** [sqlcipher/sqlcipher#351]
### Expected Behavior
should build with no error

### Actual Behavior
i got a build failed  'gethostuuid' is unavailable: not available on macCatalyst with xcode11.2
### Steps to Reproduce

SQLCipher version: 4.30

### Work Around
I modified the SQLCipher/common/sqlite3.c file
```
#ifndef HAVE_GETHOSTUUID
# define HAVE_GETHOSTUUID 0
# if defined(__APPLE__) && ((__MAC_OS_X_VERSION_MIN_REQUIRED > 1050) || \
                            (__IPHONE_OS_VERSION_MIN_REQUIRED > 2000))
#    if (!defined(TARGET_OS_EMBEDDED) || (TARGET_OS_EMBEDDED==0)) \
         && (!defined(TARGET_IPHONE_SIMULATOR) || (TARGET_IPHONE_SIMULATOR==0)) \
         && (!defined(TARGET_OS_MACCATALYST) || (TARGET_OS_MACCATALYST==0))
#      undef HAVE_GETHOSTUUID
#      define HAVE_GETHOSTUUID 1
#    else
#      warning "gethostuuid() is disabled."
#    endif
#  endif
#endif

```
and it build now successfully

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by developernotes** [comment]
Hi @jepiqueau 

This issue has already been identified [here](https://github.com/sqlcipher/sqlcipher/issues/331), the [solution](https://github.com/sqlcipher/sqlcipher/issues/331#issuecomment-568080577) worked with SQLCipher 4.3.0 (i.e., defining `-DHAVE_GETHOSTUUID=0` when building for Mac Catalyst).
