### ISSUE TITLE
Superfluous "ok" output for dot-commands

### ISSUE THREAD

**Issue by revolter** [sqlcipher/sqlcipher#355]
[This comment](https://github.com/sqlcipher/sqlcipher/issues/353#issuecomment-584624118) is incorrect:

```
> sqlcipher --version
3.30.1 2019-10-10 20:19:45 18db032d058f1436ce3dea84081f4ee5a0f2259ad97301d43c426bc7f3dfalt1

> /usr/local/opt/sqlite/bin/sqlite3 --version
3.31.1 2020-01-27 19:55:54 3bfa9cc97da10598521b342961df8f5f68c7388fa117345eeb516eaa837bb4d6

> sqlcipher -cmd "PRAGMA key = '<password>'; PRAGMA cipher_compatibility = 3; PRAGMA user_version" database.sqlite .output
ok
5

> /usr/local/opt/sqlite/bin/sqlite3 -cmd "PRAGMA user_version" database.sqlite .output
5
```

I also tested with version `3.30.1 2019-10-10 20:19:45 18db032d058f1436ce3dea84081f4ee5a0f2259ad97301d43c426bc7f3df1b0b`, with the same result, so the problem isn't that they removed it between versions `3.30.1` and `3.31.1`.

Meaning that the `ok` looks like it's being added by SQLCipher, not SQLite.

**Comment by developernotes** [comment]
Hi @revolter 

>This comment is incorrect:
>Meaning that the ok looks like it's being added by SQLCipher, not SQLite.

The upstream SQLite implementation did change the output value for the result of a `PRAMGA key` command, the change can be reviewed [here](https://www.sqlite.org/src/info/b3692c406f7ba625). You can see our [test suite](https://github.com/sqlcipher/sqlcipher/commit/2f8202bf5102d7834f365bddb68a4ddf6cf6c49c) was updated to reflect that. We utilize GitHub Issues for reporting defects within the library itself. If you have additional questions about this change, we would be happy to discuss them on the [SQLCipher discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!
