### ISSUE TITLE
How to install the lib/dll/*.h to a custom folder on Windows?

### ISSUE THREAD

**Issue by playgithub** [sqlcipher/sqlcipher#356]
I've built sqlcipher on Windows 10, the lib/dll/*.h/*.c/... are in one folder.
How to install only necessary files in a custom folder?
Then the file structure may like this:
```
path\to\sqlcipher_lib\include
path\to\sqlcipher_lib\lib
path\to\sqlcipher_lib\bin
```

Thanks

**Comment by nurupo** [comment]
When you run configure, pass `--prefix="path\to\sqlcipher_lib\include"` to it and just `make install` at the end to install whatever you have built in there. It's the well-known workflow to achieve that when dealing with gnu autotools. That's assuming you are using configure and make on Windows.
