### ISSUE TITLE
Migrate from 3.x to 4.x in iOS using objective C

### ISSUE THREAD

**Issue by sajallimbu** [sqlcipher/sqlcipher#360]
Hello! I'm having issues when migrating from sqlcpher 3.x to 4 on iOS. I have seen the tutorial [here](https://www.zetetic.net/sqlcipher/ios-tutorial/) and [here](https://discuss.zetetic.net/t/upgrading-to-sqlcipher-4/3283) but the first one only tells how to add sqlcipher to your xcode and the latter tells you how to migrate from 3.x to 4, which may seem like the solution but the migration there is done using terminal. I want to make it so that when my app encounters a sql db made using old sqlcipher(3 or less), the sql db is migrated to 4 and then read from. I want to migrate the db inside of my app like it is possible in android using prekey. Is there any solution to this? Would really appreciate the help if possible. 

The app is a hybrid app using cordova.

**Comment by developernotes** [comment]
Hello @sajallimbu 

Thank you for your interest in SQLCipher. We reserve GitHub Issues for reporting defects in the software library. This is an excellent question to pose to the community on our SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher) instead. Would you mind posting it there instead? Thanks!
