### ISSUE TITLE
Calling sqlite3_uri_parameter from sqlite3CodecQueryParameters is UB

### ISSUE THREAD

**Issue by ngg** [sqlcipher/sqlcipher#362]
SQLCipher version: 4.3.0

According to http://www.sqlite.org/c3ref/uri_parameter.html calling `sqlite3_uri_parameter` is undefined behavior if it's not called with the pointer passed to the xOpen VFS method, so it probably should be avoided.
It doesn't cause any actual problem with SQLite 3.30.1 now and I know that it is unsupported to replace SQLite version, but when I tried to upgrade to SQLite 3.31.1 it caused crashes because it assumes there is valid data before the pointer. (`sqlite3_uri_parameter` calls `databaseName` which indexes the pointer with negative indexes)

**Comment by sjlombardo** [comment]
@ngg To be honest, I have not looked at this. Can you tell me what the behavior is for the same test when you are using SQLite 3.31.1 without SQLCipher? What happens then?

**Comment by ngg** [comment]
I'm sorry, I thought this function is in SQLCipher only. However it seems it's a bug in upstream SQLite in 3.31.1, but as SQLITE_HAS_CODEC is unsupported (and already removed in the master branch), I don't think reporting it to them makes sense.
Are you planning to "revert" removing SQLITE_HAS_CODEC? If so, when you'll upgrade SQLite the next time, please be aware of this bug, and check proper usage of sqlite3_uri_parameter. (In 3.32.0, there will be a helper function sqlite3_create_filename which can be used to create a string with the proper memory layout that sqlite3_uri_parameter can use.)

**Comment by sjlombardo** [comment]
@ngg I'm not sure that I understand your response.

Does the application crash using the source distribution of SQLite 3.31.1 downloaded from here: https://www.sqlite.org/download.html? If so, then it would be most appropriate to report upstream as a bug in SQLite.

If not, and the problem only occurs with SQLCipher, then we would look into it as a SQLCipher issue. If that is the case, it would be very helpful if you could share the exact C code you are using to trigger the crash.

**Comment by sjlombardo** [comment]
@ngg - to follow up on this, we just released SQLCipher 4.4.0, which is based on SQLite 3.31.0. We can confirm that 3.31.1 is not safe to use for with SQLCipher due to a bug in SQLite that was subsequently fixed after the 3.31.1 release but has not been included in a release version of SQLite. As such 3.31.1 should be considered unsafe for use with SQLCipher.
