### ISSUE TITLE
getting error while running the project 

### ISSUE THREAD

**Issue by premkumarsepuri** [sqlcipher/sqlcipher#365]
### Steps to Reproduce

SQLCipher version:3.3.1

getting errors in sqlite 3.c

using Xcode 11

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by developernotes** [comment]
Hi @premkumarsepuri 

Thanks for your interest in SQLCipher. We would need you to post the errors you are seeing in order to provide any assistance. The more information you can provide, the better. Thanks!

**Comment by premkumarsepuri** [comment]
![Screenshot 2020-07-06 at 8 28 39 PM](https://user-images.githubusercontent.com/44166456/86607796-5a251c00-bfc7-11ea-971c-00c56cd5d9f3.png)

**Comment by premkumarsepuri** [comment]
I have attached  screen shot of errors . im using Xcode 11 .  language objective c and SQLCipher version:3.3.1

getting errors in sqlite 3.c file

**Comment by premkumarsepuri** [comment]
> Hi @premkumarsepuri
> 
> Thanks for your interest in SQLCipher. We would need you to post the errors you are seeing in order to provide any assistance. The more information you can provide, the better. Thanks!

I provided required details and screen shot of errors

**Comment by developernotes** [comment]
Hi @premkumarsepuri 

Can you verify your application header search paths is able to locate the `sqlite3.h` file? It would be helpful for you to also post a full build output for review.

**Comment by premkumarsepuri** [comment]
![Screenshot 2020-07-08 at 6 22 16 PM](https://user-images.githubusercontent.com/44166456/86920935-0c83ed00-c148-11ea-888e-812d21e76ac5.png)


I have attached above screen .I can find sqlite3.h  file when I search in project .

**Comment by developernotes** [comment]
Hello @premkumarsepuri 

Would you please provide a full build log output for review. Thanks!

**Comment by premkumarsepuri** [comment]
I cannot simulate  project  . Im getting errors in sqlite 3.c file  in sqlcipher

**Comment by premkumarsepuri** [comment]
![Screenshot 2020-07-08 at 7 03 39 PM](https://user-images.githubusercontent.com/44166456/86924970-d5b0d580-c14d-11ea-913e-b5e5c6cdb422.png)

**Comment by premkumarsepuri** [comment]
can you help me?

**Comment by developernotes** [comment]
Hello @premkumarsepuri 

We will need you to provide a full build log output from Xcode in order to identify what may be going on.

**Comment by premkumarsepuri** [comment]
![WhatsApp Image 2020-07-22 at 12 02 55 PM](https://user-images.githubusercontent.com/44166456/88143158-61c60100-cc14-11ea-8597-28fa34cd8981.jpeg)

Ii have attached screen for more information. kindly help me

**Comment by premkumarsepuri** [comment]
![Screenshot 2020-07-23 at 11 30 27 AM](https://user-images.githubusercontent.com/44166456/88256143-1117dc00-ccd8-11ea-9c35-e14a9e49d419.png)

I have tired to simulate the project im. not sqlite error . But getting error configure  errors can you help me

**Comment by sjlombardo** [comment]
This is [cross-posted](https://discuss.zetetic.net/t/unable-to-simulate-project-in-xcode-11/4530) to the SQLCipher discussion site. Based on the error it is not a defect in SQLCipher but likely a problem with the local development environment. Further discussion / resolution can take place on the forum, so I'm closing this issue.
