### ISSUE TITLE
XCODE12 Beta1 Compile Error 'Redefinition of 'sqlite3_xxxxxxx'

### ISSUE THREAD

**Issue by y25zhao** [sqlcipher/sqlcipher#366]
### Expected Behavior
I am trying to get my iOS project compiled with SQLCipher on XCode 12 beta1. I am using cocoapod and expect the compilation to succeed.

### Actual Behavior
Compilation failed with many errors indicating that 
struct sqlite3_xxxxxx has already been declared. 

### Steps to Reproduce
Create a helloworld project with cocoapod. And declare SQLCipher in podfile. 
Try pod install and open and compile the project

SQLCipher version: 4.4.0

Thanks for help

**Comment by R4N** [comment]
Hi @y25zhao 

Thanks for your interest in SQLCipher. 

I've just verified that SQLCipher version 4.4.0 pod installs and compiles fine using both Objective C and Swift projects using this environment:

macOS Big Sur: Version 11.0 Beta (20A4299v)
Xcode: Version 12.0 beta (12A6159)

* Are you using Objective C or Swift?
* If you're using Swift are you properly adding a Bridging Header?
* Are you adding any other packages which could include dependencies on standard sqlite?
* Do you have a test project which can reproduce the issue?
* Could you share your Podfile which is causing the issue?

**Comment by y25zhao** [comment]
Thanks @R4N sry for responding this late. I think we know what the problem is. We have another private library that also have sqlite3.h. For some reason, it was working fine on previous version of xcode. Now, it starts complaining about the duplicate declarations with xcode 12. Do you know if there is a way to work around that issue? Thanks

**Comment by R4N** [comment]
@y25zhao 

We do not recommend attempting to build multiple SQLCipher/SQLite dependencies within a single application. There is an inherent risk of stability introduced by attempting to load both libraries into the same running process. That being said, this information may be helpful: https://discuss.zetetic.net/t/important-advisory-sqlcipher-with-xcode-8-and-new-sdks/1688

You may also consider posting on the [SQLCipher community discussion forum](https://discuss.zetetic.net/c/sqlcipher/) with further details about your project setup.

I'm going to close this issue as we reserve GitHub for reporting issues and defects with the SQLCipher library.
