### ISSUE TITLE
.read goes on forever, database stops growing early

### ISSUE THREAD

**Issue by elig0n** [sqlcipher/sqlcipher#367]
### Expected Behavior
I'm trying to import a sqlite3 database into a sqlcipher encrypted database by opening a new file, setting the PRAGMA key, creating tables and then .read a list of INSERT commands from a file I prepared.
The file containing the commands is several GB large, but the newly opened database only gets filled up to ~100MB with only a few of rows added while the .read operation appears to go on and the sqlcipher prompt not returning.

### Actual Behavior
At start of the .read operation the file would gradually grow in size but at ~100MB it would stop growing.
Even after 24 hours of leaving it like this the .read command would not finish or show any error.

_SQLCipher version:_
3.31.0 2020-01-22 18:38:59 f6affdd41608946fcfcea914ece149038a8b25a62bbe719ed2561c649b86alt1 (SQLCipher 4.4.0 community)

**Comment by developernotes** [comment]
Hi @elig0n 

Can you try importing via `.read` with SQLCipher, but without executing the `PRAGMA key` command? Does it properly execute all SQL statements in your source file? How long does it take to complete?

**Comment by elig0n** [comment]
eventually I got that going by setting `PRAGMA synchronous = OFF; PRAGMA cache_size = 250000; `

**Comment by developernotes** [comment]
Hi @elig0n 

We are happy to hear you were able to resolve the issue. Thanks for the update!
