### ISSUE TITLE
Alpine build test failed: export-database export-attached-database

### ISSUE THREAD

**Issue by wenerme** [sqlcipher/sqlcipher#368]
### Expected Behavior
building on alpinelinux, test success
### Actual Behavior

https://gitlab.alpinelinux.org/wener/aports/-/jobs/180246#L520

 2 errors out of 170 tests on runner-jxpu8gd-project-284-concurrent-0 Linux 64-bit little-endian
 !Failures on these tests: export-database export-attached-database
 -1 files were left open

### Steps to Reproduce
under alpine build env

```bash
git clone --depth=50 https://gitlab.alpinelinux.org/alpine/aports

# start build server
docker run -d --restart=unless-stopped \
    -p 2222:22 \
    -v $PWD:/build \
    -v $PWD/home:/home/admin \
    -v $PWD/distfiles:/var/cache/distfiles \
    -v $PWD/cache:/etc/apk/cache \
    --name build-server wener/app:builder
docker exec -it -u 1000 build-server bash
cd /build/aports/testing/sqlcipher

abuild deps
abuild unpack
# check will failed
abuild check
# check error under src/sqlcipher-4.4.0/
```

SQLCipher version: 4.4.0

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by wenerme** [comment]
I don't know which one is the log for testfixture, I can provide the error log.

**Comment by developernotes** [comment]
Hi @wenerme 

I tried to run your script, however `docker exec` is failing:

```
$ docker exec -it -u 1000 build-server
"docker exec" requires at least 2 arguments.
See 'docker exec --help'.

Usage:  docker exec [OPTIONS] CONTAINER COMMAND [ARG...]

Run a command in a running container
```

Attempting to include your `cd` command with `docker exec` also appears to fail:

```
docker exec -it -u 1000 build-server "cd aports/testing/sqlcipher"
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"cd aports/testing/sqlcipher\": stat cd aports/testing/sqlcipher: no such file or directory": unknown
```

While tcl tests are you running? Typically the output from the tcl test suite is printed to stdout. If you could capture the test suite output, that would be helpful for isolating the issue.

**Comment by wenerme** [comment]
sorry, should be `docker exec -it -u 1000 build-server bash`

the test is

```bash
make testfixture
./testfixture test/sqlcipher.test
```

full output is here https://gitlab.alpinelinux.org/wener/aports/-/jobs/180246#L520

**Comment by wenerme** [comment]
I missed the error in stdout

```
export-database...
 Error: no such module: fts5
export-attached-database...
 Error: no such module: fts5
```

**Comment by sjlombardo** [comment]
@wenerme the `./configure` needs to include the `--enable-fts5` option for the export tests to pass.

**Comment by wenerme** [comment]
Thanks, build now.

**Comment by wenerme** [comment]
zero error, but still failed

```
SQLite 2020-01-22 18:38:59 f6affdd41608946fcfcea914ece149038a8b25a62bbe719ed2561c649b86alt1
0 errors out of 170 tests on 00df3da05751 Linux 64-bit little-endian
-1 files were left open
All memory allocations freed - no leaks
Memory used:          now          0  max    2737056  max-size     169120
Allocation count:     now          0  max       7019
Page-cache used:      now          0  max          0  max-size       8456
Page-cache overflow:  now          0  max    2520432
Maximum memory usage: 2737056 bytes
Current memory usage: 0 bytes
Number of malloc()  : -1 calls
>>> ERROR: sqlcipher: check failed
```

**Comment by wenerme** [comment]
After manually `./testfixture test/sqlcipher.test`, 0 errors, but the `echo $?` is `1`

**Comment by developernotes** [comment]
Hello @wenerme 

We will have the test fixture reporting fixed in the next public SQLCipher release.

**Comment by wenerme** [comment]
Sounds fixed in latest version
