### ISSUE TITLE
crashed with openssl-1.1.1g but works with openssl 1.0

### ISSUE THREAD

**Issue by yangboyd** [sqlcipher/sqlcipher#370]
tested on CentOS 7.

Program received signal SIGSEGV, Segmentation fault.
0x0000000000542062 in EVP_MD_CTX_clear_flags (ctx=0x0, flags=2) at crypto/evp/evp_lib.c:514
514	    ctx->flags &= ~flags;
Missing separate debuginfos, use: debuginfo-install glibc-2.17-157.el7.x86_64 openssl-libs-1.0.2k-12.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x0000000000542062 in EVP_MD_CTX_clear_flags (ctx=0x0, flags=2) at crypto/evp/evp_lib.c:514
#1  0x00000000005a3624 in EVP_DigestInit_ex (ctx=0x0, type=0x9c7980 <sha512_md>, impl=0x0) at crypto/evp/digest.c:68
#2  0x000000000054514a in HMAC_Init_ex (ctx=0xa29420, key=0xa10d10, len=32, md=0x9c7980 <sha512_md>, impl=0x0) at crypto/hmac/hmac.c:70
#3  0x0000000000459b27 in sqlcipher_openssl_hmac ()
#4  0x0000000000457fa5 in sqlcipher_page_hmac ()
#5  0x0000000000458203 in sqlcipher_page_cipher ()
#6  0x00000000004559f4 in sqlite3Codec ()
#7  0x0000000000472249 in pager_write_pagelist ()
#8  0x00000000004746f7 in sqlite3PagerCommitPhaseOne ()
#9  0x000000000047f50a in sqlite3BtreeCommitPhaseOne ()
#10 0x0000000000490f8a in vdbeCommit ()
#11 0x0000000000491920 in sqlite3VdbeHalt ()
#12 0x0000000000498008 in sqlite3VdbeExec ()
#13 0x000000000049548e in sqlite3Step ()
#14 0x00000000004956d7 in sqlite3_step ()
#15 0x000000000044046f in exec_prepared_stmt ()
#16 0x0000000000441011 in shell_exec ()
#17 0x0000000000451485 in runOneSqlLine ()
#18 0x000000000045194c in process_input ()
#19 0x00000000004532cc in main ()
(gdb) frame 1

**Comment by sjlombardo** [comment]
We have been unable to reproduce this issue. Can you try with the latest SQLCipher release?

**Comment by sjlombardo** [comment]
Closed for inactivity.
