### ISSUE TITLE
./configure throw error: C compiler cannot create executables

### ISSUE THREAD

**Issue by DoSeek** [sqlcipher/sqlcipher#372]
### Expected Behavior
$ ./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC" LDFLAGS="/opt/local/lib/libcrypto.a"
config.status: creating Makefile

### Actual Behavior
$ ./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC" LDFLAGS="/opt/local/lib/libcrypto.a"
C compiler cannot create executables

### Steps to Reproduce
./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC" LDFLAGS="/opt/local/lib/libcrypto.a"

SQLCipher version: 1.1.8

Build system info: Ubuntu18.04 , GCC 7.5.0
------------------------------------------------------------

I found Ubuntu18.04 need install openssl library:
```
$ sudo apt install libssl-dev
```
'libcrypto.a' file path is "/usr/lib/x86_64-linux-gnu/libcrypto.a", I use follow command to create Makefile success:
```
./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC" LDFLAGS="/usr/lib/x86_64-linux-gnu/libcrypto.a" --prefix=/home/dog/Dev/C++/sqlcipher/install-static
```
PS.
CentOS system install openssl: $ sudo yum install openssl-devel

If you unknown 'libcrypto.a' file path, could use command find it :  $ whereis libcrypto.a

**Comment by developernotes** [comment]
Hello @DoSeek 

The path to a local `libcrypto.a` will likely vary depending on your OS and environment configuration. As you note, once you provide a valid path you are able to proceed. We will close this ticket for now. If you have any other build related questions, please feel free to post those in our SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!
