### ISSUE TITLE
How to open a database encrypted with SQLCipher?

### ISSUE THREAD

**Issue by ertandrn** [sqlcipher/sqlcipher#373]
Hello, I'm developing an application with React Native. I created and encrypted a database with the package. (react-native-sqlcipher) I want to open this database with "DB Browser for SQLite" or "SQLite Studio". However, it doesn't open even though I enter the correct key. Is salt being added while encrypting the database? If so, where is salt stored? Could you help me?

Note: I use the database without any problem while in the Android application.
SQLCipher version: 4.3.0

![2020-09-29 23-14-59 ekran görüntüsü](https://user-images.githubusercontent.com/28516213/94705423-b63ed880-0349-11eb-8cc9-e7859c7a1fea.png)

**Comment by sjlombardo** [comment]
@ertandrn if you are using SQLCipher 4.x you should use the SQLCipher 4 settings. Also, we reserve Github issues for defect tracking, not general use questions or issues with separate software packages. If you continue to have trouble please post to the [SQLCipher Discussion Site](https://discuss.zetetic.net/c/sqlcipher/5)
