### ISSUE TITLE
Metadata typos in 4.4.1

### ISSUE THREAD

**Issue by dubiousjim** [sqlcipher/sqlcipher#374]
Was looking through the diffs from 4.4.0-4.4.1, and I noticed a few places where you have wrong/misplaced `/* BEGIN SQLCIPHER */` or `/* END SQLCIPHER */` labels.

* End of src/crypto.c misplaced `END`
* src/sqlite.h.in line 5995 (after sqlite3_activate_see) has a `BEGIN` that should be an `END`
* src/shell.c.in line 11121 has a `BEGIN` that should be an `END`
* src/tclsqlite.c line 3730 (in DbMain) has a `BEGIN` that should be an `END`

**Comment by sjlombardo** [comment]
Hello @dubiousjim thanks for the report, these have been resolved in the latest release
