### ISSUE TITLE
Hello, I cannot compile sqlcipher in Linux Mint 20 based on Ubuntu 20.04?

### ISSUE THREAD

**Issue by phd21** [sqlcipher/sqlcipher#375]
Hello,

I cannot compile sqlcipher in Linux Mint 20 based on Ubuntu 20.04? I use this in my Qtox application. The sqlcipher in the repositories is 3.4.1 build 2 and according to this GitHub the version is up to 4.4.2. I can compile other software including toxcore and qtox, etc...

I have tried both configure options (Static linking and Dynamic linking) and neither one will compile. OpenSSL is installed by default.

Can anyone please help me to get v4.4.2 compiled?

Thank you,
Phil
phd21

Example 1
./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC" \
		LDFLAGS="/usr/lib/x86_64-linux-gnu/libcrypto.a"

...
checking whether the C compiler works... no
configure: error: in `/home/phd21/sqlcipher':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** No targets specified and no makefile found.  Stop.

Example 2
./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC" \
		LDFLAGS="-lcrypto"
...
checking whether the C compiler works... no
configure: error: in `/home/phd21/sqlcipher':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** No targets specified and no makefile found.  Stop.

config.log
...
configure:2837: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'; did you mean '--version'?
gcc: fatal error: no input files
compilation terminated.
configure:2848: $? = 1
configure:2868: checking whether the C compiler works
configure:2890: gcc -DSQLITE_HAS_CODEC  -lcrypto conftest.c  >&5
/usr/bin/ld: cannot find -lcrypto
collect2: error: ld returned 1 exit status

**Comment by developernotes** [comment]
Hello @phd21 

Thanks for your interest in SQLCipher. We reserve GitHub Issues for reporting defects in the software library itself. For questions pertaining to building the software, I would recommend posting to the [SQLCipher community discuss site](https://discuss.zetetic.net/c/sqlcipher) for further assistance. Thanks!
