### ISSUE TITLE
OPEN SQLCipher file

### ISSUE THREAD

**Issue by alicera** [sqlcipher/sqlcipher#376]
I install SQLCipher 4.4.2 community
how to open the DB for SQLCipher?

OS: ubuntu18.04

**Comment by developernotes** [comment]
Hi @alicera 

Thank you for your interest in SQLCipher. If you are looking to open an existing SQLCipher database from the command line, you can invoke the following:

```
./sqlcipher your-sqlcipher-database.db
```

That will launch the SQLCipher command line shell, you can then provide the password used for keying the database like this:

```
PRAGMA key = 'YourPasswordHere';
```

You can read more about the SQLCipher-specific API's [here](https://www.zetetic.net/sqlcipher/sqlcipher-api/). If you have additional utilization questions, please feel free to post those directly to our [Community Discuss](https://discuss.zetetic.net/c/sqlcipher) site. Thanks!
