### ISSUE TITLE
[Doc] Please provide migration documentation for Room

### ISSUE THREAD

**Issue by arduia** [sqlcipher/sqlcipher#386]
This SQLCipher is amazing lib. It would be great if you provide migration plan for old plain text SQLite (Room) to Encrypted Database.

**Comment by developernotes** [comment]
Hello @arduia 

We are happy to hear you are enjoying SQLCipher, thanks for reaching out. Migrating from plaintext SQLite to an encrypted SQLCipher database is not specific to Room. We provide general documentation on the SQL commands required to migrate from plaintext via the [`sqlcipher_export()`](https://www.zetetic.net/sqlcipher/sqlcipher-api/#sqlcipher_export) convenience function. There are many different scenarios the function supports, however, you are most likely interested in reviewing [example #1](https://www.zetetic.net/sqlcipher/sqlcipher-api/#example-1-encrypt-a-plaintext-database). Would you give that a try and let us know if you were able to successfully migrate your database?

**Comment by arduia** [comment]
Thanks @developernotes.

**Comment by developernotes** [comment]
Hi @arduia 

No problem, happy to help!
