### ISSUE TITLE
adding key to existing database will now work

### ISSUE THREAD

**Issue by avnerbarr** [sqlcipher/sqlcipher#387]
I'm trying to add sqlcipher to existing project.

If my database existed prior to including the cipher, I noticed that the database will not be encrypted.

Is there some additional step to take when migrating existing db?

**Comment by sjlombardo** [comment]
https://discuss.zetetic.net/t/how-to-encrypt-a-plaintext-sqlite-database-to-use-sqlcipher-and-avoid-file-is-encrypted-or-is-not-a-database-errors/868
