### ISSUE TITLE
m1 mac have question

### ISSUE THREAD

**Issue by SamKun28** [sqlcipher/sqlcipher#390]
### M1 macbookpro pod install 

SQLCipher version:4.4.3

*Note:* Installing SQLCipher (4.4.3)
[!] /bin/bash -c
set -e
./configure --enable-tempstore=yes --with-crypto-lib=commoncrypto CFLAGS="-DSQLITE_HAS_CODEC -DSQLITE_TEMP_STORE=2 -DSQLITE_SOUNDEX -DSQLITE_THREADSAFE -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_STAT3 -DSQLITE_ENABLE_STAT4 -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_MEMORY_MANAGEMENT -DSQLITE_ENABLE_LOAD_EXTENSION -DSQLITE_ENABLE_UNLOCK_NOTIFY -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS4_UNICODE61 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_FTS5 -DHAVE_USLEEP=1 -DSQLITE_MAX_VARIABLE_NUMBER=99999"; make sqlite3.c

checking build system type...
Invalid configuration `arm64-apple-darwin20.3.0': machine `arm64-apple' not recognized
configure: error: /bin/sh ./config.sub arm64-apple-darwin20.3.0 failed

**Comment by billymeltdown** [comment]
Hi @SamKun28 ,

Using an M1 running Big Sur 11.3 with Xcode 12.5, I was able to run your configure command without any errors and did not see the error you mention here, that arm64-apple is not recognized. 

Your output mentions Darwin 20.3.0 -- that refers to Big Sur version 11.2, can you check your macOS version? It might also help to make sure you are using the latest Xcode as well.

Note: subsequently calling `make` after the above configure command succeeds will fail, we need to include the frameworks System and Foundation in the `LDFLAGS` during configure for that to work. 

Using this configure command:

```bash
./configure \
 --enable-tempstore=yes \
 --with-crypto-lib=commoncrypto \
 CFLAGS="-DSQLITE_HAS_CODEC -DSQLITE_TEMP_STORE=2 -DSQLITE_SOUNDEX -DSQLITE_THREADSAFE -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_STAT3 -DSQLITE_ENABLE_STAT4 -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_MEMORY_MANAGEMENT -DSQLITE_ENABLE_LOAD_EXTENSION -DSQLITE_ENABLE_UNLOCK_NOTIFY -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS4_UNICODE61 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_FTS5 -DHAVE_USLEEP=1 -DSQLITE_MAX_VARIABLE_NUMBER=99999" \
 LDFLAGS="-framework Security -framework Foundation"
```

I was able to then build successfully with `make`. 

Note that you might want additional LDFLAGS besides Framework and Security, if you want to run the tests (tcl) or want readline support for the shell, e.g.

    LDFLAGS="-framework Security -framework Foundation -lreadline -ltcl8.5"
