### ISSUE TITLE
Cannot open database in Redmi device

### ISSUE THREAD

**Issue by moylir** [sqlcipher/sqlcipher#392]
### Expected Behavior

Database gets opened with password and can be managed.

### Actual Behavior

In the instruction to open the database, this one:

    database = dbHelper.getWritableDatabase("pass");

It throws this error when executed in a Redmi device (works fine in Android emulator):

No implementation found for void net.sqlcipher.database.SQLiteDatabase.dbopen(java.lang.String, int) (tried Java_net_sqlcipher_database_SQLiteDatabase_dbopen and Java_net_sqlcipher_database_SQLiteDatabase_dbopen__Ljava_lang_String_2I)

### Steps to Reproduce

I guess it would be enough with using the previous instruction in a Redmi device (maybe it also happens in other physical devices).

SQLCipher version: 4.4.3

**Comment by developernotes** [comment]
Hi @moylir 

I am closing this ticket as it belongs in the SQLCipher for Android repository, which you've already created [here](https://github.com/sqlcipher/android-database-sqlcipher/issues/557).
