### ISSUE TITLE
Update SQLite

### ISSUE THREAD

**Issue by threema-danilo** [sqlcipher/sqlcipher#395]
### Expected Behavior

It would be nice if the bundled sqlite version could be upgraded to a version ≥ 3.35, because this will enable the use of the `RETURNING` clause for INSERT/UPDATE/DELETE statements, along with a few other very nice  features: https://sqlite.org/releaselog/3_35_0.html The current release is 3.36.

### Actual Behavior

Currently SQLite 3.34 is bundled / wrapped.

**Comment by indutny-signal** [comment]
In addition to this, sqlite now supports `DROP COLUMN` in `ALTER TABLE`. Would be great to get this too!

**Comment by threema-danilo** [comment]
> In addition to this, sqlite now supports `DROP COLUMN` in `ALTER TABLE`. Would be great to get this too!

Oh wow, that's incredible. I totally missed that. Huge improvement when writing database migrations!

**Comment by sjlombardo** [comment]
We agree that recent releases of SQLite have some excellent improvements. We are planning to update to 3.36.0 as the baseline in our next release of SQLCipher. We'll leave this issue open until then. Thanks!

**Comment by indutny-signal** [comment]
Awesome, thanks! Do you have a release schedule or plan that we could add to our calendars?

**Comment by sjlombardo** [comment]
The release of SQLCipher 4.5.0 is now based on the latest available SQLite 3.36.0.
