### ISSUE TITLE
document that zKey argument must be null-terminated

### ISSUE THREAD

**Issue by elagergren-spideroak** [sqlcipher/sqlcipher#398]
`sqlite3_key()` accepts `..., const void* pKey, int nKey`, which would lead you to believe that `pKey` does not need to be null-terminated: it's not `char*` and it has an explicit length. Indeed, SQLCipher works just fine without a null-terminated `pKey`.

Except, however, when `CODEC_DEBUG` is defined (say, while testing). In that case,`sqlite3_key()` casts `pKey` to `char*` and prints it using `%s` via `CODEC_TRACE`. If `pKey` isn't null-terminated, this crashes.

**Comment by tbvdm** [comment]
Perhaps this would be a good way to fix this? (There are more places in the code where this fix could be applied.)

```
diff --git a/src/crypto.c b/src/crypto.c
index 428b9a5..17eeb6e 100644
--- a/src/crypto.c
+++ b/src/crypto.c
@@ -858,7 +858,7 @@ void sqlite3_activate_see(const char* in) {
 }
 
 int sqlite3_key(sqlite3 *db, const void *pKey, int nKey) {
-  CODEC_TRACE("sqlite3_key entered: db=%p pKey=%s nKey=%d\n", db, (char *)pKey, nKey);
+  CODEC_TRACE("sqlite3_key entered: db=%p pKey=%.*s nKey=%d\n", db, nKey, (const char *)pKey, nKey);
   return sqlite3_key_v2(db, "main", pKey, nKey);
 }
 
```

Alternatively, given that pKey might contain unprintable characters, perhaps it shouldn't be printed as a raw string at all?

**Comment by elagergren-spideroak** [comment]
> Alternatively, given that pKey might contain unprintable characters, perhaps it shouldn't be printed as a raw string at all?

Yeah, it could or should use `%p`.

**Comment by sjlombardo** [comment]
Thank you for reporting this. We agree that it is an issue. All tracing output will be changed to use `%p` in the next release of SQLCipher.

**Comment by sjlombardo** [comment]
This issue has been resolved as of the latest release!
