### ISSUE TITLE
Mac M1 SQL Configure Failing

### ISSUE THREAD

**Issue by serajahmad01** [sqlcipher/sqlcipher#399]
### Steps to Reproduce

SQLCipher version: 4.4.3

Command --> ./configure --with-crypto-lib=commoncrypto --enable-tempstore=yes --host arm64-apple-darwin CFLAGS="-DSQLITE_HAS_CODEC -mios-version-min=10 -isysroot /Software/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk -fno-common -arch arm64 -fembed-bitcode-marker" LDFLAGS="-framework Security -framework Foundation"
checking build system type... x86_64-apple-darwin20.6.0
checking host system type... Invalid configuration `arm64-apple-darwin': machine `arm64-apple' not recognized
configure: error: /bin/sh ./config.sub arm64-apple-darwin failed

I am trying to build Libraries for iPhoneSimulator and MacCatalyst.

My System Configuration:
MacOS Big Sur 11.5.2
XCode Version - 12.5
Output of "uname -a"
Darwin 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

Thanks in advance.

**Comment by serajahmad01** [comment]
Hi Everyone,
I am still facing this issue.
Can anyone suggest a solution?
Thanks in Advance

**Comment by developernotes** [comment]
Hi @serajahmad01,

Thanks for your interest in SQLCipher. We reserve GitHub Issues for tracking defects within the software library itself. This particular question should be posted to the [SQLCipher Community Discuss site](https://discuss.zetetic.net/c/sqlcipher), please consider reposting there instead. Thanks!
