### ISSUE TITLE
command './configure'

### ISSUE THREAD

**Issue by liang1234561** [sqlcipher/sqlcipher#407]
### Steps to Reproduce

SQLCipher version:

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by developernotes** [comment]
Hi @liang1234561,

Thanks for your interest in SQLCipher. We reserve GitHub Issues for tracking defects within the software library itself. This particular report does not contain any information. If you have a question about configuring the software library, you  should consider posting to the [SQLCipher Community Discuss site](https://discuss.zetetic.net/c/sqlcipher) instead. Thanks!
