### ISSUE TITLE
iOS 15.2 beta 2 (19C5036e) throws "bad parameter or other API misuse (code: 21)"

### ISSUE THREAD

**Issue by tomrbn01** [sqlcipher/sqlcipher#412]
### Expected Behavior
Connection.rekey -> encrypts not encrypted database or changes the key on an open encrypted database

### Actual Behavior
Returns error: `bad parameter or other API misuse (code: 21)`

### Steps to Reproduce
XCode 13.2 Beta, iPhone (not simulator) with iOS 15.2 Beta (same code works on XCode 13.0 and iOS 15.1)
Podfile:
```
    pod 'SQLite.swift', '~> 0.13.0'
    pod 'SQLite.swift/SQLCipher', '~> 0.13.0'
```

SQLCipher version: 4.4.3 or 4.5.0

```
connection = try Connection(path)
_ = try connection?.scalar("SELECT count(*) FROM sqlite_master;") (Check that database is locked or not - in this case is not locked)
try connection?.rekey(newPassword)
```

**Comment by R4N** [comment]
Hi @tomrbn01

Thank you for your interest in SQLCipher.

We don't develop or maintain the SQLite.swift project, so I can't comment directly on what is occurring within that project. I would recommend raising the issue directly within the target project as is linked. I do have a few preliminary comments what you've posted here:

>Connection.rekey -> encrypts not encrypted database or changes the key on an open encrypted database

sqlite3_rekey isn't used for encrypting a non-encrypted database or vice-versa. Instead you'll want to use the [sqlcipher_export()](https://www.zetetic.net/sqlcipher/sqlcipher-api/#sqlcipher_export) convenience function.

```
    pod 'SQLite.swift', '~> 0.13.0'
    pod 'SQLite.swift/SQLCipher', '~> 0.13.0'
```

You don't want to link both standard SQLite and SQLCipher in the same project as this will cause conflicts.

On [this line in the podspec](https://github.com/stephencelis/SQLite.swift/blob/master/SQLite.swift.podspec#L35) you can see that the SQLite.swift standard podspec is linking against sqlite3.

Most likely you'll want just the SQLCipher subspec I suspect:

```
pod 'SQLite.swift/SQLCipher', '~> 0.13.0'
```

This could mean that your database wasn't encrypted using SQLCipher.

I would recommend looking at this document: https://discuss.zetetic.net/t/important-advisory-sqlcipher-with-xcode-8-and-new-sdks/1688 and implementing a runtime check to make sure SQLCipher is in fact linked at runtime.

I re-tried SQLCipher via cocoapods on iOS 15.2 beta physical device using Xcode 13.2 beta and it worked without error/issue. Are you able to reproduce the issue with standalone SQLCipher? There are instructions here: https://www.zetetic.net/sqlcipher/ios-tutorial/#option-2-cocoapod-integration for integration SQLCipher using CocoaPods.

Finally, we reserve GitHub issues for reporting issues and defects in the SQLCipher library itself. If you're unable to reproduce the issue using standard SQLCipher using CocoaPods, please post to the SQLCipher community discussion board here: https://discuss.zetetic.net/c/sqlcipher/5
