### ISSUE TITLE
Fails to build on M1 Mac Mini

### ISSUE THREAD

**Issue by jakubgs** [sqlcipher/sqlcipher#413]
### Description
Currently building of this library fails if architecture is detected as `arm64`, but works for `arm`. This appears to be due to this line:
https://github.com/sqlcipher/sqlcipher/blob/f7e9e9052397a0313dde44175a7840e36c9abf56/config.sub#L1170
As far as I can tell just adding `arm64` to this list in one form or another makes it work and build.

### Expected Behavior
```
 > ./configure | grep 'build system' 
checking build system type... arm64-apple-darwin20.6.0
```

### Actual Behavior
```
 > ./configure | grep 'build system'
Invalid configuration `arm64-apple-darwin20.6.0': machine `arm64-apple' not recognized
configure: error: /nix/store/ppzr8yab3s3883skd0da5i4ylzpksk9l-bash-5.1-p8/bin/bash ./config.sub arm64-apple-darwin20.6.0 failed
```

### Steps to Reproduce
Hardware: Mac Mini G5E (M1)
Software: Darwin 20.6.0
SQLCipher version: `3.4.2` and `4.5.0`

**Comment by jakubgs** [comment]
I've tested the current `config.guess` from [the official repo](https://git.savannah.gnu.org/gitweb/?p=config.git) and it appears to fix the issue:
```
 > bash ./config.guess
aarch64-apple-darwin20.6.
```
Because it includes this fix: https://git.savannah.gnu.org/gitweb/?p=config.git;a=commit;h=2593751ef

**Comment by jakubgs** [comment]
I've updated `config.guess` and `config.sub` to the most recent version from official repo: #414

My stab at trying to solve this issue.

**Comment by sjlombardo** [comment]
Closing related ticket per #414, ticket open with Nix team to resolve in shell.

**Comment by jakubgs** [comment]
Update: This issue appears to be related to GNU Coreutils and its `uname` utility:
```
admin@macm1-01.ms-eu-dublin.slave.ci:~ % /opt/homebrew//Cellar/coreutils/9.0/bin/guname -m
arm64
admin@macm1-01.ms-eu-dublin.slave.ci:~ % /opt/homebrew//Cellar/coreutils/9.0/bin/guname -p
arm64
```
And it's not Nix specific. So the options are either fix GNU Coreutils (will take ages) or update `config.guess` in SQLite (will take ages as well).
