### ISSUE TITLE
bug in version 3.5.5

### ISSUE THREAD

**Issue by daogepiqian** [sqlcipher/sqlcipher#415]
bug log and backtrace
I/SurfaceFlinger(  433): FPS: 27
I/DEBUG   (27641): generate native report finished
F/libc    (27641): Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc8bfc4a4 in tid 29129 (TaskManager_Thr)
I/DEBUG   (  448): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (  448): Build fingerprint: 'vivo/PD1415BA/PD1415BA:5.1.1/LMY47V/compiler07051628:user/release-keys'
I/DEBUG   (  448): Revision: '0'
I/DEBUG   (  448): ABI: 'arm'
I/DEBUG   (  448): pid: 27641, tid: 29129, name: TaskManager_Thr  >>> com.shuqi.controller <<<
I/DEBUG   (  448): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc8bfc4a4
D/SettingsProvider( 1391): lookupValue table system cache contains Key vivo_fullscreen_flag , value = Bundle[{value=1}]
D/AppConfigProvider( 2720): query.
D/AppConfigProvider( 2720): query-isEnc = true
D/SettingsProvider( 1391): lookupValue table system cache contains Key floatmode , value = Bundle[{value=0}]
D/VivoDaemon_SmartMultiWindowService( 2375): onChange isFullScreen =1isAllowActiveSpilt = falseSmartMultWindowUtils.isSplitMode(mContext) = false
I/DEBUG   (  448):     r0 c89f6f9e  r1 00000000  r2 00000030  r3 c89f70d0
I/DEBUG   (  448):     r4 c8bfc4a4  r5 00000132  r6 c89f6f9e  r7 00101f96
I/DEBUG   (  448):     r8 ac141448  r9 00000000  sl 00000003  fp 00000000
I/DEBUG   (  448):     ip 00000000  sp c35094b0  lr d4aa7ec1  pc d4aa7ec0  cpsr 400f0030
I/DEBUG   (  448): 
I/DEBUG   (  448): backtrace:
I/DEBUG   (  448):     #00 pc 000afec0  /data/app/com.shuqi.controller-1/lib/arm/libsqlcipher.so (_ZN9sqlcipher12CursorWindow8allocRowEv+57)
I/DEBUG   (  448):     #01 pc 000aec4b  /data/app/com.shuqi.controller-1/lib/arm/libsqlcipher.so
I/DEBUG   (  448):     #02 pc 02f31b93  /data/dalvik-cache/arm/data@app@com.shuqi.controller-1@base.apk@classes.dex
I/MSM-irqbalance(  738): Decided to move IRQ239 from CPU3 to CPU1
W/libbacktrace(  448): virtual bool Backtrace::VerifyReadWordArgs(uintptr_t, word_t*): invalid pointer 0xaa
W/libbacktrace(  448): virtual bool Backtrace::VerifyReadWordArgs(uintptr_t, word_t*): invalid pointer 0xaa

SQLCipher version: 3.5.5

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by sjlombardo** [comment]
Closed per https://github.com/sqlcipher/android-database-sqlcipher/issues/577 using wrong type.
