### ISSUE TITLE
OpenSSL 3.0 deprecated the HMAC low level API calls and requires use of the EVP level API.

### ISSUE THREAD

**Issue by thompsow** [sqlcipher/sqlcipher#416]
### Expected Behavior
Build of sqlcipher with OpenSSL 3.0.0 is successful.

### Actual Behavior
Build of sqlcipher with OpenSSL 3.0.0 fails:
error C4996: 'HMAC_CTX_new': Since OpenSSL 3.0
error C4996: 'HMAC_Init_ex': Since OpenSSL 3.0
error C4996: 'HMAC_Update': Since OpenSSL 3.0
error C4996: 'HMAC_Final': Since OpenSSL 3.0
error C4996: 'HMAC_CTX_free': Since OpenSSL 3.0

### Steps to Reproduce
Build sqlcipher with OpenSSL 3.0.0

SQLCipher version: 3.34.1

According to OpenSSL the HMAC APIs are now deprecated since OpenSSL 3.0 and require move to use of EVP_MAC:
EVP_MAC_fetch
EVP_MAC_CTX_new
EVP_MAC_CTX_set_params
EVP_MAC_init
EVP_MAC_update
EVP_MAC_final
EVP_MAC_CTX_free
EVP_MAC_free

**Comment by sjlombardo** [comment]
Hi @thompsow - thanks for the report. We're planning to address this in the next release of SQLCipher.

**Comment by ondrejcitek** [comment]
Hi @sjlombardo - any date when the next release with OpenSSL 3?

**Comment by sjlombardo** [comment]
Hi @ondrejcitek we haven't published a release date for the next version, but it will very likely be this quarter. It will include the change to use the EVP_MAC API when compiling against OpenSSL 3.

**Comment by sjlombardo** [comment]
This should be fixed up in the 4.5.1 release. Let us know if there are any problems.
