### ISSUE TITLE
python3.4 how to use sqlcipher?please help me,thanks

### ISSUE THREAD

**Issue by jifengtuo** [sqlcipher/sqlcipher#417]
### Steps to Reproduce

SQLCipher version:

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by jifengtuo** [comment]
if i need to compile lib file for python3.4?

**Comment by developernotes** [comment]
Hello @jifengtuo,

Thanks for your interest in SQLCipher. We reserve GitHub Issues for tracking defects within the software library itself. This particular question should be posted to the [SQLCipher Community Discuss site](https://discuss.zetetic.net/c/sqlcipher), please consider reposting there instead. Thanks!
