### ISSUE TITLE
SQLCipher GitHub repo "About" appears confusing

### ISSUE THREAD

**Issue by pchemguy** [sqlcipher/sqlcipher#418]
The "About" section of this repo states that "SQLCipher is an SQLite extension that provides 256 bit AES encryption of database files."

I understand that the software you developed is essentially an advanced SQLite extension. However, the actual product available from this repository is a modified version of SQLite, not an extension that can be used with the official SQLite distro (regardless of what was in the past). So I would think that the "About" section should be edited to reflect the actual situation because the current description is confusing.

**Comment by sjlombardo** [comment]
Hello @pchemguy, thanks for checking out SQLCipher. We really meant "extension" in the sense that the feature set is extended, not that it is a loadable library, but I can understand how that could be confusing. To address this concern, we have changed the About blurb of the repo to clarify that "SQLCipher is a standalone fork of SQLite". We will also update the contents of the README.md to clarify the same thing in the next release.

**Comment by sjlombardo** [comment]
This should be fixed up both in the github project description and the README as of the 4.5.1 release. Thanks!
