### ISSUE TITLE
4.5.1: test suite linking fails

### ISSUE THREAD

**Issue by kloczek** [sqlcipher/sqlcipher#428]
Looks like 4.5.1 test suite is failing. I've enabled tcl during autoconf execution. Build and install is OK however test suite fails.
```console
[tkloczko@devel-g2v sqlcipher-4.5.1]$ make test
./fuzzcheck /home/tkloczko/rpmbuild/BUILD/sqlcipher-4.5.1/test/fuzzdata1.db /home/tkloczko/rpmbuild/BUILD/sqlcipher-4.5.1/test/fuzzdata2.db /home/tkloczko/rpmbuild/BUILD/sqlcipher-4.5.1/test/fuzzdata3.db /home/tkloczko/rpmbuild/BUILD/sqlcipher-4.5.1/test/fuzzdata4.db /home/tkloczko/rpmbuild/BUILD/sqlcipher-4.5.1/test/fuzzdata5.db /home/tkloczko/rpmbuild/BUILD/sqlcipher-4.5.1/test/fuzzdata6.db /home/tkloczko/rpmbuild/BUILD/sqlcipher-4.5.1/test/fuzzdata7.db /home/tkloczko/rpmbuild/BUILD/sqlcipher-4.5.1/test/fuzzdata8.db
fuzzdata1.db: SQL fuzz
fuzzdata1.db: 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% - 9916 tests
fuzzdata2.db: SQL tests from Michal Zalewski on 2015-05-01
fuzzdata2.db: 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% - 9959 tests
fuzzdata3.db: Database fuzz as of 2015-06-24
fuzzdata3.db: 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% - 2316 tests
fuzzdata4.db: JSON1 test cases as of 2015-09-23
fuzzdata4.db: 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% - 2575 tests
fuzzdata5.db: Test cases received from the OSS-FUZZ project
fuzzdata5.db: 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% - 8834 tests
fuzzdata6.db: Test cases for UPSERT
fuzzdata6.db: 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% - 3896 tests
fuzzdata7.db: DB cases created using dbfuzz2
fuzzdata7.db: 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% - 8145 tests
fuzzdata8.db: 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% - 530 tests
fuzzcheck: 0 errors out of 46171 tests in 11.612 seconds
SQLite 3.37.2 2022-01-06 13:25:41 872ba256cbf61d9290b571c0e6d82a20c224ca3ad82971edc46b29818d5dalt1
./sessionfuzz run /home/tkloczko/rpmbuild/BUILD/sqlcipher-4.5.1/test/sessionfuzz-data1.db
sessionfuzz-data1.db:  339 cases, 0 crashes
./srcck1 sqlite3.c
/usr/bin/gcc   sqlite3.o   -o sqlite3
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/12/../../../../lib64/crt1.o: in function `_start':
(.text+0x1b): undefined reference to `main'
collect2: error: ld returned 1 exit status
make: *** [<builtin>: sqlite3] Error 1
[tkloczko@devel-g2v sqlcipher-4.5.1]$
```

**Comment by kloczek** [comment]
Is it any problem to put all that procedure in test suite build procedure? 🤔 
Just asking ..

**Comment by R4N** [comment]
@kloczek 

>Is it any problem to put all that procedure in test suite build procedure? 🤔
Just asking ..

Yes, as linked in the documentation above:

>In some cases encryption interferes with low-level tests that require access to database file data or features which are unsupported by SQLCipher. Those tests that are intended to support encryption are intended for non-SQLCipher implementations. In addition, because SQLite tests are not always isolated, if one test fails it can trigger a domino effect with other failures in later steps.

**Comment by kloczek** [comment]
So what is the pronblem to add that database file in git repo as resource used by test suite? 🤔

**Comment by sjlombardo** [comment]
@kloczek just to close the loop on this, the problem isn't that there is a missing database. All the databases necessary to make the SQLCipher test suite run are included in the git repo already. The problem is that the "standard" SQLite tests don't expect databases to be encrypted using SQLCipher. This is just the way it is, because SQLCipher is not upstreamed into SQLite and never will be. As a result, you can only run the subset of SQLCipher tests according to the documentation. Because of this baseline limitation we have not made adjustments to the test target in the Makefile, to minimize the diff against the upstream sources (as is consistent with our general policy of minimizing source level differences that could introduce merge conflicts whenever possible).
