### ISSUE TITLE
Garbage files after uninstalling application with SQLCipher

### ISSUE THREAD

**Issue by Hazest** [sqlcipher/sqlcipher#433]
### Expected Behavior
Application will uninstall and install without any problem.

### Actual Behavior
Garbage files remain after uninstall application with SQLCipher like **{AFBF9F1A-8EE8-4C77-AF34-C647E37CA0D9}.1.ver0x0000000000000005.db** Application with only SQLite does not cause such problems.

![image](https://user-images.githubusercontent.com/95860477/172313244-0c1a7c5f-1d67-408f-bb4e-cd10fd654112.png)

### Steps to Reproduce
1. Install the app with SQLCipher 
2. Run the app 
3. Uninstall the app

There is nothing you can do with this file other than delete it.
![image](https://user-images.githubusercontent.com/95860477/172313771-4a532f46-4931-45b0-bee4-c5ebf1b167da.png)

SQLCipher version:
4.5.1 community

Our application is WinUI in the newest versions using .NET 6. 
This problem makes it difficult for us to automate our CI/CD and can potentially occur at the customer.

**Comment by sjlombardo** [comment]
Hello @Hazest - It is not clear that this is actually related to SQLCipher. Google searches for the relevant strings like "AFBF9F1A-8EE8-4C77-AF34-C647E37CA0D9" or "cversions.1.db" return thousands of results that are completely unrelated to SQLCipher. SQLCipher would not creating these files itself and the library does not use the windows cache directory. This sounds like a problem with the installer, application, or OS.
