### ISSUE TITLE
My application giving issue of "File not a Database"

### ISSUE THREAD

**Issue by kuldipsomwanshi** [sqlcipher/sqlcipher#438]
I am using SQLCIPHER for encrypted database in my project but previously I was  using the database without encryption, So the problem is I have the database without encryption and trying to use in my project with sqlcipher database connection and tried to execute queries on it the sqlite3_exec function returns error code 26 "File not a Database".

**Comment by kuldipsomwanshi** [comment]
I use the same and its working and all data get copied into encrypted database but database user version not getting copied. Please could you help that how to match the database version for the encrypted database

**Comment by sjlombardo** [comment]
@kuldipsomwanshi you would need to use `PRAGMA user_version` to set the appropriate user version on the new database to the value from the original.
