### ISSUE TITLE
sqlcipher cause crash in macos 13 beta2+

### ISSUE THREAD

**Issue by thiefuniverse** [sqlcipher/sqlcipher#440]
### Expected Behavior
no crash
### Actual Behavior
There is a high probability of appearing crash when use sqlcipher, system malloc  will report heap corruption. I have one minimal test example below which can reproduce problem in MacOS 13 beta2. In MacOS 10 , MacOS 11 and MacOS 12, I can't reproduce it.

### Steps to Reproduce

```
# clone, compile sqlcipher
git clone https://github.com/sqlcipher/sqlcipher
cd sqlcipher
mkdir out
./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC" LDFLAGS="-framework CoreFoundation -framework Security" --with-crypto-lib=commoncrypto --prefix=$PWD/out
make install

```

```
# save as  main.c and save at same direcotry with sqlcipher
#include "sqlite3.h"
#include <string.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <stdio.h>
#include <unistd.h>
#include <pthread.h>

void ensure_ok(sqlite3 *handle, int code)
{
    if (code == SQLITE_OK)
    {
        return;
    }
    printf("ERROR %d %s\n", code, sqlite3_errmsg(handle));
    exit(1);
}

void run(sqlite3 *handle, const char *sql, void (*callback)(sqlite3_stmt *))
{
    sqlite3_stmt *stmt = NULL;
    char *unused = NULL;
    int sql_len = strlen(sql);
    int code = sqlite3_prepare_v2(handle, sql, sql_len, &stmt, &unused);
    ensure_ok(handle, code);
    code = SQLITE_ROW;
    while (code != SQLITE_DONE)
    {
        code = sqlite3_step(stmt);
        if (code != SQLITE_ROW && code != SQLITE_DONE)
        {
            printf("ERROR %d %s\n", code, sqlite3_errmsg(handle));
            exit(1);
        }
        if (callback != NULL)
        {
            callback(stmt);
        }
    }
    code = sqlite3_finalize(stmt);
    ensure_ok(handle, code);
}

void init_db(sqlite3 *handle)
{
    run(handle, "PRAGMA key = '114514'", NULL);
    run(handle, "PRAGMA cipher_compatibility = '3'", NULL);
    run(handle, "PRAGMA busy_timeout = '5000'", NULL);
    run(handle, "PRAGMA journal_mode = 'WAL'", NULL);
}

sqlite3 *open_db()
{
    char path[256] = {0};
    pid_t pid = getpid();
    sprintf(&path, "/tmp/%d", pid);
    mkdir(&path, 0777);
    sprintf(&path, "/tmp/%d/a.db", pid);
    sqlite3 *ret = NULL;
    int code = sqlite3_open(&path, &ret);
    ensure_ok(ret, code);
    init_db(ret);
    return ret;
}

void close_db(sqlite3 *handle)
{
    int code = sqlite3_close(handle);
    ensure_ok(handle, code);
}

int positive_rand(int start, int end)
{
    unsigned int ret = (unsigned int)rand();
    return (ret % (end - start)) + start;
}

void alloc_test()
{
    int count = positive_rand(128, 1024);
    for (int i = 0; i < count; i++)
    {
        int count2 = positive_rand(512, 1024);
        int **ll = malloc(sizeof(int *) * count2);
        for (int j = 0; j < count2; j++)
        {
            int count3 = positive_rand(0, 1024);
            int *l = malloc(sizeof(int) * count3);
            memset(l, i ^ j, count3);
            ll[j] = l;
        }
        for (int j = 0; j < count2; j++)
        {
            free(ll[j]);
        }
        free(ll);
    }
}

void run_thread(void *data)
{
    alloc_test();
    sqlite3 *db = open_db();
    sqlite3_close(db);
}

int main(void)
{
    sqlite3 *db = open_db();
    run(db, "CREATE TABLE student(id INTEGER, name STRING)", NULL);
    close_db(db);
    pthread_t threads[64];
    for (int i = 0; i < 64; i++)
    {
        pthread_create(&threads[i], NULL, run_thread, NULL);
    }
    for (int i = 0; i < 64; i++)
    {
        pthread_join(threads[i], NULL);
    }
    printf("done\n");
    return 0;
}
```

# compile and run demo
```
clang main.c -o demo -L ./sqlcipher/out/lib/ -I ./sqlcipher/out/include/ -lsqlcipher

export MallocScribble=1 # If set, free sets each byte of every released block to the value 0x55. This will make crash easier
export MallocPreScribble=1 # If set, malloc sets each byte of a newly allocated block to the value 0xAA.
./demo # Execute this binaray mulitple times, you will see the crash
```
![image (3)](https://user-images.githubusercontent.com/12184047/180176909-c04b2718-5655-4c6e-98a9-b42ef98eac80.png)

[Enabling the Malloc Debugging Features](https://developer.apple.com/library/archive/documentation/Performance/Conceptual/ManagingMemory/Articles/MallocDebug.html)
# some attempts
## with asan
- Using `-fsanitize=address` compile sqlcipher and demo，couldn't reproduce the crash
## with openssl
- Using openssl rather than commoncrypto as the encryption implementation of sqlcipher，could reproduce the crash.
## without encrypt
- Do not set PRAGMA key encryption options，couldn't reproduce the crash.

If macOS >= 13.0-beta.2 and follow the above steps, we shall reproduce the crash easily.
Looking forward to getting official feedback.

SQLCipher version:
master branch and tag 4.5.1

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by sjlombardo** [comment]
Hello @thiefuniverse - thanks for submitting this very detailed ticket. We were able to reproduce this using the example on 13.0 beta 2. We are looking into the issue further and will post back here with further questions / comments soon.

**Comment by thiefuniverse** [comment]
> 

hi, thanks for your reply. Now we find that using -DOMIT_MEMLOCK macro to avoid invoking mlock,munlock in sqlcipher malloc and sqlcipher free, this problem will be gone. We think it relates with mlock/munlock invoke.We will try to simplify this mini-example.

**Comment by R4N** [comment]
Hi @thiefuniverse - Just wanted to follow up with some additional findings:

Using `-DOMIT_MEMLOCK` seems to still reproduce the issue 3/5 runs (with a separate issue 1/5 runs) for me on 13.0 beta 3:

```
./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC -DOMIT_MEMLOCK" LDFLAGS="-framework CoreFoundation -framework Security" --with-crypto-lib=commoncrypto --prefix=$PWD/out
...
clang main.c -o demo -L ./sqlcipher/out/lib/ -I ./sqlcipher/out/include/ -lsqlcipher
...
export MallocScribble=1
export MallocPreScribble=1
...
./demo
demo(2980,0x7ffb513fa7c0) malloc: enabling scribbling to detect mods to free blocks
demo(2980,0x70000a50e000) malloc: Incorrect checksum for freed object 0x7fc8ba5b9c00: probably modified after being freed.
Corrupt value: 0x5555555555555555
demo(2980,0x70000a50e000) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
./demo
demo(3000,0x7ffb513fa7c0) malloc: enabling scribbling to detect mods to free blocks
demo(3000,0x70000dab9000) malloc: Incorrect checksum for freed object 0x7fb9bcc4ea00: probably modified after being freed.
Corrupt value: 0x5555555555555555
demo(3000,0x70000dab9000) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
./demo
demo(3027,0x7ffb513fa7c0) malloc: enabling scribbling to detect mods to free blocks
demo(3027,0x700006211000) malloc: small_free_list_remove_ptr_no_clear: Internal invariant broken (prev ptr of next) for 0x7fc16ebf1e00, next_prev=0x0
demo(3027,0x700006211000) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
./demo
demo(3052,0x7ffb513fa7c0) malloc: enabling scribbling to detect mods to free blocks
demo(3052,0x70000acfc000) malloc: Incorrect checksum for freed object 0x7fb668971200: probably modified after being freed.
Corrupt value: 0x5555555555555555
demo(3052,0x70000acfc000) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
./demo
demo(3083,0x7ffb513fa7c0) malloc: enabling scribbling to detect mods to free blocks
done
```

Are you doing anything differently when testing with `-DOMIT_MEMLOCK`?

**Comment by thiefuniverse** [comment]
> Hi @thiefuniverse - Just wanted to follow up with some additional findings:
> 
> Using `-DOMIT_MEMLOCK` seems to still reproduce the issue 3/5 runs (with a separate issue 1/5 runs) for me on 13.0 beta 3:
> 
> ```
> ./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC -DOMIT_MEMLOCK" LDFLAGS="-framework CoreFoundation -framework Security" --with-crypto-lib=commoncrypto --prefix=$PWD/out
> ...
> clang main.c -o demo -L ./sqlcipher/out/lib/ -I ./sqlcipher/out/include/ -lsqlcipher
> ...
> export MallocScribble=1
> export MallocPreScribble=1
> ...
> ./demo
> demo(2980,0x7ffb513fa7c0) malloc: enabling scribbling to detect mods to free blocks
> demo(2980,0x70000a50e000) malloc: Incorrect checksum for freed object 0x7fc8ba5b9c00: probably modified after being freed.
> Corrupt value: 0x5555555555555555
> demo(2980,0x70000a50e000) malloc: *** set a breakpoint in malloc_error_break to debug
> Abort trap: 6
> ./demo
> demo(3000,0x7ffb513fa7c0) malloc: enabling scribbling to detect mods to free blocks
> demo(3000,0x70000dab9000) malloc: Incorrect checksum for freed object 0x7fb9bcc4ea00: probably modified after being freed.
> Corrupt value: 0x5555555555555555
> demo(3000,0x70000dab9000) malloc: *** set a breakpoint in malloc_error_break to debug
> Abort trap: 6
> ./demo
> demo(3027,0x7ffb513fa7c0) malloc: enabling scribbling to detect mods to free blocks
> demo(3027,0x700006211000) malloc: small_free_list_remove_ptr_no_clear: Internal invariant broken (prev ptr of next) for 0x7fc16ebf1e00, next_prev=0x0
> demo(3027,0x700006211000) malloc: *** set a breakpoint in malloc_error_break to debug
> Abort trap: 6
> ./demo
> demo(3052,0x7ffb513fa7c0) malloc: enabling scribbling to detect mods to free blocks
> demo(3052,0x70000acfc000) malloc: Incorrect checksum for freed object 0x7fb668971200: probably modified after being freed.
> Corrupt value: 0x5555555555555555
> demo(3052,0x70000acfc000) malloc: *** set a breakpoint in malloc_error_break to debug
> Abort trap: 6
> ./demo
> demo(3083,0x7ffb513fa7c0) malloc: enabling scribbling to detect mods to free blocks
> done
> ```
> 
> Are you doing anything differently when testing with `-DOMIT_MEMLOCK`?

Now we have committed this issue to apple, simple example below can also reproduce this problem.  I think my compilation options is same with yours, just for removing mlock/munlock invoke.
```
// clang mlock_test.c -o mlock_test 
#include <pthread.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
void _mlock(void* ptr, uint64_t sz) {
  if (ptr == NULL || sz == 0)
    return;
  unsigned long offset = (unsigned long)ptr % sysconf(_SC_PAGESIZE);
  mlock(ptr - offset, sz + offset);
}
void _munlock(void* ptr, uint64_t sz) {
  if (ptr == NULL || sz == 0)
    return;
  unsigned long offset = (unsigned long)ptr % sysconf(_SC_PAGESIZE);
  munlock(ptr - offset, sz + offset);
}
void thread_func(void* data) {
  typedef unsigned char T;
  int count1 = 1024;
  int count2 = 1024;
  int count3 = 1024;
  for (int i = 0; i < count1; ++i) {
    T** ll = malloc(sizeof(T*) * count2);
    _mlock(ll, sizeof(T*) * count2);
    for (int j = 0; j < count2; ++j) {
      T* l = malloc(sizeof(T) * count3);
      memset(l, 0xFE, count3);
      ll[j] = l;
    }
    for (int j = 0; j < count2; ++j) {
      free(ll[j]);
    }
    _munlock(ll, sizeof(T*) * count2);
    free(ll);
  }
}
int main() {
  int count = 128;
  pthread_t threads[count];
  for (int i = 0; i < count; i++) {
    pthread_create(&threads[i], NULL, thread_func, NULL);
  }
  for (int i = 0; i < count; i++) {
    pthread_join(threads[i], NULL);
  }
  printf("done\n");
  return 0;
}
```

**Comment by R4N** [comment]
@thiefuniverse 

Thanks for updating us on your latest results. If you happen to have an open radar/link to the bug report to Apple, it would be great if you could post it here for reference. Thanks!

**Comment by thiefuniverse** [comment]
> @thiefuniverse
> 
> Thanks for updating us on your latest results. If you happen to have an open radar/link to the bug report to Apple, it would be great if you could post it here for reference. Thanks!

we submitted one feedback to apple and we got a response that this problem may be fixed in macOS 13 beta5， we can wait and check it.

**Comment by thiefuniverse** [comment]
Hi, we have checked that  this issue has been fixed in macOS 13 beta6.

**Comment by aprilandjan** [comment]
> Hi, we have checked that this issue has been fixed in macOS 13 beta6.

Yeah we've tested that this issue is gone only when compiled with `-DOMIT_MEMLOCK`.
