### ISSUE TITLE
Deleting performance is too slow  

### ISSUE THREAD

**Issue by cccccc-cccc** [sqlcipher/sqlcipher#443]
When I use SQLcipher and execute 'delete' to delete 30000 rows, the performance becomes slower.'    Update 30000 rows 'only takes 900 milliseconds  .    When I don't use SQLcipher, it only takes 1300 milliseconds to delete 30000 rows, and it takes 4500 milliseconds to delete 30000 rows using SQLcipher

SQLCipher version:

* note: * if you do not release specific questions about SQLCipher libraries, please consider your question posted to SQLCipher discussion website (https://discuss.zetetic.net/c/sqlcipher).    Thank you very much!

**Comment by developernotes** [comment]
Hello @cccccc-cccc

Thanks for your interest in SQLCipher. We reserve GitHub Issues for tracking defects within the software library itself. This particular question should be posted to the [SQLCipher Community Discuss site](https://discuss.zetetic.net/c/sqlcipher), please consider reposting there instead. Thanks!
