### ISSUE TITLE
Time taken for Query execution with sqlcipher is more than sqlite3

### ISSUE THREAD

**Issue by kuldipsomwanshi** [sqlcipher/sqlcipher#444]
I observed in my application that the time taken for query execution is much more in SqlCipher encrypted database.
There is much difference in select queries too. Please could you help why there is too much overhead using sqlcipher.

**Comment by billymeltdown** [comment]
Hi @kuldipsomwanshi,

We have information on performance speed and optimization here:
https://www.zetetic.net/sqlcipher/performance/

And some information about how SQLCipher compares here:
https://discuss.zetetic.net/t/how-does-sqlcipher-compare-to-other-sqlite-encryption-extensions/2864

If you have further questions, please post them to the discussion forum; the Github Issues tracker for the SQLCipher project is used for tracking bugs. Thanks!
