### ISSUE TITLE
ERROR /bin/sh^M: bad interpreter

### ISSUE THREAD

**Issue by peterlaw108** [sqlcipher/sqlcipher#447]
Hi,

When i install it, the MAC terminal says "/bin/bash: ./configure: /bin/sh^M: bad interpreter: No such file or directory" in 4.5.2 version, please help to fix. thanks.

Peter

**Comment by peterlaw108** [comment]
Thanks for your reply.
But my Mac OS version is 12.5.1 and the Xcode version is 13.4.1. Itwill show this error, please help, thank you so much.

peter

**Comment by developernotes** [comment]
Hi @peterlaw108 

I have just verified the SQLCipher source compiles properly with Xcode 13.4.1 and macOS 12.5.1. As @sjlombardo mentioned, the issue you are facing is likely environmental. A few options to try:

1. Compile a standalone C program from the command line without referencing SQLCipher
2. Delete and clone again the SQLCipher source tree

For the first item, the following program should be sufficient:

```
#include <stdio.h>

int main (){
  printf("Hello from C!\n");
  return 0;
}
```

With the content saved to a file named `test.c`, you could compile that via `make test`.

**Comment by peterlaw108** [comment]
Hello @sjlombardo,

  I tried. But not work, same error shows. please please help!! 

  Thanks.

Peter

**Comment by peterlaw108** [comment]
Hi @sjlombardo ,

  Finally i found a solution and it works again. Thanks a lot.

Peter
