### ISSUE TITLE
Massive size increase when using LibSqlCypher in Android Build

### ISSUE THREAD

**Issue by HeinrichGlover** [sqlcipher/sqlcipher#449]
### Steps to Reproduce : Create an Android project with SqlLite Tables, Columns and Data. Build the Project. Take the size of the output .apk. Add ref to LibSqlCypher. Build the project and see the size difference.

SQLCipher version: Can see the actual version which is in the 3rd party lib. But add and remove the lib with reflection inspection point the problem.

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

<img width="710" alt="Screenshot 2022-09-23 at 15 56 42" src="https://user-images.githubusercontent.com/11226729/192290973-2523a59c-8d5e-4772-b6a0-cceb8ec52fee.png">

**Comment by developernotes** [comment]
Hi @HeinrichGlover 

Both the new and legacy version of SQLCipher for Android support native targets of `armeabi-v7a`, `arm64-v8a`, `x86`, and `x86_64` which are common CPU architectures on various Android devices. If you wish to decrease your deployment size there are a few options: You can create multiple APK's using Gradle build variants, or `abiFilters` to limit the CPU support you wish to bundle within an APK. Using reflection would not be beneficial as that occurs at runtime on the device, after the application installed.

We reserve GitHub Issues for tracking defects within the software library itself. This particular discussion should be posted to the [SQLCipher Community Discuss site](https://discuss.zetetic.net/c/sqlcipher), please consider reposting there instead. Thanks!
