### ISSUE TITLE
Pod SQLCipher (v4.5.2) doesn't install properly

### ISSUE THREAD

**Issue by jduarter** [sqlcipher/sqlcipher#451]
Can anyone confirm `pod install` is currently working with Xcode 14  tools at Monterey (Mac OS X 12.5)?

I also tried to compile the raw source from scratch with the same result...

I would like to build the `arm64` target (static lib)

I have the same result with the original `sqlite` package as  its current version.

### Expected Behavior

Success configuring the build, building and installing the pod.

### Actual Behavior

```
Installing SQLCipher (4.5.2)
[!] /bin/bash -c 
set -e
./configure --enable-tempstore=yes --with-crypto-lib=commoncrypto CFLAGS="-DSQLITE_HAS_CODEC -DSQLITE_TEMP_STORE=2 -DSQLITE_SOUNDEX -DSQLITE_THREADSAFE -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_STAT3 -DSQLITE_ENABLE_STAT4 -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_MEMORY_MANAGEMENT -DSQLITE_ENABLE_LOAD_EXTENSION -DSQLITE_ENABLE_UNLOCK_NOTIFY -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS4_UNICODE61 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_FTS5 -DHAVE_USLEEP=1 -DSQLITE_MAX_VARIABLE_NUMBER=99999"; make sqlite3.c

checking build system type... x86_64-apple-darwin21.6.0
checking host system type... x86_64-apple-darwin21.6.0
checking how to print strings... printf
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/Users/w/Library/Caches/CocoaPods/Pods/Release/SQLCipher/4.5.2-f5b48':
configure: error: C compiler cannot create executables
See `config.log' for more details

```

### Steps to Reproduce

1) add `SQLCipher` pod to `Podfile`
2) run `pod install`

SQLCipher version: `4.5.2`

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by sjlombardo** [comment]
this is likely an environmental problem. what is the contents of `config.log`

**Comment by jduarter** [comment]
This is the issue while trying to compile automatically & manually with 
```
./configure --host=arm-apple-darwin --verbose --with-crypto-lib=none
```

Log:

```
In file included from conftest.c:12:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.0.sdk/usr/include/assert.h:42:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.0.sdk/usr/include/sys/cdefs.h:901:2: error: Unsupported architecture
#error Unsupported architecture
 ^
1 error generated.
configure:6722: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "sqlcipher"
| #define PACKAGE_TARNAME "sqlcipher"
| #define PACKAGE_VERSION "3.39.2"
| #define PACKAGE_STRING "sqlcipher 3.39.2"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| #ifdef __STDC__
| # include <limits.h>
| #else
| # include <assert.h>
| #endif
| 		     Syntax error
configure:6722: gcc -E -traditional-cpp -I/Users/user/PROJECTS/build_openssl/arm64/include conftest.c
```

I can also post the full config.log if needed. Can anyone confirm it's working on the environment (Xcode version, etc) I describe?

I was trying another SQLCipher distribution bundled in a Xcode project, and it worked, so, very likely, the problem is on the environment. Maybe the configure script should be updated? or I might be missing any flags/parameters to pass to the configure script...

I couldn't spend more time on this but I will compare the working distribution scripts to see the differences as soon as I can.

**Comment by sjlombardo** [comment]
I have verified that pod installation works for me. No other users have reported this. Can you provide a standalone project that reproduces this issue?

**Comment by tritter** [comment]
@sjlombardo definitely a problem, I also have it now. But I first noticed it after deleting my CocoaPods cache. Before it always worked that will prob happen with more people after some time... @jduarter did you find a solution?

I think it has to do with the host being arm and the simulator still being used in x86?

**Comment by tritter** [comment]
Ok I found the issue! Just reinstalled Xcode and everything works fine again. This seems to be a macOS/ENV variable problem... really annoying. Also for example ruby-build gave the same weird error...

**Comment by AS0820075980** [comment]
Chaiwat oppo A16

ในวันที่ พฤ. 23 มี.ค. 2023 23:53 น. Thom Ritterfeld <
***@***.***> เขียนว่า:
