### ISSUE TITLE
cipher_memory_security default status

### ISSUE THREAD

**Issue by Jeevhi** [sqlcipher/sqlcipher#452]
Is cipher_memory_security enabled by default in the latest release?

As per the documentation, it is enabled by default. However, as I see from the code, `sqlcipher_mem_security_on` is zero and never set unless pragma is used.

Thanks

**Comment by developernotes** [comment]
Hi @Jeevhi,

SQCipher 4.5.2, the latest release, has `cipher_memory_security` disabled by default. This change was introduced in SQLCipher 4.5.0 [^1].

[^1]: https://www.zetetic.net/blog/2021/10/28/sqlcipher-4.5.0-release/

**Comment by developernotes** [comment]
Hi @Jeevhi,

We will correct the documentation, thank you for reporting that!

**Comment by developernotes** [comment]
Hi @Jeevhi,

The documentation has been updated here: [^1].

[^1]: https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_memory_security
