### ISSUE TITLE
Installing SQLcipher using APT adds incorrect header file

### ISSUE THREAD

**Issue by mjovanc** [sqlcipher/sqlcipher#458]
### Expected Behavior

Expect to use `sqlite3_key()` function, but this is not possible. 

### Actual Behavior

Currently `sqlite3.h` is not the one of SQLcipher. I cannot use the prototype of `sqlite3_key()` in my C program. 

 Gives output: `Call to undeclared function 'sqlite3_key'; ISO C99 and later do not support implicit function declarations`

### Steps to Reproduce

1. sudo apt-get install sqlcipher libsqlcipher-dev
2. Import header file `#include <sqlcipher/sqlite3.h>`
3. Use `sqlite3_key()`

Current code:

```
sqlite3 *db;
int rc;

rc = sqlite3_open(full_db_name, &db);
if (rc != SQLITE_OK)
{
    fprintf(stderr, "Can't open database: %s\n", sqlite3_errmsg(db));
    return 1;
}
else
{
    printf("Opened database successfully\n");
}

sqlite3_key(sqlite3 *db, const void *pKey, int nKey);

// closing to save the database to file system
sqlite3_close(db);
```

SQLCipher version:

3.15.2 2016-11-28 19:13:37 bbd85d235f7037c6a033a9690534391ffeacecc8

**Comment by developernotes** [comment]
Hi @mjovanc,

When building SQLCipher, you must define `SQLITE_HAS_CODEC` along with `SQLITE_TEMP_STORE` in your `CFLAGS`. More information can be found here [^1].

[^1]: https://www.zetetic.net/sqlcipher/introduction/

**Comment by mjovanc** [comment]
So basically if I understand you correctly, I can not use a pre-compiled _shared_ SQLcipher library using the package manager?

**Comment by developernotes** [comment]
Hi @mjovanc 

The issue is not with the compiled shared library, if you were to run `strings` against the compiled library, you would see the `sqlite3_key` symbol in the output. The issue is trying to access `sqlite3_key` which is defined in `sqlite3.h`, but requires `SQLITE_HAS_CODEC` to make it available.

**Comment by mjovanc** [comment]
Yes I tried putting that C FLAG, but the header file is missing anything regarding SQLcipher itself like it exists in: https://github.com/sqlcipher/sqlcipher/blob/master/src/sqlite.h.in#L6083 for example.

The content of Sqlite3.h that I got from installing Sqlcipher through the package manager does not have any data about SQLcipher in the header file so I'm guessing the file of only the regular Sqlite3?

**Comment by developernotes** [comment]
Hi @mjovanc 

Zetetic is not the maintainer of the SQLCipher package on APT. Do you know how the package was assembled for APT distribution? I suspect the author did not specify `SQLITE_HAS_CODEC` when preparing it.

**Comment by mjovanc** [comment]
@developernotes Aha, that probably explains it. Perhaps I should include Sqlcipher in my build system to ensure it always works and gets installed correctly. Thanks for the help!
