### ISSUE TITLE
Sqlcipher failing to compile on Windows 10

### ISSUE THREAD

**Issue by Scylla2020** [sqlcipher/sqlcipher#459]
### Expected Behavior
Should be able to compile on Windows 10

### Actual Behavior
I got an error on installation after following all steps:
```
C:\Users\TestUser\sqlcipher>nmake /f Makefile.msc

Microsoft (R) Program Maintenance Utility Version 14.28.29336.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        cl -nologo -W4 -DINCLUDE_MSVC_H=1   -DSQLITE_OS_WIN=1 -I. -I. -I.\src -fp:precise -MT -DNDEBUG -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -DSQLITE_THREADSAFE=1 -DSQLITE_THREAD_OVERRIDE_LOCK=-1 -DSQLITE_TEMP_STORE=2 -DSQLITE_HAS_CODEC -IC:\ScyllaXX\OpenSSL-Win64\include  -DSQLITE_MAX_TRIGGER_DEPTH=100  -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_GEOPOLY=1 -DSQLITE_ENABLE_STMTVTAB=1 -DSQLITE_ENABLE_DBPAGE_VTAB=1 -DSQLITE_ENABLE_DBSTAT_VTAB=1 -DSQLITE_ENABLE_BYTECODE_VTAB=1 -DSQLITE_ENABLE_COLUMN_METADATA=1 -DSQLITE_ENABLE_MATH_FUNCTIONS   -O2 -Zi -Fosqlite3.lo -Fdsqlite3.pdb  -c sqlite3.c
sqlite3.c
sqlite3.c(21681): error C2065: 'OP_Ne': undeclared identifier
sqlite3.c(21681): error C2099: initializer is not a constant
sqlite3.c(21682): error C2065: 'OP_Ne': undeclared identifier
sqlite3.c(21682): error C2099: initializer is not a constant
sqlite3.c(21683): error C2065: 'OP_Ne': undeclared identifier
sqlite3.c(21683): error C2099: initializer is not a constant
sqlite3.c(21964): error C2065: 'OPFLG_INITIALIZER': undeclared identifier
...
sqlite3.c(90115): error C2065: 'OP_BitOr': undeclared identifier
sqlite3.c(90123): error C2065: 'OP_ShiftLeft': undeclared identifier
sqlite3.c(90128): error C2065: 'OP_ShiftLeft': undeclared identifier
sqlite3.c(90131): error C2065: 'OP_ShiftLeft': undeclared identifier
sqlite3.c(90154): error C2065: 'OP_AddImm': undeclared identifier
sqlite3.c(90169): error C2065: 'OP_MustBeInt': undeclared identifier
sqlite3.c(90198): error C2065: 'OP_RealAffinity': undeclared identifier
sqlite3.c(90226): error C2065: 'OP_Cast': undeclared identifier
sqlite3.c(90226): fatal error C1003: error count exceeds 100; stopping compilation
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\cl.EXE"' : return code '0x2'
Stop.
```

### Steps to Reproduce
I followed these steps [https://github.com/sqlitebrowser/sqlitebrowser/wiki/Win64-setup-%E2%80%94-Compiling-SQLCipher](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Win64-setup-%E2%80%94-Compiling-SQLCipher)

SQLCipher version:
Not sure what version this is. I just cloned this from the github today

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by sjlombardo** [comment]
Hello @Scylla2020 - thanks for getting in touch. We don't provide any specific documentation on compiling SQLCipher for Windows, due to the huge variation in environments, toolchains, etc. As such, we can't really comment on this. It looks like those instructions came from the sqlitebrowser project. I would therefore recommend opening up an issue there to see if they might be able to assist.

**Comment by xaoyaoo** [comment]
I have also encountered the same problem. How should I solve this?

**Comment by aakash-sahai** [comment]
I get similar error when compiling on Windows 10 using MSVC/Visual Studio 2022. Here is the cl command line and the exact errors I get:

` cl -nologo -W4 -DINCLUDE_MSVC_H=1   -DSQLITE_OS_WIN=1 -I. -Ic:\repos\sqlcipher -Ic:\repos\sqlcipher\src -fp:precise -MT -DNDEBUG -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -DSQLITE_THREADSAFE=1 -DSQLITE_THREAD_OVERRIDE_LOCK=-1 -DSQLITE_TEMP_STORE=2 -DSQLITE_HAS_CODEC -I"C:\Program Files\OpenSSL-Win64\include"  -DSQLITE_MAX_TRIGGER_DEPTH=100  -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_FTS5=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_GEOPOLY=1 -DSQLITE_ENABLE_STMTVTAB=1 -DSQLITE_ENABLE_DBPAGE_VTAB=1 -DSQLITE_ENABLE_DBSTAT_VTAB=1 -DSQLITE_ENABLE_BYTECODE_VTAB=1 -DSQLITE_ENABLE_COLUMN_METADATA=1 -DSQLITE_ENABLE_MATH_FUNCTIONS   -O2 -Zi -Fosqlite3.lo -Fdsqlite3.pdb  -c sqlite3.c
sqlite3.c
sqlite3.c(22449): error C2065: 'OP_Ne': undeclared identifier
sqlite3.c(22449): error C2099: initializer is not a constant
sqlite3.c(22450): error C2065: 'OP_Ne': undeclared identifier
sqlite3.c(22450): error C2099: initializer is not a constant
sqlite3.c(22451): error C2065: 'OP_Ne': undeclared identifier
sqlite3.c(22451): error C2099: initializer is not a constant
sqlite3.c(22733): error C2065: 'OPFLG_INITIALIZER': undeclared identifier
sqlite3.c(22733): error C2099: initializer is not a constant
sqlite3.c(83975): error C2065: 'OP_Init': undeclared identifier
sqlite3.c(84300): error C2065: 'OP_Goto': undeclared identifier
sqlite3.c(84307): error C2065: 'OP_String8': undeclared identifier
sqlite3.c(84329): error C2065: 'OP_Null': undeclared identifier
sqlite3.c(84329): error C2065: 'OP_String8': undeclared identifier
sqlite3.c(84331): error C2065: 'OP_Integer': undeclared identifier
sqlite3.c(84336): error C2065: 'OP_ResultRow': undeclared identifier
sqlite3.c(84395): error C2065: 'OP_PureFunc': undeclared identifier
sqlite3.c(84395): error C2065: 'OP_Function': undeclared identifier
sqlite3.c(84466): error C2065: 'OP_Explain': undeclared identifier
sqlite3.c(84496): error C2065: 'OP_ParseSchema': undeclared identifier
sqlite3.c(84505): error C2065: 'OP_EndCoroutine': undeclared identifier
sqlite3.c(84592): error C2065: 'OP_Expire': undeclared identifier
sqlite3.c(84601): error C2065: 'OP_Expire': undeclared identifier
sqlite3.c(84602): error C2065: 'OP_Noop': undeclared identifier
sqlite3.c(84821): error C2065: 'SQLITE_MX_JUMP_OPCODE': undeclared identifier
sqlite3.c(84825): error C2065: 'OP_Transaction': undeclared identifier
sqlite3.c(84829): error C2065: 'OP_AutoCommit': undeclared identifier
sqlite3.c(84830): error C2065: 'OP_Savepoint': undeclared identifier
sqlite3.c(84835): error C2065: 'OP_Checkpoint': undeclared identifier
sqlite3.c(84837): error C2065: 'OP_Vacuum': undeclared identifier
sqlite3.c(84838): error C2065: 'OP_JournalMode': undeclared identifier
sqlite3.c(84843): error C2065: 'OP_Init': undeclared identifier
sqlite3.c(84848): error C2065: 'OP_VUpdate': undeclared identifier
sqlite3.c(84852): error C2065: 'OP_VFilter': undeclared identifier
sqlite3.c(84825): error C2051: case expression not constant
sqlite3.c(84829): error C2051: case expression not constant
sqlite3.c(84830): error C2051: case expression not constant
sqlite3.c(84835): error C2051: case expression not constant
sqlite3.c(84837): error C2051: case expression not constant
sqlite3.c(84838): error C2051: case expression not constant
sqlite3.c(84843): error C2051: case expression not constant
sqlite3.c(84848): error C2051: case expression not constant
sqlite3.c(84852): error C2051: case expression not constant
sqlite3.c(85080): error C2065: 'OPFLG_JUMP': undeclared identifier
sqlite3.c(85228): error C2065: 'OP_Column': undeclared identifier
sqlite3.c(85386): error C2065: 'OP_Noop': undeclared identifier
sqlite3.c(86245): error C2065: 'OP_OpenRead': undeclared identifier
sqlite3.c(86246): error C2065: 'OP_OpenWrite': undeclared identifier
sqlite3.c(86247): error C2065: 'OP_ReopenIdx': undeclared identifier
sqlite3.c(86252): error C2065: 'OP_Explain': undeclared identifier
sqlite3.c(86253): error C2065: 'OP_Init': undeclared identifier
sqlite3.c(89273): error C2065: 'OP_PureFunc': undeclared identifier
sqlite3.c(93178): error C2065: 'OP_Goto': undeclared identifier
sqlite3.c(93234): error C2065: 'OP_Gosub': undeclared identifier
sqlite3.c(93267): error C2065: 'OP_Return': undeclared identifier
sqlite3.c(93289): error C2065: 'OP_InitCoroutine': undeclared identifier
sqlite3.c(93316): error C2065: 'OP_EndCoroutine': undeclared identifier
sqlite3.c(93342): error C2065: 'OP_Yield': undeclared identifier
sqlite3.c(93362): error C2065: 'OP_HaltIfNull': undeclared identifier
sqlite3.c(93402): error C2065: 'OP_Halt': undeclared identifier
sqlite3.c(93473): error C2065: 'OP_Integer': undeclared identifier
sqlite3.c(93485): error C2065: 'OP_Int64': undeclared identifier
sqlite3.c(93499): error C2065: 'OP_Real': undeclared identifier
sqlite3.c(93516): error C2065: 'OP_String8': undeclared identifier
sqlite3.c(93542): error C2065: 'OP_String': undeclared identifier
sqlite3.c(93560): error C2065: 'OP_String': undeclared identifier
sqlite3.c(93613): error C2065: 'OP_BeginSubrtn': undeclared identifier
sqlite3.c(93614): error C2065: 'OP_Null': undeclared identifier
sqlite3.c(93644): error C2065: 'OP_SoftNull': undeclared identifier
sqlite3.c(93658): error C2065: 'OP_Blob': undeclared identifier
sqlite3.c(93680): error C2065: 'OP_Variable': undeclared identifier
sqlite3.c(93707): error C2065: 'OP_Move': undeclared identifier
sqlite3.c(93757): error C2065: 'OP_Copy': undeclared identifier
sqlite3.c(93795): error C2065: 'OP_SCopy': undeclared identifier
sqlite3.c(93815): error C2065: 'OP_IntCopy': undeclared identifier
sqlite3.c(93834): error C2065: 'OP_FkCheck': undeclared identifier
sqlite3.c(93850): error C2065: 'OP_ResultRow': undeclared identifier
sqlite3.c(93895): error C2065: 'OP_Concat': undeclared identifier
sqlite3.c(93991): error C2065: 'OP_Add': undeclared identifier
sqlite3.c(93992): error C2065: 'OP_Subtract': undeclared identifier
sqlite3.c(93993): error C2065: 'OP_Multiply': undeclared identifier
sqlite3.c(93994): error C2065: 'OP_Divide': undeclared identifier
sqlite3.c(93995): error C2065: 'OP_Remainder': undeclared identifier
sqlite3.c(94013): error C2065: 'OP_Add': undeclared identifier
sqlite3.c(94014): error C2065: 'OP_Subtract': undeclared identifier
sqlite3.c(94015): error C2065: 'OP_Multiply': undeclared identifier
sqlite3.c(94016): error C2065: 'OP_Divide': undeclared identifier
sqlite3.c(94041): error C2065: 'OP_Add': undeclared identifier
sqlite3.c(94042): error C2065: 'OP_Subtract': undeclared identifier
sqlite3.c(94043): error C2065: 'OP_Multiply': undeclared identifier
sqlite3.c(94044): error C2065: 'OP_Divide': undeclared identifier
sqlite3.c(94092): error C2065: 'OP_CollSeq': undeclared identifier
sqlite3.c(94130): error C2065: 'OP_BitAnd': undeclared identifier
sqlite3.c(94131): error C2065: 'OP_BitOr': undeclared identifier
sqlite3.c(94132): error C2065: 'OP_ShiftLeft': undeclared identifier
sqlite3.c(94133): error C2065: 'OP_ShiftRight': undeclared identifier
sqlite3.c(94149): error C2065: 'OP_BitAnd': undeclared identifier
sqlite3.c(94151): error C2065: 'OP_BitOr': undeclared identifier
sqlite3.c(94159): error C2065: 'OP_ShiftLeft': undeclared identifier
sqlite3.c(94164): error C2065: 'OP_ShiftLeft': undeclared identifier
sqlite3.c(94167): error C2065: 'OP_ShiftLeft': undeclared identifier
sqlite3.c(94190): error C2065: 'OP_AddImm': undeclared identifier
sqlite3.c(94190): fatal error C1003: error count exceeds 100; stopping compilation`

**Comment by xaoyaoo** [comment]
Open in Visual Studio 2022, save as, and set the encoding to Unicode.
This may solve your problem.
