### ISSUE TITLE
net.sqlcipher.database.SQLiteException: variable number must be between ?1 and ?999 

### ISSUE THREAD

**Issue by bigmickyg** [sqlcipher/sqlcipher#46]
Hello,

In our app we have the primary key value of user-created rows in a particular table set to relatively high integer values (100000 and above). 

When running a query against this table using rawQuery(whereClause, whereArgs), the argument value in the whereArgs parameter is set to a correspondingly high value. 

As a resut the following exception is generated:

02-27 13:35:01.819: E/AndroidRuntime(14175): FATAL EXCEPTION: main
02-27 13:35:01.819: E/AndroidRuntime(14175): net.sqlcipher.database.SQLiteException: variable number must be between ?1 and ?999: , while compiling: <query>

We are running SQLCipher 2.1.1

Here is the relevant part of the stacktrace. 

02-27 13:35:01.819: E/AndroidRuntime(14175):    at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
02-27 13:35:01.819: E/AndroidRuntime(14175):    at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
02-27 13:35:01.819: E/AndroidRuntime(14175):    at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
02-27 13:35:01.819: E/AndroidRuntime(14175):    at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:83)
02-27 13:35:01.819: E/AndroidRuntime(14175):    at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:49)
02-27 13:35:01.819: E/AndroidRuntime(14175):    at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:42)
02-27 13:35:01.819: E/AndroidRuntime(14175):    at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1449)
02-27 13:35:01.819: E/AndroidRuntime(14175):    at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1418)

Regards,

Michael

**Comment by student-like** [comment]
The answer from cuijianzhi actually worked for me haha, first I was trying to query my data using:

`Cursor cursor = db.rawQuery("SELECT " + choice + " FROM consumption WHERE day = ?" dayTime ,null);`

where dayTime (is a String) was something like "03052016". Like bigmickyg i got the error "variable number must be between ?1 and ?999". Now after creating a new String or whatever new String[] { dayTime } is doing, it finally worked :dancer: 

`Cursor cursor = db.rawQuery("SELECT " + choice + " FROM consumption WHERE day = ?",new String[] { dayTime } ,null);`
