### ISSUE TITLE
Unable to build for Android

### ISSUE THREAD

**Issue by JinYi-Tsinghua** [sqlcipher/sqlcipher#460]
The following Bourne script should cross-compile OpenSSL and SQLCipher on any *nix system that is set up for building for Android (ie, it has ANDROID_NDK_HOME correctly set, among perhaps other things). I use linux.

After successfully cross-compiling OpenSSL, it fails to build SQLCipher. The following error is given (I truncated it from config.log) when any architecture other than android-x86_64 is specified. Notably it fails because it is trying to link to the architecture of the compiling system and not the architecture specified by --host. For testing purposes, the same result can be had by also setting --target and --build to the same as --host. No change.

> configure:2878: checking whether the C compiler works
> configure:2900: clang -DSQLITE_HAS_CODEC  ../openssl/libcrypto_1_1.so conftest.c  >&5
> ld: error: ../openssl/libcrypto_1_1.so is incompatible with elf64-x86-64
> clang-12: error: linker command failed with exit code 1 (use -v to see invocation)

Possibly the root cause is in file "configure" at the block starting at line 5748. There should perhaps be some lines in that block to specify link type for the Android architectures?

The bourne script for reproducing the issue is as follows:

`
#!/bin/sh

ANDROID_API=21
ARCHITECTURE=$1
SQLCIPHER_ARCH=""

case $ARCHITECTURE in
	"android-arm64")
	SQLCIPHER_ARCH="aarch64-linux-android"
	;;
        "android-arm")
        SQLCIPHER_ARCH="arm-linux-androideabi"
        ;;
        "android-x86")
        SQLCIPHER_ARCH="i686-linux-android"
        ;;
        "android-x86_64")
        SQLCIPHER_ARCH="x86_64-linux-android"
        ;;
	*)
	echo "Error: Invalid architecture specified. Valid architectures are: android-arm64, android-arm, android-x86, android-x86_64"
	exit 1
	;;
esac

export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/:$PATH
export CC=clang

rm -rf openssl &&
git clone -b OpenSSL_1_1_1-stable --depth=1 https://github.com/openssl/openssl.git &&
cd openssl &&

./Configure ${ARCHITECTURE} -D__ANDROID_API__=$ANDROID_API zlib-dynamic shared no-ssl3 no-dso no-weak-ssl-ciphers no-dtls no-comp no-tests no-external-tests no-fuzz-libfuzzer no-fuzz-afl &&

make -j8 SHLIB_VERSION_NUMBER= SHLIB_EXT=_1_1.so build_libs &&

cd ..

rm -rf sqlcipher &&
git clone -b v4.5.2 --depth=1 https://github.com/sqlcipher/sqlcipher.git &&
cd sqlcipher &&

./configure --host=${SQLCIPHER_ARCH} --enable-static=no LDFLAGS=../openssl/libcrypto_1_1.so CFLAGS=-DSQLITE_HAS_CODEC --enable-tempstore=yes --with-crypto-lib=openssl &&

make -j8
`

**Comment by developernotes** [comment]
Hi @JinYi-Tsinghua,

Both [SQLCipher for Android](https://github.com/sqlcipher/sqlcipher-android#building) and [SQLCipher for Android (legacy edition)](https://github.com/sqlcipher/sqlcipher-android#building) provide instructions for building library packages. Your post above suggests you may be preparing a separate build script and are facing issues. 

Based on the linking error message, I suspect your build in creating an OpenSSL artifact that is not targeting the Android architecture. We reserve GitHub Issues for tracking defects within the software library itself. This particular question should be posted to the [SQLCipher Community Discuss site](https://discuss.zetetic.net/c/sqlcipher), please consider reposting there instead. Thanks!

**Comment by JinYi-Tsinghua** [comment]
That error message can be obtained by running ./<script.sh> android-arm64, ./<script.sh> android-arm, or ./<script.sh> android-x86. (My build system is x86_64 Debian Linux)

Running the script with ./<script.sh> android-arm64, among other files it produces the referenced openssl/libcrypto_1_1.so. Calling 'file', it produces: 
> openssl/libcrypto_1_1.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, not stripped

So, in opposition to your suspicions, OpenSSL is successfully being crosscompiled for Android.
I assure you that this indeed is a bug in the build/linking process of SQLCipher and not a cross-compiling error of another source. The bourne script can indeed reproduce this issue.

**Comment by JinYi-Tsinghua** [comment]
I re-wrote the script to do all the heavy lifting (ie, set up the Android build environment).
If you run this shell script on a linux box, you will see the problem.

Depends: linux, wget, git, unzip

`
#!/bin/sh

ANDROID_API=$1		## Android API version. Recomended 21.
SSL_ARCH=$2		## Choose from android-arm64, android-arm, android-x86, android-x86_64
SQLCIPHER_ARCH=""	## Will be set automatically
static=0		## Set to 1 for static build, 0 for dynamic
proxy_cmd=""

if [ "$ANDROID_NDK_HOME" = "" ]; then
	echo "ANDROID_NDK_HOME is not set. Downloading it and setting it (if not already downloaded)"
	$proxy_cmd wget --quiet -c https://dl.google.com/android/repository/android-ndk-r25b-linux.zip &&
	unzip -q -n android-ndk-r25b-linux.zip &&
	export ANDROID_NDK_HOME=$(pwd)/android-ndk-r25b/
fi

case $SSL_ARCH in
	"android-arm64")
	SQLCIPHER_ARCH="aarch64-linux-android"
	;;
        "android-arm")
        SQLCIPHER_ARCH="arm-linux-androideabi"
        ;;
        "android-x86")
        SQLCIPHER_ARCH="i686-linux-android"
        ;;
        "android-x86_64")
        SQLCIPHER_ARCH="x86_64-linux-android"
        ;;
	*)
	echo "Error: Syntax for this shellscript is ./<script.sh> \$ANDROID_API \$SSL_ARCH. For example: ./script.sh 21 android-arm64"
	echo "Error: Valid architectures are: android-arm64, android-arm, android-x86, android-x86_64"
	exit 1
	;;
esac

export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/:$PATH
export CC=clang

########################### BELOW IS OPENSSL ##########################

rm -rf openssl &&
$proxy_cmd git clone --depth=1 -b OpenSSL_1_1_1-stable https://github.com/openssl/openssl &&
cd openssl &&

if [ "$SSL_ARCH" = "android-arm64" ] || [ "$SSL_ARCH" = "android-x86_64" ]; then
  ./Configure ${SSL_ARCH} -D__ANDROID_API__=$ANDROID_API zlib-dynamic shared no-tests no-external-tests no-fuzz-libfuzzer no-fuzz-afl enable-ec_nistp_64_gcc_128
else
  ./Configure ${SSL_ARCH} -D__ANDROID_API__=$ANDROID_API zlib-dynamic shared no-tests no-external-tests no-fuzz-libfuzzer no-fuzz-afl
fi

make -j8 SHLIB_VERSION_NUMBER= SHLIB_EXT=_1_1.so build_libs &&

########################## BELOW IS SQLCIPHER #########################

cd ..
rm -rf sqlcipher &&
$proxy_cmd git clone --depth=1 -b v4.5.3 https://github.com/sqlcipher/sqlcipher &&
cd sqlcipher &&

if [ $static != 0 ]; then ## Static, to point of link failure
	./configure --host=${SQLCIPHER_ARCH} LDFLAGS=../openssl/libcrypto.a CFLAGS="-DSQLITE_HAS_CODEC -DSQLCIPHER_CRYPTO_OPENSSL" --with-crypto-lib=none --enable-tempstore=yes
else ## Dynamic, to point of link failure
	./configure --host=${SQLCIPHER_ARCH} LDFLAGS=../openssl/libcrypto_1_1.so CFLAGS="-DSQLITE_HAS_CODEC" --enable-tempstore=yes
fi

make -j8
`

**Comment by sjlombardo** [comment]
Before looking into this further as a SQLCipher-specific issue, I would suggest trying to use your script to cross compile the vanilla [SQLite source code](https://sqlite.org/2022/sqlite-src-3390400.zip). If you are successfully able to do so, then we might be able to investigate this further. However, if your cross compilation fails for the upstream sources, then this issue is unrelated to SQLCipher. It's worth noting that cross-compilation questions/issues are frequently reported on the SQLite mailing lists and forums, and one commonly recommended suggestion is to `make sqlite3.c` and then cross-compile the resulting amalgamation.
