### ISSUE TITLE
Out of date license file

### ISSUE THREAD

**Issue by jnotting** [sqlcipher/sqlcipher#463]
### Expected Behavior
It looks like the software license file may be slightly out of date (mainly the copyright years but there could be others) when compared to the one here: https://www.zetetic.net/sqlcipher/license/

### Steps to Reproduce

SQLCipher version:

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by sjlombardo** [comment]
Hello @jnotting - thank you for reporting the discrepancy. The website has been updated with the current copyright years, and the file in the source will be updated to match exactly in the next release.

**Comment by jnotting** [comment]
Thanks @sjlombardo ! Cheers

**Comment by sjlombardo** [comment]
Fixed in release v4.5.4
