### ISSUE TITLE
Can't compile project with pod installed on Xcode 14.3

### ISSUE THREAD

**Issue by b95505017** [sqlcipher/sqlcipher#465]
![截圖 2023-02-26 下午12 46 25](https://user-images.githubusercontent.com/320815/221392849-8dc5de36-51ae-4491-bcf2-2d789cfe12c5.png)

**Comment by nitrag** [comment]
This is an issue in Xcode 14.3 which was released last week. Anyone figure this out?

**Comment by R4N** [comment]
@b95505017 @nitrag 

We haven't been able to reproduce this specific error at all on our end. 

There is an issue in the latest Xcode 14.3 version about the min deployment target. Which produces this type of message when you have use_frameworks! enabled:

```
File not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphonesimulator.a
```



Currently SQLCipher has the following min deployment targets set in the [Podspec:](https://github.com/sqlcipher/sqlcipher/blob/master/SQLCipher.podspec.json#L9)

iOS: 8.0
macOS: 10.9

We're planning on increasing these to the minimum supported by the latest Xcode in the next SQLCipher release:

iOS: 11.0
macOS: 10.13

To temporarily workaround this issue:
* Select the Pods project, then the SQLCipher target
* Set the minimum deployment target to the minimum that Xcode 14.3 supports (iOS 11.0, macOS 10.13).

While I didn't experience any failures to build when I didn't have use_frameworks! enabled, you might want to try to do the same thing with the lib project to see if it helps resolves the issue for you:

* Select the Pods project
* Select the SQLCipher lib project, select Build Settings, Search for Deployment target and set it to the minimum that Xcode 14.3 supports 

I tested with an M1 machine on Ventura 13.3 and Xcode 14.3 (14E2222b). I've tried both macOS and iOS targets with objective c and swift languages and use_frameworks! enabled and disabled and they are all building properly after using the above workaround to set the min deployment target.

Let me know if this temporary workaround allows you to build properly with Xcode 14.3.

**Comment by b95505017** [comment]
Yes that's maybe some beta issue. Currently I met same issue with min target.

**Comment by R4N** [comment]
@b95505017 

Just to confirm, were you able to use the workaround in my previous comment to allow your application which uses SQLCipher pod to build on Xcode 14.3?

**Comment by b95505017** [comment]
@R4N Yes

**Comment by sjlombardo** [comment]
Minimum targets have been updated in the latest release.
