### ISSUE TITLE
Differences in ecrypting db with Windows and Linux

### ISSUE THREAD

**Issue by gioelepozzibdsound** [sqlcipher/sqlcipher#471]
Hi, we want to encrypt a db using sqlcipher, using the sqlite3_key api, and we have found differences in creating the db from Windows or from Linux. The db created with the two OS are different and they should not.

OS used:
- Windows 11 with:
    - sqlcipher: 3.15.2
    - OpenSSL: 3.0.2 15 Mar 2022
- Linux with Ubuntu 22.04.2 LTS
    - sqlcipher: 3.15.2
    - OpenSSL: 1.1.1u  30 May 2023

Could be something related to sqlcipher and openssl versions? Or something else?

Thanks.

**Comment by sjlombardo** [comment]
What are the specific differences in the databases you are referring to?

**Comment by gioelepozzibdsound** [comment]
The two databases are the same, the encryption key is the same but the binary generated are different.
If we create the db with windows and open it with windows, everything is ok, the same creating with linux and using with linux to read it.
The problem is when we create the db with windows and we want to open it with linux (and viceversa).
The test code is the same on linux and windows, the only changes are the compiler.

**Comment by albanoandrea** [comment]
Hello, I'm @gioelepozzibdsound colleague.
Does anyone knows if there are some log options that can be enabled to see all the operation performed to encrypt and decrypt the db, in order to check if there is any difference?

**Comment by gioelepozzibdsound** [comment]
Hi, here are the differences in the two dbs created with windows (right) and linux (left):
![image](https://github.com/sqlcipher/sqlcipher/assets/77725770/9f56f3dc-8a4c-46d5-8988-149c1d6986de)
is there a way we can set the page size, write format and all other settings using the apis with the C library and not using PRAGMAS?

**Comment by sjlombardo** [comment]
Hello @gioelepozzibdsound the `.dbinfo` command is not going to provide accurate information for an encrypted database. It is just looking at the file header, which for a SQLCipher database contains a combination of random and encrypted data. Therefore the numbers being reported are not accurate.

You appear to be using a *very* old version of SQLCipher. If you upgrade to a more modern version of SQLCipher (4.5.4 is the current version as of this writing) then you will be able to use `PRAGMA key` prior to `.dbinfo` to get accurate information. 

```
$ ./sqlcipher test.db
SQLite version 3.42.0 2023-05-16 12:36:15 (SQLCipher 4.5.5 community)
Enter ".help" for usage hints.
sqlite> .dbinfo
error: file is not a database
sqlite> pragma key = 'test';
ok
sqlite> .dbinfo
database page size:  4096
write format:        1
read format:         1
reserved bytes:      80
file change counter: 1532934185
database page count: 2
freelist page count: 0
schema cookie:       1
schema format:       4
default cache size:  0
autovacuum top root: 0
incremental vacuum:  0
text encoding:       1 (utf8)
user version:        0
application id:      0
software version:    3042000
number of tables:    1
number of indexes:   0
number of triggers:  0
number of views:     0
schema size:         20
data version         2
```
