### ISSUE TITLE
Unset key for following queries

### ISSUE THREAD

**Issue by Welfordian** [sqlcipher/sqlcipher#472]
Is is possible to unset the key once we are finished, without closing the connection?

Something like the following:-

`PRAGMA key = 'eff$CgUcR~%pK}B'`
```SELECT `id`, `name`, `createdAt`, `updatedAt` FROM `applications` AS `application` LIMIT 1;```

The above should result in a successful query.

`PRAGMA key = ''`
```SELECT `id`, `name`, `createdAt`, `updatedAt` FROM `applications` AS `application` LIMIT 1;```

I would _expect_ this query to fail, but it seems the key is kept in memory (or something) and the query is still successful.

**Comment by sjlombardo** [comment]
Hi @Welfordian - thanks for getting in touch about this. Unfortunately, that is not a supported mode of operation. If you wanted to clear the key and all page cache completely, then closing the database handle is the best way to do it. One downside to frequently clearing the key is that when you reopen a new connection there will be a penalty for key derivation (more on that here https://www.zetetic.net/sqlcipher/design/).
