### ISSUE TITLE
Create shortcut for pragma key🔐

### ISSUE THREAD

**Issue by Vanillma** [sqlcipher/sqlcipher#474]
Hello Bro
What do you think about creating a shortcut for the key definition?

Currently, when opening a locked database, you must write (Pragma key = Pass)

But I think it can be written more simply... like (PK = Pass)
(or any other example)

I don't intend to replace it... but I think it will be easier to enter the database by creating a shortcut.

**Comment by sjlombardo** [comment]
Hello @Vanillma - thanks for getting in touch and for the suggestion. While having a shortcut would provide a small convenience, it would actually be a very major change to implementation. Complexities would include adding a new keyword, changes to the parser rules, and divergent behavior from upstream SQLite. Therefore, we wouldn't implement this in SQLCipher at this time.
