### ISSUE TITLE
WCDBOptimizedSQLCipher 1.4.1 no publish?

### ISSUE THREAD

**Issue by wangzhizhou** [sqlcipher/sqlcipher#476]
### Steps to Reproduce

SQLCipher version:

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by sjlombardo** [comment]
Hello @wangzhizhou - we do not maintain WCDBOptimizedSQLCipher. That appears to be a fork of a fork of our official project. I would suggest contacting the maintainer.
