### ISSUE TITLE
sqlcipher_export fails when table constraint uses "

### ISSUE THREAD

**Issue by OwnInTheFoam** [sqlcipher/sqlcipher#480]
### Expected Behavior
sqlcipher_export to succeed when table constraint uses Double-quoted String Literals (")

### Actual Behavior
sqlcipher_export fails when table constraint uses Double-quoted String Literals (")

### Steps to Reproduce
Create a database with `check` constraint using double quote string literals. E.g:
```
CREATE TABLE ExportMe(
	Parameter TEXT NOT NULL,
	Value CHAR (1) CHECK (Value IN ("Y","N","O")) NOT NULL
);
```
Export the created database to new database. E.g:
```
ATTACH DATABASE 'encrypt.db' AS encrypt KEY 'MyKey';
SELECT sqlcipher_export('encrypt');
```
Notice failure with `Runtime error: no such column: Y`

See [Double-quoted String Literals Are Accepted](https://www.sqlite.org/quirks.html)

SQLCipher version: 4.5.4

**Comment by sjlombardo** [comment]
Hello @OwnInTheFoam - are you using the command line interface? If so, please note from the page you quoted :

> As of SQLite 3.41.0 (2023-02-21) SQLITE_DBCONFIG_DQS_DDL and SQLTIE_DBCONFIG_DQS_DML are disabled by default in the CLI. Use the ".dbconfig" dot-command to reenable the legacy behavior if desired.

SQLCipher 4.5.4 is based on SQLite 3.41.2, so this behavior applies to the current version. Therefore if you are using the command line tool you are going to use `sqlcipher_export()` from the command line you would want to enable the legacy behavior. 

```
sqlite> .dbconfig dqs_ddl on
            dqs_ddl on
sqlite> .dbconfig dqs_dml on
            dqs_dml on
```

**Comment by OwnInTheFoam** [comment]
I am using the command line tool. 

Thank you for clearing that up. After turning on the legacy behavior `sqlcipher_export()` works as expected.
