### ISSUE TITLE
RFE: please start making github releases

### ISSUE THREAD

**Issue by kloczek** [sqlcipher/sqlcipher#481]
Is it possible next time on release new version make the github release to have entry on https://github.com/sqlcipher/sqlcipher/releases? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release

**Comment by sjlombardo** [comment]
Hello @kloczek - thank you for the suggestion. We have just published a release for the latest version, and will update accordingly in the future.

**Comment by kloczek** [comment]
I can confirm that my automation was able successfully process that notification.
Thank you very much 👍 😄
