### ISSUE TITLE
Null-dereference when calls sqlite3_change64

### ISSUE THREAD

**Issue by icy17** [sqlcipher/sqlcipher#482]
The return value of sqlite3_context_db_handle might be NULL. And calls sqlite3_change64 without check might cause null-dereference.
Here is the bug location:
https://github.com/sqlcipher/sqlcipher/blob/7c460791eba939e6c6872825219a6644ca47283b/src/func.c#L597C15-L597C15

**Comment by sjlombardo** [comment]
Hello @icy17 - we've looked into this issue. While we don't disagree that a NULL check wouldn't hurt, when `change` is called in the context of a SQL function `sqlite3_context_db_handle` should not return NULL. In addition, if the library is compiled with `SQLITE_ENABLE_API_ARMOR`, there is a NULL-check inside `sqlite3_total_changes64`.

Have you been able to create a reproducible scenario using the API that results in a NULL db pointer in the handle causing unexpected behavior? 

Finally, this source code is unchanged from the upstream SQLite project. The SQLCipher policy is to minimize changes between upstream where possible, As such, this report would be more appropriate to direct to the [SQLite forum](https://sqlite.org/forum/forummain) if you can reproduce an issue.

**Comment by icy17** [comment]
thanks for your reply! I think it's my wrong. Sorry!
