### ISSUE TITLE
`pragma page_size = ...` causes ErrorCorrupt

### ISSUE THREAD

**Issue by epoberezkin** [sqlcipher/sqlcipher#485]
Using these pragmas on new database before creating tables results in ErrorCorrupt error when opening the database second time and executing any query. 

Below is done in SQLCipher CLI manually, both 4.5.3 and 4.5.5 .

Fist time:
```
pragma key = '123';
pragma page_size = 16384; -- any value here other than 4096
create table users(user_id integer primary key);
select * from users; -- this works
```

Second time:
```
pragma key = '123';
pragma page_size = 16384; -- same as above
select * from users; -- this returns "Parse error: malformed database schema (?) (11)"
```

Adding `pragma cipher_page_size = 16384;` after `pragma page_size = 16384;` solves the problem.

Possibly, that's how it is supposed to work, but maybe it should be covered in the docs?

SQLCipher version: 4.5.3 or 4.5.5.

**Comment by sjlombardo** [comment]
Hello @epoberezkin - SQLCipher used alternate pragmas for changing the page size:

https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_page_size

https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_default_page_size

Please let us know if those work.

**Comment by sjlombardo** [comment]
pragma page_size and pragma cipher_page_size now interoperate as of [v4.5.6](https://github.com/sqlcipher/sqlcipher/releases/tag/v4.5.6)
