### ISSUE TITLE
Confusing license status due to both LICENSE and LICENSE.md.

### ISSUE THREAD

**Issue by petterreinholdtsen** [sqlcipher/sqlcipher#489]
The current code license status is a bit confusing as the license of LICENSE do not match the one in LICENSE.md, and the license information in the github project is missing.  Please make it easier to figure out the copyright license of this project.

**Comment by sjlombardo** [comment]
Thank you for requesting this. I agree this is confusing and we will attempt to clarify the licensing in an update.

**Comment by sjlombardo** [comment]
This is clarified as of [v4.5.6](https://github.com/sqlcipher/sqlcipher/releases/tag/v4.5.6)
