### ISSUE TITLE
mbedtls can replace openssl in this repo

### ISSUE THREAD

**Issue by zhaochengwei** [sqlcipher/sqlcipher#496]
### Expected Behavior
sqlcipher depend mbedtls or openssl
### Actual Behavior
sqlcipher only depend openssl
### Steps to Reproduce
none
SQLCipher version:
4.5.5
*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by sjlombardo** [comment]
Hello @zhaochengwei  - Unfortunately we don't have any plans to add a mbedtls as a provider at this time. The reasons for this decision are numerous and are explained in detail in PR https://github.com/sqlcipher/sqlcipher/pull/327. 

If you have a strong requirement to use you could take a look at the code in the PR and include it in your own private builds.
