### ISSUE TITLE
make test run failed

### ISSUE THREAD

**Issue by zhaochengwei** [sqlcipher/sqlcipher#497]
### Expected Behavior
make test,pass all cases

### Actual Behavior
`douding@douding-HP-Z420-Workstation:~/sqlcipher_raw$ make test
./libtool --mode=link gcc -DSQLITE_HAS_CODEC -DSQLCIPHER_TEST -DSQLCIPHER_CRYPTO_OPENSSL -DSQLITE_OS_UNIX=1 -I. -I/home/douding/sqlcipher_raw/src -I/home/douding/sqlcipher_raw/ext/rtree -I/home/douding/sqlcipher_raw/ext/icu -I/home/douding/sqlcipher_raw/ext/fts3 -I/home/douding/sqlcipher_raw/ext/async -I/home/douding/sqlcipher_raw/ext/session -I/home/douding/sqlcipher_raw/ext/userauth -D_HAVE_SQLITE_CONFIG_H -DBUILD_sqlite -DNDEBUG -I/usr/include/tcl8.6 -DSQLITE_THREADSAFE=1 -DSQLITE_ENABLE_MATH_FUNCTIONS  -DSQLITE_HAVE_ZLIB=1  -lcrypto  -o fuzzcheck -I/home/douding/sqlcipher_raw/test -I/home/douding/sqlcipher_raw/ext/recover -DSQLITE_OSS_FUZZ -DSQLITE_ENABLE_BYTECODE_VTAB -DSQLITE_ENABLE_DBPAGE_VTAB -DSQLITE_ENABLE_DBSTAT_VTAB -DSQLITE_ENABLE_BYTECODE_VTAB -DSQLITE_ENABLE_DESERIALIZE -DSQLITE_ENABLE_EXPLAIN_COMMENTS -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_GEOPOLY -DSQLITE_ENABLE_MATH_FUNCTIONS -DSQLITE_ENABLE_MEMSYS5 -DSQLITE_ENABLE_NORMALIZE -DSQLITE_ENABLE_OFFSET_SQL_FUNC -DSQLITE_ENABLE_PREUPDATE_HOOK -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_SESSION -DSQLITE_ENABLE_STMTVTAB -DSQLITE_ENABLE_UNKNOWN_SQL_FUNCTION -DSQLITE_ENABLE_STAT4 -DSQLITE_ENABLE_STMT_SCANSTATUS -DSQLITE_MAX_MEMORY=50000000 -DSQLITE_MAX_MMAP_SIZE=0 -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_PRINTF_PRECISION_LIMIT=1000 -DSQLITE_PRIVATE="" /home/douding/sqlcipher_raw/test/fuzzcheck.c /home/douding/sqlcipher_raw/test/ossfuzz.c /home/douding/sqlcipher_raw/test/fuzzinvariants.c /home/douding/sqlcipher_raw/ext/recover/dbdata.c /home/douding/sqlcipher_raw/ext/recover/sqlite3recover.c /home/douding/sqlcipher_raw/test/vt02.c sqlite3.c -lm -ldl -lz -lcrypto -lpthread  
libtool: link: gcc -DSQLITE_HAS_CODEC -DSQLCIPHER_TEST -DSQLCIPHER_CRYPTO_OPENSSL -DSQLITE_OS_UNIX=1 -I. -I/home/douding/sqlcipher_raw/src -I/home/douding/sqlcipher_raw/ext/rtree -I/home/douding/sqlcipher_raw/ext/icu -I/home/douding/sqlcipher_raw/ext/fts3 -I/home/douding/sqlcipher_raw/ext/async -I/home/douding/sqlcipher_raw/ext/session -I/home/douding/sqlcipher_raw/ext/userauth -D_HAVE_SQLITE_CONFIG_H -DBUILD_sqlite -DNDEBUG -I/usr/include/tcl8.6 -DSQLITE_THREADSAFE=1 -DSQLITE_ENABLE_MATH_FUNCTIONS -DSQLITE_HAVE_ZLIB=1 -o fuzzcheck -I/home/douding/sqlcipher_raw/test -I/home/douding/sqlcipher_raw/ext/recover -DSQLITE_OSS_FUZZ -DSQLITE_ENABLE_BYTECODE_VTAB -DSQLITE_ENABLE_DBPAGE_VTAB -DSQLITE_ENABLE_DBSTAT_VTAB -DSQLITE_ENABLE_BYTECODE_VTAB -DSQLITE_ENABLE_DESERIALIZE -DSQLITE_ENABLE_EXPLAIN_COMMENTS -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_GEOPOLY -DSQLITE_ENABLE_MATH_FUNCTIONS -DSQLITE_ENABLE_MEMSYS5 -DSQLITE_ENABLE_NORMALIZE -DSQLITE_ENABLE_OFFSET_SQL_FUNC -DSQLITE_ENABLE_PREUPDATE_HOOK -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_SESSION -DSQLITE_ENABLE_STMTVTAB -DSQLITE_ENABLE_UNKNOWN_SQL_FUNCTION -DSQLITE_ENABLE_STAT4 -DSQLITE_ENABLE_STMT_SCANSTATUS -DSQLITE_MAX_MEMORY=50000000 -DSQLITE_MAX_MMAP_SIZE=0 -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_PRINTF_PRECISION_LIMIT=1000 -DSQLITE_PRIVATE= /home/douding/sqlcipher_raw/test/fuzzcheck.c /home/douding/sqlcipher_raw/test/ossfuzz.c /home/douding/sqlcipher_raw/test/fuzzinvariants.c /home/douding/sqlcipher_raw/ext/recover/dbdata.c /home/douding/sqlcipher_raw/ext/recover/sqlite3recover.c /home/douding/sqlcipher_raw/test/vt02.c sqlite3.c  -lm -ldl -lz -lcrypto -lpthread
./libtool --mode=link gcc -DSQLITE_HAS_CODEC -DSQLCIPHER_TEST -DSQLCIPHER_CRYPTO_OPENSSL -DSQLITE_OS_UNIX=1 -I. -I/home/douding/sqlcipher_raw/src -I/home/douding/sqlcipher_raw/ext/rtree -I/home/douding/sqlcipher_raw/ext/icu -I/home/douding/sqlcipher_raw/ext/fts3 -I/home/douding/sqlcipher_raw/ext/async -I/home/douding/sqlcipher_raw/ext/session -I/home/douding/sqlcipher_raw/ext/userauth -D_HAVE_SQLITE_CONFIG_H -DBUILD_sqlite -DNDEBUG -I/usr/include/tcl8.6 -DSQLITE_THREADSAFE=1 -DSQLITE_ENABLE_MATH_FUNCTIONS  -DSQLITE_HAVE_ZLIB=1  -lcrypto  -o sessionfuzz /home/douding/sqlcipher_raw/test/sessionfuzz.c -lm -ldl -lz -lcrypto -lpthread  
libtool: link: gcc -DSQLITE_HAS_CODEC -DSQLCIPHER_TEST -DSQLCIPHER_CRYPTO_OPENSSL -DSQLITE_OS_UNIX=1 -I. -I/home/douding/sqlcipher_raw/src -I/home/douding/sqlcipher_raw/ext/rtree -I/home/douding/sqlcipher_raw/ext/icu -I/home/douding/sqlcipher_raw/ext/fts3 -I/home/douding/sqlcipher_raw/ext/async -I/home/douding/sqlcipher_raw/ext/session -I/home/douding/sqlcipher_raw/ext/userauth -D_HAVE_SQLITE_CONFIG_H -DBUILD_sqlite -DNDEBUG -I/usr/include/tcl8.6 -DSQLITE_THREADSAFE=1 -DSQLITE_ENABLE_MATH_FUNCTIONS -DSQLITE_HAVE_ZLIB=1 -o sessionfuzz /home/douding/sqlcipher_raw/test/sessionfuzz.c  -lm -ldl -lz -lcrypto -lpthread
./fuzzcheck /home/douding/sqlcipher_raw/test/fuzzdata1.db /home/douding/sqlcipher_raw/test/fuzzdata2.db /home/douding/sqlcipher_raw/test/fuzzdata3.db /home/douding/sqlcipher_raw/test/fuzzdata4.db /home/douding/sqlcipher_raw/test/fuzzdata5.db /home/douding/sqlcipher_raw/test/fuzzdata6.db /home/douding/sqlcipher_raw/test/fuzzdata7.db /home/douding/sqlcipher_raw/test/fuzzdata8.db
fuzzdata1.db: 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% - 9917 tests
fuzzdata2.db: 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% - 9959 tests
fuzzdata3.db: 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% - 2316 tests
fuzzdata4.db: 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% - 2575 tests
fuzzdata5.db: 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% - 8834 tests
fuzzdata6.db: 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% - 3896 tests
fuzzdata7.db: 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% - 8145 tests
fuzzdata8.db: 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% - 744 tests
fuzzcheck: 11010 query invariants checked
fuzzcheck: 0 errors out of 46386 tests in 38.677 seconds
SQLite 3.42.0 2023-05-16 12:36:15 831d0fb2836b71c9bc51067c49fee4b8f18047814f2ff22d817d25195cf3alt1
./sessionfuzz run /home/douding/sqlcipher_raw/test/sessionfuzz-data1.db
sessionfuzz-data1.db:  339 cases, 0 crashes
gcc  -DSQLITE_HAS_CODEC -DSQLCIPHER_TEST -DSQLCIPHER_CRYPTO_OPENSSL -o srcck1 /home/douding/sqlcipher_raw/tool/srcck1.c
./srcck1 sqlite3.c
./libtool --mode=link gcc -DSQLITE_HAS_CODEC -DSQLCIPHER_TEST -DSQLCIPHER_CRYPTO_OPENSSL -DSQLITE_OS_UNIX=1 -I. -I/home/douding/sqlcipher_raw/src -I/home/douding/sqlcipher_raw/ext/rtree -I/home/douding/sqlcipher_raw/ext/icu -I/home/douding/sqlcipher_raw/ext/fts3 -I/home/douding/sqlcipher_raw/ext/async -I/home/douding/sqlcipher_raw/ext/session -I/home/douding/sqlcipher_raw/ext/userauth -D_HAVE_SQLITE_CONFIG_H -DBUILD_sqlite -DNDEBUG -I/usr/include/tcl8.6 -DSQLITE_THREADSAFE=1 -DSQLITE_ENABLE_MATH_FUNCTIONS  -DSQLITE_HAVE_ZLIB=1  -lcrypto  -DSQLITE_NO_SYNC=1 -DSQLITE_TEMP_STORE=1 -DSQLITE_TEST=1 -DSQLITE_CRASH_TEST=1 -DTCLSH_INIT_PROC=sqlite3TestInit -DSQLITE_SERVER=1 -DSQLITE_PRIVATE="" -DSQLITE_CORE -DBUILD_sqlite -DSQLITE_SERIES_CONSTRAINT_VERIFY=1 -DSQLITE_DEFAULT_PAGE_SIZE=1024 -DSQLITE_ENABLE_STMTVTAB -DSQLITE_ENABLE_DBPAGE_VTAB -DSQLITE_ENABLE_BYTECODE_VTAB -DSQLITE_CKSUMVFS_STATIC \
        -o testfixture /home/douding/sqlcipher_raw/src/test1.c /home/douding/sqlcipher_raw/src/test2.c /home/douding/sqlcipher_raw/src/test3.c /home/douding/sqlcipher_raw/src/test4.c /home/douding/sqlcipher_raw/src/test5.c /home/douding/sqlcipher_raw/src/test6.c /home/douding/sqlcipher_raw/src/test8.c /home/douding/sqlcipher_raw/src/test9.c /home/douding/sqlcipher_raw/src/test_autoext.c /home/douding/sqlcipher_raw/src/test_async.c /home/douding/sqlcipher_raw/src/test_backup.c /home/douding/sqlcipher_raw/src/test_bestindex.c /home/douding/sqlcipher_raw/src/test_blob.c /home/douding/sqlcipher_raw/src/test_btree.c /home/douding/sqlcipher_raw/src/test_config.c /home/douding/sqlcipher_raw/src/test_delete.c /home/douding/sqlcipher_raw/src/test_demovfs.c /home/douding/sqlcipher_raw/src/test_devsym.c /home/douding/sqlcipher_raw/src/test_fs.c /home/douding/sqlcipher_raw/src/test_func.c /home/douding/sqlcipher_raw/src/test_hexio.c /home/douding/sqlcipher_raw/src/test_init.c /home/douding/sqlcipher_raw/src/test_intarray.c /home/douding/sqlcipher_raw/src/test_journal.c /home/douding/sqlcipher_raw/src/test_malloc.c /home/douding/sqlcipher_raw/src/test_md5.c /home/douding/sqlcipher_raw/src/test_multiplex.c /home/douding/sqlcipher_raw/src/test_mutex.c /home/douding/sqlcipher_raw/src/test_onefile.c /home/douding/sqlcipher_raw/src/test_osinst.c /home/douding/sqlcipher_raw/src/test_pcache.c /home/douding/sqlcipher_raw/src/test_quota.c /home/douding/sqlcipher_raw/src/test_rtree.c /home/douding/sqlcipher_raw/src/test_schema.c /home/douding/sqlcipher_raw/src/test_superlock.c /home/douding/sqlcipher_raw/src/test_syscall.c /home/douding/sqlcipher_raw/src/test_tclsh.c /home/douding/sqlcipher_raw/src/test_tclvar.c /home/douding/sqlcipher_raw/src/test_thread.c /home/douding/sqlcipher_raw/src/test_vdbecov.c /home/douding/sqlcipher_raw/src/test_vfs.c /home/douding/sqlcipher_raw/src/test_windirent.c /home/douding/sqlcipher_raw/src/test_window.c /home/douding/sqlcipher_raw/src/test_wsd.c /home/douding/sqlcipher_raw/ext/fts3/fts3_term.c /home/douding/sqlcipher_raw/ext/fts3/fts3_test.c /home/douding/sqlcipher_raw/ext/session/test_session.c /home/douding/sqlcipher_raw/ext/recover/sqlite3recover.c /home/douding/sqlcipher_raw/ext/recover/dbdata.c /home/douding/sqlcipher_raw/ext/recover/test_recover.c /home/douding/sqlcipher_raw/ext/rbu/test_rbu.c /home/douding/sqlcipher_raw/ext/expert/sqlite3expert.c /home/douding/sqlcipher_raw/ext/expert/test_expert.c /home/douding/sqlcipher_raw/ext/misc/amatch.c /home/douding/sqlcipher_raw/ext/misc/appendvfs.c /home/douding/sqlcipher_raw/ext/misc/basexx.c /home/douding/sqlcipher_raw/ext/misc/carray.c /home/douding/sqlcipher_raw/ext/misc/cksumvfs.c /home/douding/sqlcipher_raw/ext/misc/closure.c /home/douding/sqlcipher_raw/ext/misc/csv.c /home/douding/sqlcipher_raw/ext/misc/decimal.c /home/douding/sqlcipher_raw/ext/misc/eval.c /home/douding/sqlcipher_raw/ext/misc/explain.c /home/douding/sqlcipher_raw/ext/misc/fileio.c /home/douding/sqlcipher_raw/ext/misc/fuzzer.c /home/douding/sqlcipher_raw/ext/fts5/fts5_tcl.c /home/douding/sqlcipher_raw/ext/fts5/fts5_test_mi.c /home/douding/sqlcipher_raw/ext/fts5/fts5_test_tok.c /home/douding/sqlcipher_raw/ext/misc/ieee754.c /home/douding/sqlcipher_raw/ext/misc/mmapwarm.c /home/douding/sqlcipher_raw/ext/misc/nextchar.c /home/douding/sqlcipher_raw/ext/misc/normalize.c /home/douding/sqlcipher_raw/ext/misc/percentile.c /home/douding/sqlcipher_raw/ext/misc/prefixes.c /home/douding/sqlcipher_raw/ext/misc/qpvtab.c /home/douding/sqlcipher_raw/ext/misc/regexp.c /home/douding/sqlcipher_raw/ext/misc/remember.c /home/douding/sqlcipher_raw/ext/misc/series.c /home/douding/sqlcipher_raw/ext/misc/spellfix.c /home/douding/sqlcipher_raw/ext/misc/totype.c /home/douding/sqlcipher_raw/ext/misc/unionvtab.c /home/douding/sqlcipher_raw/ext/misc/wholenumber.c /home/douding/sqlcipher_raw/ext/misc/zipfile.c /home/douding/sqlcipher_raw/ext/userauth/userauth.c /home/douding/sqlcipher_raw/ext/rtree/test_rtreedoc.c /home/douding/sqlcipher_raw/src/tclsqlite.c sqlite3.c -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -lm -ldl -lz -lcrypto -lpthread  
libtool: link: gcc -DSQLITE_HAS_CODEC -DSQLCIPHER_TEST -DSQLCIPHER_CRYPTO_OPENSSL -DSQLITE_OS_UNIX=1 -I. -I/home/douding/sqlcipher_raw/src -I/home/douding/sqlcipher_raw/ext/rtree -I/home/douding/sqlcipher_raw/ext/icu -I/home/douding/sqlcipher_raw/ext/fts3 -I/home/douding/sqlcipher_raw/ext/async -I/home/douding/sqlcipher_raw/ext/session -I/home/douding/sqlcipher_raw/ext/userauth -D_HAVE_SQLITE_CONFIG_H -DBUILD_sqlite -DNDEBUG -I/usr/include/tcl8.6 -DSQLITE_THREADSAFE=1 -DSQLITE_ENABLE_MATH_FUNCTIONS -DSQLITE_HAVE_ZLIB=1 -DSQLITE_NO_SYNC=1 -DSQLITE_TEMP_STORE=1 -DSQLITE_TEST=1 -DSQLITE_CRASH_TEST=1 -DTCLSH_INIT_PROC=sqlite3TestInit -DSQLITE_SERVER=1 -DSQLITE_PRIVATE= -DSQLITE_CORE -DBUILD_sqlite -DSQLITE_SERIES_CONSTRAINT_VERIFY=1 -DSQLITE_DEFAULT_PAGE_SIZE=1024 -DSQLITE_ENABLE_STMTVTAB -DSQLITE_ENABLE_DBPAGE_VTAB -DSQLITE_ENABLE_BYTECODE_VTAB -DSQLITE_CKSUMVFS_STATIC -o testfixture /home/douding/sqlcipher_raw/src/test1.c /home/douding/sqlcipher_raw/src/test2.c /home/douding/sqlcipher_raw/src/test3.c /home/douding/sqlcipher_raw/src/test4.c /home/douding/sqlcipher_raw/src/test5.c /home/douding/sqlcipher_raw/src/test6.c /home/douding/sqlcipher_raw/src/test8.c /home/douding/sqlcipher_raw/src/test9.c /home/douding/sqlcipher_raw/src/test_autoext.c /home/douding/sqlcipher_raw/src/test_async.c /home/douding/sqlcipher_raw/src/test_backup.c /home/douding/sqlcipher_raw/src/test_bestindex.c /home/douding/sqlcipher_raw/src/test_blob.c /home/douding/sqlcipher_raw/src/test_btree.c /home/douding/sqlcipher_raw/src/test_config.c /home/douding/sqlcipher_raw/src/test_delete.c /home/douding/sqlcipher_raw/src/test_demovfs.c /home/douding/sqlcipher_raw/src/test_devsym.c /home/douding/sqlcipher_raw/src/test_fs.c /home/douding/sqlcipher_raw/src/test_func.c /home/douding/sqlcipher_raw/src/test_hexio.c /home/douding/sqlcipher_raw/src/test_init.c /home/douding/sqlcipher_raw/src/test_intarray.c /home/douding/sqlcipher_raw/src/test_journal.c /home/douding/sqlcipher_raw/src/test_malloc.c /home/douding/sqlcipher_raw/src/test_md5.c /home/douding/sqlcipher_raw/src/test_multiplex.c /home/douding/sqlcipher_raw/src/test_mutex.c /home/douding/sqlcipher_raw/src/test_onefile.c /home/douding/sqlcipher_raw/src/test_osinst.c /home/douding/sqlcipher_raw/src/test_pcache.c /home/douding/sqlcipher_raw/src/test_quota.c /home/douding/sqlcipher_raw/src/test_rtree.c /home/douding/sqlcipher_raw/src/test_schema.c /home/douding/sqlcipher_raw/src/test_superlock.c /home/douding/sqlcipher_raw/src/test_syscall.c /home/douding/sqlcipher_raw/src/test_tclsh.c /home/douding/sqlcipher_raw/src/test_tclvar.c /home/douding/sqlcipher_raw/src/test_thread.c /home/douding/sqlcipher_raw/src/test_vdbecov.c /home/douding/sqlcipher_raw/src/test_vfs.c /home/douding/sqlcipher_raw/src/test_windirent.c /home/douding/sqlcipher_raw/src/test_window.c /home/douding/sqlcipher_raw/src/test_wsd.c /home/douding/sqlcipher_raw/ext/fts3/fts3_term.c /home/douding/sqlcipher_raw/ext/fts3/fts3_test.c /home/douding/sqlcipher_raw/ext/session/test_session.c /home/douding/sqlcipher_raw/ext/recover/sqlite3recover.c /home/douding/sqlcipher_raw/ext/recover/dbdata.c /home/douding/sqlcipher_raw/ext/recover/test_recover.c /home/douding/sqlcipher_raw/ext/rbu/test_rbu.c /home/douding/sqlcipher_raw/ext/expert/sqlite3expert.c /home/douding/sqlcipher_raw/ext/expert/test_expert.c /home/douding/sqlcipher_raw/ext/misc/amatch.c /home/douding/sqlcipher_raw/ext/misc/appendvfs.c /home/douding/sqlcipher_raw/ext/misc/basexx.c /home/douding/sqlcipher_raw/ext/misc/carray.c /home/douding/sqlcipher_raw/ext/misc/cksumvfs.c /home/douding/sqlcipher_raw/ext/misc/closure.c /home/douding/sqlcipher_raw/ext/misc/csv.c /home/douding/sqlcipher_raw/ext/misc/decimal.c /home/douding/sqlcipher_raw/ext/misc/eval.c /home/douding/sqlcipher_raw/ext/misc/explain.c /home/douding/sqlcipher_raw/ext/misc/fileio.c /home/douding/sqlcipher_raw/ext/misc/fuzzer.c /home/douding/sqlcipher_raw/ext/fts5/fts5_tcl.c /home/douding/sqlcipher_raw/ext/fts5/fts5_test_mi.c /home/douding/sqlcipher_raw/ext/fts5/fts5_test_tok.c /home/douding/sqlcipher_raw/ext/misc/ieee754.c /home/douding/sqlcipher_raw/ext/misc/mmapwarm.c /home/douding/sqlcipher_raw/ext/misc/nextchar.c /home/douding/sqlcipher_raw/ext/misc/normalize.c /home/douding/sqlcipher_raw/ext/misc/percentile.c /home/douding/sqlcipher_raw/ext/misc/prefixes.c /home/douding/sqlcipher_raw/ext/misc/qpvtab.c /home/douding/sqlcipher_raw/ext/misc/regexp.c /home/douding/sqlcipher_raw/ext/misc/remember.c /home/douding/sqlcipher_raw/ext/misc/series.c /home/douding/sqlcipher_raw/ext/misc/spellfix.c /home/douding/sqlcipher_raw/ext/misc/totype.c /home/douding/sqlcipher_raw/ext/misc/unionvtab.c /home/douding/sqlcipher_raw/ext/misc/wholenumber.c /home/douding/sqlcipher_raw/ext/misc/zipfile.c /home/douding/sqlcipher_raw/ext/userauth/userauth.c /home/douding/sqlcipher_raw/ext/rtree/test_rtreedoc.c /home/douding/sqlcipher_raw/src/tclsqlite.c sqlite3.c  -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -lm -ldl -lz -lcrypto -lpthread
gcc   sqlite3.o   -o sqlite3
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
sqlite3.o: In function `pthreadMutexAlloc':
sqlite3.c:(.text+0x4e07): undefined reference to `pthread_mutexattr_init'
sqlite3.c:(.text+0x4e18): undefined reference to `pthread_mutexattr_settype'
sqlite3.c:(.text+0x4e37): undefined reference to `pthread_mutexattr_destroy'
sqlite3.o: In function `pthreadMutexTry':
sqlite3.c:(.text+0x4f00): undefined reference to `pthread_mutex_trylock'
sqlite3.o: In function `sqlite3ThreadCreate':
sqlite3.c:(.text+0xaaf0): undefined reference to `pthread_create'
sqlite3.o: In function `sqlite3ThreadJoin':
sqlite3.c:(.text+0xab85): undefined reference to `pthread_join'
sqlite3.o: In function `unixDlOpen':
sqlite3.c:(.text+0x13ac6): undefined reference to `dlopen'
sqlite3.o: In function `unixDlError':
sqlite3.c:(.text+0x13ae5): undefined reference to `dlerror'
sqlite3.o: In function `unixDlSym':
sqlite3.c:(.text+0x13b34): undefined reference to `dlsym'
sqlite3.o: In function `unixDlClose':
sqlite3.c:(.text+0x13b6a): undefined reference to `dlclose'
sqlite3.o: In function `sqlcipher_openssl_log_errors':
sqlite3.c:(.text+0x604da): undefined reference to `ERR_error_string'
sqlite3.c:(.text+0x60502): undefined reference to `ERR_get_error'
sqlite3.o: In function `sqlcipher_openssl_add_random':
sqlite3.c:(.text+0x60576): undefined reference to `RAND_add'
sqlite3.o: In function `sqlcipher_openssl_get_provider_version':
sqlite3.c:(.text+0x60725): undefined reference to `OpenSSL_version'
sqlite3.o: In function `sqlcipher_openssl_random':
sqlite3.c:(.text+0x60790): undefined reference to `RAND_bytes'
sqlite3.o: In function `sqlcipher_openssl_hmac':
sqlite3.c:(.text+0x60866): undefined reference to `HMAC_CTX_new'
sqlite3.c:(.text+0x608b4): undefined reference to `EVP_sha1'
sqlite3.c:(.text+0x608d0): undefined reference to `HMAC_Init_ex'
sqlite3.c:(.text+0x60911): undefined reference to `EVP_sha256'
sqlite3.c:(.text+0x6092d): undefined reference to `HMAC_Init_ex'
sqlite3.c:(.text+0x6096e): undefined reference to `EVP_sha512'
sqlite3.c:(.text+0x6098a): undefined reference to `HMAC_Init_ex'
sqlite3.c:(.text+0x60a02): undefined reference to `HMAC_Update'
sqlite3.c:(.text+0x60a60): undefined reference to `HMAC_Update'
sqlite3.c:(.text+0x60ab2): undefined reference to `HMAC_Final'
sqlite3.c:(.text+0x60b0b): undefined reference to `HMAC_CTX_free'
sqlite3.o: In function `sqlcipher_openssl_kdf':
sqlite3.c:(.text+0x60b6b): undefined reference to `EVP_sha1'
sqlite3.c:(.text+0x60b92): undefined reference to `PKCS5_PBKDF2_HMAC'
sqlite3.c:(.text+0x60bdb): undefined reference to `EVP_sha256'
sqlite3.c:(.text+0x60c02): undefined reference to `PKCS5_PBKDF2_HMAC'
sqlite3.c:(.text+0x60c4b): undefined reference to `EVP_sha512'
sqlite3.c:(.text+0x60c72): undefined reference to `PKCS5_PBKDF2_HMAC'
sqlite3.o: In function `sqlcipher_openssl_cipher':
sqlite3.c:(.text+0x60d13): undefined reference to `EVP_CIPHER_CTX_new'
sqlite3.c:(.text+0x60d48): undefined reference to `EVP_aes_256_cbc'
sqlite3.c:(.text+0x60d6d): undefined reference to `EVP_CipherInit_ex'
sqlite3.c:(.text+0x60db6): undefined reference to `EVP_CIPHER_CTX_set_padding'
sqlite3.c:(.text+0x60e13): undefined reference to `EVP_CipherInit_ex'
sqlite3.c:(.text+0x60e67): undefined reference to `EVP_CipherUpdate'
sqlite3.c:(.text+0x60ebd): undefined reference to `EVP_CipherFinal_ex'
sqlite3.c:(.text+0x60f16): undefined reference to `EVP_CIPHER_CTX_free'
sqlite3.o: In function `sqlcipher_openssl_get_cipher':
sqlite3.c:(.text+0x60f40): undefined reference to `EVP_aes_256_cbc'
sqlite3.c:(.text+0x60f48): undefined reference to `EVP_CIPHER_nid'
sqlite3.c:(.text+0x60f4f): undefined reference to `OBJ_nid2sn'
sqlite3.o: In function `sqlcipher_openssl_get_key_sz':
sqlite3.c:(.text+0x60f62): undefined reference to `EVP_aes_256_cbc'
sqlite3.c:(.text+0x60f6a): undefined reference to `EVP_CIPHER_key_length'
sqlite3.o: In function `sqlcipher_openssl_get_iv_sz':
sqlite3.c:(.text+0x60f7d): undefined reference to `EVP_aes_256_cbc'
sqlite3.c:(.text+0x60f85): undefined reference to `EVP_CIPHER_iv_length'
sqlite3.o: In function `sqlcipher_openssl_get_block_sz':
sqlite3.c:(.text+0x60f98): undefined reference to `EVP_aes_256_cbc'
sqlite3.c:(.text+0x60fa0): undefined reference to `EVP_CIPHER_block_size'
sqlite3.o: In function `sqlcipher_openssl_get_hmac_sz':
sqlite3.c:(.text+0x60fc7): undefined reference to `EVP_sha1'
sqlite3.c:(.text+0x60fcf): undefined reference to `EVP_MD_size'
sqlite3.c:(.text+0x60fd6): undefined reference to `EVP_sha256'
sqlite3.c:(.text+0x60fde): undefined reference to `EVP_MD_size'
sqlite3.c:(.text+0x60fe5): undefined reference to `EVP_sha512'
sqlite3.c:(.text+0x60fed): undefined reference to `EVP_MD_size'
sqlite3.o: In function `xCeil':
sqlite3.c:(.text+0x8c38f): undefined reference to `ceil'
sqlite3.o: In function `xFloor':
sqlite3.c:(.text+0x8c3be): undefined reference to `floor'
sqlite3.o: In function `logFunc':
sqlite3.c:(.text+0x8c45b): undefined reference to `log'
sqlite3.c:(.text+0x8c4b1): undefined reference to `log'
sqlite3.c:(.text+0x8c4e7): undefined reference to `log10'
sqlite3.c:(.text+0x8c504): undefined reference to `log2'
sqlite3.c:(.text+0x8c521): undefined reference to `log'
sqlite3.o:(.data.rel+0x16c0): undefined reference to `trunc'
sqlite3.o:(.data.rel+0x1870): undefined reference to `exp'
sqlite3.o:(.data.rel+0x18b8): undefined reference to `pow'
sqlite3.o:(.data.rel+0x1900): undefined reference to `pow'
sqlite3.o:(.data.rel+0x1948): undefined reference to `fmod'
sqlite3.o:(.data.rel+0x1990): undefined reference to `acos'
sqlite3.o:(.data.rel+0x19d8): undefined reference to `asin'
sqlite3.o:(.data.rel+0x1a20): undefined reference to `atan'
sqlite3.o:(.data.rel+0x1a68): undefined reference to `atan2'
sqlite3.o:(.data.rel+0x1ab0): undefined reference to `cos'
sqlite3.o:(.data.rel+0x1af8): undefined reference to `sin'
sqlite3.o:(.data.rel+0x1b40): undefined reference to `tan'
sqlite3.o:(.data.rel+0x1b88): undefined reference to `cosh'
sqlite3.o:(.data.rel+0x1bd0): undefined reference to `sinh'
sqlite3.o:(.data.rel+0x1c18): undefined reference to `tanh'
sqlite3.o:(.data.rel+0x1c60): undefined reference to `acosh'
sqlite3.o:(.data.rel+0x1ca8): undefined reference to `asinh'
sqlite3.o:(.data.rel+0x1cf0): undefined reference to `atanh'
sqlite3.o:(.data.rel+0x1d38): undefined reference to `sqrt'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'sqlite3' failed
make: *** [sqlite3] Error 1`
### Steps to Reproduce
./configure  CFLAGS="-DSQLITE_HAS_CODEC -DSQLCIPHER_TEST" LDFLAGS="-lcrypto"
make -j99
make test
SQLCipher version:
SQLite version 3.42.0 2023-05-16 12:36:15 (SQLCipher 4.5.5 community)

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by sjlombardo** [comment]
See https://github.com/sqlcipher/sqlcipher#testing
