### ISSUE TITLE
Why does "sqlcipher" not have a LoadExtension function?

### ISSUE THREAD

**Issue by dudylan** [sqlcipher/sqlcipher#498]
Why does "sqlcipher" not have a LoadExtension function?

How do I need to load external extensions

**Comment by sjlombardo** [comment]
Provided that you have compiled SQLCipher with support for loadable extensions, you can use either of the methods described here:

https://www.sqlite.org/lang_corefunc.html#load_extension

**Comment by dudylan** [comment]
Firstly, thank you for your reply
Secondly, sqlite does have a load_ Extension method.
And I'm using C # references https://github.com/praeclarum/sqlite-net When there is no load_ Extension method. I don't know what to do about it

**Comment by dudylan** [comment]
Firstly, thank you for your reply
Secondly, sqlite does have a load_ Extension method.
And I'm using C # references https://github.com/praeclarum/sqlite-net When there is no load_ Extension method. I don't know what to do about it

**Comment by developernotes** [comment]
Hi @dudylan 

In `sqlite-net`, first you should call [`EnableLoadExtension`](https://github.com/praeclarum/sqlite-net/blob/master/src/SQLite.cs#L494), then you can use [`Execute`](https://github.com/praeclarum/sqlite-net/blob/master/src/SQLite.cs#L1025) to call the `SELECT load_extension(...)` that @sjlombardo linked to.

**Comment by dudylan** [comment]
Hi @developernotes 
![image](https://github.com/sqlcipher/sqlcipher/assets/34180156/49fe21fd-094a-4bd3-b66c-933b623ae85a)
As shown in the figure, Received the following error

“SQLiteException: not an error“

**Comment by dudylan** [comment]
![image](https://github.com/sqlcipher/sqlcipher/assets/34180156/511138e0-2e89-4af1-a666-ffc47f14157e)
Similarly, I have also tried this one

**Comment by developernotes** [comment]
Hi @dudylan,

Sorry, can you try calling `ExecuteScalar` instead?

**Comment by dudylan** [comment]
@developernotes  Unable to install

I submitted an example

Please take a look

**Comment by dudylan** [comment]
https://github.com/dudylan/SqliteCheck

**Comment by developernotes** [comment]
Hi @dudylan,

If you modify your project to include the `simple.dll` and set 'Copy to output directory' as 'Copy always' for the file, the following modification to your demo will work properly:

```
var key = "aaa";
var options = new SQLiteConnectionString("xuanyou.db", true, key: key);
var _db = new SQLiteConnection(options);
_db.EnableLoadExtension(true);
var extensionPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "simple.dll");
_db.ExecuteScalar<int>($"SELECT load_extension('{extensionPath}');");
var value = _db.ExecuteScalar<string>("select simple_query('pinyin')");
```

**Comment by dudylan** [comment]
hi
Thank you for your answer
It can be executed under donet 6.0 now。
There are new issues after switching to Donet core 3.1.

**Comment by dudylan** [comment]
Thank you for your answer. I have solved a big problem
