### ISSUE TITLE
sqlite error first open database

### ISSUE THREAD

**Issue by iPermanent** [sqlcipher/sqlcipher#499]
### Expected Behavior
insert data success

### **Unknown error calling sqlite3_step (26: file is not a database) eu
DB Query: begin exclusive transaction
Unknown error finalizing or resetting statement (26: file is not a database)
DB Query: begin exclusive transaction**

### Steps to Reproduce
first :
FMDatabase *db = [FMDatabase databaseWithPath:self.dbPath];
if (![db open]) {
	db = nil;
}

//if database is not encrypt, encrypt it
if ([db goodConnection]) {
	[db setKey:self.dbEncKey];
	[self encryptDatabase:self.dbPath];
}

[self.databaseQueue inTransaction:^(FMDatabase * _Nonnull db, BOOL * _Nonnull rollback) {
	[db setKey:weakSelf.dbEncKey];
	...		
}];

then this error occurs, however this happens every time without the encrypt step, as this db only encrypt one time. And this occurs only when I call it soon , if I call it after some seconds with dispatch_asyc_after, it will be all right.

SQLCipher version: 
pod 'FMDB/SQLCipher','2.7.5'

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by R4N** [comment]
Hi @iPermanent 

Thanks for your interest in SQLCipher, we reserve GitHub issues for reporting defects with the SQLCipher library code. You didn't show what your encryptDatabase method is doing, but if you want to encrypt an existing plaintext database, you'll want to use the [sqlcipher_export()](https://www.zetetic.net/sqlcipher/sqlcipher-api/#sqlcipher_export) convenience function as shown in example 1 there.

Please create a post on the [SQLCipher community discussion forum](https://discuss.zetetic.net/c/sqlcipher/5) if you have any follow up questions purchase a [Commercial License of SQLCipher](https://www.zetetic.net/sqlcipher/buy/) if you'd like private prioritized support.
