### ISSUE TITLE
documentation in sqlcipher.1 manpage contains some kind of artifact from a merge error 

### ISSUE THREAD

**Issue by dkg** [sqlcipher/sqlcipher#508]
### Expected Behavior

I expect `sqlcipher.1` to be a clean nroff file.

### Actual Behavior

`sqlcipher.1` contains artifacts that look to be the product of a broken merge from a revision control system.

### Steps to Reproduce

- clone sqlcipher
- look at `sqlcipher.1`
- look for lines like `<<<<<<< HEAD:sqlcipher.1` and `>>>>>>> sqlite-release:sqlite3.1`

It looks like these were introduced in 884e09d9e69e08cddde3c03e68e604e4c105b07c but i haven't checked to see whether there were any other broken parts of that merge.

SQLCipher version: the current git head

**Comment by sjlombardo** [comment]
hello @dkg - thank you for pointing this out, it will be corrected in the forthcoming release

**Comment by sjlombardo** [comment]
Hello @dkg this is fixed up in release 4.5.7
