### ISSUE TITLE
how to clear password

### ISSUE THREAD

**Issue by fytgiving** [sqlcipher/sqlcipher#509]
eg.

sqlite3_rekey(mpDB, 0, 0);

but it's goes wrong

SQLITE_API int sqlite3_rekey_v2(sqlite3 *db, const char *zDb, const void *pKey, int nKey) {
  sqlcipher_log(SQLCIPHER_LOG_DEBUG, "sqlite3_rekey_v2: db=%p zDb=%s", db, zDb);
  if(db && pKey && nKey) {     // pKey && nkey can't be null  ! here
  '''
  }
  sqlcipher_log(SQLCIPHER_LOG_ERROR, "sqlite3_rekey_v2: no key provided");
  return SQLITE_ERROR;
}

Thanks!

**Comment by sjlombardo** [comment]
Close the database, e.g. using sqlite3_close()

**Comment by fytgiving** [comment]
> Close the database, e.g. using sqlite3_close()

thanks!
e.g.
sqlite3_key(myDB, "my_password1", strlen("my_password1"));
sqlite3_rekey(myDB, 0, 0);
sqlite3_close(myDB);

i think so?

**Comment by sjlombardo** [comment]
yes, that is generally correct. After a key or rekey, close will clear the key material managed internally by sqlcipher
