### ISSUE TITLE
Query related to sqlcipher rpm

### ISSUE THREAD

**Issue by NokiaOMS** [sqlcipher/sqlcipher#512]
Problem Description
---------------------------------------------------
I have added "sqlcipher-4.5.2-1.el9.x86_64 " in my machine and trying to execute below command rhel8 and rhel9 .
And I see different behavior

Commnad :

sqlcipher /var/mnt/local/omsd ata/OMS/DBChecksum/oms_checksum_db.db -echo "PRAGMA key ='`fsgetcred db_checksum root`'; INSERT INTO checksum_table (File, Checksum, Updated_Time, Validation_state) VALUES(\"/var/log/samplefile.txt\", \"s4mp53Ch3ck8um12345\", datetime('now'), \"default\");"

Output :-

RHEL8 :
sqlcipher /var/mnt/local/omsdata/OMS/DBChecksum/oms_checksum_db.db -echo "PRAGMA key ='`fsgetcred db_checksum root`'; INSERT INTO checksum_table (File, Checksum, Updated_Time, Validation_state) VALUES(\"/var/log/samplefile.txt\", \"s4mp53Ch3ck8um12345\", datetime('now'), \"default\");" | tail -n 1

When we are executing above command output is coming as "OK" in RHEL9 but in RHEL8 it is coming as "INSERT INTO checksum_table (File, Checksum, Updated_Time, Validation_state) VALUES("/var/log/samplefile.txt", "s4mp53Ch3ck8um12345", datetime('now'), "default");"
has context menu

RHEL9:
sqlcipher /var/mnt/local/omsdata/OMS/DBChecksum/oms_checksum_db.db -echo "PRAGMA key ='`fsgetcred db_checksum root`'; INSERT INTO checksum_table (File, Checksum, Updated_Time, Validation_state) VALUES(\"/var/log/samplefile.txt\", \"s4mp53Ch3ck8um12345\", datetime('now'), \"default\");" | tail -n 1
OK

**When we are executing above command output is coming as "OK" in RHEL9 but in RHEL8 it is coming as "
INSERT INTO checksum_table (File, Checksum, Updated_Time, Validation_state) VALUES("/var/log/samplefile.txt", "s4mp53Ch3ck8um12345", datetime('now'), "default");
"**

**
<img width="760" alt="RHEL8" src="https://github.com/sqlcipher/sqlcipher/assets/169340063/39249a79-2826-4bbd-b47f-16897d97a28e">
<img width="761" alt="RHEL9" src="https://github.com/sqlcipher/sqlcipher/assets/169340063/3e0ef99c-0191-4da4-a6e6-fff2ffb53ee8">**

Is it expected behavior in RHEL 9 ?

Thank You

**Comment by developernotes** [comment]
Hi @NokiaOMS,

The change to reporting `ok` from a `PRAGMA key` command originates from SQLCipher core [4.3.0](https://github.com/sqlcipher/sqlcipher/blob/master/CHANGELOG.md#430---november-2019---430-changes). Can you check the version on both RHEL 8/9 and see what is reported by executing the following SQL command?

```
PRAGMA cipher_version;
```
