### ISSUE TITLE
Conflict Between CryptoSwift and SQLCipher in Swift Project Preventing Database Encryption

### ISSUE THREAD

**Issue by Alenroyfeild** [sqlcipher/sqlcipher#514]
When including both CryptoSwift and SQLCipher in the same Swift project, the database encryption process fails. Without CryptoSwift, the encryption works correctly using SQLCipher.

Environment
SQLCipher version: 4.5.7
CryptoSwift version: 1.8.2
Xcode version: 15.3
iOS version: 17.4
Swift version: 5.10
Installation method: CocoaPods 

### Expected Behavior
The database should be encrypted independently of other libraries present in the same project.

### Actual Behavior
The database is not encrypted when both CryptoSwift and SQLCipher are included in the project. The encryption works correctly when CryptoSwift is not included.

### Steps to Reproduce
try to add both cryptoswift and sqlcipher and try to encrypt the DB.sqlite file

**Comment by R4N** [comment]
Hi @Alenroyfeild 

Thanks for your interest in SQLCipher and for reaching out. Just tested it out using this setup:

SQLCipher version: 4.5.7
CryptoSwift version: 1.8.2
Xcode version: 15.4
iOS version: 17.5
Swift version: 5.10
Installation method: CocoaPods

With this sample code:

```
import UIKit
import CryptoSwift
import SQLCipher


class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        do {
            try testSQLCipher()
        } catch {
            print("error while testing sqlcipher \(error)")
        }
    }
    
    func testSQLCipher() throws {
        var rc: Int32
        var db: OpaquePointer? = nil
        var stmt: OpaquePointer? = nil
        let password: String = "correct horse battery staple"
        let dbLocation = FileManager.default.temporaryDirectory.appendingPathComponent("sqlcipher.db")
        if FileManager.default.fileExists(atPath: dbLocation.absoluteString) {
            try FileManager.default.removeItem(at: dbLocation)
        }
        print("db location = \(dbLocation.absoluteString)")
        rc = sqlite3_open(dbLocation.absoluteString, &db)
        if (rc != SQLITE_OK) {
            let errmsg = String(cString: sqlite3_errmsg(db))
            print("Error opening database: \(errmsg)")
            return
        }
        rc = sqlite3_key(db, password, Int32(password.utf8CString.count))
        if (rc != SQLITE_OK) {
            let errmsg = String(cString: sqlite3_errmsg(db))
            print("Error setting key: \(errmsg)")
        }

        rc = sqlite3_prepare(db, "PRAGMA cipher_version;", -1, &stmt, nil)
        if (rc != SQLITE_OK) {
            let errmsg = String(cString: sqlite3_errmsg(db))
            print("Error preparing SQL: \(errmsg)")
        }
        rc = sqlite3_step(stmt)
        if (rc == SQLITE_ROW) {
            let cipherVersion = String(cString: sqlite3_column_text(stmt, 0))
            print("cipher_version: \(cipherVersion)")
        } else {
            let errmsg = String(cString: sqlite3_errmsg(db))
            print("Error retrieiving cipher_version: \(errmsg)")
        }
        let createTableQuery = "CREATE TABLE IF NOT EXISTS t1(a INTEGER, b INTEGER);"
        rc = sqlite3_exec(db, createTableQuery, nil, nil, nil)
        if (rc == SQLITE_OK) {
            print("Successfully created table")
        } else {
            let errmsg = String(cString: sqlite3_errmsg(db))
            print("Error creating table \(errmsg)")
        }
        sqlite3_finalize(stmt)
        sqlite3_close(db)
    }
}
```

The console properly output the SQLCipher cipher_version (`4.5.7 community`) and the database in the temporary location was properly encrypted using SQLCipher.

Are you attempting to encrypt an already existing plaintext SQLite database? If so you'll want to use the [sqlcipher_export()](https://www.zetetic.net/sqlcipher/sqlcipher-api/#sqlcipher_export) convenience function.

If not, could you please provide some sample code/sample project which reproduces the issue?

**Comment by Alenroyfeild** [comment]
hi @R4N ,
Thank you for your reply .
Issue got clarried from this [post](https://discuss.zetetic.net/t/important-advisory-sqlcipher-with-xcode-8-and-new-sdks/1688)
reason: One of my dependency is including the sqlite3.
if you found any workaround/solution to resolve this, please help to me.
Thanks in advance.

**Comment by R4N** [comment]
@Alenroyfeild 

Is the sqlite3 inclusion coming from one of your Pod dependencies? My comment on the discussion forum here might guide you in the right direction: https://discuss.zetetic.net/t/cannot-open-encrypted-database-with-sqlcipher-4/3654/4

If that doesn't help could you post your Podfile or explain where the sqlite3 inclusion is coming from?
