### ISSUE TITLE
i want to restore deleted data ,how can i find the free pages

### ISSUE THREAD

**Issue by pangguoming** [sqlcipher/sqlcipher#520]
i want to restore deleted data ,how can i find the free pages

**Comment by developernotes** [comment]
Hello @pangguoming,

Thanks for your interest in SQLCipher. We reserve GitHub Issues for tracking defects within the software library itself. This particular question should be posted to the [SQLCipher Community Discuss site](https://discuss.zetetic.net/c/sqlcipher), please consider reposting there instead. Thanks!
