### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by GuillaumeUnice** [sqlcipher/sqlcipher#521]
### Expected Behavior
No memory Leak

### Actual Behavior
Memory leak into:
`static void *sqlite3MemMalloc(int nByte)`

<img width="276" alt="Capture d’écran 2024-07-08 à 17 07 28" src="https://github.com/sqlcipher/sqlcipher/assets/5946720/328ae3e3-993b-4c77-a5a1-db07f8a9ceda">

<img width="1079" alt="Capture d’écran 2024-07-08 à 17 06 42" src="https://github.com/sqlcipher/sqlcipher/assets/5946720/0b3b15f1-ffb0-4822-8eb6-7228eb24d366">

<img width="841" alt="Capture d’écran 2024-07-08 à 17 30 53" src="https://github.com/sqlcipher/sqlcipher/assets/5946720/9b4d3038-c7b4-497a-bf7a-4b501a7a3c8b">

### Steps to Reproduce
Default value 
```
                .define("SQLITE_HAS_CODEC", to: "1"),
                .define("SQLITE_TEMP_STORE", to: "3"),
                .define("SQLCIPHER_CRYPTO_CC", to: nil),
                .define("NDEBUG", to: "1"),
```

SQLite version: 0.14.1

Thanks for any kind of help

**Comment by GuillaumeUnice** [comment]
I've encounter this post which is related but no conclusive answer to it

**Comment by sjlombardo** [comment]
Hello @GuillaumeUnice - before saying that this is a memory leak in SQLCipher or SQLite, you'd need to establish a minimal reproduction of the leak in a minimal iOS application using the SQLite API directly. From the stack trace you provided it looks like you are using Capacitor, which introduces a huge surface area of problem outside of SQLCipher itself. Once you are able to create a standalone native iOS application that reproduces the issue, please post it to github with a permissive license and we'll take a closer look for further troubleshooting.

**Comment by GuillaumeUnice** [comment]
Hi @sjlombardo I further investigate and it turns out, I always open an new DB connection for each SQL request by reducing that to one. I do not know whether the memory leak exist but at least it's reduce to epsilon and the XCode memory leak detector find nothing anymore.

So thanks for your prompt answer!

I close the ticket now
