### ISSUE TITLE
Encryption-related

### ISSUE THREAD

**Issue by wonkyungup** [sqlcipher/sqlcipher#526]
### Expected behavior
1. sqlite file without encryption
2. sqlciper connection to set encryption
3. sqlite access requires password

### Actual behavior
1. sqlite file without password
2. set encryption by connecting sqlciper
3. no password required to access sqlite

### Reproduction steps
```js
import * as sqlite from '@journeyapps/sqlcipher';

const sqlite3 = sqlite.verbose()
const dbPath = 'test.db'

const db = new sqlite3.Database(dbPath)
db.serialize(() => {
    db.run("PRAGMA cipher_compatibility = 4");

    db.run("PRAGMA key = ''");
    db.run("PRAGMA rekey = '123'");
})


db.close();
```

SQLCipher version: latest

**Comment by developernotes** [comment]
Hi @wonkyungup,

Thanks for your interest in SQLCipher. We reserve GitHub Issues for tracking defects within the software library itself. This particular question should be posted to the [SQLCipher Community Discuss site](https://discuss.zetetic.net/c/sqlcipher), please consider reposting there instead. That said, please consider reviewing the documentation on the convenience function `sqlcipher_export(...)` [^1] as this will allow you to convert a plaintext SQLite database to a SQLCipher encrypted database. Thanks!

[^1]: https://www.zetetic.net/sqlcipher/sqlcipher-api/#sqlcipher_export
