### ISSUE TITLE
SqlCipher reading data from encrypt database issue

### ISSUE THREAD

**Issue by sandeepkumarrepo** [sqlcipher/sqlcipher#53]
Hi Stephen,

Hope you doing good!.

I have unencrypted database and i encrypt the same database using below code:

```
BOOL success;
NSFileManager *fileManager = [NSFileManager defaultManager];
NSArray *documentPaths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
NSString *documentsDir = [documentPaths objectAtIndex:0];
databasePath = [documentsDir stringByAppendingPathComponent:@"MapOutAnalytics.sqlite"];
// Check if the database has already been created in the users filesystem
success = [fileManager fileExistsAtPath:databasePath];
// If the database already exists then return without doing anything
if(success) return;
// If not then proceed to copy the database from the application to the users filesystem
// Get the path to the database in the application package
NSString *databasePathFromApp = [[NSBundle mainBundle] pathForResource:@"MapOutAnalytics" ofType:@"sqlite"];

// Copy the database from the package to the users filesystem
BOOL val = [fileManager copyItemAtPath:databasePathFromApp toPath:databasePath error:nil];
if (sqlite3_open([databasePath UTF8String], &database) == SQLITE_OK)
{
    int result;
    NSString *encryptedPath = [NSString stringWithFormat:@"%@/Documents/MapOutAnaltics_encrypted.sqlite",NSHomeDirectory()];
    result = sqlite3_exec(database, [[NSString stringWithFormat:@"attach database '%@' as encrypted key '%@';",encryptedPath, @"test123"] UTF8String], NULL, NULL, NULL);

    if (result == SQLITE_OK){
        result = sqlite3_exec(database,[@"PRAGMA encrypted.cipher_page_size = 4096;" UTF8String], NULL, NULL, NULL);
        if (result == SQLITE_OK){
            result = sqlite3_exec(database,[@"SELECT sqlcipher_export('encrypted');" UTF8String], NULL, NULL, NULL);
            if (result == SQLITE_OK){
                result = sqlite3_exec(database, [@"DETACH DATABASE encrypted;" UTF8String], NULL, NULL, NULL);
                if (result == SQLITE_OK){
                    NSLog(@"DONE");
                }else{
                    NSLog(@"fail to detach database code == %d",result);
                }
            }else{
                NSLog(@"fail to export database with code == %d",result);
            }
        }else{
            NSLog(@"fail to set page size == %d",result);
        }
    }else{
        NSLog(@"fail to attach database with code == %d",result);
    }

sqlite3_close(database);
}else{
    NSLog(@"fail to open the database");
}
```

Above program in separate method works fine and it creates an encrypt database. 

As of now no issue.
Now issues start now:
1. opening the encrypt database from terminal:
./configure CFLAGS="-DSQLITE_HAS_CODEC -lcrypto"
make
idc-srikanth:sqlcipher ICSS-IOS4$ ./sqlite3 /Users/ICSS-IOS4/Library/Application\ Support/iPhone\ Simulator/5.1/Applications/53B95563-1B56-4970-8EE2-E5051317203C/Documents/MapOutAnaltics_encrypted.sqlite 
SQLite version 3.7.14.1 2012-10-04 19:37:12
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> pragma key = 'test123';
sqlite> select \* from sqlite_master;
Error: file is encrypted or is not a database
sqlite> .tables

i can't open the database and check. Please help if i am missing anything.
1. From code: after encrypt an database i am calling below method:

-(void)readDataBase{

```
databasePath = [[NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) objectAtIndex:0]stringByAppendingPathComponent: @"MapOutAnalytics_encrypted.sqlite"];
NSLog(@"the DataBasePath is ::%@",databasePath);

sqlite3 *db;
if (sqlite3_open([databasePath UTF8String], &db) == SQLITE_OK) {

    const char* key = [@"test123" UTF8String];
    char *error = nil;
    sqlite3_key(db, key, strlen(key));
    if (sqlite3_exec(db, (const char*) "SELECT count(*) FROM sqlite_master;", NULL, NULL, &error) == SQLITE_OK) {
        // password is correct, or, database has been initialized
        NSLog(@"correct password");
    } else {
        // incorrect password!
        NSLog(@"incorrect password");
    }
    NSString * query = [NSString stringWithFormat:@"select * from dimDistricts;"];
    sqlite3_stmt *statement = NULL;

    int rec = sqlite3_prepare_v2(db, [query UTF8String], -1, &statement, NULL);
    if (rec == SQLITE_OK){
        int row = sqlite3_step(statement);
        while ( row == SQLITE_ROW){
            NSLog(@" column name == %s ",sqlite3_column_name(statement,0));
            NSLog(@" column text == %s ",sqlite3_column_text(statement, 0));
        }
    }
    else{
        NSLog(@"Error");
    }
    sqlite3_finalize(statement);
    sqlite3_close(db);
}
```

}

Output: 
1. printing the correct password. -> Good
2. Now on the prepare query its giving the error. I checked that table name 'dimDistricts' is present in original plain database. -> Need help here. 
I just want to get the data from database.

Your small hint would be save a lot of effort. Please let me know if i am missing anything.

Issue 3: 
While converting the encrypted database to plain database i am getting the below error:

./sqlite3 /Users/ICSS-IOS4/Library/Application\ Support/iPhone\ Simulator/5.1/Applications/53B95563-1B56-4970-8EE2-E5051317203C/Documents/MapOutAnaltics_encrypted.sqlite 
SQLite version 3.7.14.1 2012-10-04 19:37:12
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> PRAGMA key = 'test123';
sqlite> ATTACH DATABASE 'plaintext.db' AS plaintext KEY '';
Error: file is encrypted or is not a database

Please suggest.

Thanks,
Sandeep

**Comment by sharmasneha** [comment]
Hi Stephen,
 I tried to encrypt the Database using above code,i was able to encrypt DB,but not able to insert Data from CSV file into Database. While inserting data should i give path of Encrypted database.

**Comment by developernotes** [comment]
Hello @sharmasneha 

We tend to use Github issues as a tool for reporting problems with SQLCipher.  If you have a specific usage related question, please feel free to post your question with specific details in our [Discuss site](https://discuss.zetetic.net/c/sqlcipher) for SQLCipher.  Thanks!

**Comment by pandiios** [comment]
Hello stephen Sandeep 


  I got the error 'file is encrypted or is not a database' while opening the database in terminal and XCode too.  I don't know how to decrypt the db.  I tried above Sandeep's code. Please help me.



Thanks
Pandi

**Comment by developernotes** [comment]
Hello @pandiios 

If you are having issues properly integrating the SQLCipher library within your application, the [discuss](https://discuss.zetetic.net/c/sqlcipher) site is the preferred public support channel.  Thanks!
