### ISSUE TITLE
Unencrypted to encrypted doesn't seem to work any longer

### ISSUE THREAD

**Issue by rayhayes** [sqlcipher/sqlcipher#532]
### Expected Behavior

Using the suggested sqlcipher_export method should create an encrypted database that can be opened by the same code that opened previous files.

### Actual Behavior
Trying to open in C# code that works with other encrypted databases returns the Sqlite 26 error, file is not a database.

### Steps to Reproduce

Follow the published steps.

SQLCipher version:

SQLitePCLRaw.bundle_e_sqlcipher 2.1.10
SQLitePCLRaw.provider_e_sqlcipher 2.1.10

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by rayhayes** [comment]
Figured it out. The connection string needs to be in a particular format in order to succeed.

**Comment by sjlombardo** [comment]
For additional details and reference: https://discuss.zetetic.net/t/trouble-using-sqlcipher-export-from-net/6732
