### ISSUE TITLE
AccessViolationException with sqlcipher

### ISSUE THREAD

**Issue by jdkyriakos** [sqlcipher/sqlcipher#68]
Hello I’m wondering if someone could help me.
I a have a window application in C#, WPF, Entity Framework and a sqlite database.
I used the sqlcipher dll  (x86) and managed to encrypt my db. Unfortunately my program always throws the following exception:

System.AccessViolationException was unhandled
  HResult=-2147467261
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=System.Data.SQLite
  StackTrace:
       at System.Data.SQLite.UnsafeNativeMethods.sqlite3_key(IntPtr db, Byte[] key, Int32 keylen)
       at System.Data.SQLite.SQLite3.SetPassword(Byte[] passwordBytes)
       at System.Data.SQLite.SQLiteConnection.Open()
       at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure)
       at System.Data.EntityClient.EntityConnection.Open()
       at System.Data.Objects.ObjectContext.EnsureConnection()
       at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
       at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
        ………

The problem occurs in FirstOrDefault or toList() in code like

```
var query = from d in _context.Doctors
                        join pd in _context.PersonalDetails on d.PersonalDetailsId equals pd.ID
                        where pd.AMKA == patientAMKA
                        select pd;
    return query.FirstOrDefault();
Or  returnquery.toList();
```

Sometimes works fine but sometimes not. 
I used the following datasource:
data source=C:\Users\.. \AppData\Local\eDoctor\eDoctor.db;Password=123456;
And also only one thread queries the db.
From testing I saw that in a slow machine(window xp) there is no problem. But in much quicker machines (xp-windows 7 x86&x64 – vista x86) the previous problem occurs. 
Last but not least, when I used the same dlls but with password=”” (without encryption) there is no problem too.
Thanks in advance.

**Comment by developernotes** [comment]
Hello @jdkyriakos 

I'm sorry for the considerable late reply, are you still seeing the issue you described above?

**Comment by Luokun2016** [comment]
> Hello I’m wondering if someone could help me. I a have a window application in C#, WPF, Entity Framework and a sqlite database. I used the sqlcipher dll (x86) and managed to encrypt my db. Unfortunately my program always throws the following exception:
> 
> System.AccessViolationException was unhandled HResult=-2147467261 Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt. Source=System.Data.SQLite StackTrace: at System.Data.SQLite.UnsafeNativeMethods.sqlite3_key(IntPtr db, Byte[] key, Int32 keylen) at System.Data.SQLite.SQLite3.SetPassword(Byte[] passwordBytes) at System.Data.SQLite.SQLiteConnection.Open() at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure) at System.Data.EntityClient.EntityConnection.Open() at System.Data.Objects.ObjectContext.EnsureConnection() at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption) at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator() at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source) ………
> 
> The problem occurs in FirstOrDefault or toList() in code like
> 
> ```
> var query = from d in _context.Doctors
>                         join pd in _context.PersonalDetails on d.PersonalDetailsId equals pd.ID
>                         where pd.AMKA == patientAMKA
>                         select pd;
>     return query.FirstOrDefault();
> Or  returnquery.toList();
> ```
> 
> Sometimes works fine but sometimes not. I used the following datasource: data source=C:\Users.. \AppData\Local\eDoctor\eDoctor.db;Password=123456; And also only one thread queries the db. From testing I saw that in a slow machine(window xp) there is no problem. But in much quicker machines (xp-windows 7 x86&x64 – vista x86) the previous problem occurs. Last but not least, when I used the same dlls but with password=”” (without encryption) there is no problem too. Thanks in advance.

Hello @jdkyriakos , how did you fix this?

**Comment by jdkyriakos** [comment]
Hello @Luokun2016

Its been ages ( 11 years ) since my post   ;-)
Projects have been delivered commits have been made ever since.

I really don't remember how we solve it but we solve it alright  !!!
Some suggestions:
- Change the version of your sqlite.
- Change the version of the sqlcypher
- Use a "clean" _context
- Debug the entity framework ( we had seen if i remember correct -  that the framework retrieved not only the foreign  keys - from another table but also the foreign keys of the foreign keys of that 2nd table - crazy i know )

Check if the error occurs after the table is larger than a specific amount and play with database extra settings

I am sure that one way or another you are going to solve it Or find a workarround - we did it too !!!
