### ISSUE TITLE
Microsoft Excel Issue

### ISSUE THREAD

**Issue by ianscarroll** [sqlcipher/sqlcipher#70]
Crashes Excel while debugging with no error.

When trying to use with a simple Excel add-in template written in VB.NET, adding the following line anywhere in code crashes Excel without generating any error.  The Excel add-in works flawlessly until this single line of code is added:

Dim conn As New SQLiteConnection()

I have tried referencing both the x86 and x64 assembly with same result.

Any other VB.NET or C# project (non Office related) on the same machine works perfectly.

Should we be able to use this product for Microsoft office develop?

We are using product version 91.0.86.0

Thanks!

**Comment by developernotes** [comment]
Hello @ianscarroll 

I'm sorry for the considerable late reply, are you still seeing the issue you described above?
