### ISSUE TITLE
Unable to build sqlcipher: missing sqlite3.c

### ISSUE THREAD

**Issue by kaspro** [sqlcipher/sqlcipher#71]
I am unable to build sqlcipher (latest git-source) on Xcode (5.0), it's failing with:
clang: error: no such file or directory: ..../sqlite.c
I'm trying to build for iOS.
openssl, openssl-xcode & sqlcipher are included as sub- projects as per documentation, targets of sqlcipher are sqlcipher and amalgamation, but for some reason the sqlite3.c is not being built.
Any ideas where to look further? I'm not an xcode expert... thanks in advance!

**Comment by ouerghemmi** [comment]
please where should i add this configuration exactly ? 
https://github.com/sqlcipher/sqlcipher/blob/master/README
this link is not working. 

Thanks

**Comment by developernotes** [comment]
Hi @ouerghemmi 

I believe you may be looking for the link to the README which is [here](https://github.com/sqlcipher/sqlcipher/blob/master/README.md).

**Comment by ouerghemmi** [comment]
Thanks, solved !
