### ISSUE TITLE
ios-intergation issue

### ISSUE THREAD

**Issue by meadlai** [sqlcipher/sqlcipher#73]
http://sqlcipher.net/ios-tutorial/
with this tour, when "Add subproject references",
the "sqlcipher.xcodeproj" has some problem, that it only added it self file, but nothing else.
you may check this images.
![picture](https://f.cloud.github.com/assets/676308/1679895/26c606a6-5d60-11e3-804c-fc1b4515d9f2.png)

I have added other xcode projects, they were all fine, 
normally, sub project can expand its folders and files, but  "sqlcipher.xcodeproj" can't, it only contains itself.

 I am using xcode5

**Comment by developernotes** [comment]
Hi @meadlai 

I'm sorry for the considerable late reply, are you still seeing the issue you described above?
