### ISSUE TITLE
SQLCipher integration issue with SalesForce SDK

### ISSUE THREAD

**Issue by rana456** [sqlcipher/sqlcipher#74]
I want to integrate commercial edition of SQL cipher in my project, but a framework is being used with the same name in SalesForce SDK which is also also integrated in my app, so i am getting Directory not found error, Please help me to resolve this issue.

**Comment by developernotes** [comment]
Hi @rana456 

My apologizes for just seeing this inquiry.  Are you still running into an issue with your integration?
