### ISSUE TITLE
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/yacc failed with exit code 1

### ISSUE THREAD

**Issue by cheshuangchun** [sqlcipher/sqlcipher#76]
![2014-01-10 12 05 17](https://f.cloud.github.com/assets/3108737/1884752/77b94164-79ac-11e3-94f7-53b33c1c2da6.png)
That is the problem,please help me.

**Comment by priyankranka** [comment]
I also run into same issue. I am running Xcode 6.1.1
