### ISSUE TITLE
how to enable COLLATE UNICODE for iOS

### ISSUE THREAD

**Issue by kaspro** [sqlcipher/sqlcipher#80]
I switched a query of mine to COLLATE UNICODE, which lead to a ROLLBACK, so I suppose the collation is not available.
Do I have to enable icu for this? If so - is there a good tutorial for it- or another way to acheive that?
Thanks in advance,
Regards Chris

**Comment by developernotes** [comment]
Hello @kaspro 

I'm sorry for the considerable late reply, are you still working through the issue you described above?

**Comment by kaspro** [comment]
Hi @developernotes 
no worries, I went somehow through it - would need to look through the code how I did it, but it works for now thanks - are there any updates to it?

**Comment by developernotes** [comment]
Hi @kaspro 

I'm glad to hear everything is working. SQLCipher is currently at version 3.4.0.
