### ISSUE TITLE
Xcode Continuous Integration

### ISSUE THREAD

**Issue by eclipse101** [sqlcipher/sqlcipher#90]
Hi,
I've integrated sqlcipher into my project and its working great, also building fine on simulator and an actual phone.
I'm also running a Xcode CI on another machine which pulls the project from git to perform tests and archive it.

However, on the CI i get the following build error in the log:

ld: warning: ignoring file /Library/Server/Xcode/Data/BotRuns/Cache/.../BuildProductsPath/Release/libsqlcipher.a, missing required architecture armv7 in file /Library/Server/Xcode/Data/BotRuns/Cache/.../Release/libsqlcipher.a (2 slices)

which results in sqlite errors:

Undefined symbols for architecture armv7: "_sqlite3_last_insert_rowid", referenced from: ...

My main project settings are as follows:

Architectures: Standard (armv7, armv7s, arm64)
Valid architectures: armv7
Build active architectures only: NO

I've been trying to figure this out for a few days now, but the result stays the same irrespective of the changes I make to the build settings.

Am I missing something obvious?
Regards

**Comment by iosfitness** [comment]
@eclipse101 I'm getting the below error.

Logs from the CI Server [Jenkins] :

clang: error: no such file or directory: '~/Library/Developer/Xcode/DerivedData/XXX-fqalbxsdmrbgnmefqteljbygjazu/Build/Intermediates.noindex/ArchiveIntermediates/XXX/BuildProductsPath/Release-iphoneos/libsqlcipher.a'

** ARCHIVE FAILED **


The following build commands failed:
	~/Library/Developer/Xcode/DerivedData/XXX-fqalbxsdmrbgnmefqteljbygjazu/Build/Intermediates.noindex/ArchiveIntermediates/XXX/IntermediateBuildFilesPath/XXX.build/Release-iphoneos/XXX.build/Objects-normal/arm64/XXX normal arm64

	~/Library/Developer/Xcode/DerivedData/XXX-fqalbxsdmrbgnmefqteljbygjazu/Build/Intermediates.noindex/ArchiveIntermediates/XXX/IntermediateBuildFilesPath/XXX.build/Release-iphoneos/XXX.build/Objects-normal/armv7/XXX normal armv7
(2 failures)
Build step 'Xcode' marked build as failure
[AWS CodePipeline Plugin] Publishing artifacts
[AWS CodePipeline Plugin] Build failed, calling PutJobFailureResult
Build step 'AWS CodePipeline Publisher' marked build as failure
Finished: FAILURE

However, libsqlcipher.a is getting generated in **Release** folder ~/Library/Developer/Xcode/DerivedData/XXX-fqalbxsdmrbgnmefqteljbygjazu/Build/Intermediates.noindex/ArchiveIntermediates/XXX/IntermediateBuildFilesPath/XXX.build/Release/XXX.build/Objects-normal/arm64/XXX normal arm64

How can I tell my CI Server to point to Release-iphoneos for libsqlcipher.a

Could you please share your CI Server settings releated to libsqlcipher.a

I'm running the following command

xcodebuild -scheme XXX -workspace XXX.xcworkspace clean archive -archivePath build/XXX

@mengxy  when I try to use -destination generic/platform=iOS, CI server complains about DYSM file not found in Release-iphoneos/
Any inputs?
