### ISSUE TITLE
InsertOrReplaceAsync operation is missing inside SQLiteAsyncConnection adapter

### ISSUE THREAD

**Issue by efimserg** [sqlcipher/sqlcipher#94]
Why is missing InsertOrReplaceAsync operation inside SQLiteAsyncConnection adapter?

**Comment by developernotes** [comment]
Hello @efimserg 

Our .NET libraries are slowly moving over to the [SQLite.Net-PCL](https://github.com/oysteinkrog/SQLite.Net-PCL) client library.  Are you still running into an issue?

**Comment by efimserg** [comment]
Hello Nick,

Thank you for information. We applied workaround fro that moment and
successfully competed project. But in any case great that you are moving
with PCL way .

Best Regards,

*Sergii Iefimov*

Mobile phone:                +380 (68) 361 4627
E-mail:                          *efimserg@gmail.com <efimserg@gmail.com>*

**Comment by developernotes** [comment]
Hi @efimserg 

Great to hear, thanks for getting back to us!

**Comment by eromanowski** [comment]
Any movement on this?
