### ISSUE TITLE
net.sqlcipher.database.SQLiteException: file is encrypted or is not a database

### ISSUE THREAD

**Issue by viewvandhana** [sqlcipher/sqlcipher#95]
I get the following trace.I get the trace when there are many apps running in the background and when i resume my app

net.sqlcipher.database.SQLiteException: file is encrypted or is not a database
E/AndroidRuntime(18723): 	at net.sqlcipher.database.SQLiteDatabase.native_setLocale(Native Method)
E/AndroidRuntime(18723): 	at net.sqlcipher.database.SQLiteDatabase.setLocale(SQLiteDatabase.java:2072)
E/AndroidRuntime(18723): 	at net.sqlcipher.database.SQLiteDatabase.<init>(SQLiteDatabase.java:1938)
E/AndroidRuntime(18723): 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:871)
E/AndroidRuntime(18723): 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:918)
E/AndroidRuntime(18723): 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:210)

**Comment by DnyaneshwarWadghanePM** [comment]
same problem facing in xamarin.android after setting password connection not opening and giving error file is encrypted or is not a database

**Comment by developernotes** [comment]
Hello @DnyaneshwarWadghanePM 

This ticket is for the native SQLCipher for Android library.  Would you mind opening a new issue in Github, or email us at [support@zetetic.net](mailto:support@zetetic.net) with a few more details about your specific scenario, we would be glad to help you resolve the issue.
